| Generated by generate.py from buffers.c.
#NO_APP
	.file	"buffers.c"
	.text
	.align	2
	.globl	dl_buffers_base
	.type	dl_buffers_base, @function
dl_buffers_base:
	mov3q.l #3,%d1
	and.l 12(%sp),%d1
	tst.l 8(%sp)
	jeq .L2
	mov3q.l #1,%d0
	and.l 4(%sp),%d0
	lea fx2_base,%a0
	lsl.l #2,%d0
	add.l %d1,%d0
	move.l (%a0,%d0.l*4),%d0
	rts
.L2:
	lea fx1_base,%a0
	move.l (%a0,%d1.l*4),%d0
	rts
	.size	dl_buffers_base, .-dl_buffers_base
	.align	2
	.globl	dl_buffers_core
	.type	dl_buffers_core, @function
dl_buffers_core:
	move.l 4(%sp),%d0
	mov3q.l #4,%d1
	eor.l %d1,%d0
	mov3q.l #1,%d1
	lsr.l #2,%d0
	and.l %d1,%d0
	rts
	.size	dl_buffers_core, .-dl_buffers_core
	.align	2
	.globl	dl_buffers_entry
	.type	dl_buffers_entry, @function
dl_buffers_entry:
	move.l %d2,-(%sp)
	move.l 8(%sp),%d1
	mov3q.l #3,%d0
	mov3q.l #7,%d2
	and.l %d1,%d0
	cmp.l %d1,%d2
	scs %d1
	move.l (%sp)+,%d2
	add.l %d0,%d0
	mvs.b %d1,%d1
	sub.l %d1,%d0
	rts
	.size	dl_buffers_entry, .-dl_buffers_entry
	.align	2
	.globl	dl_buffers_init
	.type	dl_buffers_init, @function
dl_buffers_init:
	lea (-28,%sp),%sp
	tst.l 36(%sp)
	sne %d0
	movem.l #7228,(%sp)
	move.l 32(%sp),%a2
	neg.l %d0
	tst.b %d0
	jeq .L11
	moveq #13,%d5
	move.l %a2,%d3
	clr.l %d4
	lea (240,%a2),%a4
	add.l #48,%d3
	lea fx1_base,%a3
	lea fx2_base,%a1
.L16:
	move.l %d4,%d2
	move.l %d3,%a0
	move.b #15,(%a4)
	move.b %d5,1(%a4)
	lsl.l #2,%d2
	clr.l %d0
.L15:
	move.l %d0,%d1
	lsr.l #1,%d1
	btst #0,%d0
	jeq .L13
	add.l %d2,%d1
	addq.l #1,%d0
	move.l (%a1,%d1.l*4),%d1
	move.l %d1,128(%a0)
	move.l %d1,64(%a0)
	move.l %d1,(%a0)+
	moveq #8,%d1
	cmp.l %d0,%d1
	jne .L15
.L25:
	addq.l #2,%a4
	add.l #32,%d3
	tst.l %d4
	jne .L24
	mov3q.l #1,%d4
	move.l %d4,%d2
	move.l %d3,%a0
	move.b #15,(%a4)
	move.b %d5,1(%a4)
	lsl.l #2,%d2
	clr.l %d0
	jra .L15
.L13:
	move.l (%a3,%d1.l*4),%d1
	addq.l #1,%d0
	move.l %d1,128(%a0)
	move.l %d1,64(%a0)
	move.l %d1,(%a0)+
	moveq #8,%d1
	cmp.l %d0,%d1
	jne .L15
	jra .L25
.L24:
	move.w #255,%a3
	move.l %a2,%a1
	clr.l %d1
.L18:
	move.l %d1,%d0
	lsr.l #2,%d0
	mov3q.l #1,%d2
	mov3q.l #7,%d4
	mov3q.l #3,%d3
	eor.l %d2,%d0
	cmp.l %d1,%d4
	scs %d2
	mov3q.l #1,%d4
	and.l %d1,%d3
	addq.l #1,%d1
	and.l %d4,%d0
	mvs.b %d2,%d2
	add.l %d0,%d0
	lea (%a2,%d0.l),%a0
	sub.l %d2,%a0
	mvz.b 240(%a0),%d0
	btst %d3,%d0
	jne .L17
	move.l %a3,%d3
.L17:
	move.b %d3,16(%a1)
	move.b %d3,(%a1)+
	clr.b %d0
	moveq #16,%d2
	move.b %d0,31(%a1)
	cmp.l %d1,%d2
	jne .L18
	move.b %d0,244(%a2)
	movem.l (%sp),#7228
	lea (28,%sp),%sp
	rts
.L11:
	move.l %a2,%d3
	clr.l %d4
	moveq #15,%d5
	lea (240,%a2),%a4
	add.l #48,%d3
	lea fx1_base,%a3
	lea fx2_base,%a1
	jra .L16
	.size	dl_buffers_init, .-dl_buffers_init
	.align	2
	.globl	dl_buffers_prepare
	.type	dl_buffers_prepare, @function
dl_buffers_prepare:
	lea (-68,%sp),%sp
	movem.l #31996,(%sp)
	move.l 72(%sp),%a2
	move.l 76(%sp),%a6
	move.l 84(%sp),%a4
	tst.b 244(%a2)
	jne .L50
	lea (32,%a2),%a1
	clr.l %d0
	move.l %a1,%a3
.L30:
	tst.b (%a3)+
	jne .L28
	mvz.b -33(%a3),%d1
	cmp.l #255,%d1
	jeq .L28
	mvz.b (%a6,%d0.l),%d1
	moveq #31,%d2
	cmp.l %d1,%d2
	jcs .L29
	tst.b (%a4,%d1.l)
	jne .L28
.L29:
	st %d3
	move.b %d3,-33(%a3)
.L28:
	addq.l #1,%d0
	moveq #16,%d5
	cmp.l %d0,%d5
	jne .L30
	clr.l 48(%sp)
	mov3q.l #1,%d5
	clr.l %d1
.L32:
	move.l %d1,%d0
	lsr.l #2,%d0
	mvz.b (%a2,%d1.l),%d2
	mov3q.l #1,%d3
	eor.l %d3,%d0
	mov3q.l #7,%d6
	cmp.l %d1,%d6
	scs %d4
	move.l %d5,%d3
	addq.l #1,%d1
	lsl.l %d2,%d3
	cmp.l #255,%d2
	jeq .L31
	mov3q.l #1,%d6
	and.l %d6,%d0
	mvs.b %d4,%d4
	lea (68,%sp),%a3
	sub.l %d4,%a3
	add.l %d0,%d0
	lea -20(%a3,%d0.l),%a3
	move.b (%a3),%d0
	or.l %d0,%d3
	move.b %d3,(%a3)
.L31:
	moveq #16,%d0
	cmp.l %d1,%d0
	jne .L32
	move.l 80(%sp),%a5
	move.l %sp,%d4
	lea (52,%sp),%a3
	add.l #68,%d4
	move.l %a3,%a0
.L36:
	mvz.b (%a5)+,%d1
	clr.l %d0
	moveq #31,%d2
	cmp.l %d1,%d2
	jcs .L33
	tst.b (%a4,%d1.l)
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
.L33:
	mvz.b (%a6)+,%d3
	move.b #-1,(%a0)
	cmp.l %d1,%d3
	jeq .L80
.L34:
	addq.l #1,%a0
	addq.l #1,%a1
	cmp.l %d4,%a0
	jne .L36
.L82:
	move.l %a3,%a1
	clr.l %d2
	mov3q.l #1,%a6
.L42:
	move.l 80(%sp),%a0
	moveq #31,%d1
	mvz.b (%a0,%d2.l),%d0
	cmp.l %d0,%d1
	jcs .L37
	tst.b (%a4,%d0.l)
	jeq .L37
	mvz.b (%a1),%d0
	cmp.l #255,%d0
	jeq .L81
.L37:
	addq.l #1,%d2
	addq.l #1,%a1
	moveq #16,%d1
	cmp.l %d2,%d1
	jne .L42
.L84:
	move.l %a2,%d1
	add.l #80,%d1
	lea (48,%a2),%a0
.L43:
	move.l (%a0)+,%d0
	move.l %d0,60(%a0)
	move.l %d0,124(%a0)
	cmp.l %a0,%d1
	jne .L43
	move.l %a2,%d1
	add.l #112,%d1
.L44:
	move.l (%a0)+,%d0
	move.l %d0,60(%a0)
	move.l %d0,124(%a0)
	cmp.l %a0,%d1
	jne .L44
	lea (16,%a2),%a0
	clr.l %d2
	lea fx1_base,%a4
	lea fx2_base,%a1
.L49:
	move.l %d2,%d0
	lsr.l #2,%d0
	move.b (%a3)+,%d4
	mov3q.l #1,%d3
	mov3q.l #7,%d5
	eor.l %d3,%d0
	mov3q.l #3,%d1
	cmp.l %d2,%d5
	scs %d3
	and.l %d2,%d1
	mov3q.l #3,%d6
	move.b %d4,(%a0)+
	mvz.b %d4,%d5
	and.l %d6,%d4
	mov3q.l #1,%d6
	and.l %d6,%d0
	mvs.b %d3,%d3
	add.l %d1,%d1
	cmp.l #255,%d5
	jeq .L45
	sub.l %d3,%d1
	mov3q.l #7,%d3
	cmp.l %d2,%d3
	jcc .L46
	move.l %d0,%d3
	move.l %d1,%a6
	lsl.l #3,%d3
	lsl.l #2,%d0
	lea 28(%a6,%d3.l),%a5
	add.l %d4,%d0
	lea (%a1,%d0.l*4),%a6
	move.l (%a6),(%a2,%a5.l*4)
.L45:
	addq.l #1,%d2
	moveq #16,%d0
	cmp.l %d2,%d0
	jne .L49
	mov3q.l #1,%d0
	moveq #1,%d1
	move.b %d1,244(%a2)
	movem.l (%sp),#31996
	lea (68,%sp),%sp
	rts
.L80:
	move.b -32(%a1),%d1
	mvz.b %d1,%d3
	cmp.l #255,%d3
	jeq .L34
	tst.l %d0
	jne .L35
	tst.b (%a1)
	jne .L34
.L35:
	move.b %d1,(%a0)
	addq.l #1,%a0
	addq.l #1,%a1
	cmp.l %d4,%a0
	jne .L36
	jra .L82
.L81:
	move.l %d2,%d4
	lsr.l #2,%d4
	mov3q.l #1,%d3
	mov3q.l #7,%d6
	cmp.l %d2,%d6
	scs %d5
	eor.l %d3,%d4
	lea (68,%sp),%a5
	clr.l %d1
	move.l %a3,%a0
	mvs.b %d5,%d5
	and.l %d3,%d4
	sub.l %d5,%a5
	neg.l %d5
	move.l %d4,%d0
	add.l %d0,%d0
	mvz.b -20(%a5,%d0.l),%d7
	move.l %d0,44(%sp)
.L39:
	move.l %d1,%d0
	lsr.l #2,%d0
	mvz.b (%a0)+,%d3
	mov3q.l #1,%d6
	eor.l %d6,%d0
	cmp.l #255,%d3
	jeq .L38
	and.l %d6,%d0
	cmp.l %d4,%d0
	jeq .L83
.L38:
	addq.l #1,%d1
	moveq #16,%d0
	cmp.l %d1,%d0
	jne .L39
.L85:
	move.l 44(%sp),%a0
	add.l %a2,%a0
	add.l %d5,%a0
	mvz.b 240(%a0),%d3
	not.l %d7
	moveq #15,%d1
	and.l %d7,%d3
	and.l %d3,%d1
	tst.l %d1
	jeq .L52
	mov3q.l #1,%d0
	and.l %d3,%d0
	btst #0,%d3
	jne .L53
.L41:
	addq.l #1,%d0
	btst %d0,%d1
	jeq .L41
	move.b %d0,(%a1)
.L86:
	addq.l #1,%d2
	addq.l #1,%a1
	moveq #16,%d1
	cmp.l %d2,%d1
	jne .L42
	jra .L84
.L83:
	mov3q.l #7,%d6
	cmp.l %d1,%d6
	scs %d0
	mvs.b %d0,%d0
	neg.l %d0
	cmp.l %d5,%d0
	jne .L38
	move.l %a6,%d0
	addq.l #1,%d1
	lsl.l %d3,%d0
	or.l %d0,%d7
	moveq #16,%d0
	cmp.l %d1,%d0
	jne .L39
	jra .L85
.L46:
	lsl.l #3,%d0
	move.l %d1,%a6
	addq.l #1,%d2
	lea 28(%a6,%d0.l),%a5
	lea (%a4,%d4.l*4),%a6
	move.l (%a6),(%a2,%a5.l*4)
	jra .L49
.L53:
	clr.b %d0
	move.b %d0,(%a1)
	jra .L86
.L52:
	movem.l (%sp),#31996
	mov3q.l #-1,%d0
	lea (68,%sp),%sp
	rts
.L50:
	movem.l (%sp),#31996
	moveq #-4,%d0
	lea (68,%sp),%sp
	rts
	.size	dl_buffers_prepare, .-dl_buffers_prepare
	.align	2
	.globl	dl_buffers_next
	.type	dl_buffers_next, @function
dl_buffers_next:
	move.l %d2,-(%sp)
	move.l 8(%sp),%a1
	clr.l %d0
	lea (48,%a1),%a0
.L89:
	move.l (%a0)+,%d2
	move.l 60(%a0),%d1
	cmp.l %d2,%d1
	jne .L88
	addq.l #1,%d0
	moveq #8,%d1
	cmp.l %d0,%d1
	jne .L89
	lea (80,%a1),%a0
	clr.l %d0
.L91:
	move.l (%a0)+,%a1
	move.l 60(%a0),%d1
	cmp.l %a1,%d1
	jne .L97
	addq.l #1,%d0
	moveq #8,%d1
	cmp.l %d0,%d1
	jne .L91
	move.l (%sp)+,%d2
	mov3q.l #-1,%d0
	rts
.L97:
	addq.l #8,%d0
.L88:
	move.l 12(%sp),%a0
	move.l (%sp)+,%d2
	move.l %d1,(%a0)
	rts
	.size	dl_buffers_next, .-dl_buffers_next
	.align	2
	.globl	dl_buffers_written
	.type	dl_buffers_written, @function
dl_buffers_written:
	moveq #15,%d0
	and.l 8(%sp),%d0
	move.l 4(%sp),%a0
	lea 112(%a0,%d0.l*4),%a1
	move.l (%a1),48(%a0,%d0.l*4)
	rts
	.size	dl_buffers_written, .-dl_buffers_written
	.align	2
	.globl	dl_buffers_retire
	.type	dl_buffers_retire, @function
dl_buffers_retire:
	move.l 4(%sp),%a1
	move.l %a1,%d0
	move.l %a1,%a0
	add.l #16,%d0
.L101:
	moveq #1,%d1
	move.b 16(%a0),(%a0)
	addq.l #1,%a0
	move.b %d1,31(%a0)
	cmp.l %a0,%d0
	jne .L101
	clr.b %d0
	move.b %d0,244(%a1)
	rts
	.size	dl_buffers_retire, .-dl_buffers_retire
	.align	2
	.globl	dl_buffers_cancel
	.type	dl_buffers_cancel, @function
dl_buffers_cancel:
	move.l 4(%sp),%a1
	move.l %a1,%d1
	move.l %a1,%a0
	add.l #16,%d1
.L106:
	move.b (%a0)+,%d0
	move.b %d0,15(%a0)
	cmp.l %a0,%d1
	jne .L106
	move.l %a1,%d0
	add.l #144,%d0
	lea (112,%a1),%a0
.L107:
	move.l 64(%a0),(%a0)
	addq.l #4,%a0
	cmp.l %a0,%d0
	jne .L107
	move.l %a1,%d0
	add.l #176,%d0
.L108:
	move.l 64(%a0),(%a0)
	addq.l #4,%a0
	cmp.l %a0,%d0
	jne .L108
	clr.b %d0
	move.b %d0,244(%a1)
	rts
	.size	dl_buffers_cancel, .-dl_buffers_cancel
	.section	.rodata
	.align	2
	.type	fx2_base, @object
	.size	fx2_base, 32
fx2_base:
	.long	16384
	.long	32768
	.long	196608
	.long	212992
	.long	16384
	.long	32768
	.long	229376
	.long	245760
	.align	2
	.type	fx1_base, @object
	.size	fx1_base, 16
fx1_base:
	.long	4096
	.long	7168
	.long	10240
	.long	13312
	.section	.note.GNU-stack,"",@progbits
