| Generated by generate.py from manager.c.
#NO_APP
	.file	"manager.c"
	.text
	.align	2
	.type	counts, @function
counts:
	move.l %d2,-(%sp)
	lea allocator+26,%a1
	clr.l %d0
	lea allocator+218,%a0
.L3:
	tst.b 2(%a1)
	jeq .L2
	mvz.w (%a1),%d1
	add.l %d1,%d0
.L2:
	addq.l #6,%a1
	cmp.l %a0,%a1
	jne .L3
	move.l %d0,dl_residency_words
	move.l #allocator+410,%d1
	clr.l %d0
.L5:
	tst.b 2(%a0)
	jeq .L4
	mvz.w (%a0),%d2
	add.l %d2,%d0
.L4:
	addq.l #6,%a0
	cmp.l %d1,%a0
	jne .L5
	move.l (%sp)+,%d2
	move.l %d0,dl_residency_words+4
	rts
	.size	counts, .-counts
	.align	2
	.type	slot_bound, @function
slot_bound:
	move.l %d2,-(%sp)
	move.l 12(%sp),%d0
	mov3q.l #6,%d1
	move.l 8(%sp),%d2
	muls.l %d1,%d0
	mvz.w #192,%d1
	muls.l %d1,%d2
	move.l phase,%d1
	move.l %d2,%a0
	add.l %d0,%a0
	add.l #allocator,%a0
	tst.b 28(%a0)
	jeq .L11
	subq.l #6,%d1
	tst.l %d1
	jeq .L14
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	rts
.L11:
	subq.l #5,%d1
	tst.l %d1
	jeq .L18
.L13:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
.L18:
	mov3q.l #1,%d1
	cmp.l result.l,%d1
	jne .L13
	tst.l cancelling
	jne .L13
.L14:
	tst.b 412(%a0)
	sne %d0
	move.l (%sp)+,%d2
	mvs.b %d0,%d0
	neg.l %d0
	rts
	.size	slot_bound, .-slot_bound
	.align	2
	.globl	dl_selection_cancel
	.type	dl_selection_cancel, @function
dl_selection_cancel:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jeq .L29
.L19:
	rts
.L29:
	move.l phase,%d0
	tst.l %d0
	jeq .L19
	subq.l #6,%d0
	tst.l %d0
	jeq .L19
	mov3q.l #1,cancelling
	rts
	.size	dl_selection_cancel, .-dl_selection_cancel
	.align	2
	.globl	dl_selection_commit
	.type	dl_selection_commit, @function
dl_selection_commit:
	move.l current,%d0
	cmp.l 4(%sp),%d0
	jne .L30
	mov3q.l #5,%d1
	cmp.l phase.l,%d1
	jeq .L35
.L30:
	rts
.L35:
	mov3q.l #1,%d1
	cmp.l result.l,%d1
	jne .L30
	move.l %d0,-(%sp)
	pea allocator
	jsr dl_allocator_commit
	addq.l #8,%sp
	subq.l #1,%d0
	tst.l %d0
	jeq .L32
	moveq #-3,%d0
	move.l %d0,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L30
	mov3q.l #1,dl_modal_pending
	rts
.L32:
	mov3q.l #6,phase
	clr.l cursor
	addq.l #1,dl_residency_commits
	jra counts
	.size	dl_selection_commit, .-dl_selection_commit
	.align	2
	.type	advance, @function
advance:
	link.w %fp,#-60
	movem.l #1276,(%sp)
	move.l phase,%d4
	tst.l %d4
	jeq .L36
	mov3q.l #1,%d0
	cmp.l %d4,%d0
	jeq .L211
	subq.l #5,%d4
	tst.l %d4
	jeq .L212
	tst.l waiting
	jne .L67
.L218:
	move.l cancelling,%a0
	move.l phase,%a1
	tst.l %a0
	jne .L81
.L73:
	move.l cursor,%d0
	moveq #63,%d5
	cmp.l %d0,%d5
	jcs .L82
.L76:
	moveq #31,%d3
	mov3q.l #6,%d4
	move.l %d0,%d2
	lsr.l #5,%d2
	and.l %d0,%d3
	cmp.l %a1,%d4
	jeq .L121
	clr.b %d5
	move.l #allocator,%d6
	mov3q.l #4,%d4
	cmp.l %a1,%d4
	jeq .L95
.L88:
	mov3q.l #6,%d4
	muls.l %d3,%d4
	move.l %d4,-20(%fp)
	mvz.w #192,%d4
	move.l -20(%fp),%a0
	muls.l %d2,%d4
	add.l %d4,%a0
	add.l %d6,%a0
	tst.b 412(%a0)
	jeq .L104
	tst.b 28(%a0)
	jne .L105
	tst.b %d5
	jeq .L106
	move.l %d1,cursor
.L106:
	move.l -20(%fp),%a0
	add.l %d4,%a0
	add.l #allocator+408,%a0
	move.w (%a0),%d0
	mov3q.l #2,%d5
	cmp.l %a1,%d5
	jne .L213
	move.l %d2,%d1
	add.l #64,%d0
	lsl.l #5,%d1
	pea -14(%fp)
	move.l %d2,-(%sp)
	move.w %d0,-2(%fp)
	lea dl_codes,%a1
	move.l %d1,%d0
	add.l %d3,%d0
	lsl.l #4,%d0
	lea (%a1,%d0.l),%a0
	move.w 8(%a0),-6(%fp)
	move.w 14(%a0),-4(%fp)
	move.l (%a0),-14(%fp)
	move.l 4(%a0),-10(%fp)
	jsr dl_upload_start
	addq.l #8,%sp
	move.l %d0,waiting
.L107:
	tst.l %d0
	jne .L36
	moveq #-3,%d5
	move.l %d5,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L109
	mov3q.l #1,dl_modal_pending
.L109:
	mov3q.l #1,cancelling
.L36:
	movem.l -60(%fp),#1276
	unlk %fp
	rts
.L211:
	lea desired,%a0
	clr.l %d3
	lea desired+16,%a1
.L40:
	mvz.b (%a0)+,%d0
	moveq #12,%d2
	moveq #31,%d5
	muls.l %d0,%d2
	cmp.l %d0,%d5
	jcs .L39
	lea dl_catalog,%a2
	tst.b 9(%a2,%d2.l)
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d3
.L39:
	cmp.l %a1,%a0
	jne .L40
	move.l waiting,%d0
	tst.l %d3
	jeq .L214
	tst.l %d0
	jne .L42
	move.l cursor,%d0
.L48:
	mov3q.l #1,%d5
	cmp.l %d0,%d5
	jcs .L43
	lea dl_pool_base,%a0
	tst.l (%a0,%d0.l*4)
	jeq .L215
	subq.l #1,%d0
	tst.l %d0
	jeq .L49
	tst.l dl_pool_base+4
	jeq .L149
.L49:
	mov3q.l #2,cursor
.L43:
	tst.l cancelling
	jne .L47
	tst.l initialized
	jeq .L216
	tst.w allocator+4.l
	jne .L54
.L224:
	lea dl_pool_words,%a0
	moveq #64,%d7
	cmp.l (%a0),%d7
	jcc .L54
	move.l (%a0),%d0
	add.l #-64,%d0
	move.w %d0,allocator+4
.L54:
	tst.w allocator+6.l
	jne .L55
	moveq #64,%d0
	cmp.l dl_pool_words+4.l,%d0
	jcc .L55
	move.l dl_pool_words+4,%d0
	add.l #-64,%d0
	move.w %d0,allocator+6
.L55:
	move.l current,-(%sp)
	pea desired
	pea allocator
	move.l %d1,-28(%fp)
	jsr dl_allocator_prepare
	lea (12,%sp),%sp
	move.l -28(%fp),%d1
	tst.l %d0
	jlt .L217
	mov3q.l #2,phase
	clr.l cursor
	tst.l waiting
	jeq .L218
.L67:
	move.l cursor,%d2
	lsr.l #5,%d2
.L64:
	move.l %d2,-(%sp)
	move.l %d1,-28(%fp)
	jsr dl_job_status
	addq.l #4,%sp
	tst.l %d0
	jeq .L36
	move.l %d2,-(%sp)
	move.l %d0,-24(%fp)
	jsr dl_job_release
	clr.l waiting
	addq.l #4,%sp
	move.l phase,%a1
	move.l -28(%fp),%d1
	tst.l -24(%fp)
	jlt .L219
	move.l cursor,%d0
	moveq #31,%d4
	mov3q.l #1,%d3
	and.l %d0,%d4
	lsl.l %d4,%d3
	mov3q.l #3,%d4
	cmp.l %a1,%d4
	jeq .L220
	mov3q.l #4,%d5
	cmp.l %a1,%d5
	jeq .L74
	lea (-6,%a1),%a0
	mov3q.l #1,%d7
	cmp.l %a0,%d7
	jcc .L75
	move.l %d0,%a0
	addq.l #1,%a0
	move.l %a0,cursor
	tst.l cancelling
	jne .L71
	move.l %a0,%d0
	moveq #63,%d2
	cmp.l %a0,%d2
	jcc .L76
	clr.l cursor
	mov3q.l #2,%d4
	cmp.l %a1,%d4
	jeq .L77
.L78:
	mov3q.l #4,%d1
	cmp.l %a1,%d1
	jeq .L221
	mov3q.l #6,%d5
	cmp.l %a1,%d5
	jeq .L222
	mov3q.l #7,%d7
	cmp.l %a1,%d7
	jne .L36
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_cancel
	clr.l phase
	addq.l #1,dl_residency_rollbacks
.L206:
	addq.l #8,%sp
	movem.l -60(%fp),#1276
	unlk %fp
	jra counts
.L212:
	tst.l cancelling
	jeq .L63
	mov3q.l #7,phase
	clr.l cursor
	tst.l waiting
	jne .L223
	clr.l %d0
	mov3q.l #7,%a1
	jra .L76
.L96:
	move.l %d0,%d1
	moveq #63,%d5
	addq.l #1,%d1
	cmp.l %d0,%d5
	jeq .L82
	moveq #31,%d3
	and.l %d1,%d3
	moveq #1,%d5
	move.l %d1,%d2
	lsr.l #5,%d2
	move.l %d1,%d0
.L95:
	tst.l dl_bypass_unbound
	jeq .L96
	lea dl_pool_base,%a0
	tst.l (%a0,%d2.l*4)
	jeq .L97
	moveq #12,%d4
	muls.l %d3,%d4
	move.l %d4,%a0
	add.l #dl_catalog+9,%a0
	tst.b (%a0)
	jne .L98
	move.l %d2,%d4
	lsl.l #5,%d4
	lea dl_codes,%a0
	move.l %d4,%d7
	add.l %d3,%d7
	lsl.l #4,%d7
	tst.w 8(%a0,%d7.l)
	jeq .L99
	mvz.w #192,%d7
	muls.l %d2,%d7
	move.l %d7,-20(%fp)
	mov3q.l #6,%d7
	muls.l %d3,%d7
	add.l -20(%fp),%d7
	move.l %d7,%a2
	add.l #allocator,%a2
	move.l %a2,-32(%fp)
	tst.b 412(%a2)
	jne .L100
	tst.b 28(%a2)
	jne .L101
	lea stubbed,%a2
	move.l (%a2,%d2.l*4),%d7
	btst %d3,%d7
	jne .L102
	move.l -32(%fp),%a2
	move.w 408(%a2),%d0
	tst.b %d5
	jeq .L94
	move.l %d1,cursor
.L94:
	add.l %d3,%d4
	lsl.l #4,%d4
	mvz.w %d0,%d0
	mov3q.l #3,%d7
	add.l #64,%d0
	add.l %d4,%a0
	mvz.w 12(%a0),%d1
	mvz.w 10(%a0),%d4
	add.l %d0,%d1
	add.l %d4,%d0
	cmp.l %a1,%d7
	jeq .L122
	mov3q.l #4,%d4
	cmp.l %a1,%d4
	jeq .L124
	tst.l dl_bypass_unbound
	jne .L124
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	mov3q.l #5,%a0
	move.l %a0,-(%sp)
	move.l %d2,-(%sp)
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
	jra .L107
.L214:
	tst.l %d0
	jeq .L49
.L42:
	move.l cursor,-(%sp)
	move.l %d1,-28(%fp)
	jsr dl_job_status
	addq.l #4,%sp
	tst.l %d0
	jeq .L36
	move.l cursor,-(%sp)
	move.l %d0,-24(%fp)
	jsr dl_job_release
	clr.l waiting
	addq.l #4,%sp
	move.l -28(%fp),%d1
	tst.l -24(%fp)
	jlt .L45
	move.l cursor,%d0
	lea dl_pool_base,%a0
	tst.l (%a0,%d0.l*4)
	jeq .L45
	addq.l #1,%d0
	move.l %d0,cursor
	jra .L48
.L81:
	mov3q.l #7,%d7
	cmp.l %a1,%d7
	jeq .L83
.L71:
	mov3q.l #7,phase
	mov3q.l #7,%a1
	clr.l cursor
	clr.l %d0
	jra .L76
.L149:
	clr.l -(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	mov3q.l #1,-(%sp)
	move.l %d4,-(%sp)
	mov3q.l #1,cursor
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
.L227:
	movem.l -60(%fp),#1276
	unlk %fp
	rts
.L104:
	move.l %d0,%d1
	moveq #63,%d5
	addq.l #1,%d1
	cmp.l %d0,%d5
	jne .L203
.L82:
	clr.l cursor
	mov3q.l #2,%d7
	cmp.l %a1,%d7
	jeq .L77
	mov3q.l #3,%d0
	cmp.l %a1,%d0
	jne .L78
	movem.l -60(%fp),#1276
	mov3q.l #4,phase
	unlk %fp
	rts
.L97:
	move.l %d0,%d1
	moveq #63,%d7
	addq.l #1,%d1
	cmp.l %d0,%d7
	jeq .L82
.L203:
	moveq #31,%d3
	and.l %d1,%d3
	moveq #1,%d5
	move.l %d1,%d2
	lsr.l #5,%d2
	move.l %d1,%d0
.L225:
	mov3q.l #4,%d4
	cmp.l %a1,%d4
	jne .L88
	jra .L95
.L105:
	move.l %d0,%d1
	moveq #63,%d5
	addq.l #1,%d1
	cmp.l %d0,%d5
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d5
	lsr.l #5,%d2
	jra .L88
.L58:
	mov3q.l #-1,result
	addq.l #1,dl_residency_failures
	tst.l %d1
	jeq .L47
	mov3q.l #2,%d4
	move.l %d4,dl_modal_pending
.L47:
	clr.l phase
.L228:
	movem.l -60(%fp),#1276
	unlk %fp
	rts
.L63:
	mov3q.l #2,%d7
	cmp.l automatic.l,%d7
	jne .L36
	lea desired,%a0
	mov3q.l #1,%d1
	move.l #-2147479868,%a1
	move.l #desired+16,%d3
	sub.l %a0,%a1
.L66:
	move.b (%a1,%a0.l),%d0
	move.b (%a0)+,%d2
	eor.l %d2,%d0
	tst.b %d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	and.l %d0,%d1
	cmp.l %d3,%a0
	jne .L66
	tst.l %d1
	jeq .L36
	move.l current,-(%sp)
	jsr dl_selection_commit
	movem.l -60(%fp),#1276
	addq.l #4,%sp
	unlk %fp
	rts
.L98:
	move.l %d0,%d1
	moveq #63,%d7
	addq.l #1,%d1
	cmp.l %d0,%d7
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d5
	lsr.l #5,%d2
	jra .L95
.L216:
	clr.l -(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	pea dl_catalog
	pea allocator
	move.l %d1,-28(%fp)
	jsr dl_allocator_init
	mov3q.l #1,initialized
	lea (24,%sp),%sp
	move.l -28(%fp),%d1
	tst.w allocator+4.l
	jne .L54
	jra .L224
.L99:
	move.l %d0,%d1
	moveq #63,%d2
	addq.l #1,%d1
	cmp.l %d0,%d2
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d5
	lsr.l #5,%d2
	jra .L225
.L220:
	lea stubbed,%a0
	not.l %d3
	addq.l #1,%d0
	and.l %d3,(%a0,%d2.l*4)
	move.l %d0,cursor
	tst.l cancelling
	jne .L71
	move.l cursor,%d0
	moveq #63,%d5
	cmp.l %d0,%d5
	jcc .L76
	jra .L82
.L83:
	move.l cursor,%d0
	moveq #63,%d2
	cmp.l %d0,%d2
	jcc .L76
	move.l current,-(%sp)
	clr.l cursor
	pea allocator
	jsr dl_allocator_cancel
	clr.l phase
	addq.l #1,dl_residency_rollbacks
	jra .L206
.L221:
	move.b allocator+825,%d0
	btst #0,%d0
	jne .L226
	mov3q.l #1,%d2
	btst #1,%d0
	jne .L114
.L113:
	mov3q.l #5,phase
	mov3q.l #1,result
	tst.l automatic
	jeq .L36
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_commit
	movem.l -60(%fp),#1276
	mov3q.l #6,phase
	addq.l #8,%sp
	addq.l #1,dl_residency_commits
	unlk %fp
	jra counts
.L226:
	clr.l %d2
.L114:
	move.l %d2,-(%sp)
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_ack
	lea (12,%sp),%sp
	subq.l #1,%d2
	tst.l %d2
	jeq .L113
	move.b allocator+825,%d0
	mov3q.l #1,%d2
	btst #1,%d0
	jeq .L113
	jra .L114
.L77:
	movem.l -60(%fp),#1276
	mov3q.l #3,phase
	unlk %fp
	rts
.L124:
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	mov3q.l #6,%a0
	move.l %a0,-(%sp)
	move.l %d2,-(%sp)
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
	jra .L107
.L122:
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	mov3q.l #4,%a0
	move.l %a0,-(%sp)
	move.l %d2,-(%sp)
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
	jra .L107
.L223:
	clr.l %d2
	jra .L64
.L215:
	clr.l -(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	mov3q.l #1,-(%sp)
	move.l %d0,%d4
	move.l %d4,-(%sp)
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
	jra .L227
.L217:
	move.l automatic,%d1
	moveq #-2,%d2
	cmp.l %d0,%d2
	jeq .L57
	mov3q.l #-1,%d5
	cmp.l %d0,%d5
	jeq .L58
	addq.l #5,%d0
	tst.l %d0
	jeq .L58
	moveq #-3,%d0
	move.l %d0,result
	addq.l #1,dl_residency_failures
	tst.l %d1
	jeq .L47
	move.l %d4,dl_modal_pending
	jra .L47
.L121:
	clr.b %d6
	move.l #allocator,%d5
.L84:
	mvz.w #192,%d4
	mov3q.l #6,%d7
	muls.l %d3,%d7
	muls.l %d2,%d4
	move.l %d7,%a0
	add.l %d4,%a0
	add.l %d5,%a0
	tst.b 28(%a0)
	jeq .L91
	tst.b 412(%a0)
	jne .L92
	move.l %d2,%d4
	move.w 408(%a0),%d0
	lsl.l #5,%d4
	tst.b %d6
	jeq .L205
	move.l %d1,cursor
.L205:
	lea dl_codes,%a0
	jra .L94
.L91:
	move.l %d0,%d1
	moveq #63,%d7
	addq.l #1,%d1
	cmp.l %d0,%d7
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d6
	lsr.l #5,%d2
	jra .L84
.L92:
	move.l %d0,%d1
	moveq #63,%d2
	addq.l #1,%d1
	cmp.l %d0,%d2
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d6
	lsr.l #5,%d2
	jra .L84
.L222:
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_retire
	movem.l -60(%fp),#1276
	clr.l phase
	addq.l #8,%sp
	unlk %fp
	jra counts
.L219:
	moveq #-3,%d0
	move.l %d0,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L70
	mov3q.l #1,dl_modal_pending
.L70:
	subq.l #6,%a1
	mov3q.l #1,%d2
	cmp.l %a1,%d2
	jcc .L36
	mov3q.l #1,cancelling
	mov3q.l #7,phase
	mov3q.l #7,%a1
	clr.l cursor
	clr.l %d0
	jra .L76
.L74:
	lea stubbed,%a0
	addq.l #1,%d0
	or.l %d3,(%a0,%d2.l*4)
	move.l cancelling,%a0
	move.l %d0,cursor
.L229:
	tst.l %a0
	jeq .L73
	jra .L81
.L45:
	moveq #-3,%d0
	move.l %d0,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L47
	mov3q.l #1,dl_modal_pending
	clr.l phase
	jra .L228
.L100:
	move.l %d0,%d1
	moveq #63,%d2
	addq.l #1,%d1
	cmp.l %d0,%d2
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d5
	lsr.l #5,%d2
	jra .L95
.L75:
	tst.l dl_bypass_unbound
	jne .L74
	lea stubbed,%a0
	not.l %d3
	and.l %d3,(%a0,%d2.l*4)
	addq.l #1,%d0
	move.l cancelling,%a0
	move.l %d0,cursor
	jra .L229
.L101:
	move.l %d0,%d1
	moveq #63,%d4
	addq.l #1,%d1
	cmp.l %d0,%d4
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d5
	lsr.l #5,%d2
	jra .L225
.L57:
	moveq #-2,%d2
	move.l %d2,result
	addq.l #1,dl_residency_failures
	tst.l %d1
	jeq .L47
	mov3q.l #3,%d4
	move.l %d4,dl_modal_pending
	jra .L47
.L102:
	move.l %d0,%d1
	moveq #63,%d4
	addq.l #1,%d1
	cmp.l %d0,%d4
	jeq .L82
	moveq #31,%d3
	move.l %d1,%d2
	move.l %d1,%d0
	and.l %d1,%d3
	moveq #1,%d5
	lsr.l #5,%d2
	jra .L95
.L213:
	move.l %d2,%d4
	lsl.l #5,%d4
	lea dl_codes,%a0
	jra .L94
	.size	advance, .-advance
	.align	2
	.globl	dl_selection_prepare
	.type	dl_selection_prepare, @function
dl_selection_prepare:
	move.l %d2,-(%sp)
	tst.l dl_residency_enabled
	jne .L241
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	rts
.L241:
	jsr dl_publication_finish
	jsr advance
	jsr advance
	tst.l phase
	jne .L233
	move.l 8(%sp),%a0
	move.l 8(%sp),%d1
	add.l #80,%d1
	lea (72,%a0),%a0
.L234:
	mvz.b (%a0),%d0
	addq.l #1,%a0
	mov3q.l #4,%d2
	cmp.l %d0,%d2
	jcs .L233
	cmp.l %a0,%d1
	jne .L234
	move.l 8(%sp),%a1
	lea desired,%a0
	lea (48,%a1),%a1
.L235:
	move.b (%a1)+,(%a0)+
	cmp.l #desired+16,%a0
	jne .L235
	lea (12,%sp),%a0
	move.l (%a0),current
	clr.l automatic
	clr.l result
	mov3q.l #1,phase
	clr.l cursor
	clr.l waiting
	clr.l cancelling
	jsr advance
	move.l (%sp)+,%d2
	move.l result,%d0
	rts
.L233:
	move.l (%sp)+,%d2
	moveq #-3,%d0
	rts
	.size	dl_selection_prepare, .-dl_selection_prepare
	.align	2
	.globl	dl_selection_poll
	.type	dl_selection_poll, @function
dl_selection_poll:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jne .L244
	jsr advance
	move.l result,%d0
	rts
.L244:
	moveq #-3,%d0
	rts
	.size	dl_selection_poll, .-dl_selection_poll
	.align	2
	.globl	dl_residency_tick
	.type	dl_residency_tick, @function
dl_residency_tick:
	lea (-56,%sp),%sp
	movem.l #19708,(%sp)
	tst.l dl_residency_enabled
	jne .L301
.L247:
	movem.l (%sp),#19708
	lea (56,%sp),%sp
	rts
.L301:
	jsr advance
	jsr dl_publication_tick
	clr.l %d2
	lea dl_catalog,%a2
.L251:
	move.l %d2,%d0
	lsr.l #2,%d0
	mov3q.l #1,%d1
	move.l %d2,%a0
	add.l #-2147479868,%a0
	moveq #12,%d3
	moveq #31,%d4
	and.l %d1,%d0
	mvz.b (%a0),%d1
	muls.l %d1,%d3
	cmp.l %d1,%d4
	jcs .L249
	tst.b 9(%a2,%d3.l)
	jne .L249
	move.l %d1,-(%sp)
	mov3q.l #1,%d1
	eor.l %d0,%d1
	move.l %d1,-(%sp)
	jsr slot_bound
	addq.l #8,%sp
	tst.l %d0
	jne .L249
	move.l unsafe_valid,%d2
	move.l #-2147479868,%a2
	lea unsafe,%a1
	move.l %a1,%a0
	sub.l %a1,%a2
.L254:
	move.b (%a2,%a0.l),%d0
	mvz.b (%a0)+,%d1
	mvz.b %d0,%d0
	cmp.l %d1,%d0
	jeq .L253
	clr.l %d2
.L253:
	cmp.l #unsafe+16,%a0
	jne .L254
	tst.l %d2
	jne .L255
.L256:
	move.b (%a2,%a1.l),%d0
	move.b %d0,(%a1)+
	cmp.l #unsafe+16,%a1
	jne .L256
	mov3q.l #1,unsafe_valid
	addq.l #1,dl_unguarded
.L255:
	tst.l dl_reinit_enabled
	jeq .L257
	clr.l %d2
	lea last,%a3
	lea slot_bound,%a6
.L262:
	mov3q.l #1,%d4
	lsl.l %d2,%d4
	move.l %d2,%d1
	lsr.l #2,%d1
	mov3q.l #1,%d0
	move.l parked,%d5
	move.l %d2,%a2
	add.l #-2147479868,%a2
	and.l %d0,%d1
	move.b (%a2),%d7
	mov3q.l #1,%d3
	move.l %d4,%d0
	and.l %d5,%d0
	eor.l %d3,%d1
	mvz.b %d7,%d3
	tst.l %d0
	jeq .L258
	tst.l %d3
	jeq .L259
	move.l %d4,%d0
	not.l %d0
	and.l %d5,%d0
	move.l %d0,parked
.L258:
	mvz.b (%a3,%d2.l),%d0
	cmp.l %d3,%d0
	jeq .L261
	moveq #31,%d0
	cmp.l %d3,%d0
	jcs .L261
	moveq #12,%d0
	muls.l %d3,%d0
	lea dl_catalog,%a0
	tst.b 9(%a0,%d0.l)
	jne .L261
	move.l %d3,-(%sp)
	move.l %d1,-(%sp)
	move.l %d1,44(%sp)
	jsr (%a6)
	addq.l #8,%sp
	move.l 36(%sp),%d1
	tst.l %d0
	jne .L261
	move.l dl_stub_at_boot,%d0
	lea stubbed,%a0
	or.l (%a0,%d1.l*4),%d0
	btst %d3,%d0
	jne .L302
.L261:
	move.b %d7,(%a3,%d2.l)
.L260:
	addq.l #1,%d2
	moveq #16,%d1
	cmp.l %d2,%d1
	jne .L262
.L257:
	move.l phase,%d0
	tst.l %d0
	jne .L247
	move.l parked,%d2
	lea (40,%sp),%a1
	move.l %a1,%a0
	lea owed_id,%a3
.L265:
	move.l %d0,%a2
	add.l #-2147479868,%a2
	btst %d0,%d2
	jeq .L263
	move.b (%a3,%d0.l),%d1
	addq.l #1,%d0
	moveq #16,%d3
	move.b %d1,(%a0)+
	cmp.l %d0,%d3
	jne .L265
.L304:
	tst.l observed_valid
	seq %d1
	lea observed,%a3
	move.l %a1,%d3
	move.l %a3,%a2
	add.l #16,%d3
	move.l %a1,%a0
	mvs.b %d1,%d1
	neg.l %d1
.L266:
	move.b (%a0)+,%d0
	move.b (%a2)+,%d2
	eor.l %d2,%d0
	tst.b %d0
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d1
	cmp.l %a0,%d3
	jne .L266
	tst.l %d1
	jeq .L247
	lea observed,%a0
.L267:
	move.b (%a1)+,(%a0)+
	cmp.l %a1,%d3
	jne .L267
	move.l auto_serial,%d0
	addq.l #1,%d0
	mov3q.l #1,observed_valid
	tst.l %d0
	jne .L303
	move.l #-2147483648,%d1
	move.l %d1,%d0
	move.l %d1,auto_serial
	lea desired,%a0
.L269:
	move.b (%a3)+,(%a0)+
	cmp.l #observed+16,%a3
	jne .L269
	movem.l (%sp),#19708
	move.l %d0,current
	mov3q.l #1,automatic
	clr.l result
	mov3q.l #1,phase
	clr.l cursor
	clr.l waiting
	clr.l cancelling
	lea (56,%sp),%sp
	rts
.L263:
	move.b (%a2),%d1
	addq.l #1,%d0
	moveq #16,%d3
	move.b %d1,(%a0)+
	cmp.l %d0,%d3
	jne .L265
	jra .L304
.L249:
	addq.l #1,%d2
	moveq #16,%d3
	cmp.l %d2,%d3
	jne .L251
	clr.l unsafe_valid
	jra .L255
.L259:
	lea owed_id,%a0
	move.b (%a0,%d2.l),%d3
	mvz.b %d3,%d0
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr (%a6)
	addq.l #8,%sp
	tst.l %d0
	jeq .L260
	not.l %d4
	move.b %d3,(%a2)
	and.l %d5,%d4
	move.b %d3,(%a3,%d2.l)
	addq.l #1,%d2
	moveq #16,%d1
	addq.l #1,dl_reinit
	move.l %d4,parked
	cmp.l %d2,%d1
	jne .L262
	jra .L257
.L302:
	clr.b %d0
	clr.b (%a2)
	lea owed_id,%a0
	moveq #16,%d1
	move.b %d7,(%a0,%d2.l)
	or.l %d4,parked
	move.b %d0,(%a3,%d2.l)
	addq.l #1,dl_parked
	addq.l #1,%d2
	cmp.l %d2,%d1
	jne .L262
	jra .L257
.L303:
	move.l %d0,%d1
	move.l %d1,auto_serial
	lea desired,%a0
	jra .L269
	.size	dl_residency_tick, .-dl_residency_tick
	.align	2
	.globl	dl_publication_prepare
	.type	dl_publication_prepare, @function
dl_publication_prepare:
	move.l %d2,-(%sp)
	tst.l phase
	jne .L308
	move.l 12(%sp),%a0
	move.l %a0,%d1
	addq.l #8,%d1
.L309:
	addq.l #1,%a0
	mvz.b -1(%a0),%d0
	mov3q.l #4,%d2
	cmp.l %d0,%d2
	jcs .L308
	cmp.l %a0,%d1
	jne .L309
	move.l 8(%sp),%a1
	lea desired,%a0
.L310:
	move.b (%a1)+,(%a0)+
	cmp.l #desired+16,%a0
	jne .L310
	lea (16,%sp),%a0
	move.l (%a0),current
	clr.l automatic
	clr.l result
	mov3q.l #1,phase
	clr.l cursor
	clr.l waiting
	clr.l cancelling
	jsr advance
	move.l (%sp)+,%d2
	move.l result,%d0
	rts
.L308:
	move.l (%sp)+,%d2
	moveq #-3,%d0
	rts
	.size	dl_publication_prepare, .-dl_publication_prepare
	.align	2
	.globl	dl_publication_poll
	.type	dl_publication_poll, @function
dl_publication_poll:
	move.l current,%d0
	cmp.l 4(%sp),%d0
	jne .L317
	jsr advance
	move.l result,%d0
	rts
.L317:
	moveq #-3,%d0
	rts
	.size	dl_publication_poll, .-dl_publication_poll
	.align	2
	.globl	dl_publication_arm
	.type	dl_publication_arm, @function
dl_publication_arm:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jeq .L324
.L320:
	rts
.L324:
	mov3q.l #5,%d0
	cmp.l phase.l,%d0
	jne .L320
	mov3q.l #1,%d0
	cmp.l result.l,%d0
	jne .L320
	mov3q.l #2,automatic
	rts
	.size	dl_publication_arm, .-dl_publication_arm
	.align	2
	.globl	dl_publication_ready
	.type	dl_publication_ready, @function
dl_publication_ready:
	lea (-36,%sp),%sp
	movem.l #7228,(%sp)
	move.l 40(%sp),%a1
	tst.l dl_residency_enabled
	jeq .L326
	clr.l %d1
	clr.l %d3
	lea dl_catalog,%a2
.L333:
	mvz.b (%a1,%d1.l),%d2
	moveq #12,%d0
	moveq #31,%d4
	muls.l %d2,%d0
	cmp.l %d2,%d4
	jcs .L327
.L363:
	lea (%a2,%d0.l),%a0
	tst.b 10(%a0)
	jeq .L327
	move.b 8(%a0),%d0
	mov3q.l #7,%d5
	cmp.l %d1,%d5
	jcs .L330
	addq.l #1,%d1
	btst #0,%d0
	jeq .L327
	tst.b 9(%a0)
	seq %d0
	mvz.b (%a1,%d1.l),%d2
	moveq #31,%d4
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d3
	moveq #12,%d0
	muls.l %d2,%d0
	cmp.l %d2,%d4
	jcc .L363
.L327:
	movem.l (%sp),#7228
	clr.l %d0
	lea (36,%sp),%sp
	rts
.L330:
	addq.l #1,%d1
	btst #1,%d0
	jeq .L327
	tst.b 9(%a0)
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d3
	moveq #16,%d0
	cmp.l %d1,%d0
	jne .L333
	tst.l %d3
	jeq .L326
	tst.l initialized
	jeq .L327
	move.l phase,%d2
	move.l %d2,32(%sp)
	subq.l #5,%d2
	tst.l %d2
	jeq .L364
.L335:
	clr.l %d1
	move.l %a1,%a3
	move.l #desired+16,%d3
	lea desired,%a0
.L338:
	move.b (%a3)+,%d0
	move.b (%a0)+,%d4
	eor.l %d4,%d0
	tst.b %d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	and.l %d0,%d1
	cmp.l %d3,%a0
	jne .L338
	sub.l %a3,%a3
.L344:
	mvz.b (%a1,%a3.l),%d2
	moveq #12,%d0
	muls.l %d2,%d0
	tst.b 9(%a2,%d0.l)
	jne .L339
	move.l %a3,%d0
	lsr.l #2,%d0
	mov3q.l #1,%d3
	mov3q.l #6,%d5
	muls.l %d2,%d5
	and.l %d3,%d0
	lea allocator,%a4
	move.l %d5,%a0
	move.l %d5,28(%sp)
	eor.l %d3,%d0
	mvz.w #192,%d3
	muls.l %d0,%d3
	add.l %d3,%a0
	tst.b 28(%a4,%a0.l)
	jeq .L340
	mov3q.l #7,%d4
	cmp.l 32(%sp),%d4
	jcs .L345
	mvz.w #161,%d4
	move.l 32(%sp),%d5
	btst %d5,%d4
	jne .L339
.L345:
	mvz.b %d0,%d0
	clr.l %d4
	move.l %d0,%a0
.L343:
	move.l %d4,%d0
	lsr.l #2,%d0
	mov3q.l #1,%d5
	and.l %d5,%d0
	eor.l %d5,%d0
	cmp.l %a0,%d0
	jeq .L365
	addq.l #1,%d4
	moveq #16,%d0
	cmp.l %d4,%d0
	jne .L343
.L340:
	tst.l %d1
	jeq .L327
	move.l 28(%sp),%a0
	add.l %d3,%a0
	add.l #allocator+412,%a0
	tst.b (%a0)
	jeq .L327
.L339:
	addq.l #1,%a3
	moveq #16,%d2
	cmp.l %a3,%d2
	jne .L344
.L326:
	movem.l (%sp),#7228
	mov3q.l #1,%d0
	lea (36,%sp),%sp
	rts
.L365:
	lea desired,%a4
	mvz.b (%a4,%d4.l),%d0
	cmp.l %d2,%d0
	jeq .L339
	addq.l #1,%d4
	moveq #16,%d0
	cmp.l %d4,%d0
	jne .L343
	jra .L340
.L364:
	mov3q.l #1,%d4
	cmp.l result.l,%d4
	jne .L335
	tst.l cancelling
	seq %d1
	move.l %a1,%a3
	move.l #desired+16,%d3
	lea desired,%a0
	mvs.b %d1,%d1
	neg.l %d1
	jra .L338
	.size	dl_publication_ready, .-dl_publication_ready
	.align	2
	.globl	dl_publication_idle
	.type	dl_publication_idle, @function
dl_publication_idle:
	tst.l phase
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	rts
	.size	dl_publication_idle, .-dl_publication_idle
	.data
	.align	2
	.type	unsafe_valid, @object
	.size	unsafe_valid, 4
unsafe_valid:
	.zero	4
	.type	unsafe, @object
	.size	unsafe, 16
unsafe:
	.zero	16
	.globl	dl_reinit_enabled
	.align	2
	.type	dl_reinit_enabled, @object
	.size	dl_reinit_enabled, 4
dl_reinit_enabled:
	.long	1
	.globl	dl_parked
	.align	2
	.type	dl_parked, @object
	.size	dl_parked, 4
dl_parked:
	.zero	4
	.globl	dl_reinit
	.align	2
	.type	dl_reinit, @object
	.size	dl_reinit, 4
dl_reinit:
	.zero	4
	.align	2
	.type	parked, @object
	.size	parked, 4
parked:
	.zero	4
	.type	owed_id, @object
	.size	owed_id, 16
owed_id:
	.zero	16
	.type	last, @object
	.size	last, 16
last:
	.base64	"/////////////////////w=="
	.globl	dl_unguarded
	.align	2
	.type	dl_unguarded, @object
	.size	dl_unguarded, 4
dl_unguarded:
	.zero	4
	.globl	dl_residency_words
	.align	2
	.type	dl_residency_words, @object
	.size	dl_residency_words, 8
dl_residency_words:
	.zero	8
	.globl	dl_residency_failures
	.align	2
	.type	dl_residency_failures, @object
	.size	dl_residency_failures, 4
dl_residency_failures:
	.zero	4
	.globl	dl_residency_rollbacks
	.align	2
	.type	dl_residency_rollbacks, @object
	.size	dl_residency_rollbacks, 4
dl_residency_rollbacks:
	.zero	4
	.globl	dl_residency_commits
	.align	2
	.type	dl_residency_commits, @object
	.size	dl_residency_commits, 4
dl_residency_commits:
	.zero	4
	.align	2
	.type	stubbed, @object
	.size	stubbed, 8
stubbed:
	.zero	8
	.globl	dl_bypass_unbound
	.align	2
	.type	dl_bypass_unbound, @object
	.size	dl_bypass_unbound, 4
dl_bypass_unbound:
	.long	1
	.globl	dl_residency_enabled
	.align	2
	.type	dl_residency_enabled, @object
	.size	dl_residency_enabled, 4
dl_residency_enabled:
	.long	1
	.align	2
	.type	result, @object
	.size	result, 4
result:
	.zero	4
	.align	2
	.type	current, @object
	.size	current, 4
current:
	.zero	4
	.align	2
	.type	cancelling, @object
	.size	cancelling, 4
cancelling:
	.zero	4
	.align	2
	.type	automatic, @object
	.size	automatic, 4
automatic:
	.zero	4
	.align	2
	.type	waiting, @object
	.size	waiting, 4
waiting:
	.zero	4
	.align	2
	.type	cursor, @object
	.size	cursor, 4
cursor:
	.zero	4
	.align	2
	.type	phase, @object
	.size	phase, 4
phase:
	.zero	4
	.align	2
	.type	initialized, @object
	.size	initialized, 4
initialized:
	.zero	4
	.align	2
	.type	auto_serial, @object
	.size	auto_serial, 4
auto_serial:
	.long	-2147483648
	.align	2
	.type	observed_valid, @object
	.size	observed_valid, 4
observed_valid:
	.zero	4
	.type	observed, @object
	.size	observed, 16
observed:
	.zero	16
	.type	desired, @object
	.size	desired, 16
desired:
	.zero	16
	.align	2
	.type	allocator, @object
	.size	allocator, 828
allocator:
	.zero	828
