| Generated by generate.py from manager.c.
#NO_APP
	.file	"manager.c"
	.text
	.align	2
	.type	counts, @function
counts:
	move.l %d2,-(%sp)
	lea allocator+26,%a1
	clr.l %d0
	lea allocator+218,%a0
.L3:
	tst.b 2(%a1)
	jeq .L2
	mvz.w (%a1),%d1
	add.l %d1,%d0
.L2:
	addq.l #6,%a1
	cmp.l %a0,%a1
	jne .L3
	move.l %d0,dl_residency_words
	move.l #allocator+410,%d1
	clr.l %d0
.L5:
	tst.b 2(%a0)
	jeq .L4
	mvz.w (%a0),%d2
	add.l %d2,%d0
.L4:
	addq.l #6,%a0
	cmp.l %d1,%a0
	jne .L5
	move.l (%sp)+,%d2
	move.l %d0,dl_residency_words+4
	rts
	.size	counts, .-counts
	.align	2
	.globl	dl_selection_cancel
	.type	dl_selection_cancel, @function
dl_selection_cancel:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jeq .L20
.L10:
	rts
.L20:
	move.l phase,%d0
	tst.l %d0
	jeq .L10
	subq.l #6,%d0
	tst.l %d0
	jeq .L10
	mov3q.l #1,cancelling
	rts
	.size	dl_selection_cancel, .-dl_selection_cancel
	.align	2
	.globl	dl_selection_commit
	.type	dl_selection_commit, @function
dl_selection_commit:
	move.l current,%d0
	cmp.l 4(%sp),%d0
	jne .L21
	mov3q.l #5,%d1
	cmp.l phase.l,%d1
	jeq .L26
.L21:
	rts
.L26:
	mov3q.l #1,%d1
	cmp.l result.l,%d1
	jne .L21
	move.l %d0,-(%sp)
	pea allocator
	jsr dl_allocator_commit
	addq.l #8,%sp
	subq.l #1,%d0
	tst.l %d0
	jeq .L23
	moveq #-3,%d0
	move.l %d0,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L21
	mov3q.l #1,dl_modal_pending
	rts
.L23:
	mov3q.l #6,phase
	clr.l cursor
	addq.l #1,dl_residency_commits
	jra counts
	.size	dl_selection_commit, .-dl_selection_commit
	.align	2
	.type	advance, @function
advance:
	link.w %fp,#-52
	movem.l #1148,(%sp)
	move.l phase,%d3
	tst.l %d3
	jeq .L27
	mov3q.l #1,%d0
	cmp.l %d3,%d0
	jeq .L145
	subq.l #5,%d3
	tst.l %d3
	jeq .L146
	tst.l waiting
	jne .L56
.L152:
	move.l phase,%d2
	move.l cancelling,%d0
	move.l %d2,-20(%fp)
	tst.l %d0
	jne .L61
.L153:
	move.l cursor,%d0
	moveq #63,%d1
	cmp.l %d0,%d1
	jcs .L63
.L62:
	moveq #31,%d2
	mov3q.l #6,%d3
	move.l %d0,%d1
	move.l #allocator,%d4
	and.l %d0,%d2
	clr.b %d5
	lsr.l #5,%d1
	cmp.l -20(%fp),%d3
	jeq .L65
.L66:
	mov3q.l #6,%d3
	muls.l %d2,%d3
	addq.l #1,%d0
	move.l %d3,%a1
	mvz.w #192,%d3
	muls.l %d1,%d3
	lea (%a1,%d3.l),%a0
	add.l %d4,%a0
	tst.b 412(%a0)
	jeq .L74
	tst.b 28(%a0)
	jne .L75
	tst.b %d5
	jeq .L76
	move.l -28(%fp),%d5
	move.l %d5,cursor
.L76:
	add.l %d3,%a1
	add.l #allocator+408,%a1
	move.w (%a1),%d0
	mov3q.l #2,%d6
	cmp.l -20(%fp),%d6
	jne .L73
	move.l %d1,%d3
	add.l #64,%d0
	lsl.l #5,%d3
	pea -14(%fp)
	move.l %d1,-(%sp)
	move.w %d0,-2(%fp)
	lea dl_codes,%a1
	move.l %d3,%d0
	add.l %d2,%d0
	lsl.l #4,%d0
	lea (%a1,%d0.l),%a0
	move.w 8(%a0),-6(%fp)
	move.w 14(%a0),-4(%fp)
	move.l (%a0),-14(%fp)
	move.l 4(%a0),-10(%fp)
	jsr dl_upload_start
	addq.l #8,%sp
	move.l %d0,waiting
	tst.l %d0
	jeq .L147
.L27:
	movem.l -52(%fp),#1148
	unlk %fp
	rts
.L145:
	lea desired,%a0
	clr.l %d2
	lea desired+16,%a1
.L31:
	mvz.b (%a0)+,%d0
	moveq #12,%d1
	moveq #31,%d5
	muls.l %d0,%d1
	cmp.l %d0,%d5
	jcs .L30
	lea dl_catalog,%a2
	tst.b 9(%a2,%d1.l)
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d2
.L30:
	cmp.l %a1,%a0
	jne .L31
	move.l waiting,%d0
	tst.l %d2
	jeq .L148
	tst.l %d0
	jne .L33
	move.l cursor,%d0
.L39:
	mov3q.l #1,%d2
	cmp.l %d0,%d2
	jcs .L34
	lea dl_pool_base,%a0
	tst.l (%a0,%d0.l*4)
	jeq .L149
	subq.l #1,%d0
	tst.l %d0
	jeq .L40
	tst.l dl_pool_base+4
	jeq .L107
.L40:
	mov3q.l #2,cursor
.L34:
	tst.l cancelling
	jne .L38
	tst.l initialized
	jeq .L150
.L44:
	move.l current,-(%sp)
	pea desired
	pea allocator
	jsr dl_allocator_prepare
	lea (12,%sp),%sp
	tst.l %d0
	jlt .L151
	mov3q.l #2,phase
	clr.l cursor
	tst.l waiting
	jeq .L152
.L56:
	move.l cursor,%d2
	lsr.l #5,%d2
.L53:
	move.l %d2,-(%sp)
	jsr dl_job_status
	addq.l #4,%sp
	tst.l %d0
	jeq .L27
	move.l %d2,-(%sp)
	move.l %d0,-24(%fp)
	jsr dl_job_release
	move.l phase,%d3
	addq.l #4,%sp
	clr.l waiting
	move.l %d3,-20(%fp)
	tst.l -24(%fp)
	jlt .L58
	move.l cancelling,%d0
	addq.l #1,cursor
	tst.l %d0
	jeq .L153
	jra .L61
.L146:
	tst.l cancelling
	jeq .L52
	mov3q.l #7,phase
	clr.l cursor
	tst.l waiting
	jne .L154
	clr.l %d0
	moveq #31,%d2
	mov3q.l #6,%d3
	move.l %d0,%d1
	move.l #allocator,%d4
	and.l %d0,%d2
	clr.b %d5
	lsr.l #5,%d1
	mov3q.l #7,-20(%fp)
	cmp.l -20(%fp),%d3
	jne .L66
	jra .L65
.L70:
	moveq #64,%d1
	cmp.l %d0,%d1
	jeq .L63
	moveq #31,%d2
	and.l %d0,%d2
	moveq #1,%d5
	move.l %d0,%d1
	lsr.l #5,%d1
	move.l %d0,-28(%fp)
.L65:
	mvz.w #192,%d3
	mov3q.l #6,%d6
	muls.l %d2,%d6
	addq.l #1,%d0
	muls.l %d1,%d3
	move.l %d6,%a0
	add.l %d3,%a0
	add.l %d4,%a0
	tst.b 28(%a0)
	jeq .L70
	tst.b 412(%a0)
	jne .L71
	move.w 408(%a0),%d0
	tst.b %d5
	jeq .L73
	move.l -28(%fp),%a0
	move.l %a0,cursor
.L73:
	mvz.w %d0,%d0
	move.l %d0,%a1
	move.l %d1,%d0
	lsl.l #5,%d0
	lea (64,%a1),%a1
	add.l %d2,%d0
	lsl.l #4,%d0
	move.l %d0,%a0
	add.l #dl_codes,%a0
	mvz.w 10(%a0),%d0
	mvz.w 12(%a0),%d3
	lea (%a1,%d3.l),%a0
	add.l %d0,%a1
	mov3q.l #3,%d0
	cmp.l -20(%fp),%d0
	jeq .L155
	move.l %a0,-(%sp)
	move.l %a1,-(%sp)
	move.l %d2,-(%sp)
	mov3q.l #5,%d0
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
.L160:
	tst.l %d0
	jne .L27
	jra .L147
.L148:
	tst.l %d0
	jeq .L40
.L33:
	move.l cursor,-(%sp)
	jsr dl_job_status
	addq.l #4,%sp
	tst.l %d0
	jeq .L27
	move.l cursor,-(%sp)
	move.l %d0,-24(%fp)
	jsr dl_job_release
	clr.l waiting
	addq.l #4,%sp
	tst.l -24(%fp)
	jlt .L36
	lea dl_pool_base,%a0
	move.l cursor,%d0
	tst.l (%a0,%d0.l*4)
	jeq .L36
	addq.l #1,%d0
	move.l %d0,cursor
	jra .L39
.L61:
	mov3q.l #7,%d2
	cmp.l -20(%fp),%d2
	jeq .L64
	mov3q.l #7,phase
	mov3q.l #7,-20(%fp)
	clr.l cursor
	clr.l %d0
.L162:
	moveq #31,%d2
	mov3q.l #6,%d3
	move.l %d0,%d1
	move.l #allocator,%d4
	lsr.l #5,%d1
	and.l %d0,%d2
	clr.b %d5
	cmp.l -20(%fp),%d3
	jne .L66
	jra .L65
.L107:
	clr.l -(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	mov3q.l #1,-(%sp)
	move.l %d3,-(%sp)
	mov3q.l #1,cursor
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
.L161:
	movem.l -52(%fp),#1148
	unlk %fp
	rts
.L74:
	moveq #64,%d5
	cmp.l %d0,%d5
	jne .L140
.L63:
	clr.l cursor
	mov3q.l #2,%d2
	cmp.l -20(%fp),%d2
	jeq .L156
	mov3q.l #3,%d3
	cmp.l -20(%fp),%d3
	jeq .L157
	mov3q.l #6,%d6
	cmp.l -20(%fp),%d6
	jeq .L158
	mov3q.l #7,%d0
	cmp.l -20(%fp),%d0
	jne .L27
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_cancel
	clr.l phase
	addq.l #1,dl_residency_rollbacks
.L141:
	addq.l #8,%sp
	movem.l -52(%fp),#1148
	unlk %fp
	jra counts
.L75:
	moveq #64,%d6
	cmp.l %d0,%d6
	jeq .L63
.L140:
	moveq #31,%d2
	move.l %d0,%d1
	lsr.l #5,%d1
	and.l %d0,%d2
	moveq #1,%d5
	move.l %d0,-28(%fp)
	jra .L66
.L71:
	moveq #64,%d2
	cmp.l %d0,%d2
	jeq .L63
	moveq #31,%d2
	move.l %d0,%d1
	lsr.l #5,%d1
	and.l %d0,%d2
	moveq #1,%d5
	move.l %d0,-28(%fp)
	jra .L65
.L47:
	mov3q.l #-1,result
	addq.l #1,dl_residency_failures
	tst.l %d1
	jeq .L38
	mov3q.l #2,%d3
	move.l %d3,dl_modal_pending
.L38:
	clr.l phase
.L163:
	movem.l -52(%fp),#1148
	unlk %fp
	rts
.L52:
	mov3q.l #2,%d1
	cmp.l automatic.l,%d1
	jne .L27
	lea desired,%a0
	mov3q.l #1,%d1
	move.l #-2147479868,%a1
	sub.l %a0,%a1
.L55:
	move.b (%a1,%a0.l),%d0
	move.b (%a0)+,%d2
	eor.l %d2,%d0
	tst.b %d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	and.l %d0,%d1
	cmp.l #desired+16,%a0
	jne .L55
	tst.l %d1
	jeq .L27
	move.l current,-(%sp)
	jsr dl_selection_commit
	movem.l -52(%fp),#1148
	addq.l #4,%sp
	unlk %fp
	rts
.L157:
	move.b allocator+825,%d0
	btst #0,%d0
	jne .L159
	mov3q.l #1,%d2
	btst #1,%d0
	jne .L84
.L83:
	mov3q.l #5,phase
	mov3q.l #1,result
	tst.l automatic
	jeq .L27
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_commit
	movem.l -52(%fp),#1148
	mov3q.l #6,phase
	addq.l #8,%sp
	addq.l #1,dl_residency_commits
	unlk %fp
	jra counts
.L159:
	clr.l %d2
.L84:
	move.l %d2,-(%sp)
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_ack
	lea (12,%sp),%sp
	subq.l #1,%d2
	tst.l %d2
	jeq .L83
	move.b allocator+825,%d0
	mov3q.l #1,%d2
	btst #1,%d0
	jeq .L83
	jra .L84
.L147:
	moveq #-3,%d1
	move.l %d1,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L79
	mov3q.l #1,dl_modal_pending
.L79:
	mov3q.l #1,cancelling
	movem.l -52(%fp),#1148
	unlk %fp
	rts
.L150:
	clr.l -(%sp)
	clr.l -(%sp)
	pea 1344.w
	pea 1344.w
	pea dl_catalog
	pea allocator
	jsr dl_allocator_init
	mov3q.l #1,initialized
	lea (24,%sp),%sp
	jra .L44
.L64:
	move.l cursor,%d0
	moveq #63,%d1
	cmp.l %d0,%d1
	jcc .L62
	move.l current,-(%sp)
	clr.l cursor
	pea allocator
	jsr dl_allocator_cancel
	clr.l phase
	addq.l #1,dl_residency_rollbacks
	jra .L141
.L156:
	movem.l -52(%fp),#1148
	mov3q.l #3,phase
	unlk %fp
	rts
.L155:
	move.l %a0,-(%sp)
	move.l %a1,-(%sp)
	move.l %d2,-(%sp)
	mov3q.l #4,%d0
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
	jra .L160
.L154:
	clr.l %d2
	jra .L53
.L149:
	clr.l -(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	mov3q.l #1,-(%sp)
	move.l %d0,%d3
	move.l %d3,-(%sp)
	jsr dl_command_start
	lea (20,%sp),%sp
	move.l %d0,waiting
	jra .L161
.L151:
	move.l automatic,%d1
	moveq #-2,%d5
	cmp.l %d0,%d5
	jeq .L46
	mov3q.l #-1,%d6
	cmp.l %d0,%d6
	jeq .L47
	addq.l #5,%d0
	tst.l %d0
	jeq .L47
	moveq #-3,%d5
	move.l %d5,result
	addq.l #1,dl_residency_failures
	tst.l %d1
	jeq .L38
	move.l %d3,dl_modal_pending
	jra .L38
.L158:
	move.l current,-(%sp)
	pea allocator
	jsr dl_allocator_retire
	movem.l -52(%fp),#1148
	clr.l phase
	addq.l #8,%sp
	unlk %fp
	jra counts
.L58:
	moveq #-3,%d5
	move.l %d5,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L59
	mov3q.l #1,dl_modal_pending
.L59:
	mov3q.l #1,%d6
	move.l -20(%fp),%d0
	subq.l #6,%d0
	cmp.l %d0,%d6
	jcc .L27
	mov3q.l #1,cancelling
	mov3q.l #7,phase
	mov3q.l #7,-20(%fp)
	clr.l cursor
	clr.l %d0
	jra .L162
.L36:
	moveq #-3,%d0
	move.l %d0,result
	addq.l #1,dl_residency_failures
	tst.l automatic
	jeq .L38
	mov3q.l #1,dl_modal_pending
	clr.l phase
	jra .L163
.L46:
	moveq #-2,%d6
	move.l %d6,result
	addq.l #1,dl_residency_failures
	tst.l %d1
	jeq .L38
	mov3q.l #3,%d3
	move.l %d3,dl_modal_pending
	jra .L38
	.size	advance, .-advance
	.align	2
	.globl	dl_selection_prepare
	.type	dl_selection_prepare, @function
dl_selection_prepare:
	move.l %d2,-(%sp)
	tst.l dl_residency_enabled
	jne .L175
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	rts
.L175:
	jsr dl_publication_finish
	jsr advance
	jsr advance
	tst.l phase
	jne .L167
	move.l 8(%sp),%a0
	move.l 8(%sp),%d1
	add.l #80,%d1
	lea (72,%a0),%a0
.L168:
	mvz.b (%a0),%d0
	addq.l #1,%a0
	mov3q.l #4,%d2
	cmp.l %d0,%d2
	jcs .L167
	cmp.l %a0,%d1
	jne .L168
	move.l 8(%sp),%a1
	lea desired,%a0
	lea (48,%a1),%a1
.L169:
	move.b (%a1)+,(%a0)+
	cmp.l #desired+16,%a0
	jne .L169
	lea (12,%sp),%a0
	move.l (%a0),current
	clr.l automatic
	clr.l result
	mov3q.l #1,phase
	clr.l cursor
	clr.l waiting
	clr.l cancelling
	jsr advance
	move.l (%sp)+,%d2
	move.l result,%d0
	rts
.L167:
	move.l (%sp)+,%d2
	moveq #-3,%d0
	rts
	.size	dl_selection_prepare, .-dl_selection_prepare
	.align	2
	.globl	dl_selection_poll
	.type	dl_selection_poll, @function
dl_selection_poll:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jne .L178
	jsr advance
	move.l result,%d0
	rts
.L178:
	moveq #-3,%d0
	rts
	.size	dl_selection_poll, .-dl_selection_poll
	.align	2
	.globl	dl_residency_tick
	.type	dl_residency_tick, @function
dl_residency_tick:
	lea (-24,%sp),%sp
	movem.l #1052,(%sp)
	tst.l dl_residency_enabled
	jne .L215
.L181:
	movem.l (%sp),#1052
	lea (24,%sp),%sp
	rts
.L215:
	jsr advance
	jsr dl_publication_tick
	move.l phase,%d2
	move.l #allocator,%d3
	move.l result,%d0
	move.l cancelling,%d1
	sub.l %a1,%a1
	move.l %d0,16(%sp)
	move.l %d1,20(%sp)
	lea dl_catalog,%a2
.L186:
	move.l #-2147479868,%a0
	moveq #31,%d4
	add.l %a1,%a0
	mvz.b (%a0),%d0
	cmp.l %d0,%d4
	jcs .L183
	moveq #12,%d1
	muls.l %d0,%d1
	tst.b 9(%a2,%d1.l)
	jne .L183
	mov3q.l #6,%d1
	muls.l %d1,%d0
	move.l %a1,%d1
	lsr.l #2,%d1
	mov3q.l #1,%d4
	and.l %d4,%d1
	move.l %d0,%a0
	eor.l %d4,%d1
	mvz.w #192,%d4
	muls.l %d4,%d1
	add.l %d1,%a0
	add.l %d3,%a0
	tst.b 28(%a0)
	jeq .L184
	mov3q.l #6,%d0
	cmp.l %d2,%d0
	jne .L183
	tst.b 412(%a0)
	jne .L183
.L185:
	move.l unsafe_valid,%d3
	move.l #-2147479868,%a2
	lea unsafe,%a1
	move.l %a1,%a0
	sub.l %a1,%a2
.L189:
	move.b (%a2,%a0.l),%d0
	mvz.b (%a0)+,%d1
	mvz.b %d0,%d0
	cmp.l %d1,%d0
	jeq .L188
	clr.l %d3
.L188:
	cmp.l #unsafe+16,%a0
	jne .L189
	tst.l %d3
	jne .L190
.L191:
	move.b (%a2,%a1.l),%d0
	move.b %d0,(%a1)+
	cmp.l #unsafe+16,%a1
	jne .L191
	mov3q.l #1,unsafe_valid
	addq.l #1,dl_unguarded
.L190:
	tst.l %d2
	jne .L181
	tst.l observed_valid
	seq %d1
	lea observed,%a2
	move.l #-2147479868,%a1
	move.l %a2,%a0
	sub.l %a2,%a1
	mvs.b %d1,%d1
	neg.l %d1
.L192:
	move.b (%a1,%a0.l),%d0
	move.b (%a0)+,%d2
	eor.l %d2,%d0
	tst.b %d0
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d1
	cmp.l #observed+16,%a0
	jne .L192
	tst.l %d1
	jeq .L181
	lea observed,%a0
.L193:
	move.b (%a0,%a1.l),%d0
	move.b %d0,(%a0)+
	cmp.l #observed+16,%a0
	jne .L193
	move.l auto_serial,%d0
	addq.l #1,%d0
	mov3q.l #1,observed_valid
	tst.l %d0
	jne .L216
	move.l #-2147483648,%d1
	move.l %d1,%d0
	move.l %d1,auto_serial
	lea desired,%a0
.L195:
	move.b (%a2)+,(%a0)+
	cmp.l #observed+16,%a2
	jne .L195
	movem.l (%sp),#1052
	move.l %d0,current
	mov3q.l #1,automatic
	clr.l result
	mov3q.l #1,phase
	clr.l cursor
	clr.l waiting
	clr.l cancelling
	lea (24,%sp),%sp
	rts
.L183:
	addq.l #1,%a1
	moveq #16,%d0
	cmp.l %a1,%d0
	jne .L186
	clr.l unsafe_valid
	jra .L190
.L184:
	mov3q.l #5,%d1
	cmp.l %d2,%d1
	jne .L185
	mov3q.l #1,%d4
	cmp.l 16(%sp),%d4
	jne .L185
	tst.l 20(%sp)
	jne .L185
	tst.b 412(%a0)
	jeq .L185
	jra .L183
.L216:
	move.l %d0,%d1
	move.l %d1,auto_serial
	lea desired,%a0
	jra .L195
	.size	dl_residency_tick, .-dl_residency_tick
	.align	2
	.globl	dl_publication_prepare
	.type	dl_publication_prepare, @function
dl_publication_prepare:
	move.l %d2,-(%sp)
	tst.l phase
	jne .L220
	move.l 12(%sp),%a0
	move.l %a0,%d1
	addq.l #8,%d1
.L221:
	addq.l #1,%a0
	mvz.b -1(%a0),%d0
	mov3q.l #4,%d2
	cmp.l %d0,%d2
	jcs .L220
	cmp.l %a0,%d1
	jne .L221
	move.l 8(%sp),%a1
	lea desired,%a0
.L222:
	move.b (%a1)+,(%a0)+
	cmp.l #desired+16,%a0
	jne .L222
	lea (16,%sp),%a0
	move.l (%a0),current
	clr.l automatic
	clr.l result
	mov3q.l #1,phase
	clr.l cursor
	clr.l waiting
	clr.l cancelling
	jsr advance
	move.l (%sp)+,%d2
	move.l result,%d0
	rts
.L220:
	move.l (%sp)+,%d2
	moveq #-3,%d0
	rts
	.size	dl_publication_prepare, .-dl_publication_prepare
	.align	2
	.globl	dl_publication_poll
	.type	dl_publication_poll, @function
dl_publication_poll:
	move.l current,%d0
	cmp.l 4(%sp),%d0
	jne .L229
	jsr advance
	move.l result,%d0
	rts
.L229:
	moveq #-3,%d0
	rts
	.size	dl_publication_poll, .-dl_publication_poll
	.align	2
	.globl	dl_publication_arm
	.type	dl_publication_arm, @function
dl_publication_arm:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jeq .L236
.L232:
	rts
.L236:
	mov3q.l #5,%d0
	cmp.l phase.l,%d0
	jne .L232
	mov3q.l #1,%d0
	cmp.l result.l,%d0
	jne .L232
	mov3q.l #2,automatic
	rts
	.size	dl_publication_arm, .-dl_publication_arm
	.align	2
	.globl	dl_publication_ready
	.type	dl_publication_ready, @function
dl_publication_ready:
	lea (-24,%sp),%sp
	movem.l #1084,(%sp)
	move.l 28(%sp),%a1
	tst.l dl_residency_enabled
	jeq .L238
	clr.l %d0
	clr.l %d2
.L243:
	mvz.b (%a1,%d0.l),%d1
	moveq #12,%d3
	moveq #31,%d5
	muls.l %d1,%d3
	cmp.l %d1,%d5
	jcs .L239
.L279:
	lea dl_catalog,%a0
	add.l %d3,%a0
	tst.b 10(%a0)
	jeq .L239
	move.b 8(%a0),%d1
	mov3q.l #7,%d3
	cmp.l %d0,%d3
	jcs .L240
	addq.l #1,%d0
	btst #0,%d1
	jeq .L239
	tst.b 9(%a0)
	seq %d1
	moveq #12,%d3
	moveq #31,%d5
	mvs.b %d1,%d1
	neg.l %d1
	or.l %d1,%d2
	mvz.b (%a1,%d0.l),%d1
	muls.l %d1,%d3
	cmp.l %d1,%d5
	jcc .L279
.L239:
	clr.l %d0
.L237:
	movem.l (%sp),#1084
	lea (24,%sp),%sp
	rts
.L240:
	addq.l #1,%d0
	btst #1,%d1
	jeq .L239
	tst.b 9(%a0)
	seq %d1
	moveq #16,%d5
	mvs.b %d1,%d1
	neg.l %d1
	or.l %d1,%d2
	cmp.l %d0,%d5
	jne .L243
	tst.l %d2
	jeq .L238
	tst.l initialized
	jeq .L239
	move.l phase,%d3
	tst.l %d3
	jeq .L255
	mov3q.l #5,%d0
	cmp.l %d3,%d0
	jeq .L247
	mov3q.l #6,%d1
	cmp.l %d3,%d1
	jne .L239
.L255:
	clr.l %d2
.L254:
	mvz.b (%a1,%d2.l),%d0
	moveq #31,%d1
	cmp.l %d0,%d1
	jcs .L239
	moveq #12,%d1
	muls.l %d0,%d1
	lea dl_catalog,%a0
	add.l %d1,%a0
	tst.b 10(%a0)
	jeq .L239
	move.b 8(%a0),%d1
	mov3q.l #7,%d5
	cmp.l %d2,%d5
	jcs .L249
	btst #0,%d1
	jeq .L239
	tst.b 9(%a0)
	jne .L280
.L250:
	move.l %d2,%d1
	lsr.l #2,%d1
	mov3q.l #1,%d5
	and.l %d5,%d1
	eor.l %d5,%d1
	mov3q.l #6,%d5
	cmp.l %d3,%d5
	jeq .L281
	mov3q.l #6,%d5
	muls.l %d5,%d0
	mvz.w #192,%d5
	muls.l %d5,%d1
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #allocator,%a0
	tst.b 28(%a0)
	jne .L252
	mov3q.l #5,%d0
	cmp.l %d3,%d0
	jne .L239
	mov3q.l #1,%d1
	cmp.l result.l,%d1
	jne .L239
	tst.b 412(%a0)
	jeq .L239
.L252:
	addq.l #1,%d2
	moveq #16,%d5
	cmp.l %d2,%d5
	jne .L254
.L238:
	movem.l (%sp),#1084
	mov3q.l #1,%d0
	lea (24,%sp),%sp
	rts
.L249:
	btst #1,%d1
	jeq .L239
	tst.b 9(%a0)
	jeq .L250
	addq.l #1,%d2
	moveq #16,%d5
	cmp.l %d2,%d5
	jne .L254
	jra .L238
.L280:
	addq.l #1,%d2
	jra .L254
.L247:
	mov3q.l #1,%d5
	cmp.l result.l,%d5
	jne .L239
	move.l cancelling,%d2
	tst.l %d2
	jne .L239
	move.l %a1,%d0
	lea desired,%a0
.L248:
	move.l %d0,%a2
	addq.l #1,%a0
	mvz.b (%a2),%d1
	addq.l #1,%d0
	move.l %d1,20(%sp)
	mvz.b -1(%a0),%d1
	cmp.l 20(%sp),%d1
	jne .L239
	cmp.l #desired+16,%a0
	jne .L248
	jra .L254
.L281:
	muls.l %d5,%d0
	mvz.w #192,%d5
	muls.l %d5,%d1
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #allocator+412,%a0
	tst.b (%a0)
	jne .L252
	clr.l %d0
	jra .L237
	.size	dl_publication_ready, .-dl_publication_ready
	.align	2
	.globl	dl_publication_idle
	.type	dl_publication_idle, @function
dl_publication_idle:
	tst.l phase
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	rts
	.size	dl_publication_idle, .-dl_publication_idle
	.data
	.align	2
	.type	unsafe_valid, @object
	.size	unsafe_valid, 4
unsafe_valid:
	.zero	4
	.type	unsafe, @object
	.size	unsafe, 16
unsafe:
	.zero	16
	.globl	dl_unguarded
	.align	2
	.type	dl_unguarded, @object
	.size	dl_unguarded, 4
dl_unguarded:
	.zero	4
	.globl	dl_residency_words
	.align	2
	.type	dl_residency_words, @object
	.size	dl_residency_words, 8
dl_residency_words:
	.zero	8
	.globl	dl_residency_failures
	.align	2
	.type	dl_residency_failures, @object
	.size	dl_residency_failures, 4
dl_residency_failures:
	.zero	4
	.globl	dl_residency_rollbacks
	.align	2
	.type	dl_residency_rollbacks, @object
	.size	dl_residency_rollbacks, 4
dl_residency_rollbacks:
	.zero	4
	.globl	dl_residency_commits
	.align	2
	.type	dl_residency_commits, @object
	.size	dl_residency_commits, 4
dl_residency_commits:
	.zero	4
	.globl	dl_residency_enabled
	.align	2
	.type	dl_residency_enabled, @object
	.size	dl_residency_enabled, 4
dl_residency_enabled:
	.long	1
	.align	2
	.type	result, @object
	.size	result, 4
result:
	.zero	4
	.align	2
	.type	current, @object
	.size	current, 4
current:
	.zero	4
	.align	2
	.type	cancelling, @object
	.size	cancelling, 4
cancelling:
	.zero	4
	.align	2
	.type	automatic, @object
	.size	automatic, 4
automatic:
	.zero	4
	.align	2
	.type	waiting, @object
	.size	waiting, 4
waiting:
	.zero	4
	.align	2
	.type	cursor, @object
	.size	cursor, 4
cursor:
	.zero	4
	.align	2
	.type	phase, @object
	.size	phase, 4
phase:
	.zero	4
	.align	2
	.type	initialized, @object
	.size	initialized, 4
initialized:
	.zero	4
	.align	2
	.type	auto_serial, @object
	.size	auto_serial, 4
auto_serial:
	.long	-2147483648
	.align	2
	.type	observed_valid, @object
	.size	observed_valid, 4
observed_valid:
	.zero	4
	.type	observed, @object
	.size	observed, 16
observed:
	.zero	16
	.type	desired, @object
	.size	desired, 16
desired:
	.zero	16
	.align	2
	.type	allocator, @object
	.size	allocator, 828
allocator:
	.zero	828
