| Generated by generate.py from preflight.c.
#NO_APP
	.file	"preflight.c"
	.text
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"r"
	.text
	.align	2
	.type	dl_read_file, @function
dl_read_file:
	lea (-32,%sp),%sp
	movem.l #3324,(%sp)
	move.l 1187521578,%a0
	pea .LC0
	move.l 40(%sp),-(%sp)
	move.l 48(%sp),%d5
	move.l 52(%sp),%d6
	move.l 56(%sp),%d4
	jsr (%a0)
	addq.l #8,%sp
	move.l %d0,%d3
	tst.l %d0
	jle .L9
	move.l 1187521566,%a0
	move.l %d0,-(%sp)
	jsr (%a0)
	addq.l #4,%sp
	tst.l %d0
	jlt .L5
	cmp.l %d0,%d5
	jhi .L5
	sub.l %d5,%d0
	cmp.l %d0,%d4
	jhi .L5
	sub.l %a3,%a3
	lea file_buffer+134217728,%a2
.L8:
	move.l %d5,%d2
	add.l %a3,%d2
	move.l %d2,%d0
	and.l #-512,%d0
	move.l 1187521598,%a0
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	jsr (%a0)
	addq.l #8,%sp
	tst.l %d0
	jlt .L5
	move.l 1187521574,%a0
	mov3q.l #1,-(%sp)
	move.l %a2,-(%sp)
	move.l %d3,-(%sp)
	jsr (%a0)
	lea (12,%sp),%sp
	tst.l %d0
	jle .L5
	and.l #511,%d2
	mvz.w #512,%d1
	move.l %d4,%d0
	sub.l %a3,%d0
	sub.l %d2,%d1
	cmp.l %d0,%d1
	jcc .L6
	move.l %d1,%d0
.L6:
	lea (%a3,%d6.l),%a0
	lea file_buffer+134217728,%a1
	move.l %a0,%d1
	add.l %d2,%a1
	add.l %d0,%d1
.L7:
	move.b (%a1)+,(%a0)+
	cmp.l %a0,%d1
	jne .L7
	add.l %d0,%a3
	cmp.l %d4,%a3
	jcs .L8
	move.l 1187521570,%a0
	mov3q.l #1,%d2
	move.l %d3,-(%sp)
	jsr (%a0)
	addq.l #4,%sp
	not.l %d0
	add.l %d0,%d0
	subx.l %d0,%d0
	neg.l %d0
	and.l %d2,%d0
.L1:
	movem.l (%sp),#3324
	lea (32,%sp),%sp
	rts
.L5:
	move.l 1187521570,%a0
	clr.l %d2
	move.l %d3,-(%sp)
	jsr (%a0)
	addq.l #4,%sp
	not.l %d0
	add.l %d0,%d0
	subx.l %d0,%d0
	neg.l %d0
	and.l %d2,%d0
	jra .L1
.L9:
	movem.l (%sp),#3324
	clr.l %d0
	lea (32,%sp),%sp
	rts
	.size	dl_read_file, .-dl_read_file
	.section	.rodata.str1.1
.LC1:
	.string	"/project.work"
.LC2:
	.string	"/bank"
.LC3:
	.string	".work"
.LC4:
	.string	"BANK="
.LC5:
	.string	"PATTERN="
.LC6:
	.string	"PART="
	.text
	.align	2
	.globl	dl_project_metadata
	.type	dl_project_metadata, @function
dl_project_metadata:
	link.w %fp,#-1012
	movem.l #15484,(%sp)
	move.l 8(%fp),%a2
	move.b (%a2),%d1
	jeq .L15
	clr.l %d0
	lea (-768,%fp),%a0
.L17:
	move.b %d1,(%a0)
	addq.l #1,%d0
	move.b (%a2,%d0.l),%d1
	addq.l #1,%a0
	tst.b %d1
	jeq .L16
	cmp.l #255,%d0
	jne .L17
.L15:
	clr.l %d0
.L14:
	movem.l -1012(%fp),#15484
	unlk %fp
	rts
.L16:
	clr.b %d6
	moveq #47,%d1
	lea (%fp,%d0.l),%a0
	lea (-768,%fp),%a1
	add.l %d0,%a1
	move.b %d6,-768(%a0)
	lea .LC1,%a0
.L58:
	addq.l #1,%a0
	cmp.l #255,%d0
	jeq .L138
	move.b %d1,(%a1)+
	move.b (%a0),%d1
	addq.l #1,%d0
	cmp.l #.LC1+13,%a0
	jne .L58
.L18:
	clr.b %d1
	lea (%fp,%d0.l),%a0
	move.l 12(%fp),%a1
	clr.l 8(%a1)
	clr.l 4(%a1)
	clr.l (%a1)
	move.b %d1,-768(%a0)
	move.l 1187521578,%a0
	pea .LC0
	pea -768(%fp)
	jsr (%a0)
	addq.l #8,%sp
	move.l %d0,%d2
	tst.l %d0
	jle .L15
	move.l 1187521566,%a0
	move.l %d0,-(%sp)
	jsr (%a0)
	move.l 1187521570,%a0
	move.l %d2,-(%sp)
	move.l %d0,-960(%fp)
	jsr (%a0)
	addq.l #8,%sp
	tst.l %d0
	jlt .L15
	move.l -960(%fp),%d0
	subq.l #1,%d0
	cmp.l #65535,%d0
	jhi .L15
	clr.l -968(%fp)
	clr.l -956(%fp)
	clr.l %d2
	lea (-512,%fp),%a3
	move.l %a2,-952(%fp)
.L43:
	move.l -960(%fp),%d3
	sub.l -968(%fp),%d3
	cmp.l #512,%d3
	jls .L20
	mvz.w #512,%d3
.L20:
	move.l %d3,-(%sp)
	move.l %a3,-(%sp)
	move.l -968(%fp),-(%sp)
	pea -768(%fp)
	jsr dl_read_file
	lea (16,%sp),%sp
	tst.l %d0
	jeq .L14
	add.l %d3,-968(%fp)
	move.l -968(%fp),%a2
	move.l %d3,%d1
	clr.l %d0
	lea .LC4,%a4
	cmp.l -960(%fp),%a2
	seq %d5
	mvs.b %d5,%d5
	sub.l %d5,%d1
.L42:
	cmp.l %d3,%d0
	jeq .L22
	move.b (%a3,%d0.l),%d5
	moveq #13,%d6
	mvz.b %d5,%d4
	cmp.l %d4,%d6
	jeq .L23
	moveq #10,%d6
	cmp.l %d4,%d6
	jeq .L22
	moveq #94,%d4
	cmp.l %d2,%d4
	jcs .L59
	lea (%fp,%d2.l),%a0
	addq.l #1,%d2
	move.b %d5,-864(%a0)
.L23:
	addq.l #1,%d0
	cmp.l %d1,%d0
	jne .L42
.L142:
	move.l -968(%fp),%d4
	cmp.l -960(%fp),%d4
	jcs .L43
	move.l -952(%fp),%a2
	mov3q.l #7,%d6
	cmp.l -956(%fp),%d6
	jne .L15
	move.b (%a2),%d1
	jeq .L61
	lea (-768,%fp),%a0
	clr.l %d0
.L45:
	move.b %d1,(%a0)
	addq.l #1,%d0
	move.b (%a2,%d0.l),%d1
	addq.l #1,%a0
	tst.b %d1
	jeq .L44
	cmp.l #255,%d0
	jne .L45
	moveq #47,%d1
	clr.l %d0
	lea (-768,%fp),%a1
	move.l %d0,%d2
	add.l %d0,%a1
	addq.l #5,%d2
	lea .LC2,%a0
.L47:
	addq.l #1,%a0
	cmp.l #255,%d0
	jeq .L139
	move.b %d1,(%a1)+
	move.b (%a0),%d1
	addq.l #1,%d0
	cmp.l %d2,%d0
	jne .L47
.L48:
	clr.b %d2
	lea (%fp,%d0.l),%a0
	move.l %d0,%d1
	add.l #12,%d1
	move.b %d2,-768(%a0)
	cmp.l #255,%d1
	jhi .L15
	move.l 12(%fp),%a1
	moveq #10,%d1
	moveq #46,%d3
	lea (-766,%fp),%a3
	move.l (%a1),%d2
	addq.l #1,%d2
	remu.l %d1,%d4:%d2
	divu.l %d1,%d2
	move.l %d0,%d1
	addq.l #2,%d1
	lea (%fp,%d1.l),%a2
	lea (%a3,%d0.l),%a1
	addq.l #7,%d0
	add.l #48,%d2
	move.b %d2,-768(%a0)
	clr.b %d2
	add.l #48,%d4
	move.b %d4,-767(%a0)
	lea .LC3,%a0
	move.b %d2,-768(%a2)
.L51:
	move.b %d3,(%a1)
	addq.l #1,%a0
	addq.l #1,%d1
	addq.l #1,%a1
	cmp.l %d1,%d0
	jeq .L50
	move.b (%a0),%d3
	cmp.l #255,%d1
	jne .L51
	tst.b %d3
	jne .L15
.L50:
	clr.b %d4
	lea (%fp,%d1.l),%a0
	lea (-932,%fp),%a2
	move.b %d4,-768(%a0)
	pea 16.w
	move.l %a2,-(%sp)
	clr.l -(%sp)
	pea -768(%fp)
	jsr dl_read_file
	lea (16,%sp),%sp
	tst.l %d0
	jeq .L14
	move.b %d4,-942(%fp)
	move.l #1179603533,%a1
	clr.l %d0
	move.l %a1,-946(%fp)
.L52:
	lea (-946,%fp),%a3
	mvz.b (%a2,%d0.l),%d2
	mvz.b (%a3,%d0.l),%d1
	addq.l #1,%d0
	cmp.l %d2,%d1
	jne .L15
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jne .L52
	clr.b %d2
	move.l #1146114865,%d4
	clr.l %d0
	move.l #1111576139,%d6
	move.l %d4,-941(%fp)
	move.l %d6,-937(%fp)
	move.b %d2,-933(%fp)
.L53:
	lea (-941,%fp),%a0
	mvz.b 8(%a2,%d0.l),%d2
	mvz.b (%a0,%d0.l),%d1
	addq.l #1,%d0
	cmp.l %d2,%d1
	jne .L15
	moveq #8,%d1
	cmp.l %d0,%d1
	jne .L53
	move.l 12(%fp),%a0
	mvz.w #36588,%d2
	move.l 4(%a0),%d0
	mov3q.l #1,-(%sp)
	pea -947(%fp)
	muls.l %d2,%d0
	add.l #36605,%d0
	move.l %d0,-(%sp)
	pea -768(%fp)
	jsr dl_read_file
	lea (16,%sp),%sp
	tst.l %d0
	jeq .L14
	mvz.b -947(%fp),%d0
	move.l 12(%fp),%a1
	cmp.l 8(%a1),%d0
	jne .L15
	mvz.w #6331,%d1
	pea 51.w
	lea (-916,%fp),%a2
	move.l %a2,-(%sp)
	muls.l %d1,%d0
	add.l #585430,%d0
	move.l %d0,-(%sp)
	pea -768(%fp)
	jsr dl_read_file
	lea (16,%sp),%sp
	tst.l %d0
	jeq .L14
	mvz.b -916(%fp),%d1
	moveq #80,%d2
	cmp.l %d1,%d2
	jne .L15
	mvz.b -915(%fp),%d1
	moveq #65,%d4
	cmp.l %d1,%d4
	jne .L15
	mvz.b -914(%fp),%d1
	moveq #82,%d6
	cmp.l %d1,%d6
	jne .L15
	mvz.b -913(%fp),%d1
	moveq #84,%d2
	cmp.l %d1,%d2
	jne .L15
	clr.l %d1
.L55:
	lea 9(%a2,%d1.l),%a1
	move.l 12(%fp),%a0
	moveq #16,%d2
	move.b (%a1),12(%a0,%d1.l)
	addq.l #1,%d1
	cmp.l %d1,%d2
	jne .L55
	clr.l %d1
.L56:
	lea 43(%a2,%d1.l),%a1
	move.l 12(%fp),%a0
	moveq #8,%d2
	move.b (%a1),28(%a0,%d1.l)
	addq.l #1,%d1
	cmp.l %d1,%d2
	jeq .L14
	lea 43(%a2,%d1.l),%a1
	move.l 12(%fp),%a0
	moveq #8,%d2
	move.b (%a1),28(%a0,%d1.l)
	addq.l #1,%d1
	cmp.l %d1,%d2
	jne .L56
	jra .L14
.L138:
	tst.b %d1
	jeq .L18
	clr.l %d0
	jra .L14
.L22:
	moveq #96,%d6
	cmp.l %d2,%d6
	jeq .L140
	moveq #95,%d6
	cmp.l %d2,%d6
	jcc .L141
.L26:
	clr.l %d2
.L147:
	addq.l #1,%d0
	cmp.l %d1,%d0
	jne .L42
	jra .L142
.L141:
	lea (%fp,%d2.l),%a0
	clr.l %d5
	clr.b %d2
	move.l #.LC5,%d4
	move.l #.LC6,%d6
	move.l %a4,-916(%fp)
	move.l %d4,-912(%fp)
	move.l %d6,-908(%fp)
	lea (-916,%fp),%a5
	move.b %d2,-864(%a0)
	moveq #66,%d2
.L29:
	tst.b %d2
	jeq .L60
	move.l (%a5),%a2
	sub.l %a1,%a1
	lea (-864,%fp),%a0
.L41:
	mvs.b (%a0),%d4
	mvs.b %d2,%d2
	addq.l #1,%a1
	addq.l #1,%a0
	cmp.l %d4,%d2
	jne .L143
	move.b (%a2,%a1.l),%d2
	jne .L41
.L30:
	move.l -956(%fp),%d2
	lsr.l %d5,%d2
	mov3q.l #1,%d4
	and.l %d2,%d4
	btst #0,%d2
	jne .L15
	lea (-864,%fp),%a2
	sub.l %a0,%a0
	add.l %a1,%a2
	move.l %a2,-964(%fp)
	move.l %a5,-976(%fp)
	move.l %d3,%a2
	move.l %d0,%a5
	move.l %d1,-972(%fp)
.L34:
	moveq #10,%d3
	moveq #9,%d6
	muls.l %d4,%d3
	move.l -964(%fp),%a1
	move.b (%a1,%a0.l),%d0
	move.l %d0,%d2
	add.l #-48,%d2
	mvz.b %d2,%d2
	mvs.b %d0,%d1
	cmp.l %d2,%d6
	jcs .L144
	move.l %d3,%a1
	addq.l #1,%a0
	lea -48(%a1,%d1.l),%a1
	mov3q.l #3,%d0
	move.l %a1,%d4
	cmp.l %a0,%d0
	jne .L34
	clr.l %d0
	jra .L14
.L59:
	moveq #96,%d2
	addq.l #1,%d0
	cmp.l %d1,%d0
	jne .L42
	jra .L142
.L140:
	mvs.b -864(%fp),%d2
	moveq #66,%d4
	cmp.l %d2,%d4
	jeq .L145
	moveq #80,%d4
	cmp.l %d2,%d4
	jne .L26
	mvs.b -863(%fp),%d2
	moveq #65,%d6
	cmp.l %d2,%d6
	jne .L26
	mvs.b -862(%fp),%d2
	moveq #82,%d4
	cmp.l %d2,%d4
	jeq .L146
	moveq #84,%d4
	cmp.l %d2,%d4
	jne .L26
	mvs.b -861(%fp),%d2
	moveq #84,%d4
	cmp.l %d2,%d4
	jne .L26
	mvs.b -860(%fp),%d2
	moveq #69,%d6
	cmp.l %d2,%d6
	jne .L26
	mvs.b -859(%fp),%d2
	moveq #82,%d4
	cmp.l %d2,%d4
	jne .L26
	mvs.b -858(%fp),%d2
	moveq #78,%d6
	cmp.l %d2,%d6
	jne .L26
	mvs.b -857(%fp),%d2
	moveq #61,%d4
	cmp.l %d2,%d4
	jeq .L15
	clr.l %d2
	jra .L147
.L143:
	addq.l #1,%d5
	mov3q.l #3,%d2
	cmp.l %d5,%d2
	jeq .L26
	move.l 4(%a5),%a0
	addq.l #4,%a5
	move.b (%a0),%d2
	jra .L29
.L145:
	mvs.b -863(%fp),%d2
	moveq #65,%d6
	cmp.l %d2,%d6
	jne .L26
	mvs.b -862(%fp),%d2
	moveq #78,%d4
	cmp.l %d2,%d4
	jne .L26
	mvs.b -861(%fp),%d2
	moveq #75,%d6
	cmp.l %d2,%d6
	jne .L26
	mvs.b -860(%fp),%d2
	moveq #61,%d6
	cmp.l %d2,%d6
	jeq .L15
	clr.l %d2
	jra .L147
.L60:
	sub.l %a1,%a1
	jra .L30
.L146:
	mvs.b -861(%fp),%d2
	moveq #84,%d6
	cmp.l %d2,%d6
	jne .L26
	mvs.b -860(%fp),%d2
	moveq #61,%d4
	cmp.l %d2,%d4
	jeq .L15
	clr.l %d2
	jra .L147
.L144:
	move.w %d0,%a1
	move.l %a5,%d0
	move.l %a2,%d3
	move.l -972(%fp),%d1
	move.l -976(%fp),%a5
	tst.l %a0
	jeq .L15
	move.w %a1,%d2
	tst.b %d2
	jne .L15
	mov3q.l #2,%d6
	cmp.l %d5,%d6
	jeq .L36
	moveq #15,%d2
	cmp.l %d4,%d2
	jcs .L15
	tst.l %d5
	jeq .L148
	move.l 12(%fp),%a0
	addq.l #4,%a5
	mov3q.l #2,%d2
	or.l %d2,-956(%fp)
	move.l %d4,4(%a0)
	move.l (%a5),%a0
	mov3q.l #2,%d5
	move.b (%a0),%d2
	jra .L29
.L36:
	mov3q.l #3,%d6
	cmp.l %d4,%d6
	jcs .L15
	move.l 12(%fp),%a0
	mov3q.l #4,%d2
	or.l %d2,-956(%fp)
	clr.l %d2
	move.l %d4,8(%a0)
	jra .L147
.L148:
	move.l 12(%fp),%a0
	addq.l #4,%a5
	mov3q.l #1,%d2
	or.l %d2,-956(%fp)
	move.l %d4,(%a0)
	move.l (%a5),%a0
	mov3q.l #1,%d5
	move.b (%a0),%d2
	jra .L29
.L139:
	tst.b %d1
	jeq .L48
	clr.l %d0
	jra .L14
.L61:
	clr.l %d0
.L44:
	clr.b %d1
	lea (%fp,%d0.l),%a0
	lea (-768,%fp),%a1
	move.l %d0,%d2
	add.l %d0,%a1
	addq.l #5,%d2
	move.b %d1,-768(%a0)
	moveq #47,%d1
	lea .LC2,%a0
	jra .L47
	.size	dl_project_metadata, .-dl_project_metadata
	.data
	.align	512
	.type	file_buffer, @object
	.size	file_buffer, 512
file_buffer:
	.zero	512
