| Generated by generate.py from publication.c.
#NO_APP
	.file	"publication.c"
	.text
	.align	2
	.type	immediate_request, @function
immediate_request:
	move.l %d2,-(%sp)
#APP
| 75 "publication.c" 1
	move.w %sr,%d1
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l 8(%sp),%a0
	clr.l %d0
	addq.l #1,immediate_version
	lea immediate_args,%a1
.L2:
	move.l (%a0)+,(%a1,%d0.l*4)
	mov3q.l #5,%d2
	addq.l #1,%d0
	cmp.l %d0,%d2
	jne .L2
	lea (12,%sp),%a0
	move.l (%a0),immediate_passthrough
	lea (16,%sp),%a0
	move.l (%a0),immediate_kind
	move.b -2147457601,%d0
	mvz.b -2147457600,%d2
	mvz.b %d0,%d0
	lsl.l #8,%d0
	or.l %d0,%d2
	move.l %d2,immediate_next
	addq.l #1,immediate_version
#APP
| 80 "publication.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	move.l (%sp)+,%d2
	rts
	.size	immediate_request, .-immediate_request
	.align	2
	.type	capture.part.0, @function
capture.part.0:
	move.l %a2,-(%sp)
	move.l %d2,-(%sp)
	move.l #635712,%d2
	move.w 18(%sp),%d1
	move.l 12(%sp),%d0
	muls.l %d2,%d0
	mulu.w #36568,%d1
	move.l %d1,%a0
	add.l #1074704439,%a0
	move.b (%a0,%d0.l),%d1
	mvz.b %d1,%d2
	move.l %d2,%a0
	mov3q.l #3,%d2
	cmp.l %a0,%d2
	jcs .L10
	ext.w %d1
	add.l #1075253088,%d0
	move.l 20(%sp),%a0
	move.w %d1,%d2
	move.l %a0,%d1
	add.l #16,%d1
	mulu.w #6322,%d2
	move.l %d2,%a1
	lea (%a1,%d0.l),%a2
	move.l %a2,%a1
	sub.l %a0,%a1
.L9:
	move.b (%a1,%a0.l),%d0
	move.b %d0,(%a0)+
	cmp.l %a0,%d1
	jne .L9
	move.l 24(%sp),%a0
	moveq #34,%d0
	sub.l %a0,%d0
	add.l %d0,%a2
	lea (8,%a0),%a1
.L11:
	move.b (%a2,%a0.l),%d0
	addq.l #1,%a0
	mvz.b %d0,%d1
	move.b %d0,-1(%a0)
	mov3q.l #4,%d0
	cmp.l %d1,%d0
	jcs .L10
	cmp.l %a0,%a1
	jne .L11
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	move.l (%sp)+,%a2
	rts
.L10:
	move.l (%sp)+,%d2
	clr.l %d0
	move.l (%sp)+,%a2
	rts
	.size	capture.part.0, .-capture.part.0
	.align	2
	.type	project_tick.part.0, @function
project_tick.part.0:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	tst.l pending
	jne .L64
	tst.l immediate_pending
	jne .L65
.L18:
	mov3q.l #1,%d0
	cmp.l project_pending.l,%d0
	jeq .L66
.L19:
	mov3q.l #2,%d1
	cmp.l project_pending.l,%d1
	jeq .L67
.L22:
	move.l project_pending,%d1
	mov3q.l #2,%d2
	cmp.l %d1,%d2
	jeq .L68
	move.l project_pending,%d1
	mov3q.l #3,%d2
	cmp.l %d1,%d2
	jeq .L69
.L27:
	mov3q.l #4,%d0
	cmp.l project_pending.l,%d0
	jeq .L70
.L30:
	mov3q.l #4,%d1
	cmp.l project_pending.l,%d1
	jeq .L71
.L21:
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	addq.l #8,%sp
	rts
.L65:
	move.l immediate_token,-(%sp)
	jsr dl_selection_cancel
	clr.l immediate_pending
	addq.l #4,%sp
	lea immediate_version,%a0
	mov3q.l #1,%d0
	move.l (%a0),immediate_seen
	cmp.l project_pending.l,%d0
	jne .L19
	jra .L66
.L64:
	move.l token,-(%sp)
	jsr dl_selection_cancel
	clr.l pending
	clr.l missed
	addq.l #4,%sp
	tst.l immediate_pending
	jeq .L18
	jra .L65
.L67:
	tst.l dl_stub_at_boot
	jeq .L22
	mov3q.l #1,project_authorized
	mov3q.l #4,project_pending
	pea project_name
	clr.l project_token
	addq.l #1,dl_project_admitted
	jsr dl_project_post_body
	addq.l #4,%sp
	tst.l %d0
	jne .L21
	clr.l project_authorized
	clr.l project_pending
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	addq.l #8,%sp
	rts
.L70:
	tst.l project_done
	jeq .L30
	tst.l dl_stub_at_boot
	jeq .L30
	clr.l project_authorized
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	clr.l project_pending
	addq.l #1,dl_project_completed
	addq.l #8,%sp
	rts
.L66:
	move.l immediate_token,-(%sp)
	lea dl_selection_cancel,%a0
	move.l %a0,12(%sp)
	jsr (%a0)
	move.l token,-(%sp)
	move.l 16(%sp),%a0
	jsr (%a0)
	pea project_target
	pea project_path
	jsr dl_project_metadata
	lea (16,%sp),%sp
	tst.l %d0
	jeq .L72
	mov3q.l #2,project_pending
	mov3q.l #2,%d1
	cmp.l project_pending.l,%d1
	jne .L22
	jra .L67
.L71:
	tst.l project_done
	jeq .L21
	move.l #-2147479880,%a1
	mov3q.l #1,%d1
	lea project_target+12,%a0
	sub.l #project_target,%a1
.L31:
	move.b (%a1,%a0.l),%d0
	move.b (%a0)+,%d2
	eor.l %d2,%d0
	tst.b %d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	and.l %d0,%d1
	cmp.l #project_target+28,%a0
	jne .L31
	tst.l %d1
	jeq .L32
	tst.l project_result
	jle .L32
	move.l project_token,-(%sp)
	jsr dl_selection_commit
	addq.l #4,%sp
	addq.l #1,dl_project_completed
	clr.l project_authorized
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	clr.l project_pending
	addq.l #8,%sp
	rts
.L68:
	move.l %d1,4(%sp)
	jsr dl_publication_idle
	move.l 4(%sp),%d1
	tst.l %d0
	jeq .L21
	move.l serial,%d0
	addq.l #1,%d0
	tst.l %d0
	jeq .L33
	move.l %d0,%a0
.L24:
	move.l %d0,-(%sp)
	pea project_target+28
	pea project_target+12
	move.l %d1,16(%sp)
	move.l %a0,serial
	move.l %d0,project_token
	jsr dl_publication_prepare
	lea (12,%sp),%sp
	move.l 4(%sp),%d1
	tst.l %d0
	jlt .L73
	mov3q.l #3,project_pending
	move.l project_pending,%d1
	mov3q.l #3,%d2
	cmp.l %d1,%d2
	jne .L27
.L69:
	move.l project_token,-(%sp)
	move.l %d1,8(%sp)
	jsr dl_publication_poll
	addq.l #4,%sp
	move.l 4(%sp),%d1
	tst.l %d0
	jeq .L21
	mov3q.l #1,%d2
	cmp.l %d0,%d2
	jeq .L28
	move.l project_token,-(%sp)
	move.l %d0,12(%sp)
	move.l %d1,8(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	mov3q.l #-1,%d2
	addq.l #1,dl_project_refused
	move.l 8(%sp),%d0
	addq.l #1,dl_publication_refused
	move.l 4(%sp),%d1
	cmp.l %d0,%d2
	jeq .L35
	addq.l #2,%d0
	tst.l %d0
	jeq .L29
.L36:
	mov3q.l #1,%d1
.L29:
	move.l %d1,dl_modal_pending
	clr.l project_pending
.L74:
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	addq.l #8,%sp
	rts
.L72:
	addq.l #1,dl_project_refused
	addq.l #1,dl_publication_refused
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	mov3q.l #1,dl_modal_pending
	clr.l project_pending
	addq.l #8,%sp
	rts
.L32:
	clr.l project_authorized
	mov3q.l #5,project_pending
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	addq.l #8,%sp
	rts
.L33:
	move.l #1073741825,%a0
	move.l %a0,%d0
	jra .L24
.L35:
	mov3q.l #2,%d1
	move.l %d1,dl_modal_pending
	clr.l project_pending
	jra .L74
.L28:
	mov3q.l #1,project_authorized
	mov3q.l #4,project_pending
	pea project_name
	addq.l #1,dl_project_admitted
	jsr dl_project_post_body
	addq.l #4,%sp
	tst.l %d0
	jne .L21
	move.l project_token,-(%sp)
	clr.l project_authorized
	jsr dl_selection_cancel
	addq.l #4,%sp
	clr.l project_pending
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	addq.l #8,%sp
	rts
.L73:
	addq.l #1,dl_project_refused
	addq.l #1,dl_publication_refused
	mov3q.l #-1,%d2
	cmp.l %d0,%d2
	jeq .L29
	addq.l #2,%d0
	tst.l %d0
	jne .L36
	mov3q.l #3,%d1
	move.l %d1,dl_modal_pending
	clr.l project_pending
	jra .L74
	.size	project_tick.part.0, .-project_tick.part.0
	.align	2
	.globl	dl_pattern_boundary
	.type	dl_pattern_boundary, @function
dl_pattern_boundary:
	link.w %fp,#-36
	move.l %d2,-(%sp)
	moveq #15,%d2
	move.b -2147457601,%d1
	move.b -2147457600,%d0
	move.w %d0,%a0
	move.l %a0,%d0
	or.l %d1,%d0
	mvz.b %d0,%d0
	cmp.l %d0,%d2
	jcc .L85
	mov3q.l #1,%d1
.L75:
	move.l -40(%fp),%d2
	move.l %d1,%d0
	unlk %fp
	rts
.L85:
	move.w %a0,%d2
	mvz.b %d1,%d1
	pea -24(%fp)
	pea -16(%fp)
	move.l %d1,-36(%fp)
	mvz.b %d2,%d2
	move.l %d2,-(%sp)
	move.l %d1,-(%sp)
	move.l %d2,-28(%fp)
	jsr (capture.part.0)
	lea (16,%sp),%sp
	tst.l %d0
	jne .L77
	move.l -36(%fp),%d0
	lsl.l #8,%d0
	or.l -28(%fp),%d0
	bset #16,%d0
	move.l %d0,missed
	tst.l pending
	jeq .L79
.L78:
	move.l -36(%fp),%d2
	cmp.l bank.l,%d2
	jeq .L86
.L79:
	addq.l #1,dl_publication_deferred
#APP
| 35 "publication.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #-2147457603,%a0
	move.b (%a0),-2147457601
	move.l #-2147457602,%a0
	move.b (%a0),-2147457600
#APP
| 40 "publication.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	clr.l %d1
.L87:
	move.l -40(%fp),%d2
	move.l %d1,%d0
	unlk %fp
	rts
.L77:
	pea -16(%fp)
	move.l %d0,-32(%fp)
	jsr dl_publication_ready
	addq.l #4,%sp
	move.l -32(%fp),%d1
	tst.l %d0
	jne .L75
	move.l -36(%fp),%d0
	lsl.l #8,%d0
	or.l -28(%fp),%d0
	bset #16,%d0
	move.l %d0,missed
	tst.l pending
	jne .L78
	jra .L79
.L86:
	move.l -28(%fp),%d2
	cmp.l pattern.l,%d2
	jne .L79
	mov3q.l #1,deferred
	addq.l #1,dl_publication_deferred
#APP
| 35 "publication.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #-2147457603,%a0
	move.b (%a0),-2147457601
	move.l #-2147457602,%a0
	move.b (%a0),-2147457600
#APP
| 40 "publication.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	clr.l %d1
	jra .L87
	.size	dl_pattern_boundary, .-dl_pattern_boundary
	.align	2
	.globl	dl_pattern_request_guard
	.type	dl_pattern_request_guard, @function
dl_pattern_request_guard:
	link.w %fp,#-28
	mov3q.l #1,%d0
	move.l %d2,-(%sp)
	cmp.l -2147457608.l,%d0
	jeq .L92
	mov3q.l #-1,%d1
	move.l 8(%fp),%a0
	move.l 4(%a0),%d0
	cmp.l %d0,%d1
	jne .L118
.L92:
	tst.l immediate_pending
	jne .L90
	move.l immediate_seen,%a0
	cmp.l immediate_version.l,%a0
	jeq .L97
.L90:
	clr.l -(%sp)
	mov3q.l #1,-(%sp)
	move.l 8(%fp),-(%sp)
	jsr immediate_request
	lea (12,%sp),%sp
.L97:
	mov3q.l #1,%d1
.L88:
	move.l %d1,%d0
	move.l -32(%fp),%d2
	unlk %fp
	rts
.L118:
	move.l (%a0),%d1
	move.l %d0,%d2
	or.l %d1,%d2
	move.l %d2,%a0
	moveq #15,%d2
	cmp.l %a0,%d2
	jcs .L95
	pea -24(%fp)
	lea (-16,%fp),%a0
	move.l %a0,-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	move.l %a0,-28(%fp)
	jsr (capture.part.0)
	lea (16,%sp),%sp
	move.l -28(%fp),%a0
	tst.l %d0
	jeq .L95
	move.l %a0,-(%sp)
	move.l %d0,-28(%fp)
	jsr dl_publication_ready
	addq.l #4,%sp
	move.l -28(%fp),%d1
	tst.l %d0
	jne .L92
	tst.l project_pending
	jeq .L98
	mov3q.l #4,%d0
	cmp.l project_pending.l,%d0
	jne .L88
	tst.l project_done
	jeq .L88
.L98:
	clr.l -(%sp)
	clr.l -(%sp)
	move.l 8(%fp),-(%sp)
	jsr immediate_request
	lea (12,%sp),%sp
	clr.l %d1
.L119:
	move.l -32(%fp),%d2
	move.l %d1,%d0
	unlk %fp
	rts
.L95:
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	clr.l %d1
	jra .L119
	.size	dl_pattern_request_guard, .-dl_pattern_request_guard
	.align	2
	.globl	dl_chain_stop_guard
	.type	dl_chain_stop_guard, @function
dl_chain_stop_guard:
	link.w %fp,#-52
	move.l %d2,-(%sp)
	mvs.b -2147457603,%d0
	move.l %d0,-20(%fp)
	mvs.b -2147457707,%d1
	clr.l -12(%fp)
	mov3q.l #-1,-8(%fp)
	clr.l -4(%fp)
	move.l %d1,-16(%fp)
	tst.l dl_residency_enabled
	jne .L134
	mov3q.l #1,-52(%fp)
.L120:
	move.l -52(%fp),%d0
	move.l -56(%fp),%d2
	unlk %fp
	rts
.L134:
	moveq #15,%d2
	cmp.l %d0,%d2
	jcs .L124
	moveq #15,%d2
	cmp.l %d1,%d2
	jcs .L124
	pea -44(%fp)
	lea (-36,%fp),%a0
	move.l %a0,-(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %a0,-48(%fp)
	jsr (capture.part.0)
	lea (16,%sp),%sp
	move.l -48(%fp),%a0
	move.l %d0,-52(%fp)
	tst.l %d0
	jeq .L124
	move.l %a0,-(%sp)
	jsr dl_publication_ready
	addq.l #4,%sp
	tst.l %d0
	jne .L120
	addq.l #1,dl_chain_deferred
	tst.l project_pending
	jeq .L126
	mov3q.l #4,%d0
	cmp.l project_pending.l,%d0
	jeq .L135
.L123:
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
.L127:
	clr.l -52(%fp)
.L136:
	move.l -52(%fp),%d0
	move.l -56(%fp),%d2
	unlk %fp
	rts
.L124:
	addq.l #1,dl_chain_deferred
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	jra .L127
.L135:
	tst.l project_done
	jeq .L123
.L126:
	mov3q.l #1,-(%sp)
	clr.l -(%sp)
	pea -20(%fp)
	jsr immediate_request
	lea (12,%sp),%sp
	clr.l -52(%fp)
	jra .L136
	.size	dl_chain_stop_guard, .-dl_chain_stop_guard
	.align	2
	.globl	dl_publication_tick
	.type	dl_publication_tick, @function
dl_publication_tick:
	lea (-60,%sp),%sp
	movem.l #17436,(%sp)
	tst.l project_pending
	jeq .L138
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	jra (project_tick.part.0)
.L138:
	move.l immediate_version,%a0
	mov3q.l #1,%d0
	move.l %a0,%d2
	move.l %a0,%d1
	and.l %d0,%d2
	btst #0,%d1
	jne .L137
	cmp.l immediate_seen.l,%a0
	jeq .L140
	tst.l immediate_pending
	jne .L247
	clr.l immediate_token
	tst.l pending
	jne .L248
.L142:
	lea immediate_saved,%a1
	lea immediate_args,%a2
.L143:
	move.l (%a2,%d2.l*4),(%a1)+
	mov3q.l #5,%d3
	addq.l #1,%d2
	cmp.l %d2,%d3
	jne .L143
	lea immediate_kind,%a1
	move.l (%a1),immediate_saved_kind
	lea immediate_next,%a1
	move.l (%a1),immediate_saved_next
	move.l immediate_passthrough,%d0
	cmp.l immediate_version.l,%a0
	jeq .L249
.L137:
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L249:
	tst.l %d0
	seq %d1
	move.l %a0,immediate_seen
	mvs.b %d1,%d1
	neg.l %d1
	move.l %d1,immediate_pending
	tst.l %d0
	jne .L137
.L140:
	move.l immediate_pending,%d2
	tst.l %d2
	jeq .L144
	tst.l immediate_saved_kind
	jne .L250
	move.b -2147457601,%d0
	mvz.b -2147457600,%d1
	mvz.b %d0,%d0
	lsl.l #8,%d0
	or.l %d1,%d0
	cmp.l immediate_saved_next.l,%d0
	jne .L149
	lea immediate_saved,%a1
	move.l (%a1),%d0
	move.l immediate_saved+4,%d1
	move.l %a1,24(%sp)
.L147:
	move.l %d0,%d2
	moveq #15,%d3
	or.l %d1,%d2
	cmp.l %d2,%d3
	jcs .L150
	lea (36,%sp),%a1
	move.l %a1,32(%sp)
	move.l %a1,-(%sp)
	lea (48,%sp),%a6
	move.l %a6,-(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %a0,36(%sp)
	jsr (capture.part.0)
	lea (16,%sp),%sp
	move.l %d0,%d2
	move.l 20(%sp),%a0
	tst.l %d0
	jeq .L150
	move.l immediate_pending,%d3
	mov3q.l #1,%d0
	cmp.l %d3,%d0
	jeq .L251
	lea ids,%a2
	lea ids+16,%a1
.L158:
	move.b (%a2)+,%d1
	move.b (%a6)+,%d3
	eor.l %d3,%d1
	tst.b %d1
	seq %d1
	mvs.b %d1,%d1
	neg.l %d1
	and.l %d1,%d2
	cmp.l %a1,%a2
	jne .L158
	move.l 32(%sp),%a1
	move.l #sources+8,%d3
	lea sources,%a2
.L159:
	move.b (%a2)+,%d1
	move.b (%a1)+,%d0
	eor.l %d0,%d1
	tst.b %d1
	seq %d1
	mvs.b %d1,%d1
	neg.l %d1
	and.l %d1,%d2
	cmp.l %d3,%a2
	jne .L159
	move.l immediate_token,%d0
	tst.l %d2
	jeq .L252
	move.l %d0,-(%sp)
	move.l %a0,24(%sp)
	jsr dl_publication_poll
	addq.l #4,%sp
	move.l 20(%sp),%a0
	tst.l %d0
	jeq .L137
	mov3q.l #1,%d3
	cmp.l %d0,%d3
	jne .L253
	cmp.l immediate_version.l,%a0
	jne .L137
	move.l immediate_token,-(%sp)
	jsr dl_publication_arm
	addq.l #1,dl_publication_prepared
	clr.l immediate_pending
	addq.l #4,%sp
	tst.l immediate_saved_kind
	jne .L254
	move.l immediate_saved+16,-(%sp)
	move.l immediate_saved+12,-(%sp)
	move.l immediate_saved+8,-(%sp)
	move.l immediate_saved+4,-(%sp)
	move.l 40(%sp),%a1
	move.l (%a1),-(%sp)
	jsr dl_pattern_post_body
	lea (20,%sp),%sp
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L144:
	move.b -2147457601,%d0
	move.b -2147457600,%d1
	mvz.b -2147457603,%d3
	move.l %d3,24(%sp)
	mvz.b -2147457602,%d4
	move.l pending,%d3
	move.w %d1,%a1
	move.l %d4,28(%sp)
	mvz.b %d0,%d1
	move.w %a1,%d4
	mvz.b %d4,%d4
	move.l %d4,%a2
	tst.l %d3
	jeq .L167
	cmp.l bank.l,%d1
	jeq .L255
.L168:
	tst.l deferred
	jeq .L241
	cmp.l 24(%sp),%d1
	jne .L241
	cmp.l 28(%sp),%a2
	jeq .L169
.L241:
	move.l token,-(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	movem.l (%sp),#17436
	clr.l pending
	lea (60,%sp),%sp
	rts
.L167:
	tst.l missed
	jeq .L179
	cmp.l 24(%sp),%d1
	jeq .L256
	move.l %a1,%d2
	or.l %d2,%d0
	tst.l missed
	jeq .L182
	mvz.b %d0,%d0
	clr.l missed
	moveq #15,%d4
	cmp.l %d0,%d4
	jcs .L137
.L183:
	pea sources
	pea ids
	move.l %a2,-(%sp)
	move.l %d1,-(%sp)
	move.l %d1,36(%sp)
	jsr (capture.part.0)
	lea (16,%sp),%sp
	move.l %d0,%d2
	move.l 20(%sp),%d1
	tst.l %d0
	jeq .L257
	move.l %d1,bank
	move.l %a2,pattern
	move.l serial,%d0
	addq.l #1,%d0
	move.l %d3,deferred
	tst.l %d0
	jne .L258
	move.l #1073741825,%d1
	move.l %d1,%d0
.L186:
	move.l %d0,-(%sp)
	pea sources
	move.l %d1,serial
	pea ids
	move.l %d0,token
	jsr dl_publication_prepare
	lea (12,%sp),%sp
	moveq #-3,%d1
	cmp.l %d0,%d1
	jeq .L259
	tst.l %d0
	jlt .L260
	movem.l (%sp),#17436
	clr.l missed
	mov3q.l #1,pending
	lea (60,%sp),%sp
	rts
.L179:
	move.l missed,%d3
	tst.l %d3
	jeq .L181
	clr.l missed
	clr.l %d3
.L181:
	move.l %a2,%d0
	moveq #15,%d2
	or.l %d1,%d0
	cmp.l %d0,%d2
	jcs .L137
	cmp.l 24(%sp),%d1
	jne .L183
	cmp.l 28(%sp),%a2
	jne .L183
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L248:
	move.l token,-(%sp)
	move.l %a0,24(%sp)
	jsr dl_selection_cancel
	clr.l pending
	addq.l #4,%sp
	clr.l missed
	lea immediate_saved,%a1
	lea immediate_args,%a2
	move.l 20(%sp),%a0
	jra .L143
.L247:
	move.l immediate_token,-(%sp)
	move.l %a0,24(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	clr.l immediate_token
	move.l 20(%sp),%a0
	tst.l pending
	jeq .L142
	jra .L248
.L255:
	cmp.l pattern.l,%d4
	jne .L168
.L169:
	move.l pattern,%d1
	move.l %d1,%d3
	move.l bank,%d0
	moveq #15,%d4
	clr.l 44(%sp)
	lea (44,%sp),%a6
	or.l %d0,%d3
	clr.l 48(%sp)
	clr.l 52(%sp)
	clr.l 56(%sp)
	clr.l 36(%sp)
	clr.l 40(%sp)
	cmp.l %d3,%d4
	jcs .L261
	lea (36,%sp),%a1
	move.l %a1,32(%sp)
	move.l %a1,-(%sp)
	move.l %a6,-(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	jsr (capture.part.0)
	lea (16,%sp),%sp
	lea ids,%a2
	move.l %a6,%a0
	move.l %d0,%d2
	lea (60,%sp),%a1
.L173:
	move.b (%a0)+,%d1
	move.b (%a2)+,%d3
	eor.l %d3,%d1
	tst.b %d1
	seq %d1
	mvs.b %d1,%d1
	neg.l %d1
	and.l %d1,%d2
	cmp.l %a1,%a0
	jne .L173
	move.l 32(%sp),%a1
	lea sources,%a2
.L174:
	move.b (%a1)+,%d1
	move.b (%a2)+,%d0
	eor.l %d0,%d1
	tst.b %d1
	seq %d1
	mvs.b %d1,%d1
	neg.l %d1
	and.l %d1,%d2
	cmp.l %a6,%a1
	jne .L174
	tst.l %d2
	jeq .L241
	mov3q.l #2,%d0
	cmp.l pending.l,%d0
	jeq .L262
	move.l token,-(%sp)
	jsr dl_publication_poll
	addq.l #4,%sp
	tst.l %d0
	jeq .L137
	move.l token,%d1
	mov3q.l #1,%d3
	cmp.l %d0,%d3
	jeq .L177
	move.l %d1,-(%sp)
	move.l %d0,24(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	mov3q.l #-1,%d4
	addq.l #1,dl_publication_refused
	move.l 20(%sp),%d0
	cmp.l %d0,%d4
	jeq .L193
	addq.l #2,%d0
	tst.l %d0
	jeq .L263
	move.l %d2,dl_modal_pending
#APP
| 35 "publication.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #-2147457603,%a0
	move.b (%a0),-2147457601
	move.l #-2147457602,%a1
	move.b (%a1),-2147457600
#APP
| 40 "publication.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	clr.l missed
.L242:
	movem.l (%sp),#17436
	clr.l pending
	lea (60,%sp),%sp
	rts
.L250:
	tst.l -2147457608
	jne .L146
	tst.l -2147457722
	jeq .L146
	lea immediate_saved,%a1
	move.l %a1,24(%sp)
	mvs.b -2147457603,%d1
	move.l (%a1),%d0
	cmp.l %d1,%d0
	jne .L146
	mvs.b -2147457707,%d2
	move.l immediate_saved+4,%d1
	cmp.l %d2,%d1
	jeq .L147
.L146:
	move.l immediate_token,-(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	movem.l (%sp),#17436
	clr.l immediate_pending
	addq.l #1,dl_chain_dropped
	lea (60,%sp),%sp
	rts
.L182:
	mvz.b %d0,%d0
	moveq #15,%d4
	cmp.l %d0,%d4
	jcc .L183
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L258:
	move.l %d0,%d1
	jra .L186
.L261:
	lea (36,%sp),%a0
	move.l %a0,32(%sp)
	move.l %a6,%a0
	lea (60,%sp),%a1
	lea ids,%a2
	jra .L173
.L251:
	move.l %a0,20(%sp)
	jsr dl_publication_idle
	move.l 20(%sp),%a0
	tst.l %d0
	jeq .L137
	move.l serial,%d1
	addq.l #1,%d1
	move.l %d1,28(%sp)
	tst.l %d1
	jeq .L190
	move.l 28(%sp),%d4
	move.l %d1,%d0
	move.l %d0,serial
	move.l %sp,%d1
	move.l %a6,%a2
	move.l %d4,immediate_token
	add.l #60,%d1
	lea ids,%a1
.L154:
	move.b (%a2)+,(%a1)+
	cmp.l %a2,%d1
	jne .L154
	move.l 32(%sp),%a2
	lea sources,%a1
.L155:
	move.b (%a2)+,(%a1)+
	cmp.l %a6,%a2
	jne .L155
	move.l 28(%sp),-(%sp)
	pea sources
	pea ids
	move.l %a0,32(%sp)
	jsr dl_publication_prepare
	lea (12,%sp),%sp
	move.l 20(%sp),%a0
	tst.l %d0
	jlt .L264
	mov3q.l #2,immediate_pending
	lea ids,%a2
	lea ids+16,%a1
	jra .L158
.L263:
	mov3q.l #3,%d2
	move.l %d2,dl_modal_pending
#APP
| 35 "publication.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #-2147457603,%a0
	move.b (%a0),-2147457601
	move.l #-2147457602,%a1
	move.b (%a1),-2147457600
#APP
| 40 "publication.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	clr.l missed
	jra .L242
.L256:
	cmp.l 28(%sp),%d4
	jne .L179
	move.l missed,%d1
	lsr.l #8,%d1
	move.l missed,%d0
	mov3q.l #1,%d3
	mvz.b %d0,%d0
	mvz.b %d1,%d1
	move.l %d0,%a2
	jra .L181
.L149:
	move.l immediate_token,-(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	movem.l (%sp),#17436
	clr.l immediate_pending
	addq.l #1,dl_publication_superseded
	lea (60,%sp),%sp
	rts
.L257:
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
#APP
| 35 "publication.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #-2147457603,%a0
	move.l #-2147457602,%a1
	move.b (%a0),-2147457601
	move.b (%a1),-2147457600
#APP
| 40 "publication.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	clr.l missed
.L268:
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L252:
	move.l %d0,-(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	movem.l (%sp),#17436
	mov3q.l #1,immediate_pending
	lea (60,%sp),%sp
	rts
.L150:
	move.l immediate_token,-(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	movem.l (%sp),#17436
	clr.l immediate_pending
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	lea (60,%sp),%sp
	rts
.L262:
	move.l 24(%sp),%d1
	cmp.l bank.l,%d1
	jne .L137
	move.l 28(%sp),%d2
	cmp.l pattern.l,%d2
	jeq .L242
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L253:
	move.l immediate_token,-(%sp)
	move.l %d0,24(%sp)
	jsr dl_selection_cancel
	clr.l immediate_pending
	addq.l #4,%sp
	mov3q.l #-1,%d4
	addq.l #1,dl_publication_refused
	move.l 20(%sp),%d0
	cmp.l %d0,%d4
	jeq .L192
	addq.l #2,%d0
	tst.l %d0
	jeq .L265
	move.l %d2,dl_modal_pending
.L266:
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L265:
	mov3q.l #3,%d2
	move.l %d2,dl_modal_pending
	jra .L266
.L260:
	addq.l #1,dl_publication_refused
	mov3q.l #-1,%d3
	cmp.l %d0,%d3
	jeq .L195
	addq.l #2,%d0
	tst.l %d0
	jeq .L267
	move.l %d2,dl_modal_pending
.L269:
#APP
| 35 "publication.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #-2147457603,%a0
	move.b (%a0),-2147457601
	move.l #-2147457602,%a1
	move.b (%a1),-2147457600
#APP
| 40 "publication.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	clr.l missed
	jra .L268
.L267:
	mov3q.l #3,%d2
	move.l %d2,dl_modal_pending
	jra .L269
.L259:
	jsr dl_publication_idle
	tst.l %d0
	jeq .L137
	addq.l #1,dl_publication_refused
	move.l %d2,dl_modal_pending
	jra .L269
.L177:
	move.l %d1,-(%sp)
	jsr dl_publication_arm
	addq.l #1,dl_publication_prepared
	mov3q.l #2,pending
	addq.l #4,%sp
	tst.l deferred
	jeq .L137
	clr.l missed
	clr.l -(%sp)
	move.l pattern,%d0
	mov3q.l #-1,-(%sp)
	clr.l -(%sp)
	move.l %d0,-(%sp)
	move.l bank,-(%sp)
	jsr 1074398576
	lea (20,%sp),%sp
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L190:
	move.l #1073741825,%d0
	move.l %d0,28(%sp)
	move.l 28(%sp),%d4
	move.l %sp,%d1
	move.l %d0,serial
	move.l %a6,%a2
	add.l #60,%d1
	move.l %d4,immediate_token
	lea ids,%a1
	jra .L154
.L193:
	mov3q.l #2,%d2
	move.l %d2,dl_modal_pending
#APP
| 35 "publication.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #-2147457603,%a0
	move.b (%a0),-2147457601
	move.l #-2147457602,%a1
	move.b (%a1),-2147457600
#APP
| 40 "publication.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	clr.l missed
	jra .L242
.L192:
	mov3q.l #2,%d2
	move.l %d2,dl_modal_pending
	jra .L266
.L195:
	mov3q.l #2,%d2
	move.l %d2,dl_modal_pending
	jra .L269
.L264:
	clr.l immediate_pending
	addq.l #1,dl_publication_refused
	mov3q.l #-1,%d1
	cmp.l %d0,%d1
	jeq .L191
	addq.l #2,%d0
	tst.l %d0
	jeq .L270
	move.l %d3,dl_modal_pending
.L271:
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L270:
	mov3q.l #3,%d3
	move.l %d3,dl_modal_pending
	jra .L271
.L254:
	addq.l #1,dl_chain_restarted
	clr.l -2147457718
	move.l #635712,%d3
	move.l -2147457710,%d0
	mvz.w #36568,%d4
	move.b %d0,-2147457602
	mvs.b %d0,%d0
	move.b -2147457603,%d1
	move.l %d0,-(%sp)
	mvs.b %d1,%d1
	move.l %d1,-(%sp)
	jsr 1074401328
	addq.l #8,%sp
	move.l -2147457718,%d1
	addq.l #1,%d1
	move.l %d1,-2147457718
	move.l %d1,%d0
	lsl.l #2,%d0
	move.l %d0,%a0
	add.l #-2147457707,%a0
	move.b (%a0),-2147457600
	clr.l -2147457488
	move.b -2147457600,%d0
	mvs.b -2147457603,%d2
	muls.l %d3,%d2
	mvs.b %d0,%d0
	muls.l %d4,%d0
	add.l %d2,%d0
	move.l %d0,%a0
	add.l #1074704437,%a0
	tst.b (%a0)
	jeq .L164
	add.l #1074704432,%d0
	move.l %d0,%a0
	mvs.w (%a0),%d0
.L165:
	move.l %d0,-2147457484
	cmp.l -2147457714.l,%d1
	jlt .L166
	clr.l -2147457718
.L166:
	move.l #-2147457602,%a0
	move.b (%a0),1074626917
	move.l #1074626916,-(%sp)
	move.l #1175263150,-(%sp)
	jsr 1073744956
	addq.l #8,%sp
	movem.l (%sp),#17436
	lea (60,%sp),%sp
	rts
.L164:
	add.l #1074704435,%d0
	move.l %d0,%a1
	mvs.b (%a1),%d0
	jra .L165
.L191:
	mov3q.l #2,%d3
	move.l %d3,dl_modal_pending
	jra .L271
	.size	dl_publication_tick, .-dl_publication_tick
	.align	2
	.globl	dl_project_guard
	.type	dl_project_guard, @function
dl_project_guard:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	move.l 12(%sp),%a0
	mov3q.l #4,%d0
	cmp.l project_pending.l,%d0
	jeq .L307
.L273:
	tst.l %a0
	jeq .L274
.L309:
	move.l project_pending,%d2
	tst.l %d2
	jne .L274
	clr.l %d0
	lea project_name,%a1
.L275:
	move.b (%a0,%d0.l),%d1
	move.b %d1,(%a1,%d0.l)
	jeq .L308
	addq.l #1,%d0
	cmp.l #256,%d0
	jne .L275
.L281:
	move.l %d2,%d0
	move.l (%sp)+,%d2
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	addq.l #4,%sp
	rts
.L307:
	tst.l project_done
	jeq .L273
	tst.l project_pending
	jeq .L273
	move.l %a0,4(%sp)
	jsr (project_tick.part.0)
	move.l 4(%sp),%a0
	tst.l %a0
	jne .L309
.L274:
	clr.l %d2
	move.l %d2,%d0
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L308:
	tst.l %d0
	jeq .L281
	move.l %a0,-(%sp)
	clr.l -(%sp)
	jsr 1073893936
	addq.l #8,%sp
	clr.l %d1
	move.l %d0,%a1
	move.b (%a1,%d1.l),%d0
	lea project_path,%a0
	move.b %d0,(%a0,%d1.l)
	jeq .L310
.L280:
	addq.l #1,%d1
	cmp.l #260,%d1
	jeq .L281
	move.b (%a1,%d1.l),%d0
	move.b %d0,(%a0,%d1.l)
	jne .L280
.L310:
	tst.l %d1
	jeq .L281
	clr.l project_done
	clr.l project_authorized
	mov3q.l #1,%d2
	move.l %d2,%d0
	mov3q.l #1,project_pending
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
	.size	dl_project_guard, .-dl_project_guard
	.align	2
	.globl	dl_project_engine_guard
	.type	dl_project_engine_guard, @function
dl_project_engine_guard:
	move.l project_authorized,%d0
	move.l %d2,-(%sp)
	tst.l %d0
	jeq .L321
	move.l 8(%sp),%a1
	addq.l #1,%a1
	lea project_name,%a0
.L315:
	move.b (%a0),%d0
	mvz.b (%a1),%d2
	addq.l #1,%a1
	addq.l #1,%a0
	mvz.b %d0,%d1
	cmp.l %d2,%d1
	jne .L322
	tst.b %d0
	jeq .L317
	cmp.l #project_name+256,%a0
	jne .L315
	clr.l %d0
.L311:
	move.l (%sp)+,%d2
	rts
.L321:
	addq.l #1,dl_project_refused
	move.l (%sp)+,%d2
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	rts
.L322:
	addq.l #1,dl_project_refused
	addq.l #1,dl_publication_refused
	mov3q.l #1,dl_modal_pending
	clr.l %d0
	jra .L311
.L317:
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	rts
	.size	dl_project_engine_guard, .-dl_project_engine_guard
	.align	2
	.globl	dl_project_finished
	.type	dl_project_finished, @function
dl_project_finished:
	lea (4,%sp),%a0
	move.l (%a0),project_result
	mov3q.l #1,project_done
	rts
	.size	dl_project_finished, .-dl_project_finished
	.align	2
	.globl	dl_publication_finish
	.type	dl_publication_finish, @function
dl_publication_finish:
	mov3q.l #4,%d0
	cmp.l project_pending.l,%d0
	jeq .L335
.L325:
	rts
.L335:
	tst.l project_done
	jeq .L325
	tst.l project_pending
	jeq .L325
	jra (project_tick.part.0)
	.size	dl_publication_finish, .-dl_publication_finish
	.globl	dl_project_completed
	.data
	.align	2
	.type	dl_project_completed, @object
	.size	dl_project_completed, 4
dl_project_completed:
	.zero	4
	.globl	dl_project_refused
	.align	2
	.type	dl_project_refused, @object
	.size	dl_project_refused, 4
dl_project_refused:
	.zero	4
	.globl	dl_project_admitted
	.align	2
	.type	dl_project_admitted, @object
	.size	dl_project_admitted, 4
dl_project_admitted:
	.zero	4
	.align	2
	.type	project_target, @object
	.size	project_target, 36
project_target:
	.zero	36
	.type	project_path, @object
	.size	project_path, 260
project_path:
	.zero	260
	.type	project_name, @object
	.size	project_name, 256
project_name:
	.zero	256
	.align	2
	.type	project_result, @object
	.size	project_result, 4
project_result:
	.zero	4
	.align	2
	.type	project_token, @object
	.size	project_token, 4
project_token:
	.zero	4
	.align	2
	.type	project_done, @object
	.size	project_done, 4
project_done:
	.zero	4
	.align	2
	.type	project_authorized, @object
	.size	project_authorized, 4
project_authorized:
	.zero	4
	.align	2
	.type	project_pending, @object
	.size	project_pending, 4
project_pending:
	.zero	4
	.align	2
	.type	immediate_pending, @object
	.size	immediate_pending, 4
immediate_pending:
	.zero	4
	.globl	dl_publication_superseded
	.align	2
	.type	dl_publication_superseded, @object
	.size	dl_publication_superseded, 4
dl_publication_superseded:
	.zero	4
	.globl	dl_chain_dropped
	.align	2
	.type	dl_chain_dropped, @object
	.size	dl_chain_dropped, 4
dl_chain_dropped:
	.zero	4
	.globl	dl_chain_restarted
	.align	2
	.type	dl_chain_restarted, @object
	.size	dl_chain_restarted, 4
dl_chain_restarted:
	.zero	4
	.globl	dl_chain_deferred
	.align	2
	.type	dl_chain_deferred, @object
	.size	dl_chain_deferred, 4
dl_chain_deferred:
	.zero	4
	.align	2
	.type	immediate_saved_next, @object
	.size	immediate_saved_next, 4
immediate_saved_next:
	.zero	4
	.align	2
	.type	immediate_saved_kind, @object
	.size	immediate_saved_kind, 4
immediate_saved_kind:
	.zero	4
	.align	2
	.type	immediate_saved, @object
	.size	immediate_saved, 20
immediate_saved:
	.zero	20
	.align	2
	.type	immediate_token, @object
	.size	immediate_token, 4
immediate_token:
	.zero	4
	.align	2
	.type	immediate_passthrough, @object
	.size	immediate_passthrough, 4
immediate_passthrough:
	.zero	4
	.align	2
	.type	immediate_seen, @object
	.size	immediate_seen, 4
immediate_seen:
	.zero	4
	.align	2
	.type	immediate_next, @object
	.size	immediate_next, 4
immediate_next:
	.zero	4
	.align	2
	.type	immediate_kind, @object
	.size	immediate_kind, 4
immediate_kind:
	.zero	4
	.align	2
	.type	immediate_args, @object
	.size	immediate_args, 20
immediate_args:
	.zero	20
	.align	2
	.type	immediate_version, @object
	.size	immediate_version, 4
immediate_version:
	.zero	4
	.globl	dl_publication_refused
	.align	2
	.type	dl_publication_refused, @object
	.size	dl_publication_refused, 4
dl_publication_refused:
	.zero	4
	.globl	dl_publication_deferred
	.align	2
	.type	dl_publication_deferred, @object
	.size	dl_publication_deferred, 4
dl_publication_deferred:
	.zero	4
	.globl	dl_publication_prepared
	.align	2
	.type	dl_publication_prepared, @object
	.size	dl_publication_prepared, 4
dl_publication_prepared:
	.zero	4
	.type	sources, @object
	.size	sources, 8
sources:
	.zero	8
	.type	ids, @object
	.size	ids, 16
ids:
	.zero	16
	.align	2
	.type	missed, @object
	.size	missed, 4
missed:
	.zero	4
	.align	2
	.type	deferred, @object
	.size	deferred, 4
deferred:
	.zero	4
	.align	2
	.type	pattern, @object
	.size	pattern, 4
pattern:
	.zero	4
	.align	2
	.type	bank, @object
	.size	bank, 4
bank:
	.zero	4
	.align	2
	.type	pending, @object
	.size	pending, 4
pending:
	.zero	4
	.align	2
	.type	token, @object
	.size	token, 4
token:
	.zero	4
	.align	2
	.type	serial, @object
	.size	serial, 4
serial:
	.long	1073741824
