| Generated by generate.py from selection.c.
#NO_APP
	.file	"selection.c"
	.text
	.align	2
	.type	dl_selection_capture, @function
dl_selection_capture:
	lea (-28,%sp),%sp
	movem.l #3084,(%sp)
	move.l 1187521622,%d0
	mov3q.l #2,%d3
	move.l 40(%sp),%a1
	move.l %d0,(%a1)
	mvz.b -2147483646,%d1
	move.l %d1,4(%a1)
	mvz.b -2147483644,%d1
	move.l %d1,8(%a1)
	move.b -2147483645,%d1
	move.w %d1,%a0
	mvz.b %d1,%d1
	move.l %d1,12(%a1)
	mvz.b -2147483648,%d2
	move.l 32(%sp),20(%a1)
	move.l %d2,16(%a1)
	cmp.l 32(%sp),%d3
	jeq .L27
	tst.l 32(%sp)
	jeq .L28
	move.l #1175280808,%a2
	mov3q.l #2,%d3
	move.l (%a2),24(%a1)
	cmp.l 32(%sp),%d3
	jcc .L3
.L5:
	clr.l %d0
.L1:
	movem.l (%sp),#3084
	lea (28,%sp),%sp
	rts
.L28:
	move.l #1175280788,%a2
	move.l (%a2),24(%a1)
.L3:
	mov3q.l #3,%d3
	cmp.l %d1,%d3
	jcs .L5
	mov3q.l #7,%d1
	cmp.l %d2,%d1
	jcs .L5
	move.l 24(%a1),%d3
	moveq #31,%d1
	move.l %d3,20(%sp)
	cmp.l %d3,%d1
	jcs .L5
	tst.l %d0
	jeq .L1
	move.w %a0,%d1
	add.l #585088,%d0
	move.l %d0,24(%sp)
	lea (28,%a1),%a0
	lea (44,%a1),%a2
	ext.w %d1
	mulu.w #6322,%d1
	add.l %d1,%d0
	move.l %d0,%a3
	lea (-28,%a3),%a3
	sub.l %a1,%a3
.L8:
	move.b (%a3,%a0.l),%d1
	move.b %d1,(%a0)+
	move.b %d1,15(%a0)
	cmp.l %a0,%a2
	jne .L8
	move.l %d0,%d1
	add.l #-26,%d1
	lea (60,%a1),%a0
	move.l %d1,%d0
	sub.l %a1,%d0
	move.l %a0,16(%sp)
	lea (68,%a1),%a3
.L9:
	move.b (%a0,%d0.l),%d1
	move.b %d1,(%a0)+
	move.b %d1,7(%a0)
	cmp.l %a0,%a3
	jne .L9
	mov3q.l #2,%d0
	cmp.l 32(%sp),%d0
	jeq .L29
	tst.l 32(%sp)
	jeq .L14
	move.l #1074618512,%a0
.L13:
	move.l 20(%sp),%d3
	move.l (%a0,%d3.l*4),%d0
	tst.l %d0
	jeq .L1
	move.l %d0,%a2
	moveq #31,%d0
	move.l (%a2),%a0
	cmp.l %a0,%d0
	jcs .L5
	move.l 32(%sp),%d1
	mov3q.l #1,%d0
	lsl.l #3,%d1
	add.l %d1,%a1
	move.w %a0,%d1
	move.b %d1,44(%a1,%d2.l)
	movem.l (%sp),#3084
	lea (28,%sp),%sp
	rts
.L27:
	move.l 36(%sp),24(%a1)
	jra .L3
.L29:
	mov3q.l #3,%d1
	cmp.l 36(%sp),%d1
	jcs .L5
	mvz.w #6322,%d2
	move.l 36(%sp),%d1
	move.l 24(%sp),%d0
	muls.l %d2,%d1
	add.l %d1,%d0
	move.l %d0,%a0
	lea (-44,%a0),%a0
	sub.l %a1,%a0
.L11:
	move.b (%a0,%a2.l),%d1
	move.b %d1,(%a2)+
	cmp.l 16(%sp),%a2
	jne .L11
	add.l #-34,%d0
	move.l %a1,%d1
	move.l %d0,%a0
	add.l #76,%d1
	sub.l %a1,%a0
.L12:
	move.b (%a0,%a3.l),%d0
	move.b %d0,(%a3)+
	cmp.l %a3,%d1
	jne .L12
	movem.l (%sp),#3084
	mov3q.l #1,%d0
	lea (28,%sp),%sp
	rts
.L14:
	move.l #1074618464,%a0
	jra .L13
	.size	dl_selection_capture, .-dl_selection_capture
	.align	2
	.type	same.constprop.0, @function
same.constprop.0:
	subq.l #4,%sp
	move.l %a2,-(%sp)
	move.l %d2,-(%sp)
	move.l 16(%sp),%a0
	move.l (%a0),%d0
	cmp.l queued.l,%d0
	jne .L33
	move.l 4(%a0),%d1
	cmp.l queued+4.l,%d1
	jeq .L40
.L33:
	move.l (%sp)+,%d2
	clr.l %d0
	move.l (%sp)+,%a2
	addq.l #4,%sp
	rts
.L40:
	move.l 8(%a0),%d2
	cmp.l queued+8.l,%d2
	jne .L33
	move.l 12(%a0),%a2
	cmp.l queued+12.l,%a2
	jne .L33
	move.l 16(%a0),%d0
	cmp.l queued+16.l,%d0
	jne .L33
	move.l 20(%a0),%d1
	cmp.l queued+20.l,%d1
	jne .L33
	move.l 24(%a0),%d2
	cmp.l queued+24.l,%d2
	jne .L33
	move.l %a0,%d0
	add.l #28,%d0
	lea queued+28,%a1
.L34:
	mvz.b (%a1),%d1
	addq.l #1,%d0
	move.l %d0,%a2
	addq.l #1,%a1
	move.l %d1,8(%sp)
	mvz.b -1(%a2),%d1
	cmp.l 8(%sp),%d1
	jne .L33
	mvz.b 15(%a1),%d1
	move.l %d1,8(%sp)
	mvz.b 15(%a2),%d1
	cmp.l 8(%sp),%d1
	jne .L33
	cmp.l #queued+44,%a1
	jne .L34
	lea (60,%a0),%a1
	lea (68,%a0),%a0
	move.l #queued+60,%d0
	move.l %a0,8(%sp)
.L35:
	addq.l #1,%d0
	move.l %d0,%a2
	addq.l #1,%a1
	mvz.b -1(%a2),%d2
	mvz.b -1(%a1),%d1
	cmp.l %d2,%d1
	jne .L33
	mvz.b 7(%a2),%d1
	move.l %d1,%a0
	mvz.b 7(%a1),%d1
	cmp.l %a0,%d1
	jne .L33
	cmp.l 8(%sp),%a1
	jne .L35
	move.l (%sp)+,%d2
	mov3q.l #1,%d0
	move.l (%sp)+,%a2
	addq.l #4,%sp
	rts
	.size	same.constprop.0, .-same.constprop.0
	.align	2
	.type	guard, @function
guard:
	lea (-80,%sp),%sp
	move.l %a6,-(%sp)
	pea 8(%sp)
	move.l 96(%sp),-(%sp)
	move.l 96(%sp),-(%sp)
	jsr dl_selection_capture
	lea (12,%sp),%sp
	move.l %d0,%a6
	tst.l %d0
	jeq .L64
	tst.l replay
	jeq .L44
	pea 8(%sp)
	jsr (same.constprop.0)
	addq.l #4,%sp
	move.l %d0,%a6
	tst.l %d0
	jne .L61
.L41:
	move.l %a6,%d0
	move.l (%sp)+,%a6
	lea (80,%sp),%sp
	rts
.L44:
	tst.l pending
	jeq .L48
	pea 8(%sp)
	jsr (same.constprop.0)
	addq.l #4,%sp
	tst.l %d0
	jne .L56
	move.l token,-(%sp)
	jsr dl_selection_cancel
	clr.l pending
	addq.l #1,dl_selection_cancelled
	addq.l #4,%sp
.L48:
	mov3q.l #2,%d0
	cmp.l 88(%sp),%d0
	jeq .L65
	move.l 88(%sp),%d0
	lsl.l #3,%d0
	add.l 24(%sp),%d0
	mvz.b 36(%sp,%d0.l),%d1
	mvz.b 52(%sp,%d0.l),%d0
	cmp.l %d1,%d0
	jeq .L41
.L51:
	move.l serial,%d0
	addq.l #1,%d0
	tst.l %d0
	jeq .L58
	move.l %d0,%d1
.L52:
	move.l %d0,-(%sp)
	move.l %d1,serial
	pea 12(%sp)
	move.l %d0,token
	addq.l #1,dl_selection_requested
	jsr dl_selection_prepare
	addq.l #8,%sp
	mov3q.l #1,%d1
	cmp.l %d0,%d1
	jeq .L61
	tst.l %d0
	jne .L66
	lea (8,%sp),%a0
	lea (84,%sp),%a6
	lea queued,%a1
.L57:
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%a6
	jne .L57
	mov3q.l #1,pending
.L56:
	sub.l %a6,%a6
.L68:
	move.l %a6,%d0
	move.l (%sp)+,%a6
	lea (80,%sp),%sp
	rts
.L61:
	move.l %a6,%d0
	move.l (%sp)+,%a6
	lea token,%a0
	move.l (%a0),applying
	lea (80,%sp),%sp
	rts
.L64:
	move.l %a6,%d0
	move.l (%sp)+,%a6
	addq.l #1,dl_selection_refused
	mov3q.l #1,dl_modal_pending
	lea (80,%sp),%sp
	rts
.L65:
	move.l 20(%sp),%d1
	cmp.l 32(%sp),%d1
	jne .L51
	move.l %a6,%d0
	move.l (%sp)+,%a6
	lea (80,%sp),%sp
	rts
.L58:
	move.l %a6,%d1
	move.l %a6,%d0
	jra .L52
.L66:
	move.l token,-(%sp)
	move.l %d0,8(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	addq.l #1,dl_selection_refused
	move.l 4(%sp),%d0
	mov3q.l #-1,%d1
	cmp.l %d0,%d1
	jeq .L59
	addq.l #2,%d0
	tst.l %d0
	jeq .L67
	move.l %a6,dl_modal_pending
.L69:
	sub.l %a6,%a6
	jra .L68
.L67:
	mov3q.l #3,%a6
	move.l %a6,dl_modal_pending
	jra .L69
.L59:
	mov3q.l #2,%a6
	move.l %a6,dl_modal_pending
	jra .L69
	.size	guard, .-guard
	.align	2
	.globl	dl_selection_guard
	.type	dl_selection_guard, @function
dl_selection_guard:
	clr.l -(%sp)
	move.l 8(%sp),-(%sp)
	jsr guard
	addq.l #8,%sp
	rts
	.size	dl_selection_guard, .-dl_selection_guard
	.align	2
	.globl	dl_selection_part_guard
	.type	dl_selection_part_guard, @function
dl_selection_part_guard:
	move.l 4(%sp),-(%sp)
	mov3q.l #2,-(%sp)
	jsr guard
	addq.l #8,%sp
	rts
	.size	dl_selection_part_guard, .-dl_selection_part_guard
	.align	2
	.globl	dl_selection_applied
	.type	dl_selection_applied, @function
dl_selection_applied:
	move.l applying,%d0
	tst.l %d0
	jne .L81
	rts
.L81:
	move.l %d0,-(%sp)
	jsr dl_selection_commit
	clr.l applying
	addq.l #1,dl_selection_completed
	addq.l #4,%sp
	rts
	.size	dl_selection_applied, .-dl_selection_applied
	.align	2
	.globl	dl_selection_tick
	.type	dl_selection_tick, @function
dl_selection_tick:
	lea (-84,%sp),%sp
	move.l %a6,-(%sp)
	move.l %d2,-(%sp)
	tst.l pending
	jne .L101
.L82:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a6
	lea (84,%sp),%sp
	rts
.L101:
	pea 16(%sp)
	move.l queued+24,-(%sp)
	move.l queued+20,-(%sp)
	jsr dl_selection_capture
	lea (12,%sp),%sp
	move.l token,%a6
	tst.l %d0
	jeq .L84
	pea 16(%sp)
	jsr (same.constprop.0)
	addq.l #4,%sp
	tst.l %d0
	jne .L85
.L84:
	move.l %a6,-(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	move.l (%sp)+,%d2
	clr.l pending
	addq.l #1,dl_selection_cancelled
	move.l (%sp)+,%a6
	lea (84,%sp),%sp
	rts
.L85:
	move.l %a6,-(%sp)
	move.l %d0,12(%sp)
	jsr dl_selection_poll
	addq.l #4,%sp
	move.l 8(%sp),%d1
	tst.l %d0
	jeq .L82
	mov3q.l #1,%d2
	cmp.l %d0,%d2
	jeq .L86
	move.l token,-(%sp)
	move.l %d0,16(%sp)
	move.l %d1,12(%sp)
	jsr dl_selection_cancel
	addq.l #4,%sp
	clr.l pending
	mov3q.l #-1,%d2
	addq.l #1,dl_selection_cancelled
	move.l 12(%sp),%d0
	addq.l #1,dl_selection_refused
	move.l 8(%sp),%d1
	cmp.l %d0,%d2
	jeq .L91
	addq.l #2,%d0
	tst.l %d0
	jeq .L102
	move.l %d1,dl_modal_pending
.L104:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a6
	lea (84,%sp),%sp
	rts
.L86:
	move.l queued+20,%d0
	mov3q.l #2,%d1
	mov3q.l #1,replay
	cmp.l %d0,%d1
	jeq .L103
	tst.l %d0
	jeq .L92
	move.l #1074078836,%a0
	jsr (%a0)
.L89:
	clr.l replay
	clr.l pending
.L105:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a6
	lea (84,%sp),%sp
	rts
.L91:
	mov3q.l #2,%d1
	move.l %d1,dl_modal_pending
	jra .L104
.L102:
	mov3q.l #3,%d1
	move.l %d1,dl_modal_pending
	jra .L104
.L103:
	move.l queued+24,-(%sp)
	jsr 1074047140
	addq.l #4,%sp
	clr.l replay
	clr.l pending
	jra .L105
.L92:
	move.l #1074079460,%a0
	jsr (%a0)
	jra .L89
	.size	dl_selection_tick, .-dl_selection_tick
	.data
	.align	2
	.type	replay, @object
	.size	replay, 4
replay:
	.zero	4
	.align	2
	.type	pending, @object
	.size	pending, 4
pending:
	.zero	4
	.align	2
	.type	applying, @object
	.size	applying, 4
applying:
	.zero	4
	.align	2
	.type	token, @object
	.size	token, 4
token:
	.zero	4
	.align	2
	.type	serial, @object
	.size	serial, 4
serial:
	.zero	4
	.align	2
	.type	queued, @object
	.size	queued, 76
queued:
	.zero	76
	.globl	dl_selection_refused
	.align	2
	.type	dl_selection_refused, @object
	.size	dl_selection_refused, 4
dl_selection_refused:
	.zero	4
	.globl	dl_selection_cancelled
	.align	2
	.type	dl_selection_cancelled, @object
	.size	dl_selection_cancelled, 4
dl_selection_cancelled:
	.zero	4
	.globl	dl_selection_completed
	.align	2
	.type	dl_selection_completed, @object
	.size	dl_selection_completed, 4
dl_selection_completed:
	.zero	4
	.globl	dl_selection_requested
	.align	2
	.type	dl_selection_requested, @object
	.size	dl_selection_requested, 4
dl_selection_requested:
	.zero	4
