| Generated by generate.py from selection_probe.c.
#NO_APP
	.file	"selection_probe.c"
	.text
	.align	2
	.globl	dl_selection_prepare
	.type	dl_selection_prepare, @function
dl_selection_prepare:
	lea (-12,%sp),%sp
	movem.l #28,(%sp)
	move.l 16(%sp),%d3
	move.l %d3,%a0
	move.l %d3,%a1
	lea (48,%a0),%a0
	lea (64,%a1),%a1
.L5:
	mvz.b (%a0),%d1
	mov3q.l #1,%d0
	addq.l #1,%a0
	moveq #31,%d4
	lsl.l %d1,%d0
	cmp.l %d1,%d4
	jcs .L4
	and.l #286208305,%d0
	tst.l %d0
	jeq .L4
	cmp.l %a0,%a1
	jne .L5
	move.l %d3,%a0
	add.l #80,%d3
	lea (72,%a0),%a0
.L6:
	mvz.b (%a0),%d0
	addq.l #1,%a0
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jcs .L4
	cmp.l %a0,%d3
	jne .L6
	movem.l (%sp),#28
	move.l dl_probe_selection_result,%d0
	lea (20,%sp),%a0
	move.l (%a0),current
	lea (12,%sp),%sp
	rts
.L4:
	movem.l (%sp),#28
	moveq #-3,%d0
	lea (12,%sp),%sp
	rts
	.size	dl_selection_prepare, .-dl_selection_prepare
	.align	2
	.globl	dl_selection_poll
	.type	dl_selection_poll, @function
dl_selection_poll:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jne .L16
	move.l dl_probe_selection_result,%d0
	rts
.L16:
	moveq #-3,%d0
	rts
	.size	dl_selection_poll, .-dl_selection_poll
	.align	2
	.globl	dl_selection_cancel
	.type	dl_selection_cancel, @function
dl_selection_cancel:
	move.l 4(%sp),%d0
	cmp.l current.l,%d0
	jeq .L23
	rts
.L23:
	clr.l current
	rts
	.size	dl_selection_cancel, .-dl_selection_cancel
	.align	2
	.globl	dl_selection_commit
	.type	dl_selection_commit, @function
dl_selection_commit:
	move.l current,%d0
	cmp.l 4(%sp),%d0
	jeq .L28
	rts
.L28:
	clr.l current
	rts
	.size	dl_selection_commit, .-dl_selection_commit
	.align	2
	.globl	dl_residency_tick
	.type	dl_residency_tick, @function
dl_residency_tick:
	rts
	.size	dl_residency_tick, .-dl_residency_tick
	.data
	.align	2
	.type	current, @object
	.size	current, 4
current:
	.zero	4
	.globl	dl_probe_selection_result
	.align	2
	.type	dl_probe_selection_result, @object
	.size	dl_probe_selection_result, 4
dl_probe_selection_result:
	.long	1
