| Generated by generate.py from transfer.c.
#NO_APP
	.file	"transfer.c"
	.text
	.align	2
	.type	packet, @function
packet:
	lea (-76,%sp),%sp
	movem.l #31996,(%sp)
	move.l 80(%sp),%d3
	move.l %d3,%d4
	lsl.l #7,%d4
	move.l 84(%sp),%d6
	add.l #dl_tx,%d4
	move.l %d4,%a0
	add.l #134217728,%a0
	move.l %d4,%d0
	move.l %a0,%a1
	add.l #134217856,%d0
	move.l %a0,54(%sp)
.L2:
	clr.w (%a1)+
	cmp.l %d0,%a1
	jne .L2
	lea sequence,%a1
	move.w (%a1,%d3.l*2),%d1
	addq.l #1,%d1
	move.w %d1,%a2
	tst.w %d1
	jeq .L16
	move.w %d1,%d5
	move.w #19524,(%a0)
	move.w %a2,2(%a0)
	move.w %d6,4(%a0)
	move.w %d3,6(%a0)
	mvz.w %d1,%d2
	move.l %d3,%d1
	add.l #1193046,%d1
	add.l #134217744,%d4
	add.l %d2,%d1
	move.w %d5,(%a1,%d3.l*2)
	moveq #24,%d5
	move.l %d1,%a3
	move.l %d4,%d2
	add.l #127730520,%a3
	move.w %d5,8(%a0)
.L4:
	move.l %d1,%d7
	lsr.l #8,%d7
	move.l %d2,%a1
	move.l %d1,%d5
	mvz.b %d5,%d5
	addq.l #4,%d2
	move.w %d7,(%a1)+
	add.l #5322105,%d1
	move.w %d5,(%a1)
	cmp.l %a3,%d1
	jne .L4
	moveq #30,%d1
	muls.l %d3,%d1
	move.l %d1,%a1
	add.l #jobs,%a1
	move.l %d1,50(%sp)
	move.w 28(%a1),%d1
	mvz.w %d1,%d1
	subq.l #2,%d1
	tst.l %d1
	jeq .L27
.L6:
	sub.l %a1,%a1
.L15:
	move.w (%a0)+,%d1
	add.l %a1,%d1
	move.w %d1,%a1
	cmp.l %d0,%a0
	jne .L15
	clr.w %d0
	move.l 54(%sp),%a0
	neg.l %d1
	move.w %d1,12(%a0)
	lea pending,%a0
	move.w %a2,(%a0,%d3.l*2)
	lea age,%a0
	move.w %d0,(%a0,%d3.l*2)
	movem.l (%sp),#31996
	lea (76,%sp),%sp
	rts
.L16:
	moveq #1,%d5
	move.w #1,%a2
	move.w #19524,(%a0)
	mov3q.l #1,%d2
	move.l %d3,%d1
	add.l #1193046,%d1
	add.l %d2,%d1
	add.l #134217744,%d4
	move.l %d1,%a3
	move.l %d4,%d2
	add.l #127730520,%a3
	move.w %d5,(%a1,%d3.l*2)
	moveq #24,%d5
	move.w %a2,2(%a0)
	move.w %d6,4(%a0)
	move.w %d3,6(%a0)
	move.w %d5,8(%a0)
	jra .L4
.L27:
	mov3q.l #3,%d5
	cmp.l %d6,%d5
	jeq .L28
	subq.l #4,%d6
	mov3q.l #3,%d1
	cmp.l %d6,%d1
	jcs .L6
	move.w 22(%a1),%d4
	move.w 24(%a1),%d2
	move.w 26(%a1),%d1
	sub.l %a1,%a1
	move.w %d4,8(%a0)
	move.w %d2,10(%a0)
	move.w %d1,14(%a0)
	jra .L15
.L28:
	move.w 18(%a1),%d1
	mvz.w 8(%a1),%d2
	move.l %d2,%d6
	mvz.w %d1,%d5
	sub.l %d5,%d6
	move.l %d6,58(%sp)
	moveq #24,%d6
	cmp.l 58(%sp),%d6
	jcc .L8
	move.l %d6,58(%sp)
.L8:
	move.l 50(%sp),%a1
	add.l #jobs,%a1
	clr.l 14(%a1)
	move.w 12(%a1),%a4
	move.w 60(%sp),8(%a0)
	add.l %a4,%d1
	move.w %d1,10(%a0)
	cmp.l %d2,%d5
	jeq .L6
	move.w 10(%a1),%d7
	mvz.w %a4,%d1
	move.l %d5,%d2
	addq.l #4,%a1
	lsl.l #2,%d2
	move.l 50(%sp),%a3
	clr.l %d6
	move.l %d1,%a4
	move.l %a1,46(%sp)
	move.w %a2,66(%sp)
	lea jobs,%a1
	move.l 46(%sp),%a2
	mvz.w %d7,%d1
	move.l (%a1,%a3.l),%a6
	lea dl_pool_base,%a5
	add.l %d2,%a6
	add.l %d1,%d1
	move.l %d0,68(%sp)
	sub.l %a3,%a3
	move.l %a0,72(%sp)
	move.l %d1,62(%sp)
.L14:
	move.l (%a6)+,%d2
	tst.w %d7
	jeq .L10
	move.l (%a2),%a0
	move.l 62(%sp),%a1
	add.l %a0,%a1
.L13:
	move.w (%a0)+,%d0
	move.l %d0,%d1
	and.l #32767,%d1
	cmp.l %d1,%d5
	jeq .L29
	cmp.l %a1,%a0
	jne .L13
.L10:
	move.l %d2,%d0
	move.l %d4,%a0
	and.l #16777215,%d0
	mvz.b %d2,%d2
	addq.l #1,%a3
	addq.l #4,%d4
	addq.l #1,%d5
	move.l %d0,%d1
	lsr.l #8,%d1
	add.l %d0,%d6
	and.l #16777215,%d6
	move.w %d1,(%a0)+
	move.w %d2,(%a0)
	cmp.l 58(%sp),%a3
	jcs .L14
	move.l 50(%sp),%a3
	lea jobs,%a1
	move.w 66(%sp),%a2
	move.l %d6,14(%a1,%a3.l)
	move.l 68(%sp),%d0
	sub.l %a1,%a1
	move.l 72(%sp),%a0
	jra .L15
.L29:
	move.l (%a5,%d3.l*4),%d1
	add.l %a4,%d1
	tst.w %d0
	jlt .L30
	add.l %d1,%d2
	cmp.l %a1,%a0
	jne .L13
	jra .L10
.L30:
	sub.l %d1,%d2
	cmp.l %a1,%a0
	jne .L13
	jra .L10
	.size	packet, .-packet
	.align	2
	.globl	dl_upload_start
	.type	dl_upload_start, @function
dl_upload_start:
	lea (-36,%sp),%sp
	mov3q.l #1,%d1
	move.l 40(%sp),%d0
	movem.l #7420,(%sp)
	cmp.l %d0,%d1
	jcs .L50
	moveq #30,%d1
	muls.l %d0,%d1
	lea jobs,%a0
	lea 28(%a0,%d1.l),%a1
	move.w (%a1),%d2
	jne .L50
	lea dl_pool_base,%a1
	move.l (%a1,%d0.l*4),%a1
	tst.l %a1
	jeq .L50
	tst.l 44(%sp)
	jeq .L50
	move.l 44(%sp),%a1
	move.l (%a1),%d5
	tst.l %d5
	jeq .L50
	move.w 8(%a1),%d6
	jeq .L50
	move.w 12(%a1),%d7
	moveq #63,%d2
	mvz.w %d7,%d3
	cmp.l %d3,%d2
	jcc .L50
	mvz.w %d6,%d2
	lea dl_pool_words,%a1
	move.l (%a1,%d0.l*4),%d0
	add.l %d2,%d3
	cmp.l %d3,%d0
	jcs .L50
	move.l 44(%sp),%a1
	move.w 10(%a1),%a2
	move.w %a2,%d0
	jeq .L33
	tst.l 4(%a1)
	jeq .L50
.L33:
	move.l %d5,%a1
	clr.l %d0
.L34:
	addq.l #1,%d0
	move.l #16777215,%d3
	cmp.l (%a1)+,%d3
	jcs .L50
	cmp.l %d0,%d2
	jne .L34
	mvz.w %a2,%d0
	move.l 44(%sp),%a1
	move.l %d0,%a3
	move.w %a2,%d0
	move.l 4(%a1),%a4
	tst.w %d0
	jeq .L35
	move.l %a4,%a1
	move.w (%a1)+,%d0
	and.l #32767,%d0
	cmp.l %d2,%d0
	jcc .L50
	clr.l %d3
.L36:
	addq.l #1,%d3
	cmp.l %d3,%a3
	jeq .L35
	move.w (%a1),%d0
	addq.l #2,%a1
	and.l #32767,%d0
	cmp.l %d2,%d0
	jcc .L50
	move.w -4(%a1),%d4
	and.l #32767,%d4
	cmp.l %d0,%d4
	jcs .L36
.L50:
	movem.l (%sp),#7420
	clr.l %d0
	lea (36,%sp),%sp
	rts
.L35:
	lea (%a0,%d1.l),%a1
	move.w %d6,8(%a1)
	move.w %a2,10(%a1)
	move.w %d7,12(%a1)
	move.l %a4,4(%a1)
	move.l %d5,(%a0,%d1.l)
	mov3q.l #3,18(%a0,%d1.l)
	movem.l (%sp),#7420
	lea (28,%a1),%a1
	mov3q.l #1,%d0
	move.w #1,(%a1)
	lea (36,%sp),%sp
	rts
	.size	dl_upload_start, .-dl_upload_start
	.align	2
	.globl	dl_command_start
	.type	dl_command_start, @function
dl_command_start:
	move.l %d2,-(%sp)
	move.l 8(%sp),%d0
	mov3q.l #1,%d1
	cmp.l %d0,%d1
	jcs .L75
	moveq #30,%d1
	muls.l %d0,%d1
	lea jobs,%a0
	lea 28(%a0,%d1.l),%a1
	move.w (%a1),%d2
	jne .L75
	moveq #31,%d2
	cmp.l 16(%sp),%d2
	jcs .L75
	mov3q.l #1,%d2
	cmp.l 12(%sp),%d2
	jeq .L63
	mov3q.l #4,%d2
	cmp.l 12(%sp),%d2
	jeq .L64
	move.l 12(%sp),%d0
	mov3q.l #1,%d2
	subq.l #5,%d0
	cmp.l %d0,%d2
	jcc .L63
	mov3q.l #7,%d0
	cmp.l 12(%sp),%d0
	jne .L75
	cmp.l 16(%sp),%d0
	jcs .L75
	move.l 20(%sp),%d2
	cmp.l #65535,%d2
	jhi .L75
	move.l 24(%sp),%d0
	cmp.l #255,%d0
	jhi .L75
.L63:
	add.l %d1,%a0
	move.w 14(%sp),20(%a0)
	move.w 18(%sp),22(%a0)
	move.w 22(%sp),24(%a0)
	move.w 26(%sp),26(%a0)
	lea (28,%a0),%a0
	mov3q.l #1,%d0
	move.w #1,(%a0)
.L61:
	move.l (%sp)+,%d2
	rts
.L64:
	moveq #63,%d2
	cmp.l 20(%sp),%d2
	jcs .L81
.L75:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
.L81:
	cmp.l 24(%sp),%d2
	jcc .L75
	lea dl_pool_words,%a1
	move.l (%a1,%d0.l*4),%d2
	cmp.l 20(%sp),%d2
	jls .L75
	move.l (%a1,%d0.l*4),%d0
	cmp.l 24(%sp),%d0
	jls .L75
	add.l %d1,%a0
	move.w 14(%sp),20(%a0)
	move.w 18(%sp),22(%a0)
	move.w 22(%sp),24(%a0)
	move.w 26(%sp),26(%a0)
	lea (28,%a0),%a0
	mov3q.l #1,%d0
	move.w #1,(%a0)
	jra .L61
	.size	dl_command_start, .-dl_command_start
	.align	2
	.globl	dl_job_status
	.type	dl_job_status, @function
dl_job_status:
	move.l 4(%sp),%d0
	mov3q.l #1,%d1
	cmp.l %d0,%d1
	jcs .L85
	moveq #30,%d1
	muls.l %d1,%d0
	move.l %d0,%a0
	add.l #jobs+28,%a0
	move.w (%a0),%d0
	mvz.w %d0,%d0
	mov3q.l #3,%d1
	cmp.l %d0,%d1
	jeq .L86
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jeq .L85
	tst.l %d0
	jeq .L87
	clr.l %d0
	rts
.L86:
	mov3q.l #1,%d0
	rts
.L85:
	mov3q.l #-1,%d0
	rts
.L87:
	moveq #-2,%d0
	rts
	.size	dl_job_status, .-dl_job_status
	.align	2
	.globl	dl_job_release
	.type	dl_job_release, @function
dl_job_release:
	move.l 4(%sp),%d0
	mov3q.l #1,%d1
	cmp.l %d0,%d1
	jcc .L97
.L93:
	rts
.L97:
	moveq #30,%d1
	muls.l %d1,%d0
	mov3q.l #2,%d1
	move.l %d0,%a0
	add.l #jobs+28,%a0
	move.w (%a0),%d0
	mvz.w %d0,%d0
	cmp.l %d0,%d1
	jcc .L93
	clr.w (%a0)
	rts
	.size	dl_job_release, .-dl_job_release
	.align	2
	.globl	dl_frame
	.type	dl_frame, @function
dl_frame:
	lea (-44,%sp),%sp
	clr.l %d0
	movem.l #31868,(%sp)
	move.l dl_frames,%d1
	addq.l #1,%d1
	lea pending,%a6
	move.l %a6,%a3
	move.l %d1,dl_frames
	lea dl_tx+134217728,%a2
	lea age,%a0
	lea dl_rx+134217728,%a1
	lea jobs+8,%a4
.L118:
	move.w (%a3)+,%d1
	jeq .L100
	move.w (%a1),%d2
	mvz.w %d2,%d2
	cmp.l #16715,%d2
	jeq .L151
.L101:
	move.w (%a0),%d1
	moveq #63,%d3
	addq.l #1,%d1
	mvz.w %d1,%d2
	move.w %d1,(%a0)
	cmp.l %d2,%d3
	jcs .L152
.L100:
	lea (128,%a2),%a2
	addq.l #2,%a0
	lea (64,%a1),%a1
	lea (30,%a4),%a4
	tst.l %d0
	jne .L153
	mov3q.l #1,%d0
	jra .L118
.L153:
	tst.w pending.l
	jne .L119
	move.w jobs+28,%d0
	mvz.w %d0,%d0
	subq.l #1,%d0
	tst.l %d0
	jeq .L154
.L119:
	tst.w pending+2.l
	jne .L120
	move.w jobs+58,%d0
	mvz.w %d0,%d0
	subq.l #1,%d0
	tst.l %d0
	jeq .L155
.L120:
	move.l dl_request_probe,%d1
	move.l (%a6),%d0
	move.l stages,%d2
	cmp.l requests.l,%d1
	jeq .L121
	tst.l %d0
	jne .L122
	move.w jobs+28,%d1
	jne .L123
	move.w jobs+58,%d1
	jne .L123
	move.l dl_request_probe,%d0
	mov3q.l #1,-(%sp)
	clr.l -(%sp)
	move.l %d0,requests
	lea packet,%a2
	jsr (%a2)
	mov3q.l #1,-(%sp)
	mov3q.l #1,-(%sp)
	jsr (%a2)
	lea (16,%sp),%sp
.L121:
	move.l dl_request_stage,%d1
	move.l (%a6),%d0
	cmp.l %d1,%d2
	jeq .L124
	tst.l %d0
	jne .L124
	move.w jobs+28,%d0
	jne .L126
.L125:
	move.w jobs+58,%d0
	jne .L126
	move.l dl_request_stage,%d0
	mov3q.l #2,-(%sp)
	clr.l -(%sp)
	move.l %d0,stages
	lea packet,%a2
	jsr (%a2)
	mov3q.l #2,-(%sp)
	mov3q.l #1,-(%sp)
	jsr (%a2)
	lea (16,%sp),%sp
	move.l (%a6),%d0
.L124:
	tst.l %d0
	sne %d0
	movem.l (%sp),#31868
	mvs.b %d0,%d0
	neg.l %d0
	lea (44,%sp),%sp
	rts
.L152:
	clr.w %d4
	move.l dl_errors,%d1
	addq.l #1,%d1
	move.l %d1,dl_errors
	moveq #30,%d5
	muls.l %d0,%d5
	move.w %d4,-2(%a3)
	clr.w (%a2)
	move.l %d5,%a5
	add.l #jobs+28,%a5
	move.w (%a5),%d1
	mvz.w %d1,%d1
	subq.l #2,%d1
	tst.l %d1
	jeq .L156
	mov3q.l #1,dl_modal_pending
	jra .L100
.L151:
	move.w 2(%a1),%d2
	mvz.w %d1,%d1
	mvz.w %d2,%d2
	cmp.l %d1,%d2
	jne .L101
	move.w 4(%a1),%d1
	jne .L102
	move.w 6(%a1),%d1
	mvz.w %d1,%d1
	cmp.l %d1,%d0
	jeq .L157
.L102:
	moveq #30,%d1
	muls.l %d0,%d1
	move.l #jobs,%d2
	move.l %d2,%a5
	lea 28(%a5,%d1.l),%a5
	move.w (%a5),%d3
	move.l #dl_rejected,%d3
	move.l %d3,%a5
	move.l (%a5,%d0.l*4),%d4
	move.l %d2,%a5
	lea 28(%a5,%d1.l),%a5
	move.l %d4,%d1
	addq.l #1,%d1
	move.l %a5,%d2
	move.l %d3,%a5
	move.l %d1,(%a5,%d0.l*4)
	move.l dl_errors,%d1
	addq.l #1,%d1
	move.l %d1,dl_errors
	mov3q.l #1,dl_modal_pending
	move.l %d2,%a5
	move.w (%a5),%d1
	mvz.w %d1,%d1
	subq.l #2,%d1
	tst.l %d1
	jeq .L158
.L109:
	clr.w %d1
	move.w %d1,-2(%a3)
	clr.w (%a2)
	jra .L100
.L122:
	tst.l %d0
	sne %d0
	movem.l (%sp),#31868
	move.l dl_request_stage,%d1
	mvs.b %d0,%d0
	neg.l %d0
	lea (44,%sp),%sp
	rts
.L123:
	move.l dl_request_stage,%d1
	cmp.l %d1,%d2
	jeq .L124
	move.w jobs+28,%d0
	jeq .L125
.L126:
	move.l (%a6),%d0
	movem.l (%sp),#31868
	tst.l %d0
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	lea (44,%sp),%sp
	rts
.L156:
	move.w #4,(%a5)
	mov3q.l #1,dl_modal_pending
	jra .L100
.L154:
	moveq #2,%d2
	mvz.w jobs+20,%d0
	move.l %d0,-(%sp)
	clr.l -(%sp)
	move.w %d2,jobs+28
	jsr packet
	addq.l #8,%sp
	jra .L119
.L155:
	moveq #2,%d4
	mvz.w jobs+50,%d0
	move.l %d0,-(%sp)
	mov3q.l #1,-(%sp)
	move.w %d4,jobs+58
	jsr packet
	addq.l #8,%sp
	jra .L120
.L158:
	clr.w %d1
	move.w #4,(%a5)
	move.w %d1,-2(%a3)
	clr.w (%a2)
	jra .L100
.L157:
	moveq #30,%d1
	muls.l %d0,%d1
	move.l #jobs,%d2
	move.l %d2,%a5
	lea 28(%a5,%d1.l),%a5
	move.w (%a5),%d3
	mvz.w %d3,%d3
	subq.l #2,%d3
	tst.l %d3
	jeq .L159
.L103:
	move.l #dl_accepted,%d3
	move.l %d3,%a5
	move.l (%a5,%d0.l*4),%d4
	addq.l #1,%d4
	move.l %d4,(%a5,%d0.l*4)
	move.w 12(%a1),%d3
	jeq .L106
	move.w 14(%a1),%d3
	moveq #64,%d4
	mvz.w %d3,%d3
	cmp.l %d3,%d4
	jcc .L106
	move.w 12(%a1),%d3
	move.w 14(%a1),%d4
	mvz.w %d3,%d3
	mvz.w %d4,%d4
	add.l %d4,%d3
	cmp.l #8192,%d3
	jgt .L106
	move.w 14(%a1),%d3
	move.l %d2,%a5
	move.l #dl_pool_words,%d4
	lea 28(%a5,%d1.l),%a5
	mvz.w %d3,%d3
	move.l %a5,40(%sp)
	move.l %d4,%a5
	move.l #dl_pool_base,%d4
	move.l %d3,(%a5,%d0.l*4)
	move.l %d4,%a5
	move.w 12(%a1),%d3
	mvz.w %d3,%d3
	move.l %d3,(%a5,%d0.l*4)
	move.l 40(%sp),%a5
	move.w (%a5),%d3
	mvz.w %d3,%d3
	subq.l #2,%d3
	tst.l %d3
	jne .L109
.L108:
	move.w 12(%a4),%d3
	mvz.w %d3,%d4
	subq.l #3,%d4
	tst.l %d4
	jeq .L160
	move.l %d2,%a5
	lea 28(%a5,%d1.l),%a5
	clr.w %d1
	move.w #3,(%a5)
	move.w %d1,-2(%a3)
	clr.w (%a2)
	jra .L100
.L159:
	mvz.w 12(%a4),%d3
	subq.l #3,%d3
	tst.l %d3
	jne .L103
	move.w 10(%a1),%d3
	move.w 8(%a1),%d4
	swap %d3
	clr.w %d3
	mvz.w %d4,%d4
	or.l %d4,%d3
	cmp.l 6(%a4),%d3
	jeq .L103
	move.l #dl_rejected,%d3
	move.l %d3,%a5
	move.l (%a5,%d0.l*4),%d4
	move.l %d2,%a5
	lea 28(%a5,%d1.l),%a5
	move.l %d4,%d1
	addq.l #1,%d1
	move.l %a5,%d2
	move.l %d3,%a5
	move.l %d1,(%a5,%d0.l*4)
	move.l dl_errors,%d1
	addq.l #1,%d1
	move.l %d1,dl_errors
	mov3q.l #1,dl_modal_pending
	move.l %d2,%a5
	move.w (%a5),%d1
	mvz.w %d1,%d1
	subq.l #2,%d1
	tst.l %d1
	jne .L109
	jra .L158
.L106:
	move.l %d2,%a5
	lea 28(%a5,%d1.l),%a5
	move.w (%a5),%d3
	mvz.w %d3,%d3
	subq.l #2,%d3
	tst.l %d3
	jeq .L108
	clr.w %d1
	move.w %d1,-2(%a3)
	clr.w (%a2)
	jra .L100
.L160:
	move.w 10(%a4),%a5
	mvz.w (%a4),%d5
	move.l %d5,%d4
	mvz.w %a5,%d6
	sub.l %d6,%d4
	moveq #24,%d6
	cmp.l %d4,%d6
	jcc .L114
	moveq #24,%d4
.L114:
	add.l %a5,%d4
	mvz.w %d4,%d6
	move.w %d4,10(%a4)
	cmp.l %d5,%d6
	jeq .L115
	moveq #1,%d3
.L115:
	move.l %d2,%a5
	lea 28(%a5,%d1.l),%a5
	clr.w %d1
	move.w %d3,(%a5)
	move.w %d1,-2(%a3)
	clr.w (%a2)
	jra .L100
	.size	dl_frame, .-dl_frame
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"DSP LOAD FAILED"
.LC1:
	.string	"DSP MEMORY FULL"
.LC2:
	.string	"DSP OVERLOAD"
	.text
	.align	2
	.globl	dl_ui
	.type	dl_ui, @function
dl_ui:
	move.l %d2,-(%sp)
	jsr dl_selection_tick
	jsr dl_residency_tick
	move.l dl_modal_pending,%d0
	tst.l %d0
	jeq .L161
	move.l dl_modal_pending,%d1
	clr.l dl_modal_pending
	move.l dl_modal_shown,%d0
	addq.l #1,%d0
	move.l %d0,dl_modal_shown
	mov3q.l #2,%d0
	cmp.l %d1,%d0
	jeq .L164
	move.l #.LC0,%d0
	subq.l #3,%d1
	tst.l %d1
	jeq .L171
	pea 48.w
	move.l %d0,-(%sp)
	jsr 1074111160
	addq.l #8,%sp
.L161:
	move.l (%sp)+,%d2
	rts
.L164:
	pea 48.w
	move.l #.LC1,%d0
	move.l %d0,-(%sp)
	jsr 1074111160
	addq.l #8,%sp
	jra .L161
.L171:
	pea 48.w
	move.l #.LC2,%d0
	move.l %d0,-(%sp)
	jsr 1074111160
	addq.l #8,%sp
	jra .L161
	.size	dl_ui, .-dl_ui
	.data
	.align	2
	.type	jobs, @object
	.size	jobs, 60
jobs:
	.zero	60
	.globl	dl_pool_words
	.align	2
	.type	dl_pool_words, @object
	.size	dl_pool_words, 8
dl_pool_words:
	.zero	8
	.globl	dl_pool_base
	.align	2
	.type	dl_pool_base, @object
	.size	dl_pool_base, 8
dl_pool_base:
	.zero	8
	.align	2
	.type	stages, @object
	.size	stages, 4
stages:
	.zero	4
	.align	2
	.type	requests, @object
	.size	requests, 4
requests:
	.zero	4
	.align	2
	.type	age, @object
	.size	age, 4
age:
	.zero	4
	.align	2
	.type	pending, @object
	.size	pending, 4
pending:
	.zero	4
	.align	2
	.type	sequence, @object
	.size	sequence, 4
sequence:
	.zero	4
	.globl	dl_modal_shown
	.align	2
	.type	dl_modal_shown, @object
	.size	dl_modal_shown, 4
dl_modal_shown:
	.zero	4
	.globl	dl_modal_pending
	.align	2
	.type	dl_modal_pending, @object
	.size	dl_modal_pending, 4
dl_modal_pending:
	.zero	4
	.globl	dl_request_stage
	.align	2
	.type	dl_request_stage, @object
	.size	dl_request_stage, 4
dl_request_stage:
	.zero	4
	.globl	dl_request_probe
	.align	2
	.type	dl_request_probe, @object
	.size	dl_request_probe, 4
dl_request_probe:
	.zero	4
	.globl	dl_errors
	.align	2
	.type	dl_errors, @object
	.size	dl_errors, 4
dl_errors:
	.zero	4
	.globl	dl_rejected
	.align	2
	.type	dl_rejected, @object
	.size	dl_rejected, 8
dl_rejected:
	.zero	8
	.globl	dl_accepted
	.align	2
	.type	dl_accepted, @object
	.size	dl_accepted, 8
dl_accepted:
	.zero	8
	.globl	dl_frames
	.align	2
	.type	dl_frames, @object
	.size	dl_frames, 4
dl_frames:
	.zero	4
	.globl	dl_rx
	.align	2
	.type	dl_rx, @object
	.size	dl_rx, 128
dl_rx:
	.zero	128
	.globl	dl_tx
	.align	2
	.type	dl_tx, @object
	.size	dl_tx, 256
dl_tx:
	.zero	256
	.section	.note.GNU-stack,"",@progbits
