#!/usr/bin/env python3
"""Offline fixed-point designs from the measured FX-pedal tape voice.

No proprietary plugin code/data. RBJ biquads at 44.1 kHz, stored as three
signed Q1.31 EMAC operands per section; controls Q4.28 (feedback Q2.30);
the record curve is a signed table of finished ring words. Runtime uses no
floating point or libm.
"""
import math
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent

def biquad(kind, f, q, db=0):
    w = 2*math.pi*f/44100
    c, a = math.cos(w), math.sin(w)/(2*q)
    if kind == 'lp': b0,b1,b2,a0,a1,a2 = (1-c)/2,1-c,(1-c)/2,1+a,-2*c,1-a
    elif kind == 'hp': b0,b1,b2,a0,a1,a2 = (1+c)/2,-1-c,(1+c)/2,1+a,-2*c,1-a
    else:
        A = 10**(db/40)
        b0,b1,b2,a0,a1,a2 = 1+a*A,-2*c,1-a*A,1+a/A,-2*c,1-a/A
    values = [b0/a0,b1/a0,b2/a0,-a1/a0,-a2/a0]
    assert sum(map(abs,values)) < 8 and max(map(abs,values)) < 2
    return values

Q31 = 1 << 31

def section(values, gain=1.0):
    """One EMAC section: y = g*(x +/- 2*x1 + x2) + y1 + (a1-1)*y1 + a2*y2.

    Low- and high-pass RBJ numerators are exactly b0*(1, +/-2, 1), so one
    numerator operand serves all three input taps (MAC or MSAC). The unit
    y1 term is an exact accumulator load; a1-1 and a2 fit Q1.31. `gain`
    folds a constant output gain into the numerator (the wet makeup)."""
    b0, b1, b2, a1, a2 = values
    assert abs(b2 - b0) < 1e-12 and abs(abs(b1) - 2*b0) < 1e-12
    row = [round(b0*gain*Q31), round((a1 - 1)*Q31), round(a2*Q31)]
    assert all(-Q31 <= v < Q31 for v in row), row
    return row

def generate():
    out = ['/* Generated by generate_tables.py; do not hand edit. */']
    def array(name, values, width=None):
        out.append('static const int32_t '+name+(f'[][{width}]' if width else '[]')+' = {')
        if width:
            out.extend('    {'+', '.join(map(str,row))+'},' for row in values)
        else:
            out.extend('    '+', '.join(map(str,values[i:i+8]))+',' for i in range(0,len(values),8))
        out.append('};')
    # Economy model: one record LP instead of a sixth-order top and
    # emphasis, plus the playback low cut. The opposed emphasis EQs and
    # subtle low-mid lift are omitted. Speed and age filters stay separate.
    rec = [10**((5.44+(35*i/127-14 if i/127 < .4 else 14*(i/127-.4)))/20) for i in range(128)]
    makeup = [round((x/10**(5.44/20))**.4/x*(1<<28)) for x in rec]
    # DRIVE is fixed at 0: the wet makeup gain is a constant folded into
    # the tone section's numerator, so the loop carries makeup*wet.
    wet_gain = makeup[0]/(1<<28)
    array('te_hp', section(biquad('hp',106,.53)))
    # Collapse the two playback low-passes into one biquad. Fit the old
    # cascade's digital magnitudes at 4/8.4 kHz analytically (no optimizer or
    # runtime design). The remaining high-frequency difference is measured
    # explicitly by the voice gate; the bass cut and record curve stay put.
    def folded(speed, age):
        f1=1516*speed
        f2=min(8000/max(age,.001)**.46,.45*44100)
        def inverse_power(f, corner, q):
            u=math.tan(math.pi*f/44100)/math.tan(math.pi*corner/44100)
            return (1-u*u)**2+u*u/(q*q)
        v=[math.tan(math.pi*f/44100)**2 for f in (4000,8400)]
        d=[inverse_power(f,f1,.7)*inverse_power(f,f2,.5)*inverse_power(f,11500,.707)
           *(1-.5*math.sin(math.pi*f/44100)**2)**2-1 for f in (4000,8400)]
        b=(d[1]/v[1]-d[0]/v[0])/(v[1]-v[0])
        x=math.sqrt(b)
        a=d[0]/v[0]-b*v[0]
        # A sixth-order far-stopband cannot always be represented by a
        # non-resonant second-order section. Bound Q to Butterworth rather
        # than introducing a resonant peak or an unstable fit there.
        q=1/math.sqrt(max(2,2+a/x))
        return biquad('lp',44100/math.pi*math.atan(1/math.sqrt(x)),q)
    array('te_tone', [section(folded(1+i/8,age/127),wet_gain)
                      for age in range(128) for i in range(57)],3)
    # The loop carries makeup*wet, so feedback is divided by the same
    # makeup. Q2.30 (the largest, 2.3/makeup, is below 2); applied twice.
    array('te_feedback', [round(2.3*(i/127)**2.26/wet_gain*(1<<30)) for i in range(128)])
    array('te_record_gain', [round(x*(1<<28)) for x in rec])
    array('te_makeup', makeup)
    array('te_hiss', [round((1e-6+4e-6*(i/127)**2)*(1<<26)) for i in range(128)])
    # Signed record curve over +/-4 FS in 1/256 FS steps, entry 1024 at 0,
    # holding finished ring words (Q1.31 FS). Odd symmetry is tabulated,
    # so the runtime does no sign handling.
    def curve(x):
        return math.copysign(math.tanh(1.7*abs(x)/(1+.4*abs(x)))/1.7, x)
    array('te_tape_curve', [round(curve((k-1024)/256)*Q31) for k in range(2049)])
    array('te_sine', [round(math.sin(2*math.pi*i/1024)*(1<<30)) for i in range(1025)])
    return '\n'.join(out)+'\n'

if __name__ == '__main__':
    dst = HERE/'cpu_tables.h'
    source = generate()
    if '--check' in sys.argv:
        if not dst.exists() or dst.read_text() != source:
            sys.exit('Tape Echo tables are stale: run modules/tapeecho/generate_tables.py')
        print('Tape Echo coefficient/curve tables match their designs')
    else:
        dst.write_text(source)
