#!/usr/bin/env python3
"""Offline fixed-point designs from the measured FX-pedal tape voice.

No proprietary plugin code/data. RBJ biquads at 44.1 kHz, Q2.30; controls
Q4.28; curve Q6.26. Runtime uses no floating point or libm.
"""
import math
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent

def biquad(kind, f, q, db=0):
    w = 2*math.pi*f/44100
    c, a = math.cos(w), math.sin(w)/(2*q)
    if kind == 'lp': b0,b1,b2,a0,a1,a2 = (1-c)/2,1-c,(1-c)/2,1+a,-2*c,1-a
    elif kind == 'hp': b0,b1,b2,a0,a1,a2 = (1+c)/2,-1-c,(1+c)/2,1+a,-2*c,1-a
    else:
        A = 10**(db/40)
        b0,b1,b2,a0,a1,a2 = 1+a*A,-2*c,1-a*A,1+a/A,-2*c,1-a/A
    values = [b0/a0,b1/a0,b2/a0,-a1/a0,-a2/a0]
    # Four-FS bounded histories and sum(abs(coeff)) < 8 cannot overflow Q6.26.
    assert sum(map(abs,values)) < 8 and max(map(abs,values)) < 2
    return [round(x*(1<<30)) for x in values]

def generate():
    out = ['/* Generated by generate_tables.py; do not hand edit. */']
    def array(name, values, width=None):
        out.append('static const int32_t '+name+(f'[][{width}]' if width else '[]')+' = {')
        if width:
            out.extend('    {'+', '.join(map(str,row))+'},' for row in values)
        else:
            out.extend('    '+', '.join(map(str,values[i:i+8]))+',' for i in range(0,len(values),8))
        out.append('};')
    # Economy model: one record LP instead of a sixth-order top and
    # emphasis, plus the playback low cut. The opposed emphasis EQs and
    # subtle low-mid lift are omitted. Speed and age filters stay separate.
    array('te_fixed', [biquad('lp',11500,.707), biquad('hp',106,.53)],5)
    array('te_corner', [biquad('lp',1516*(1+i/32),.7) for i in range(225)],5)
    array('te_worn', [biquad('lp',min(8000/max(i/127,.001)**.46,.45*44100),.5)
                      for i in range(128)],5)
    # Collapse the two playback low-passes into one biquad. Fit the old
    # cascade's digital magnitudes at 4/8.4 kHz analytically (no optimizer or
    # runtime design). The remaining high-frequency difference is measured
    # explicitly by the voice gate; the bass cut and record curve stay put.
    def folded(speed, age):
        f1=1516*speed
        f2=min(8000/max(age,.001)**.46,.45*44100)
        def inverse_power(f, corner, q):
            u=math.tan(math.pi*f/44100)/math.tan(math.pi*corner/44100)
            return (1-u*u)**2+u*u/(q*q)
        v=[math.tan(math.pi*f/44100)**2 for f in (4000,8400)]
        d=[inverse_power(f,f1,.7)*inverse_power(f,f2,.5)*inverse_power(f,11500,.707)
           *(1-.5*math.sin(math.pi*f/44100)**2)**2-1 for f in (4000,8400)]
        b=(d[1]/v[1]-d[0]/v[0])/(v[1]-v[0])
        x=math.sqrt(b)
        a=d[0]/v[0]-b*v[0]
        # A sixth-order far-stopband cannot always be represented by a
        # non-resonant second-order section. Bound Q to Butterworth rather
        # than introducing a resonant peak or an unstable fit there.
        q=1/math.sqrt(max(2,2+a/x))
        return biquad('lp',44100/math.pi*math.atan(1/math.sqrt(x)),q)
    array('te_tone', [folded(1+i/8,age/127) for age in range(128) for i in range(57)],5)
    array('te_feedback', [round(2.3*(i/127)**2.26*(1<<28)) for i in range(128)])
    rec = [10**((5.44+(35*i/127-14 if i/127 < .4 else 14*(i/127-.4)))/20) for i in range(128)]
    array('te_record_gain', [round(x*(1<<28)) for x in rec])
    array('te_makeup', [round((x/10**(5.44/20))**.4/x*(1<<28)) for x in rec])
    array('te_hiss', [round((1e-6+4e-6*(i/127)**2)*(1<<26)) for i in range(128)])
    array('te_curve', [round(math.tanh(1.7*(i/256)/(1+.4*i/256))/1.7*(1<<26)) for i in range(2049)])
    array('te_sine', [round(math.sin(2*math.pi*i/1024)*(1<<30)) for i in range(1025)])
    return '\n'.join(out)+'\n'

if __name__ == '__main__':
    dst = HERE/'cpu_tables.h'
    source = generate()
    if '--check' in sys.argv:
        if not dst.exists() or dst.read_text() != source:
            sys.exit('Tape Echo tables are stale: run modules/tapeecho/generate_tables.py')
        print('Tape Echo coefficient/curve tables match their designs')
    else:
        dst.write_text(source)
