#!/usr/bin/env python3
"""Generate the freestanding ColdFire unit (same pattern as Euclid)."""
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FLAGS = ['-mcpu=54454', '-msoft-float', '-O3', '-ffreestanding', '-fno-builtin',
         '-fno-common', '-fno-jump-tables', '-fno-asynchronous-unwind-tables',
         '-fno-ident', '-fomit-frame-pointer']

def generate():
    subprocess.run([sys.executable, str(HERE/'generate_tables.py'), '--check'], check=True)
    with tempfile.TemporaryDirectory() as td:
        asm = pathlib.Path(td) / 'cpu.s'
        subprocess.run(['m68k-elf-gcc', *FLAGS, '-S', 'modules/tapeecho_half/cpu.c',
                        '-o', str(asm)], cwd=ROOT, check=True)
        source = ('| Generated by generate_cpu.py; edit cpu.c / cpu_hooks.s / cpu_kernels.s.\n'
                  + asm.read_text() + '\n' + (HERE / 'cpu_hooks.s').read_text()
                  + '\n' + (HERE / 'cpu_kernels.s').read_text())
        if '*8)' in source:
            raise RuntimeError('scaled-*8 ColdFire address mode is hardware-unsafe (Vec 03)')
        asm.write_text(source)
        binaries=[]
        for cpu in ('54454','5475'):
            obj=pathlib.Path(td)/f'{cpu}.o'
            binary=pathlib.Path(td)/f'{cpu}.bin'
            subprocess.run(['m68k-elf-as',f'-mcpu={cpu}',str(asm),'-o',str(obj)],check=True)
            subprocess.run(['m68k-elf-objcopy','-O','binary','-j','.text',str(obj),str(binary)],check=True)
            binaries.append(binary.read_bytes())
        if binaries[0]!=binaries[1]:
            raise RuntimeError('54454 machine code differs from platform ISA-B encoding')
        return source

if __name__ == '__main__':
    source = generate()
    dest = HERE / 'cpu.s'
    if '--check' in sys.argv:
        if not dest.exists() or source != dest.read_text():
            sys.exit('Tape Echo cpu.s is stale: run modules/tapeecho/generate_cpu.py')
        print('Tape Echo ColdFire source matches cpu.c, cpu_hooks.s and cpu_kernels.s')
    else:
        dest.write_text(source)
