| Generated by generate.py; edit control.c.
#NO_APP
	.file	"control.c"
	.text
	.align	2
	.type	signed_track, @function
signed_track:
	move.l %d2,-(%sp)
	move.l 12(%sp),%d0
	mov3q.l #7,%d1
	cmp.l %d0,%d1
	jcs .L4
	move.l 8(%sp),%a0
	mvz.b 34(%a0,%d0.l),%d1
	subq.l #1,%d1
	tst.l %d1
	jeq .L7
.L4:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
.L7:
	moveq #30,%d1
	moveq #65,%d2
	muls.l %d1,%d0
	lea 60(%a0,%d0.l),%a0
	mvz.b (%a0),%d0
	cmp.l %d0,%d2
	jne .L4
	mvz.b 1(%a0),%d0
	moveq #66,%d1
	cmp.l %d0,%d1
	jne .L4
	move.b 2(%a0),%d0
	mov3q.l #1,%d2
	eor.l %d2,%d0
	move.l (%sp)+,%d2
	tst.b %d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	rts
	.size	signed_track, .-signed_track
	.align	2
	.globl	ab_model_fmt
	.type	ab_model_fmt, @function
ab_model_fmt:
	move.l 4(%sp),%a0
	tst.l 8(%sp)
	jeq .L10
	moveq #57,%d0
	moveq #48,%d1
	move.b %d0,(%a0)
	move.b %d0,2(%a0)
	clr.b %d0
	move.b %d1,1(%a0)
	move.b %d0,3(%a0)
	rts
.L10:
	moveq #56,%d0
	moveq #48,%d1
	move.b %d0,(%a0)
	move.b %d0,2(%a0)
	clr.b %d0
	move.b %d1,1(%a0)
	move.b %d0,3(%a0)
	rts
	.size	ab_model_fmt, .-ab_model_fmt
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"SYN"
.LC1:
	.string	"ANALOG BD"
	.text
	.align	2
	.type	page_for, @function
page_for:
	lea (-84,%sp),%sp
	movem.l #31996,(%sp)
	tst.l ab_desc_p
	jne .L14
	move.l #ab_lpf_fmt,%d0
	lsr.l #8,%d0
	move.l #ab_lpf_fmt,%d7
	move.l #ab_lpf_fmt,%d1
	move.l #ab_model_fmt,%d2
	move.l %d0,72(%sp)
	moveq #24,%d0
	lsr.l %d0,%d7
	clr.w %d1
	swap %d1
	clr.w %d2
	swap %d2
	lea desc,%a0
	move.b %d7,83(%sp)
	move.l %a0,%d0
	neg.l %d0
	move.l %a0,52(%sp)
	lea (names.0),%a5
	lea desc+65,%a0
	move.l %a5,60(%sp)
	move.l %d0,64(%sp)
	move.l %d1,76(%sp)
	move.l %d2,68(%sp)
	move.l %a0,56(%sp)
	lea desc+458,%a2
.L31:
	move.l 52(%sp),%a0
	move.l 64(%sp),%a1
	add.l #1074606454,%a1
.L15:
	move.b (%a1,%a0.l),%d0
	move.b %d0,(%a0)+
	cmp.l %a0,%a2
	jne .L15
	move.l 52(%sp),%d2
	add.l #60,%d2
	clr.l %d0
	lea .LC0,%a0
	move.l %d2,%a1
.L16:
	move.b (%a0),%d1
	addq.l #1,%a0
	tst.b %d1
	jeq .L17
	move.b %d1,(%a1)+
	addq.l #1,%d0
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jne .L16
.L17:
	move.l %d0,%a0
	add.l %d2,%a0
	move.l 56(%sp),%d0
.L19:
	clr.b (%a0)+
	cmp.l %a0,%d0
	jne .L19
	move.l 56(%sp),%a3
	sub.l %a1,%a1
	lea .LC1,%a0
.L20:
	move.b (%a0),%d0
	addq.l #1,%a0
	tst.b %d0
	jeq .L21
	move.b %d0,(%a3)+
	addq.l #1,%a1
	moveq #12,%d2
	cmp.l %a1,%d2
	jne .L20
.L21:
	move.l 52(%sp),%d7
	move.l %d7,%d0
	add.l #78,%d0
	lea 65(%a1,%d7.l),%a0
.L23:
	clr.b (%a0)+
	move.l %d0,%a1
	cmp.l %a0,%d0
	jne .L23
	move.l 52(%sp),%a5
	sub.l %a3,%a3
	move.l 52(%sp),%a0
	move.l 60(%sp),%a4
	lea (150,%a5),%a5
	move.l 52(%sp),%d0
	add.l #84,%d0
	lea (162,%a0),%a0
	move.l %a5,48(%sp)
.L30:
	move.l (%a4)+,%a6
	sub.l %a5,%a5
.L24:
	move.b (%a6,%a5.l),%d1
	jeq .L25
	move.b %d1,(%a1,%a5.l)
	addq.l #1,%a5
	mov3q.l #5,%d1
	cmp.l %a5,%d1
	jne .L24
.L25:
	add.l %a1,%a5
.L27:
	clr.b (%a5)+
	cmp.l %a5,%d0
	jne .L27
	clr.b %d1
	lea ab_defaults,%a5
	mov3q.l #6,%d2
	lea (%a5,%a3.l),%a6
	move.l 48(%sp),%a5
	move.b (%a6),(%a5,%a3.l)
	clr.b (%a0)
	move.b %d1,1(%a0)
	move.b %d1,2(%a0)
	move.b %d1,3(%a0)
	cmp.l %a3,%d2
	jeq .L52
	clr.b %d2
	moveq #-128,%d7
	moveq #8,%d1
	move.b %d2,48(%a0)
	move.b %d2,49(%a0)
	move.b %d2,50(%a0)
	move.b %d7,51(%a0)
	cmp.l %a3,%d1
	jeq .L53
	clr.b %d7
	clr.b %d2
	sub.l %a5,%a5
	sub.l %a6,%a6
	clr.b %d6
	clr.b %d3
	clr.b %d4
	clr.b %d5
	addq.l #1,%a3
	addq.l #4,%a0
	move.b %d7,47(%sp)
	move.b %d2,143(%a0)
	clr.b %d2
	move.w %a6,%d7
	move.w %a5,%d1
	move.b %d6,95(%a0)
	move.b %d4,141(%a0)
	move.b %d5,140(%a0)
	move.b %d3,142(%a0)
	addq.l #6,%a1
	move.b 47(%sp),94(%a0)
	addq.l #6,%d0
	move.b %d2,188(%a0)
	move.b %d7,93(%a0)
	move.b %d1,92(%a0)
	move.b %d2,189(%a0)
	move.b %d2,190(%a0)
	move.b %d2,191(%a0)
	moveq #12,%d7
	cmp.l %a3,%d7
	jne .L30
.L54:
	moveq #1,%d0
	moveq #17,%d1
	move.b %d2,-8(%a2)
	move.b %d2,-7(%a2)
	mvz.w #458,%d2
	moveq #48,%d7
	add.l %d7,60(%sp)
	add.l %d2,52(%sp)
	add.l %d2,56(%sp)
	move.b %d0,-6(%a2)
	mvs.w #-458,%d0
	move.b %d1,-5(%a2)
	move.b %d1,-4(%a2)
	move.b %d1,-3(%a2)
	move.b %d1,-2(%a2)
	move.b %d1,-1(%a2)
	move.l 52(%sp),%d1
	add.l %d2,%a2
	add.l %d0,64(%sp)
	cmp.l #desc+916,%d1
	jne .L31
	move.l #desc+56,%d2
	move.l %d2,ab_desc_p
.L14:
	tst.l 88(%sp)
	sne %d0
	neg.l %d0
	tst.b %d0
	jeq .L32
	movem.l (%sp),#31996
	mvz.w #514,%d0
	add.l #desc,%d0
	lea (84,%sp),%sp
	rts
.L52:
	move.b %d1,-224(%a2)
	move.b %d1,-223(%a2)
	move.b %d1,-222(%a2)
	move.b 71(%sp),%d1
	moveq #2,%d7
	move.l #ab_model_fmt,%d2
	addq.l #1,%a3
	move.b %d2,%d6
	moveq #-44,%d2
	moveq #119,%d3
	moveq #4,%d4
	moveq #64,%d5
	addq.l #4,%a0
	addq.l #6,%a1
	move.w %d1,%a6
	move.l #ab_model_fmt,%d1
	addq.l #6,%d0
	lsr.l #8,%d1
	move.b %d7,-221(%a2)
	move.l #ab_model_fmt,%d7
	move.b %d2,143(%a0)
	move.b %d1,47(%sp)
	moveq #24,%d1
	lsr.l %d1,%d7
	clr.b %d2
	move.b %d6,95(%a0)
	move.b %d5,140(%a0)
	move.l %d7,%a5
	move.w %a6,%d7
	move.w %a5,%d1
	move.b %d4,141(%a0)
	move.b 47(%sp),94(%a0)
	move.b %d3,142(%a0)
	move.b %d2,188(%a0)
	move.b %d2,189(%a0)
	move.b %d2,190(%a0)
	move.b %d2,191(%a0)
	move.b %d7,93(%a0)
	move.b %d1,92(%a0)
	moveq #12,%d7
	cmp.l %a3,%d7
	jne .L30
	jra .L54
.L53:
	move.b 79(%sp),%d7
	move.b 83(%sp),%d1
	move.l #ab_lpf_fmt,%d2
	addq.l #1,%a3
	move.b %d2,%d6
	clr.b %d2
	move.b 75(%sp),47(%sp)
	clr.b %d3
	clr.b %d4
	clr.b %d5
	addq.l #4,%a0
	move.w %d7,%a6
	move.w %d1,%a5
	addq.l #6,%a1
	move.b %d6,95(%a0)
	move.b %d2,143(%a0)
	clr.b %d2
	move.b 47(%sp),94(%a0)
	move.b %d4,141(%a0)
	move.b %d5,140(%a0)
	move.b %d3,142(%a0)
	move.w %a6,%d7
	move.w %a5,%d1
	addq.l #6,%d0
	move.b %d2,188(%a0)
	move.b %d2,189(%a0)
	move.b %d2,190(%a0)
	move.b %d2,191(%a0)
	move.b %d7,93(%a0)
	move.b %d1,92(%a0)
	moveq #12,%d7
	cmp.l %a3,%d7
	jne .L30
	jra .L54
.L32:
	movem.l (%sp),#31996
	moveq #56,%d0
	add.l #desc,%d0
	lea (84,%sp),%sp
	rts
	.size	page_for, .-page_for
	.section	.rodata.str1.1
.LC2:
	.string	"ORIG"
	.text
	.align	2
	.globl	ab_lpf_fmt
	.type	ab_lpf_fmt, @function
ab_lpf_fmt:
	lea (-28,%sp),%sp
	move.l 36(%sp),%d0
	movem.l #17436,(%sp)
	move.l 32(%sp),%a2
	tst.l %d0
	jeq .L75
	moveq #64,%d3
	cmp.l %d0,%d3
	jeq .L76
	move.l %d0,-(%sp)
	jsr ab_lpf_frequency
	move.l %sp,%d2
	add.l #27,%d2
	addq.l #4,%sp
	sub.l %a1,%a1
	move.l %d2,%a0
.L64:
	move.l %d0,%d3
	moveq #10,%d4
	remu.l %d4,%d1:%d3
	divu.l %d4,%d3
	addq.l #1,%a0
	addq.l #1,%a1
	add.l #48,%d1
	move.b %d1,-1(%a0)
	moveq #9,%d1
	cmp.l %d0,%d1
	jcc .L63
	move.l %d3,%d0
	mov3q.l #5,%d3
	cmp.l %a1,%d3
	jne .L64
.L63:
	lea (%a1,%d2.l),%a0
	move.l %a2,%a6
.L65:
	move.b -(%a0),(%a6)+
	cmp.l %d2,%a0
	jne .L65
	clr.b %d4
	move.b %d4,(%a2,%a1.l)
.L55:
	movem.l (%sp),#17436
	lea (28,%sp),%sp
	rts
.L75:
	moveq #70,%d0
	clr.b %d1
	move.w #20294,(%a2)
	move.b %d0,2(%a2)
	move.b %d1,3(%a2)
	movem.l (%sp),#17436
	lea (28,%sp),%sp
	rts
.L76:
	lea .LC2,%a0
	clr.l %d0
.L59:
	move.b (%a0),%d1
	addq.l #1,%a0
	tst.b %d1
	jeq .L60
	move.b %d1,(%a2,%d0.l)
	addq.l #1,%d0
	mov3q.l #4,%d4
	cmp.l %d0,%d4
	jne .L59
.L60:
	lea (%a2,%d0.l),%a0
	addq.l #5,%a2
.L62:
	clr.b (%a0)+
	cmp.l %a2,%a0
	jeq .L55
	clr.b (%a0)+
	cmp.l %a2,%a0
	jne .L62
	jra .L55
	.size	ab_lpf_fmt, .-ab_lpf_fmt
	.align	2
	.globl	ab_admit_track
	.type	ab_admit_track, @function
ab_admit_track:
	lea (-12,%sp),%sp
	clr.l %d0
	movem.l #1036,(%sp)
	move.l 16(%sp),%a2
	sub.l %a1,%a1
	move.l 20(%sp),%d1
	lea (60,%a2),%a0
	lea (34,%a2),%a2
.L81:
	cmp.l %d1,%d0
	jeq .L80
	mvz.b (%a2,%d0.l),%d2
	subq.l #1,%d2
	tst.l %d2
	jeq .L85
.L80:
	addq.l #1,%d0
	lea (30,%a0),%a0
	moveq #8,%d2
	cmp.l %d0,%d2
	jne .L81
.L86:
	mov3q.l #7,%d3
	mov3q.l #1,%d2
	cmp.l %a1,%d2
	scc %d0
	cmp.l %d1,%d3
	scc %d1
	movem.l (%sp),#1036
	neg.l %d0
	neg.l %d1
	and.l %d1,%d0
	mvz.b %d0,%d0
	lea (12,%sp),%sp
	rts
.L85:
	mvz.b (%a0),%d2
	moveq #65,%d3
	cmp.l %d2,%d3
	jne .L80
	mvz.b 1(%a0),%d2
	moveq #66,%d3
	cmp.l %d2,%d3
	jne .L80
	mvz.b 2(%a0),%d2
	subq.l #1,%d2
	tst.l %d2
	jne .L80
	addq.l #1,%a1
	addq.l #1,%d0
	lea (30,%a0),%a0
	moveq #8,%d2
	cmp.l %d0,%d2
	jne .L81
	jra .L86
	.size	ab_admit_track, .-ab_admit_track
	.align	2
	.globl	ab_selected_source
	.type	ab_selected_source, @function
ab_selected_source:
	move.b 269161676,%d0
	tst.b -2147483627.l
	jne .L90
	mvz.b %d0,%d0
	mov3q.l #7,%d1
	cmp.l %d0,%d1
	jcc .L93
.L90:
	clr.l %d0
	rts
.L93:
	move.l 1187521622,%a0
	add.l #585088,%a0
	move.b 269161679,%d1
	move.l %d0,-(%sp)
	mov3q.l #3,%d0
	and.l %d0,%d1
	mvz.w #6322,%d0
	muls.l %d0,%d1
	pea (%a0,%d1.l)
	jsr signed_track
	addq.l #8,%sp
	rts
	.size	ab_selected_source, .-ab_selected_source
	.align	2
	.globl	ab_type
	.type	ab_type, @function
ab_type:
	move.l %d2,-(%sp)
	move.l 1187521622,%d0
	mov3q.l #1,%d2
	move.b 269161679,%d1
	cmp.l 8(%sp),%d2
	jeq .L103
.L96:
	move.l 8(%sp),%d0
	move.l (%sp)+,%d2
	rts
.L103:
	mov3q.l #3,%d2
	and.l %d1,%d2
	mvz.w #6322,%d1
	move.l 12(%sp),%a1
	add.l #585088,%d0
	lea (-34,%a1),%a0
	muls.l %d1,%d2
	add.l %d2,%d0
	sub.l %d0,%a0
	mov3q.l #7,%d2
	cmp.l %a0,%d2
	jcs .L96
	move.l %a0,-(%sp)
	move.l %d0,-(%sp)
	jsr signed_track
	addq.l #8,%sp
	tst.l %d0
	jeq .L96
	mov3q.l #5,8(%sp)
	move.l 8(%sp),%d0
	move.l (%sp)+,%d2
	rts
	.size	ab_type, .-ab_type
	.align	2
	.globl	ab_track_page
	.type	ab_track_page, @function
ab_track_page:
	move.l %d2,-(%sp)
	move.l 1187521622,%a1
	mov3q.l #3,%d2
	move.b 269161679,%d1
	add.l #585088,%a1
	move.l 8(%sp),%d0
	add.l #-34,%d0
	and.l %d2,%d1
	mvz.w #6322,%d2
	muls.l %d2,%d1
	add.l %d1,%a1
	sub.l %a1,%d0
	mov3q.l #7,%d1
	cmp.l %d0,%d1
	jcs .L106
	moveq #30,%d2
	muls.l %d2,%d0
	move.l %d0,%a0
	lea (480,%a0),%a0
	mvz.b (%a1,%a0.l),%d0
	move.l %d0,8(%sp)
	move.l (%sp)+,%d2
	jra page_for
.L106:
	clr.l %d0
	move.l %d0,8(%sp)
	move.l (%sp)+,%d2
	jra page_for
	.size	ab_track_page, .-ab_track_page
	.align	2
	.globl	ab_ui_tick
	.type	ab_ui_tick, @function
ab_ui_tick:
	subq.l #8,%sp
	move.l %d3,-(%sp)
	move.l #1187521622,%a0
	move.l %d2,-(%sp)
	move.l #1073741823,%d0
	cmp.l (%a0),%d0
	jcc .L110
	move.l #1207959551,%d1
	cmp.l (%a0),%d1
	jcc .L111
.L110:
	clr.l -(%sp)
	jsr page_for
	addq.l #4,%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	move.l %d0,1074618188
	addq.l #8,%sp
	rts
.L111:
	move.l (%a0),%d0
	add.l #585088,%d0
	move.b 269161679,%d2
	move.b 269161676,%d3
	move.l (%a0),%a1
	add.l #585088,%a1
	move.b %d3,11(%sp)
	mov3q.l #3,%d3
	and.l %d3,%d2
	mov3q.l #7,%d3
	move.b 269161679,%d1
	move.l %d2,%a0
	move.b 11(%sp),%d2
	and.l %d3,%d2
	move.l %a0,%d3
	move.l %d2,8(%sp)
	mov3q.l #3,%d2
	and.l %d2,%d1
	mvz.w #6322,%d2
	muls.l %d2,%d3
	muls.l %d2,%d1
	add.l %d3,%d0
	mov3q.l #7,%d3
	add.l %d1,%a1
	sub.l %a1,%d0
	add.l 8(%sp),%d0
	cmp.l %d0,%d3
	jcs .L114
	moveq #30,%d1
	muls.l %d1,%d0
	move.l %d0,%a0
	lea (480,%a0),%a0
	mvz.b (%a1,%a0.l),%d0
	move.l %d0,-(%sp)
	jsr page_for
	addq.l #4,%sp
	move.l %d0,1074618188
.L117:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #8,%sp
	rts
.L114:
	clr.l %d0
	move.l %d0,-(%sp)
	jsr page_for
	addq.l #4,%sp
	move.l %d0,1074618188
	jra .L117
	.size	ab_ui_tick, .-ab_ui_tick
	.align	2
	.globl	ab_validate_part
	.type	ab_validate_part, @function
ab_validate_part:
	lea (-140,%sp),%sp
	movem.l #31996,(%sp)
	move.l 144(%sp),%d2
	mov3q.l #6,%a6
	lea (44,%sp),%a2
	clr.l %d5
	move.l %a2,%a4
	clr.l %d3
.L122:
	move.l %d5,-(%sp)
	move.l %d2,-(%sp)
	jsr signed_track
	addq.l #8,%sp
	tst.l %d0
	jne .L147
.L119:
	addq.l #1,%d5
	lea (30,%a6),%a6
	lea (12,%a4),%a4
	cmp.l #246,%a6
	jne .L122
	move.l %d2,-(%sp)
	jsr ab_stock_validate
	addq.l #4,%sp
	clr.l %d5
	mov3q.l #6,%a0
.L127:
	btst %d5,%d3
	jne .L148
	addq.l #1,%d5
	lea (30,%a0),%a0
	lea (12,%a2),%a2
	cmp.l #246,%a0
	jne .L127
.L151:
	movem.l (%sp),#31996
	lea (140,%sp),%sp
	rts
.L147:
	mov3q.l #1,%d0
	lsl.l %d5,%d0
	sub.l %a0,%a0
	or.l %d0,%d3
.L121:
	move.l #1074606604,%a5
	mov3q.l #5,%d0
	add.l %a0,%a5
	lea 42(%a6,%a0.l),%a3
	move.l %a5,%a1
	cmp.l %a0,%d0
	jcc .L120
.L149:
	move.l %a0,%d1
	mov3q.l #6,%d7
	remu.l %d7,%d0:%d1
	lea (%a6,%d0.l),%a1
	moveq #12,%d0
	lea (474,%a1),%a1
	add.l %d2,%a1
	move.b (%a1),(%a4,%a0.l)
	addq.l #1,%a0
	move.b (%a5),(%a1)
	cmp.l %a0,%d0
	jeq .L119
	move.l #1074606604,%a5
	mov3q.l #5,%d0
	add.l %a0,%a5
	lea 42(%a6,%a0.l),%a3
	move.l %a5,%a1
	cmp.l %a0,%d0
	jcs .L149
.L120:
	lea (%a3,%d2.l),%a5
	move.b (%a5),(%a4,%a0.l)
	addq.l #1,%a0
	move.b (%a1),(%a5)
	jra .L121
.L148:
	clr.l %d1
	lea (%a0,%d2.l),%a3
.L126:
	mov3q.l #5,%d4
	cmp.l %d1,%d4
	jcs .L124
.L150:
	lea (%a2,%d1.l),%a4
	mov3q.l #5,%d4
	move.l %d2,%a1
	add.l %d1,%a1
	move.b (%a4),42(%a0,%a1.l)
	addq.l #1,%d1
	cmp.l %d1,%d4
	jcc .L150
.L124:
	move.l %d1,%d6
	mov3q.l #6,%d7
	remu.l %d7,%d4:%d6
	lea (%a2,%d1.l),%a4
	addq.l #1,%d1
	lea (%a3,%d4.l),%a1
	moveq #12,%d4
	move.b (%a4),474(%a1)
	cmp.l %d1,%d4
	jne .L126
	addq.l #1,%d5
	lea (30,%a0),%a0
	lea (12,%a2),%a2
	cmp.l #246,%a0
	jne .L127
	jra .L151
	.size	ab_validate_part, .-ab_validate_part
	.align	2
	.globl	ab_render
	.type	ab_render, @function
ab_render:
	lea (-56,%sp),%sp
	mov3q.l #7,%d0
	movem.l #19516,(%sp)
	move.l 60(%sp),%d2
	move.l 72(%sp),%d4
	move.l 64(%sp),36(%sp)
	move.l 68(%sp),32(%sp)
	cmp.l %d2,%d0
	jcc .L189
	move.l %d4,72(%sp)
	move.l %d2,60(%sp)
	movem.l (%sp),#19516
	move.l 32(%sp),68(%sp)
	move.l 36(%sp),64(%sp)
	lea (56,%sp),%sp
	jmp 1073758216
.L189:
	move.l 1187521622,%a0
	mov3q.l #3,%d1
	move.b 269161679,%d0
	mvz.w #136,%d5
	move.l %d2,-(%sp)
	add.l #585088,%a0
	lea signed_track,%a3
	muls.l %d2,%d5
	and.l %d1,%d0
	mvz.w #6322,%d1
	add.l #voices,%d5
	muls.l %d1,%d0
	pea (%a0,%d0.l)
	jsr (%a3)
	addq.l #8,%sp
	tst.l %d0
	jeq .L190
	move.l 1187521622,%a2
	move.b 269161679,%d0
	tst.l %d2
	jeq .L174
	mov3q.l #3,%d1
	and.l %d1,%d0
	mvz.w #6322,%d1
	add.l #585088,%a2
	clr.l %d3
	sub.l %a6,%a6
	muls.l %d1,%d0
	add.l %d0,%a2
.L156:
	move.l %a6,-(%sp)
	move.l %a2,-(%sp)
	jsr (%a3)
	addq.l #1,%a6
	addq.l #8,%sp
	add.l %d0,%d3
	cmp.l %d2,%a6
	jne .L156
	moveq #72,%d1
	sub.l %a0,%a0
	muls.l %d2,%d1
	addq.l #1,ab_render_calls
	move.l -2147476352,%a2
	move.l -2147458396,%a1
	move.l -2147458392,%a6
	lea (44,%sp),%a3
	move.l %a1,28(%sp)
	move.l %a2,40(%sp)
	move.l %a3,%a1
	add.l #-2147481558,%d1
.L160:
	mov3q.l #5,%d0
	cmp.l %a0,%d0
	jcs .L157
.L191:
	move.w (%a6)+,%d0
	addq.l #1,%a0
	lsr.l #8,%d0
	move.b %d0,(%a1)+
	mov3q.l #5,%d0
	cmp.l %a0,%d0
	jcc .L191
.L157:
	move.b (%a0,%d1.l),(%a1)
	addq.l #1,%a0
	moveq #12,%d0
	cmp.l %a0,%d0
	jeq .L159
	addq.l #1,%a1
	addq.l #2,%a6
	jra .L160
.L159:
	mov3q.l #1,%d1
	cmp.l %d3,%d1
	jcs .L161
	cmp.l 32(%sp),%d4
	jls .L162
	moveq #16,%d0
	cmp.l %d4,%d0
	jcs .L162
	move.l %d4,%d3
	sub.l 32(%sp),%d3
	addq.l #2,%d3
	move.l %d3,%d1
	add.l %d1,%d1
	lsl.l #3,%d3
	tst.l %d1
	jeq .L165
	clr.l %d0
.L166:
	clr.l (%a2)+
	addq.l #1,%d0
	cmp.l %d0,%d1
	jhi .L166
.L165:
	moveq #16,%d1
	cmp.l %d4,%d1
	jeq .L192
.L167:
	add.l 40(%sp),%d3
	move.l %d3,-2147476352
	move.l %d5,-(%sp)
	jsr ab_reset
	addq.l #4,%sp
.L175:
	clr.l %d0
	movem.l (%sp),#19516
	lea (56,%sp),%sp
	rts
.L161:
	move.l %d5,-(%sp)
	jsr ab_reset
	addq.l #4,%sp
	cmp.l 32(%sp),%d4
	jls .L186
	moveq #16,%d0
	cmp.l %d4,%d0
	jcs .L186
	move.l 28(%sp),%a0
	moveq #63,%d0
	moveq #26,%d1
	clr.l %d2
	sub.l 32(%sp),%d4
	and.l 32(%a0),%d0
	move.l #67108864,%a0
	move.l %a2,%d3
	add.l #16,%d3
	move.l %d4,(%a2)
	lea ab_sample,%a6
	move.l %d0,%a3
	lsl.l %d1,%d0
	move.l %a3,4(%a2)
	move.l %a0,8(%a2)
	move.l %d0,12(%a2)
.L173:
	pea 44(%sp)
	move.l %d5,-(%sp)
	jsr (%a6)
	addq.l #8,%sp
	addq.l #1,%d2
	move.l %d3,%a0
	addq.l #8,%d3
	lsl.l #8,%d0
	move.l %d0,(%a0)+
	move.l %d0,(%a0)
	cmp.l %d4,%d2
	jne .L173
	move.l %d4,%d0
	moveq #63,%d1
	add.l %a3,%d0
	addq.l #2,%d4
	and.l %d1,%d0
	move.l 28(%sp),%a0
	moveq #26,%d1
	lsl.l #3,%d4
	move.l #67108864,%d2
	move.l %d0,32(%a0)
	move.l 32(%a0),%d0
	add.l %d4,%a2
	lsl.l %d1,%d0
	move.l %d0,(%a0)
	clr.l 4(%a0)
	move.l %d2,36(%a0)
	move.l %a2,-2147476352
.L193:
	clr.l %d0
	movem.l (%sp),#19516
	lea (56,%sp),%sp
	rts
.L162:
	moveq #16,%d3
	mov3q.l #4,%d1
	clr.l %d0
	jra .L166
.L192:
	mov3q.l #1,%d1
	and.l 36(%sp),%d1
	move.l %d2,%a0
	add.l #1175473420,%a0
	move.b (%a0),%d4
	mvz.w #336,%d0
	muls.l %d2,%d0
	mulu.w #2688,%d1
	move.l %d0,%a1
	moveq #56,%d0
	add.l %sp,%d0
	move.l %d1,%a0
	moveq #16,%d1
	and.l %d1,%d4
	add.l #-2147476336,%a0
	add.l %a1,%a0
	move.l #-1425473536,(%a0)
	lea (16,%a0),%a1
	move.l %d4,%d1
	lsr.l #4,%d1
	or.l #151584768,%d1
	move.l %d1,4(%a0)
	clr.l 12(%a0)
	clr.l 8(%a0)
.L168:
	mvz.b (%a3),%d1
	addq.l #2,%a3
	swap %d1
	clr.w %d1
	mvz.b -1(%a3),%d2
	or.l %d2,%d1
	move.l %d1,(%a1)+
	cmp.l %d0,%a3
	jne .L168
	tst.b %d4
	jeq .L167
	add.l 40(%sp),%d3
	addq.l #1,ab_hits
	move.l %d3,-2147476352
	move.l %d5,-(%sp)
	jsr ab_reset
	addq.l #4,%sp
	jra .L175
.L186:
	move.l 28(%sp),%a0
	moveq #63,%d0
	moveq #26,%d2
	moveq #16,%d4
	and.l 32(%a0),%d0
	clr.l (%a2)
	move.l #67108864,%a0
	move.l %d0,%d1
	lsl.l %d2,%d1
	move.l %d0,4(%a2)
	move.l #67108864,%d2
	move.l %a0,8(%a2)
	move.l 28(%sp),%a0
	move.l %d1,12(%a2)
	moveq #26,%d1
	move.l %d0,32(%a0)
	move.l 32(%a0),%d0
	add.l %d4,%a2
	lsl.l %d1,%d0
	move.l %d0,(%a0)
	clr.l 4(%a0)
	move.l %d2,36(%a0)
	move.l %a2,-2147476352
	jra .L193
.L190:
	move.l %d5,-(%sp)
	jsr ab_reset
	addq.l #4,%sp
	move.l %d4,72(%sp)
	move.l %d2,60(%sp)
	movem.l (%sp),#19516
	move.l 32(%sp),68(%sp)
	move.l 36(%sp),64(%sp)
	lea (56,%sp),%sp
	jmp 1073758216
.L174:
	moveq #72,%d1
	clr.l %d3
	muls.l %d2,%d1
	addq.l #1,ab_render_calls
	move.l -2147476352,%a2
	sub.l %a0,%a0
	move.l -2147458396,%a1
	lea (44,%sp),%a3
	move.l %a2,40(%sp)
	move.l %a1,28(%sp)
	move.l -2147458392,%a6
	move.l %a3,%a1
	add.l #-2147481558,%d1
	jra .L160
	.size	ab_render, .-ab_render
	.section	.rodata.str1.1
.LC3:
	.string	"PITCH"
.LC4:
	.string	"DECAY"
.LC5:
	.string	"TONE"
.LC6:
	.string	"ATK"
.LC7:
	.string	"SWEEP"
.LC8:
	.string	"SAT"
.LC9:
	.string	"MODEL"
.LC10:
	.string	"ACCNT"
.LC11:
	.string	"LPF"
.LC12:
	.string	"LOW"
.LC13:
	.string	"HIGH"
.LC14:
	.string	"---"
.LC15:
	.string	"TUNE"
.LC16:
	.string	"TDEP"
	.section	.rodata
	.align	2
	.type	names.0, @object
	.size	names.0, 96
names.0:
	.long	.LC3
	.long	.LC4
	.long	.LC5
	.long	.LC6
	.long	.LC7
	.long	.LC8
	.long	.LC9
	.long	.LC10
	.long	.LC11
	.long	.LC12
	.long	.LC13
	.long	.LC14
	.long	.LC3
	.long	.LC4
	.long	.LC15
	.long	.LC6
	.long	.LC16
	.long	.LC8
	.long	.LC9
	.long	.LC10
	.long	.LC11
	.long	.LC12
	.long	.LC13
	.long	.LC14
	.globl	ab_hits
	.data
	.align	2
	.type	ab_hits, @object
	.size	ab_hits, 4
ab_hits:
	.zero	4
	.globl	ab_render_calls
	.align	2
	.type	ab_render_calls, @object
	.size	ab_render_calls, 4
ab_render_calls:
	.zero	4
	.globl	ab_desc_p
	.align	2
	.type	ab_desc_p, @object
	.size	ab_desc_p, 4
ab_desc_p:
	.zero	4
	.type	desc, @object
	.size	desc, 916
desc:
	.zero	916
	.align	2
	.type	voices, @object
	.size	voices, 1088
voices:
	.zero	1088
