#!/usr/bin/env python3
"""Generate original coefficient tables and freestanding ColdFire assembly."""
import math
import pathlib
import subprocess
import sys
import tempfile
HERE=pathlib.Path(__file__).resolve().parent
ROOT=HERE.parents[1]
def table(name, values, typ='int32_t'):
    return 'static const '+typ+' '+name+'[] = {\n'+',\n'.join('    '+', '.join(str(v) for v in values[i:i+8]) for i in range(0,len(values),8))+'\n};\n'
def interp(x, nodes, values):
    for j in range(1,len(nodes)):
        if x<=nodes[j]:
            a=(x-nodes[j-1])/(nodes[j]-nodes[j-1])
            return values[j-1]*(1-a)+values[j]*a
    return values[-1]

def tables():
    fs=88200
    # Service notes pp.11-12: R473/474 + R530/532, loaded by R531/533.
    # Normalize DC gain: level belongs to AMP, not this filter control.
    nominal=1/(2*math.pi*(3200*10000/(3200+10000))*10e-9)
    lpf=[0]+[500*(nominal/500)**((i-1)/63) if i<=64 else
              nominal*(18000/nominal)**((i-64)/63) for i in range(1,128)]
    freq=[50*2**((i-64)/48) for i in range(128)]
    # Original fits to isolated Drumazon 2 Init control sweeps at velocity 100.
    # Center detent 64 maps to 50%; both endpoints remain reachable.
    u=[i/128 if i<=64 else .5+(i-64)/126 for i in range(128)]
    nodes=[0,.125,.25,.375,.5,.75,1]
    exponent=2*math.log(70/(52.7583-30)-1)
    f909=[30+70*math.expm1(exponent*x)/math.expm1(exponent) for x in u]
    pitch_time=[interp(x,nodes,[.003335,.006112,.009581,.013949,.019059,.027856,.032506]) for x in u]
    decay_time=[interp(x,nodes,[.009156,.011198,.015104,.0249,.090601,.220737,.453521]) for x in u]
    bend=[interp(x,nodes,[112.255,144.510,176.139,206.375,234.779,285.99,329.078]) for x in u]
    # Fastest TUNE's exponential extrapolation is ill-conditioned; cap its
    # initial excursion rather than claim a fit to the unresolved first ms.
    tune_gain=[interp(x,nodes,[1.7,1.4558,1.1466,1.0581,1,.9561,.9399]) for x in u]
    return ('/* Generated by generate.py; original mathematical tables, 88.2 kHz. */\n'
      +table('ab_lpf_freq',[round(f) for f in lpf])
      +table('ab_lpf_coef',[32768 if not f else round(32768*(-math.expm1(-2*math.pi*f/fs))) for f in lpf])
      +table('ab_k',[round(32768*2*math.sin(math.pi*f/fs)) for f in freq])
      +table('ab_inc',[round(f/fs*2**32) for f in freq],'uint32_t')
      +table('ab909_inc',[round(f/fs*2**32) for f in f909],'uint32_t')
      +table('ab909_bend',[round(f/fs*2**32) for f in bend])
      +table('ab909_pitch_loss',[round(8388608*(-math.expm1(-1/(fs*t)))) for t in pitch_time])
      +table('ab909_amp_loss',[round(8388608*(-math.expm1(-1/(fs*t)))) for t in decay_time])
      +table('ab909_depth',[round(8192*(2*x)**2.3) for x in u])
      +table('ab909_tune_gain',[round(16384*x) for x in tune_gain])
      +table('ab_loss',[max(1,round(8388608*(-math.expm1(-1/(fs*(0.025*100**(i/127))))))) for i in range(128)])
      # DAFx-14 Eq. 4: negative diode branch, volts normalized by 14 V.
      +table('ab_diode',[round(8388608*(.71/14)*math.expm1(-14*i/256)) for i in range(257)])
      +table('ab_tone',[round(32768*(-math.expm1(-2*math.pi*(180*40**(i/127))/fs))) for i in range(128)])
)
FLAGS=['-mcpu=5407','-msoft-float','-O2','-ffreestanding','-fno-builtin','-fno-common','-fno-jump-tables','-fno-asynchronous-unwind-tables','-fno-ident','-fomit-frame-pointer','-fno-zero-initialized-in-bss','-Wall','-Wextra','-Werror']
def main():
    check='--check' in sys.argv
    outputs={HERE/'tables.inc':tables()}
    with tempfile.TemporaryDirectory() as tmp:
        for name in ('engine','control'):
            if not (HERE/(name+'.c')).exists(): continue
            dest=pathlib.Path(tmp)/(name+'.s')
            # Local include is deliberately checked/generated before compiling.
            if not check: (HERE/'tables.inc').write_text(outputs[HERE/'tables.inc'])
            subprocess.run(['m68k-elf-gcc',*FLAGS,'-S',str(HERE/(name+'.c')),'-o',str(dest)],check=True)
            outputs[HERE/(name+'.s')]='| Generated by generate.py; edit '+name+'.c.\n'+dest.read_text()
    for path,body in outputs.items():
        if check:
            if not path.exists() or path.read_text()!=body: raise SystemExit(f'stale: {path}')
        else: path.write_text(body)
    print('Analog Bassdrum generated sources match' if check else 'Analog Bassdrum sources generated')
if __name__=='__main__': main()
