#!/usr/bin/env python3
"""Generate original coefficient tables and freestanding ColdFire assembly."""
import math
import pathlib
import subprocess
import sys
import tempfile
HERE=pathlib.Path(__file__).resolve().parent
ROOT=HERE.parents[1]
def table(name, values, typ='int32_t'):
    return 'static const '+typ+' '+name+'[] = {\n'+',\n'.join('    '+', '.join(str(v) for v in values[i:i+8]) for i in range(0,len(values),8))+'\n};\n'
def tables():
    # Service notes pp.11-12: R473/474 + R530/532, loaded by R531/533.
    # Normalize DC gain: level belongs to AMP, not this filter control.
    nominal=1/(2*math.pi*(3200*10000/(3200+10000))*10e-9)
    lpf=[0]+[500*(nominal/500)**((i-1)/63) if i<=64 else
              nominal*(18000/nominal)**((i-64)/63) for i in range(1,128)]
    return ('/* Generated LPF display frequencies; synthesis tables live in dsp808/dsp909. */\n'
            +table('ab_lpf_freq',[round(f) for f in lpf]))
FLAGS=['-mcpu=5407','-msoft-float','-O2','-ffreestanding','-fno-builtin','-fno-common','-fno-jump-tables','-fno-asynchronous-unwind-tables','-fno-ident','-fomit-frame-pointer','-fno-zero-initialized-in-bss','-Wall','-Wextra','-Werror']
def main():
    check='--check' in sys.argv
    outputs={HERE/'tables.inc':tables()}
    with tempfile.TemporaryDirectory() as tmp:
        for name in ('engine','control'):
            if not (HERE/(name+'.c')).exists(): continue
            dest=pathlib.Path(tmp)/(name+'.s')
            # Local include is deliberately checked/generated before compiling.
            if not check: (HERE/'tables.inc').write_text(outputs[HERE/'tables.inc'])
            subprocess.run(['m68k-elf-gcc',*FLAGS,'-S',str(HERE/(name+'.c')),'-o',str(dest)],check=True)
            outputs[HERE/(name+'.s')]='| Generated by generate.py; edit '+name+'.c.\n'+dest.read_text()
    for path,body in outputs.items():
        if check:
            if not path.exists() or path.read_text()!=body: raise SystemExit(f'stale: {path}')
        else: path.write_text(body)
    print('Analog Bassdrum generated sources match' if check else 'Analog Bassdrum sources generated')
if __name__=='__main__': main()
