| Generated by generate.py; edit loader.c.
#NO_APP
	.file	"loader.c"
	.text
	.align	2
	.globl	ab_load_record
	.type	ab_load_record, @function
ab_load_record:
	lea (-88,%sp),%sp
	movem.l #31996,(%sp)
	move.l 96(%sp),%d3
	move.l 92(%sp),%a0
	cmp.l old_bank.l,%d3
	jeq .L102
	lea old_models,%a4
	mov3q.l #1,%d2
	lea (34,%a0),%a2
	lea (480,%a0),%a0
	lea (88,%sp),%a6
	move.l %a4,%a3
	lea (56,%sp),%a1
.L6:
	mvz.b (%a2),%d0
	mov3q.l #-1,%d1
	subq.l #1,%d0
	tst.l %d0
	jeq .L103
.L5:
	cmp.l (%a3)+,%d1
	sne %d0
	addq.l #1,%a2
	lea (30,%a0),%a0
	move.l %d1,(%a1)+
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d2
	cmp.l %a1,%a6
	jne .L6
.L104:
	tst.l %d2
	jeq .L25
	move.l %d3,old_bank
	move.l 100(%sp),%d3
	addq.l #1,ab_load_generation
	clr.l ab_load_error
	move.l %d3,old_part
	lea (56,%sp),%a0
.L12:
	move.l (%a0)+,(%a4)+
	cmp.l %a0,%a6
	jne .L12
	clr.l %d6
	move.l %d6,%d0
	mov3q.l #4,%d4
	lea plans+96,%a6
	clr.l %d7
	lsl.l #2,%d0
	move.l #1086324752,%a4
	move.l %d2,52(%sp)
	move.l #plans+64,%d3
	clr.l 24(%a6)
	clr.l 20(%a6)
	clr.l 16(%a6)
	clr.l 12(%a6)
	clr.l 8(%a6)
	clr.l 4(%a6)
	clr.l (%a6)
	mvz.w #11072,%d5
	lea (-96,%a6),%a3
	lea (-48,%a6),%a1
	eor.l %d4,%d0
	move.l (%a4),%d2
	mvz.w %d0,%d0
	lea 56(%sp,%d0.l*4),%a2
.L23:
	move.l (%a2)+,%d0
	mov3q.l #-1,%d1
	move.l %d0,16(%a1)
	clr.l (%a1)+
	clr.l 28(%a1)
	cmp.l %d0,%d1
	jeq .L14
	move.l #1094863921,%d4
	cmp.l 1086324736.l,%d4
	jne .L21
	mov3q.l #1,%d1
	cmp.l 1086324740.l,%d1
	jne .L21
	moveq #16,%d4
	swap %d4
	cmp.l 1086324744.l,%d4
	jcs .L21
	move.l 1086324748,%d1
	cmp.l #128,%d1
	jhi .L21
	cmp.l %d0,%d1
	jls .L21
	moveq #48,%d1
	muls.l %d1,%d0
	move.l (%a6),%d1
	move.l %d0,%a0
	add.l #1086324800,%a0
	tst.l %d1
	jeq .L17
	move.l %a3,%a5
	clr.l %d0
.L16:
	lea (12,%a5),%a5
	cmp.l -12(%a5),%a0
	jeq .L19
	addq.l #1,%d0
	cmp.l %d0,%d1
	jne .L16
.L17:
	move.l 4(%a0),%d4
	move.l 4(%a4),%d0
	sub.l %d2,%d0
	cmp.l %d4,%d0
	jcs .L21
	move.l 8(%a0),%d0
	move.l %d0,44(%sp)
	mvz.w #14080,%d0
	sub.l %d5,%d0
	cmp.l 44(%sp),%d0
	jcs .L21
	moveq #12,%d0
	muls.l %d1,%d0
	move.l %d0,%a5
	move.l %d1,%d0
	move.l %d2,4(%a3,%a5.l)
	move.l %d5,8(%a3,%a5.l)
	move.l %a0,(%a5,%a3.l)
	addq.l #1,%d1
	move.l %d1,(%a6)
	moveq #12,%d1
	muls.l %d1,%d0
	add.l %d4,%d2
	add.l 44(%sp),%d5
	move.l 4(%a3,%d0.l),%d0
	add.l 44(%a0),%d0
	move.l %d0,-4(%a1)
.L14:
	cmp.l %a1,%d3
	jne .L23
.L105:
	move.l 24(%a6),%d0
	addq.l #8,%a4
	lea (124,%a6),%a6
	add.l #124,%d3
	lsl.l %d6,%d0
	subq.l #1,%d6
	or.l %d0,%d7
	move.l %d7,ab_load_error
	tst.l %d6
	jeq .L25
	move.l 52(%sp),%d6
	move.l %d6,%d0
	lsl.l #2,%d0
	mov3q.l #4,%d4
	clr.l 24(%a6)
	clr.l 20(%a6)
	clr.l 16(%a6)
	clr.l 12(%a6)
	clr.l 8(%a6)
	clr.l 4(%a6)
	clr.l (%a6)
	mvz.w #11072,%d5
	lea (-96,%a6),%a3
	lea (-48,%a6),%a1
	eor.l %d4,%d0
	move.l (%a4),%d2
	mvz.w %d0,%d0
	lea 56(%sp,%d0.l*4),%a2
	jra .L23
.L103:
	mvz.b -420(%a0),%d0
	moveq #65,%d4
	cmp.l %d0,%d4
	jne .L5
	mvz.b -419(%a0),%d0
	moveq #66,%d4
	cmp.l %d0,%d4
	jne .L5
	mvz.b -418(%a0),%d0
	subq.l #1,%d0
	tst.l %d0
	jne .L5
	mvz.b (%a0),%d1
	addq.l #1,%a2
	lea (30,%a0),%a0
	cmp.l (%a3)+,%d1
	sne %d0
	move.l %d1,(%a1)+
	mvs.b %d0,%d0
	neg.l %d0
	or.l %d0,%d2
	cmp.l %a1,%a6
	jne .L6
	jra .L104
.L21:
	mov3q.l #1,24(%a6)
	cmp.l %a1,%d3
	jne .L23
	jra .L105
.L19:
	cmp.l %d1,%d0
	jeq .L17
	moveq #12,%d1
	muls.l %d1,%d0
	move.l 4(%a3,%d0.l),%d0
	add.l 44(%a0),%d0
	move.l %d0,-4(%a1)
	jra .L14
.L25:
	mov3q.l #3,%d0
	cmp.l 104(%sp),%d0
	scc %d1
	neg.l %d1
	tst.b %d1
	jeq .L8
	move.w #124,%a1
	mov3q.l #5,%d2
	add.l #plans,%a1
	move.l 100(%a1),%d0
	move.l %d0,%d5
	cmp.l %d0,%d2
	jcs .L106
.L10:
	move.l 108(%sp),%a0
	lea (4,%a0),%a2
	btst #0,3(%a2)
	jne .L107
.L26:
	tst.l %d0
	jne .L108
.L28:
	move.l 108(%sp),%a0
	move.l #196608,%a2
	addq.l #1,ab_load_packets
	move.l %a2,8(%a0)
	move.l 112(%a1),%d0
	move.l %d0,%d1
	addq.l #1,%d1
	move.l %d1,112(%a1)
	move.l %d0,12(%a0)
	tst.l 120(%a1)
	jeq .L69
	mov3q.l #6,%d0
	move.l %d0,100(%a1)
.L1:
	movem.l (%sp),#31996
	lea (88,%sp),%sp
	rts
.L8:
	sub.l %a1,%a1
	add.l #plans,%a1
	move.l 100(%a1),%d0
	mov3q.l #5,%d2
	move.l %d0,%d5
	cmp.l %d0,%d2
	jcc .L10
.L106:
	mov3q.l #6,%d2
	cmp.l %d0,%d2
	jeq .L65
.L30:
	move.l %d0,%d5
.L52:
	mov3q.l #3,%d3
	cmp.l %d5,%d3
	jeq .L109
	mov3q.l #4,%d4
	cmp.l %d5,%d4
	jeq .L55
	subq.l #5,%d5
	tst.l %d5
	jne .L1
	moveq #4,%d0
	swap %d0
	move.l 108(%sp),%a0
	addq.l #1,ab_load_packets
	move.l 116(%a1),40(%a0)
	move.l %d0,8(%a0)
	move.l 112(%a1),%d0
	move.l %d0,%d1
	addq.l #1,%d1
	move.l %d1,112(%a1)
	move.l %d0,12(%a0)
	mov3q.l #6,100(%a1)
	tst.l 120(%a1)
	jne .L1
	mov3q.l #3,%d0
	and.l 104(%sp),%d0
	add.l #20,%d0
	tst.l (%a1,%d0.l*4)
	jeq .L1
	move.l 4(%a0),%d1
	mov3q.l #2,%d2
	and.l #-65536,%d1
	or.l %d1,%d2
	move.l %d2,4(%a0)
	movem.l (%sp),#31996
	clr.l (%a1,%d0.l*4)
	lea (88,%sp),%sp
	rts
.L107:
	mov3q.l #3,%d0
	and.l 104(%sp),%d0
	mov3q.l #6,%d2
	mov3q.l #1,80(%a1,%d0.l*4)
	moveq #-2,%d0
	and.l %d0,4(%a0)
	move.l 100(%a1),%d0
	move.l %d0,%d5
	cmp.l %d0,%d2
	jne .L26
.L65:
	tst.l 120(%a1)
	jne .L30
	mov3q.l #3,%d2
	and.l 104(%sp),%d2
	move.l %d2,%a0
	lea (20,%a0),%a0
	tst.l (%a1,%a0.l*4)
	jeq .L30
	move.l 108(%sp),%a2
	mov3q.l #2,%d2
	move.l 4(%a2),%d0
	and.l #-65536,%d0
	or.l %d0,%d2
	move.l %d2,4(%a2)
	move.l 100(%a1),%d0
	move.l %d0,%d5
	clr.l (%a1,%a0.l*4)
	tst.l %d0
	jeq .L28
.L108:
	move.l %d0,%a0
	mov3q.l #1,%d3
	subq.l #1,%a0
	cmp.l %a0,%d3
	jcs .L30
	move.l 104(%a1),%d2
	moveq #12,%d0
	move.l 96(%a1),%a0
	muls.l %d2,%d0
	cmp.l %d2,%a0
	jeq .L110
.L33:
	lea (%a1,%d0.l),%a4
	mov3q.l #1,%d3
	move.l (%a4),%a3
	cmp.l %d5,%d3
	jeq .L111
	move.l 8(%a3),%d4
	move.l 108(%a1),%d0
	cmp.l %d0,%d4
	jeq .L112
.L37:
	sub.l %d0,%d4
	moveq #16,%d2
	cmp.l %d4,%d2
	jcc .L38
	moveq #16,%d4
.L38:
	mov3q.l #1,%d3
	cmp.l %d5,%d3
	jeq .L113
	moveq #2,%d3
	swap %d3
	move.l 108(%sp),%d2
	add.l #40,%d2
	move.l 8(%a4),%d7
	mov3q.l #2,%d5
	add.l %d0,%d7
	move.l %d2,%a2
	move.l %d3,44(%sp)
	mov3q.l #1,%d3
	cmp.l %d5,%d3
	jeq .L114
.L70:
	clr.l %d1
	move.l #1086324736,%a0
.L41:
	add.l %d1,%d0
	add.l 20(%a3),%d0
	addq.l #1,%d1
	move.l (%a0,%d0.l*4),(%a2)+
	move.l 108(%a1),%d0
	cmp.l %d4,%d1
	jne .L41
	move.l 44(%sp),%d3
	move.l %d7,%d1
	add.l %d4,%d0
	swap %d1
	clr.w %d1
	or.l %d4,%d3
	move.l %d0,108(%a1)
.L50:
	move.l 116(%a1),%d0
	move.l %d2,%a0
	mvz.w %d4,%d6
	add.l 112(%a1),%d0
	lea (%a0,%d6.l*4),%a2
	add.l %d4,%d0
	add.l %d7,%d0
	add.l %d5,%d0
	and.l #16777215,%d0
	move.l %d0,116(%a1)
.L63:
	add.l (%a0)+,%d0
	and.l #16777215,%d0
	move.l %d0,116(%a1)
	cmp.l %a2,%a0
	jne .L63
	move.l 108(%sp),%a0
	addq.l #1,ab_load_packets
	move.l %d3,8(%a0)
	move.l 112(%a1),%d0
	move.l %d0,%a2
	addq.l #1,%a2
	move.l %a2,112(%a1)
	or.l %d1,%d0
	movem.l (%sp),#31996
	move.l %d0,12(%a0)
	lea (88,%sp),%sp
	rts
.L102:
	move.l 100(%sp),%d0
	lea old_models,%a4
	lea (34,%a0),%a2
	cmp.l old_part.l,%d0
	sne %d2
	lea (480,%a0),%a0
	lea (88,%sp),%a6
	move.l %a4,%a3
	lea (56,%sp),%a1
	mvs.b %d2,%d2
	neg.l %d2
	jra .L6
.L111:
	move.l 4(%a3),%d4
	move.l 108(%a1),%d0
	cmp.l %d0,%d4
	jne .L37
.L112:
	addq.l #1,%d2
	move.l %d2,104(%a1)
	move.l 100(%a1),%d5
	mov3q.l #1,%d2
	move.l %d5,%d0
	subq.l #1,%d0
	clr.l 108(%a1)
	cmp.l %d0,%d2
	jcs .L52
.L100:
	move.l 104(%a1),%d2
	moveq #12,%d0
	muls.l %d2,%d0
	cmp.l %d2,%a0
	jne .L33
.L110:
	move.l %d5,%d2
	addq.l #1,%d2
	move.l %d2,100(%a1)
	move.l %d5,%d0
	move.l %d2,%d5
	clr.l 108(%a1)
	clr.l 104(%a1)
	mov3q.l #1,%d2
	cmp.l %d0,%d2
	jcc .L100
	jra .L52
.L113:
	moveq #1,%d2
	swap %d2
	move.l 4(%a4),%d7
	mov3q.l #1,%d3
	add.l %d0,%d7
	move.l %d2,44(%sp)
	move.l 108(%sp),%d2
	add.l #40,%d2
	move.l %d2,%a2
	cmp.l %d5,%d3
	jne .L70
.L114:
	mvz.b %d1,%d1
	move.l %d7,48(%sp)
	move.l #1086324736,%a6
	clr.l %d6
	addq.l #3,%d1
	move.l %d1,%d7
.L48:
	add.l %d6,%d0
	move.l %d0,%a0
	add.l (%a3,%d7.l*4),%a0
	move.l 28(%a3),%d1
	move.l (%a6,%a0.l*4),%d3
	tst.l %d1
	jeq .L42
	move.l 24(%a3),%a0
	lea (%a0,%d1.l),%a5
	add.l #271581184,%a0
	move.l %a0,%d1
	add.l #271581184,%a5
	lsl.l #2,%d1
	move.l %d1,%a0
	move.l %a5,%d1
	lsl.l #2,%d1
.L44:
	cmp.l (%a0),%d0
	jeq .L115
	addq.l #4,%a0
	cmp.l %a0,%d1
	jne .L44
.L42:
	move.l 36(%a3),%d1
	tst.l %d1
	jeq .L45
	move.l 32(%a3),%a0
	lea (%a0,%d1.l),%a5
	add.l #271581184,%a0
	move.l %a0,%d1
	add.l #271581184,%a5
	lsl.l #2,%d1
	move.l %d1,%a0
	move.l %a5,%d1
	lsl.l #2,%d1
.L47:
	cmp.l (%a0),%d0
	jeq .L116
	addq.l #4,%a0
	cmp.l %d1,%a0
	jne .L47
.L45:
	and.l #16777215,%d3
	addq.l #1,%d6
	move.l %d3,(%a2)+
	move.l 108(%a1),%d0
	cmp.l %d4,%d6
	jne .L48
	move.l 44(%sp),%d3
	add.l %d4,%d0
	move.l %d0,108(%a1)
	move.l 48(%sp),%d7
	move.l %d7,%d1
	swap %d1
	clr.w %d1
	or.l %d4,%d3
	jra .L50
.L69:
	mov3q.l #1,%d0
	move.l %d0,100(%a1)
	jra .L1
.L115:
	move.l 4(%a4),%a5
	addq.l #4,%a0
	lea (-8192,%a5),%a5
	add.l %a5,%d3
	cmp.l %a0,%d1
	jne .L44
	jra .L42
.L116:
	move.l 8(%a4),%a5
	addq.l #4,%a0
	lea (-16384,%a5),%a5
	add.l %a5,%d3
	cmp.l %d1,%a0
	jne .L47
	jra .L45
.L109:
	move.l 108(%a1),%d0
	cmp.l #256,%d0
	jeq .L117
	move.l %d0,%d7
	move.l #1094863921,%d4
	add.l #14080,%d7
	cmp.l 1086324736.l,%d4
	jne .L56
	mov3q.l #1,%d1
	cmp.l 1086324740.l,%d1
	jne .L56
	moveq #16,%d2
	swap %d2
	cmp.l 1086324744.l,%d2
	jcs .L56
	move.l 1086324748,%d1
	cmp.l #128,%d1
	jhi .L56
	lsr.l #6,%d0
	move.l 64(%a1,%d0.l*4),%d0
	cmp.l %d0,%d1
	jls .L56
	moveq #48,%d3
	muls.l %d3,%d0
	move.l %d0,%a2
	add.l #1086324800,%a2
.L58:
	move.l 108(%sp),%d2
	add.l #40,%d2
	move.l %d2,%a0
	clr.l %d0
	tst.l %a2
	jeq .L59
	move.l #1086324736,%a3
.L60:
	moveq #63,%d1
	moveq #16,%d4
	and.l 108(%a1),%d1
	add.l %d0,%d1
	add.l 40(%a2),%d1
	addq.l #1,%d0
	move.l (%a3,%d1.l*4),(%a0)+
	cmp.l %d0,%d4
	jne .L60
.L61:
	move.l 116(%a1),%d0
	moveq #16,%d4
	mov3q.l #2,%d5
	mvz.w %d4,%d6
	add.l 112(%a1),%d0
	moveq #16,%d3
	move.l %d7,%d1
	move.l %d2,%a0
	add.l %d3,108(%a1)
	add.l %d4,%d0
	add.l %d7,%d0
	add.l %d5,%d0
	move.l #131088,%d3
	and.l #16777215,%d0
	swap %d1
	clr.w %d1
	lea (%a0,%d6.l*4),%a2
	move.l %d0,116(%a1)
	jra .L63
.L56:
	sub.l %a2,%a2
	jra .L58
.L59:
	clr.l (%a0)+
	moveq #16,%d1
	addq.l #1,%d0
	cmp.l %d0,%d1
	jeq .L61
	clr.l (%a0)+
	moveq #16,%d1
	addq.l #1,%d0
	cmp.l %d0,%d1
	jne .L59
	jra .L61
.L117:
	mov3q.l #4,100(%a1)
	clr.l 108(%a1)
.L55:
	move.l 108(%sp),%a0
	mov3q.l #4,%d4
	mvz.w #14336,%d7
	mov3q.l #2,%d5
	mvz.w %d4,%d6
	move.l 48(%a1),40(%a0)
	move.l 52(%a1),44(%a0)
	move.l 56(%a1),48(%a0)
	move.l 60(%a1),52(%a0)
	move.l %a0,%d2
	add.l #40,%d2
	move.l %d2,%a0
	move.l #131076,%d3
	move.l #939524096,%d1
	move.l 116(%a1),%d0
	lea (%a0,%d6.l*4),%a2
	addq.l #1,100(%a1)
	add.l 112(%a1),%d0
	add.l %d4,%d0
	add.l %d7,%d0
	add.l %d5,%d0
	and.l #16777215,%d0
	move.l %d0,116(%a1)
	jra .L63
	.size	ab_load_record, .-ab_load_record
	.globl	ab_load_packets
	.data
	.align	2
	.type	ab_load_packets, @object
	.size	ab_load_packets, 4
ab_load_packets:
	.zero	4
	.globl	ab_load_generation
	.align	2
	.type	ab_load_generation, @object
	.size	ab_load_generation, 4
ab_load_generation:
	.zero	4
	.globl	ab_load_error
	.align	2
	.type	ab_load_error, @object
	.size	ab_load_error, 4
ab_load_error:
	.zero	4
	.align	2
	.type	old_models, @object
	.size	old_models, 32
old_models:
	.zero	32
	.align	2
	.type	old_part, @object
	.size	old_part, 4
old_part:
	.zero	4
	.align	2
	.type	old_bank, @object
	.size	old_bank, 4
old_bank:
	.zero	4
	.align	2
	.type	plans, @object
	.size	plans, 248
plans:
	.zero	248
