#!/usr/bin/env python3
"""Rebuild md_ctl.s (the ColdFire source Linked consumes) or --check for drift.

The firmware builder accepts GNU-as units, so the control engine is kept in
C (md_ctl.c) with its compiler output checked in beside it, as Euclid does.
md_pan.inc, the constant-power PAN table, is generated here too. Neither
file holds an Elektron byte: the engine table comes from the user's OS at
build time (handler_build.py writes it into out/machinedrum/handlers.s).
"""
import math
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FLAGS = ['-mcpu=5407', '-msoft-float', '-O2', '-ffreestanding', '-fno-builtin',
         '-fno-common', '-fno-jump-tables', '-fno-asynchronous-unwind-tables',
         '-fno-ident', '-fomit-frame-pointer', '-fno-zero-initialized-in-bss',
         '-Wall', '-Wextra', '-Werror']


def pan_table():
    """Q15 left gains for PAN 0..127: sqrt(2) cos(pan/127 * pi/2), so a
    centred part keeps its full-VOL level; the right gain reads 127 - pan."""
    rows = [round(32768 * math.sqrt(2) * math.cos(p / 127 * math.pi / 2))
            for p in range(128)]
    body = ",\n".join("    " + ", ".join(f"{v:5d}" for v in rows[i:i + 8])
                      for i in range(0, 128, 8))
    return ("/* Generated by modules/machinedrum/generate_ctl.py: Q15 left gain,\n"
            " * sqrt(2) * cos(pan / 127 * pi / 2). */\n"
            "static const uint16_t md_pan_q15[128] = {\n" + body + "\n};\n")


def generate():
    with tempfile.TemporaryDirectory() as td:
        inc = pathlib.Path(td) / 'md_pan.inc'
        inc.write_text(pan_table())
        asm = pathlib.Path(td) / 'md_ctl.s'
        subprocess.run(['m68k-elf-gcc', *FLAGS, '-I', td, '-S',
                        'modules/machinedrum/md_ctl.c', '-o', str(asm)], cwd=ROOT, check=True)
        return (pan_table(),
                '| Generated by modules/machinedrum/generate_ctl.py; edit md_ctl.c / md_ctl_tail.s.\n'
                + asm.read_text() + '\n' + (HERE / 'md_ctl_tail.s').read_text())


if __name__ == '__main__':
    pan, source = generate()
    outs = ((HERE / 'md_pan.inc', pan), (HERE / 'md_ctl.s', source))
    if '--check' in sys.argv:
        stale = [p.name for p, text in outs if not p.exists() or p.read_text() != text]
        if stale:
            sys.exit(f"Machinedrum {', '.join(stale)} stale: run modules/machinedrum/generate_ctl.py")
        print('Machinedrum md_ctl.s and md_pan.inc match md_ctl.c')
    else:
        for p, text in outs:
            p.write_text(text)
