| Generated by modules/machinedrum/generate_ctl.py; edit md_ctl.c / md_ctl_tail.s.
#NO_APP
	.file	"md_ctl.c"
	.text
	.align	2
	.type	put, @function
put:
	lea (-16,%sp),%sp
	movem.l #3084,(%sp)
	move.l 20(%sp),%a3
	move.l 32(%sp),%a1
	move.l 28(%sp),%a2
	move.l (%a3),%a0
	move.l 4(%a3),%d3
	move.l %d3,%d0
	lea (%a0,%d0.l*2),%a0
	move.w 26(%sp),(%a0)
	move.w %a1,2(%a0)
	tst.l %a1
	jeq .L2
	move.l 36(%sp),%d1
	addq.l #4,%a0
	addq.l #4,%a0
	clr.l %d0
	and.l #16777215,%d1
	addq.l #1,%d0
	move.l %d1,%d2
	clr.w %d2
	swap %d2
	move.w %d1,-2(%a0)
	move.w %d2,-4(%a0)
	cmp.l %a1,%d0
	jeq .L2
.L4:
	move.l (%a2,%d0.l*4),%d1
	addq.l #4,%a0
	addq.l #1,%d0
	and.l #16777215,%d1
	move.l %d1,%d2
	clr.w %d2
	swap %d2
	move.w %d1,-2(%a0)
	move.w %d2,-4(%a0)
	cmp.l %a1,%d0
	jne .L4
.L2:
	addq.l #1,%a1
	mvz.w %a1,%d0
	move.l %d3,%a0
	addq.l #1,8(%a3)
	lea (%a0,%d0.l*2),%a0
	move.l %a0,4(%a3)
	movem.l (%sp),#3084
	lea (16,%sp),%sp
	rts
	.size	put, .-put
	.align	2
	.type	part_gains.constprop.0, @function
part_gains.constprop.0:
	lea (-12,%sp),%sp
	move.l 16(%sp),%d1
	movem.l #1036,(%sp)
	lea md_lanes,%a1
	move.w 16(%a1,%d1.l*2),%d2
	btst #8,%d2
	jne .L11
	moveq #12,%d0
	muls.l %d1,%d0
	move.l %d0,%a0
	add.l #md_run+1345,%d0
	move.l %d0,%a2
	move.b (%a2),%d0
.L12:
	mvz.b %d0,%d0
	btst #9,%d2
	jne .L13
	move.l %a0,%a1
	add.l #md_run+1346,%a1
	move.b (%a1),%d1
	add.l #md_run+1347,%a0
	move.b (%a0),%d2
	mvz.b %d1,%d1
	btst #0,%d2
	jne .L18
.L23:
	moveq #127,%d3
	cmp.l %d0,%d3
	jcs .L21
	moveq #127,%d2
	cmp.l %d1,%d2
	jcs .L22
.L17:
	move.w #127,%a1
	lea md_pan_q15,%a0
	mulu.w %d0,%d0
	mvz.w #252,%d3
	sub.l %d1,%a1
	move.w (%a0,%d1.l*2),%d1
	mulu.w %d0,%d1
	mulu.w (%a0,%a1.l*2),%d0
	divu.l %d3,%d1
	divu.l %d3,%d0
.L15:
	movem.l (%sp),#1036
	move.l 20(%sp),%a0
	move.l %d1,(%a0)
	move.l 24(%sp),%a0
	move.l %d0,(%a0)
	lea (12,%sp),%sp
	rts
.L13:
	moveq #10,%d2
	add.l #md_run+1347,%a0
	muls.l %d2,%d1
	move.b (%a0),%d2
	move.b 57(%a1,%d1.l),%d1
	mvz.b %d1,%d1
	btst #0,%d2
	jeq .L23
.L18:
	movem.l (%sp),#1036
	move.l 20(%sp),%a0
	clr.l %d1
	clr.l %d0
	move.l %d1,(%a0)
	move.l 24(%sp),%a0
	move.l %d0,(%a0)
	lea (12,%sp),%sp
	rts
.L11:
	moveq #10,%d0
	moveq #12,%d3
	muls.l %d1,%d0
	muls.l %d1,%d3
	move.b 56(%a1,%d0.l),%d0
	move.l %d3,%a0
	jra .L12
.L22:
	move.w #127,%a1
	moveq #127,%d1
	lea md_pan_q15,%a0
	mulu.w %d0,%d0
	sub.l %d1,%a1
	move.w (%a0,%d1.l*2),%d1
	mvz.w #252,%d3
	mulu.w %d0,%d1
	mulu.w (%a0,%a1.l*2),%d0
	divu.l %d3,%d1
	divu.l %d3,%d0
	jra .L15
.L21:
	moveq #127,%d0
	moveq #127,%d2
	cmp.l %d1,%d2
	jcc .L17
	jra .L22
	.size	part_gains.constprop.0, .-part_gains.constprop.0
	.align	2
	.type	build_record.constprop.0, @function
build_record.constprop.0:
	lea (-36,%sp),%sp
	moveq #12,%d0
	movem.l #17436,(%sp)
	move.l 40(%sp),%d2
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l #md_run+1344,%a0
	mvz.b (%a0),%d4
	moveq #72,%d0
	cmp.l %d4,%d0
	jcc .L34
	lea md_engines,%a2
.L35:
	move.w %d2,%d0
	lea md_lanes,%a0
	clr.l %d4
	mvz.w 16(%a0,%d2.l*2),%d3
	clr.l %d1
	lea (20,%sp),%a0
	mulu.w #12,%d0
	move.l %d0,%a6
	add.l #md_run+1348,%a6
	move.w %d2,%d0
	mulu.w #10,%d0
	move.l %d0,%a1
	add.l #md_lanes,%a1
.L30:
	btst %d1,%d3
	jeq .L28
	move.b 48(%a1,%d1.l),%d0
	addq.l #1,%d1
	lsl.l #7,%d0
	and.l #16256,%d0
	move.w %d0,(%a0)+
	moveq #8,%d0
	cmp.l %d1,%d0
	jne .L30
.L39:
	mulu.w #84,%d2
	move.l (%a2,%d4.l),%a1
	move.l %d2,%a0
	add.l #md_run,%a0
	move.l 44(%sp),(%a0)
	pea 20(%sp)
	move.l %a0,-(%sp)
	jsr (%a1)
	addq.l #8,%sp
	moveq #21,%d1
	cmp.l %d0,%d1
	jcc .L31
	moveq #21,%d0
.L31:
	movem.l (%sp),#17436
	lea (36,%sp),%sp
	rts
.L28:
	move.b (%a6,%d1.l),%d0
	addq.l #1,%d1
	lsl.l #7,%d0
	and.l #16256,%d0
	move.w %d0,(%a0)+
	moveq #8,%d0
	cmp.l %d1,%d0
	jne .L30
	jra .L39
.L34:
	moveq #52,%d1
	muls.l %d1,%d4
	lea md_engines,%a2
	tst.l (%a2,%d4.l)
	jeq .L35
	move.b 44(%a2,%d4.l),%d0
	btst #0,%d0
	jeq .L35
	move.w %d2,%d0
	lea md_lanes,%a0
	clr.l %d1
	mvz.w 16(%a0,%d2.l*2),%d3
	lea (20,%sp),%a0
	mulu.w #12,%d0
	move.l %d0,%a6
	add.l #md_run+1348,%a6
	move.w %d2,%d0
	mulu.w #10,%d0
	move.l %d0,%a1
	add.l #md_lanes,%a1
	jra .L30
	.size	build_record.constprop.0, .-build_record.constprop.0
	.align	2
	.globl	md_engine_ok
	.type	md_engine_ok, @function
md_engine_ok:
	moveq #72,%d0
	cmp.l 4(%sp),%d0
	jcs .L43
	move.l 4(%sp),%d0
	moveq #52,%d1
	lea md_engines,%a0
	muls.l %d1,%d0
	tst.l (%a0,%d0.l)
	jeq .L43
	move.b 44(%a0,%d0.l),%d0
	mov3q.l #1,%d1
	and.l %d1,%d0
	rts
.L43:
	clr.l %d0
	rts
	.size	md_engine_ok, .-md_engine_ok
	.align	2
	.globl	md_gain
	.type	md_gain, @function
md_gain:
	move.l %d2,-(%sp)
	tst.l 20(%sp)
	jne .L51
	move.l 8(%sp),%d0
	moveq #127,%d1
	cmp.l %d0,%d1
	jcs .L57
	move.l 12(%sp),%d1
	moveq #127,%d2
	cmp.l %d1,%d2
	jcs .L58
.L49:
	tst.l 16(%sp)
	jeq .L50
.L59:
	moveq #127,%d2
	sub.l %d1,%d2
	move.l %d2,%d1
.L50:
	mulu.w %d0,%d0
	lea md_pan_q15,%a0
	mvz.w #252,%d2
	mulu.w (%a0,%d1.l*2),%d0
	divu.l %d2,%d0
	move.l (%sp)+,%d2
	rts
.L58:
	moveq #127,%d1
	tst.l 16(%sp)
	jeq .L50
	jra .L59
.L57:
	move.l 12(%sp),%d1
	moveq #127,%d0
	moveq #127,%d2
	cmp.l %d1,%d2
	jcc .L49
	jra .L58
.L51:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
	.size	md_gain, .-md_gain
	.align	2
	.globl	md_params
	.type	md_params, @function
md_params:
	lea (-12,%sp),%sp
	moveq #10,%d1
	move.l 24(%sp),%d0
	movem.l #3076,(%sp)
	move.l 20(%sp),%a1
	muls.l %d1,%d0
	move.l 16(%sp),%a3
	clr.l %d1
	move.l 28(%sp),%a0
	move.l 24(%sp),%d2
	addq.l #8,%d2
	lea (%a1,%d0.l),%a2
.L63:
	mvz.w (%a1,%d2.l*2),%d0
	btst %d1,%d0
	jeq .L61
	move.b 48(%a2,%d1.l),%d0
	addq.l #1,%d1
	lsl.l #7,%d0
	and.l #16256,%d0
	move.w %d0,(%a0)+
	moveq #8,%d0
	cmp.l %d1,%d0
	jne .L63
.L67:
	movem.l (%sp),#3076
	lea (12,%sp),%sp
	rts
.L61:
	move.b 4(%a3,%d1.l),%d0
	addq.l #1,%d1
	lsl.l #7,%d0
	and.l #16256,%d0
	move.w %d0,(%a0)+
	moveq #8,%d0
	cmp.l %d1,%d0
	jne .L63
	jra .L67
	.size	md_params, .-md_params
	.align	2
	.globl	md_default_kit
	.type	md_default_kit, @function
md_default_kit:
	lea (-16,%sp),%sp
	movem.l #15360,(%sp)
	move.l 20(%sp),%a2
	lea md_default_engines,%a4
	lea (12,%a2),%a2
.L77:
	moveq #100,%d1
	move.b (%a4)+,%d0
	lea (-8,%a2),%a0
	move.b %d1,-11(%a2)
	moveq #64,%d1
	move.b %d0,-12(%a2)
	move.b %d1,-10(%a2)
	clr.b %d1
	move.b %d1,-9(%a2)
	mvz.b %d0,%d1
	move.w %d1,%d0
	mulu.w #52,%d0
	move.l %d0,%a1
	add.l #md_engines,%a1
.L76:
	moveq #72,%d0
	cmp.l %d1,%d0
	jcc .L87
	clr.b (%a0)+
	addq.l #1,%a1
	cmp.l %a0,%a2
	jne .L76
.L74:
	lea (12,%a2),%a2
	cmp.l #md_default_engines+16,%a4
	jne .L77
.L89:
	movem.l (%sp),#15360
	lea (16,%sp),%sp
	rts
.L87:
	moveq #52,%d0
	muls.l %d0,%d1
	lea md_engines,%a3
	lea 44(%a3,%d1.l),%a5
.L69:
	tst.l (%a3,%d1.l)
	jeq .L71
.L88:
	move.b (%a5),%d0
	btst #0,%d0
	jeq .L71
	move.b 4(%a1),(%a0)+
	addq.l #1,%a1
	cmp.l %a2,%a0
	jeq .L74
	tst.l (%a3,%d1.l)
	jne .L88
.L71:
	clr.b (%a0)+
	addq.l #1,%a1
	cmp.l %a0,%a2
	jne .L69
	lea (12,%a2),%a2
	cmp.l #md_default_engines+16,%a4
	jne .L77
	jra .L89
	.size	md_default_kit, .-md_default_kit
	.align	2
	.globl	md_clock_start
	.type	md_clock_start, @function
md_clock_start:
	move.l 4(%sp),%a0
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
	.size	md_clock_start, .-md_clock_start
	.align	2
	.globl	md_clock_update
	.type	md_clock_update, @function
md_clock_update:
	move.l 4(%sp),%a0
	tst.l 16(%a0)
	jeq .L104
	move.l 8(%sp),%d0
	sub.l (%a0),%d0
	move.l 8(%sp),(%a0)
	add.l 8(%a0),%d0
	tst.l %d0
	jge .L105
	move.l 4(%a0),%d1
	subq.l #1,%d1
.L98:
	move.l %d1,%a1
	add.l #1323000,%d0
	subq.l #1,%d1
	tst.l %d0
	jlt .L98
	move.l %a1,4(%a0)
.L97:
	move.l %d0,8(%a0)
.L92:
	rts
.L104:
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
.L105:
	cmp.l #1322999,%d0
	jle .L97
	move.l 4(%a0),%d1
.L99:
	addq.l #1,%d1
	add.l #-1323000,%d0
	cmp.l #1322999,%d0
	jhi .L99
	move.l %d1,4(%a0)
	move.l %d0,8(%a0)
	jra .L92
	.size	md_clock_update, .-md_clock_update
	.align	2
	.globl	md_seq_frame
	.type	md_seq_frame, @function
md_seq_frame:
	lea (-104,%sp),%sp
	movem.l #31996,(%sp)
	move.l 108(%sp),%a3
	move.l #635712,%d5
	mvz.w #36437,%d4
	move.l 112(%sp),%a1
	move.l 116(%sp),%d1
	move.b -2147457603,%d0
	mvz.b -2147457602,%d3
	mvz.b 208(%a3),%d2
	mulu.w #36568,%d3
	mulu.w #2330,%d2
	mvz.b %d0,%d0
	muls.l %d5,%d0
	move.l %d0,%a0
	add.l %d3,%a0
	add.l #1074668000,%a0
	lea (%a0,%d2.l),%a2
	tst.b (%a0,%d4.l)
	jeq .L107
	move.b 81(%a2),%d0
	move.b 80(%a2),%d2
.L108:
	mvz.b %d2,%d2
	mvz.b %d0,%d0
	mov3q.l #6,%d6
	move.l %d2,56(%sp)
	cmp.l %d0,%d6
	jcs .L129
	lea (scales.0),%a0
	mvz.b (%a0,%d0.l),%d2
	move.l %d2,%d7
	add.l %d7,%d7
	move.l %d7,52(%sp)
.L109:
	move.l 56(%sp),%d0
	moveq #63,%d3
	subq.l #1,%d0
	cmp.l %d0,%d3
	jcc .L110
	moveq #16,%d4
	move.l %d4,56(%sp)
.L110:
	mvz.b 82(%a2),%d0
	moveq #29,%d5
	cmp.l %d0,%d5
	jcs .L130
	mvz.b 82(%a2),%d3
	move.l 64(%a2),%d6
	move.l 68(%a2),%d7
	move.l 12(%a1),%a0
	move.l %d6,96(%sp)
	move.l %d7,100(%sp)
	move.b -2147457603,%d0
	move.b -2147457602,%d4
	cmp.l (%a3),%a0
	jeq .L112
.L155:
	move.l %a0,(%a3)
	clr.l 4(%a3)
	move.l 52(%sp),8(%a3)
	clr.l 12(%a3)
.L113:
	move.b %d1,209(%a3)
	tst.l %d1
	jeq .L106
	moveq #15,%d1
	and.l %d1,%d0
	and.l %d1,%d4
	move.l 4(%a1),%d5
	move.l %d5,%d1
	move.l 4(%a3),%a6
	sub.l %a6,%d1
	lsl.l #4,%d0
	add.l %d4,%d0
	move.l %d0,68(%sp)
	move.l %d2,%d0
	lsl.l #2,%d0
	cmp.l %d1,%d0
	jge .L115
	move.l 52(%sp),%d4
	move.l %d5,%d0
	divu.l %d4,%d0
	addq.l #1,%d0
	muls.l %d0,%d4
	move.l %d4,%a6
	move.l %d4,4(%a3)
.L115:
	move.l -2147477476,%d1
	move.l %a6,%d0
	mulu.w %d2,%d3
	sub.l %d5,%d0
	move.l #1323000,%d7
	lsl.l #4,%d1
	move.w 70(%sp),%d2
	move.w 70(%sp),%d5
	move.l 52(%sp),%d6
	move.l 8(%a1),%a1
	move.l %d3,80(%sp)
	muls.l %d7,%d6
	move.l %a1,72(%sp)
	mov3q.l #3,64(%sp)
	move.l %a6,48(%sp)
	move.l %d1,76(%sp)
	mulu.w #96,%d2
	move.l %d7,%d1
	mulu.w #384,%d5
	muls.l %d0,%d1
	move.l %d6,92(%sp)
	move.l %d2,88(%sp)
	mov3q.l #1,%d2
	move.l %d5,%a1
	add.l #md_patterns+384,%a1
	move.l %d5,84(%sp)
	move.l %d1,60(%sp)
.L128:
	move.l 52(%sp),%d3
	moveq #31,%d5
	move.l 48(%sp),%d0
	divu.l %d3,%d0
	move.l 56(%sp),%d4
	remu.l %d4,%d3:%d0
	cmp.l %d3,%d5
	jcs .L116
	move.l 100(%sp),%d0
	lsr.l %d3,%d0
	mov3q.l #1,%d6
	and.l %d6,%d0
.L117:
	mulu.w 82(%sp),%d0
	mvz.w #52920,%d1
	muls.l %d1,%d0
	add.l 60(%sp),%d0
	sub.l 72(%sp),%d0
	cmp.l 76(%sp),%d0
	jgt .L106
	move.l 52(%sp),%d4
	move.l %d3,%d1
	lsl.l #8,%d1
	moveq #31,%d6
	clr.l %d0
	add.l %d4,48(%sp)
	move.l %d3,%d4
	lsr.l #5,%d4
	and.l %d3,%d6
	move.l %d2,%d5
	lea md_patterns,%a2
	add.l 88(%sp),%d4
	clr.w %d7
	move.l 48(%sp),4(%a3)
	move.b 71(%sp),%d1
	mvz.w %d4,%d4
	lsl.l %d6,%d5
	lea (%a2,%d4.l*4),%a0
	move.w %d1,210(%a3)
.L119:
	move.l %d5,%d1
	move.l %d2,%d4
	and.l (%a0),%d1
	lsl.l %d0,%d4
	addq.l #1,%d0
	addq.l #8,%a0
	tst.l %d1
	jeq .L118
	or.l %d4,%d7
.L118:
	moveq #16,%d1
	cmp.l %d0,%d1
	jne .L119
	tst.w %d7
	jeq .L120
	clr.w %d5
	mvz.w %d7,%d6
	lea (16,%a3),%a0
	clr.l %d0
.L123:
	btst %d0,%d6
	jeq .L121
	move.w (%a0),%d1
	move.l %d2,%d4
	lsl.l %d0,%d4
	and.l #768,%d1
	tst.w %d1
	jeq .L122
	or.l %d4,%d5
.L122:
	clr.w (%a0)
.L121:
	addq.l #1,%d0
	addq.l #2,%a0
	moveq #16,%d4
	cmp.l %d0,%d4
	jne .L123
	move.w %d5,%a4
	move.w %d7,%a5
	move.l 84(%sp),%a0
	add.l #md_patterns+128,%a0
	move.l %d6,44(%sp)
.L127:
	mvz.b 1(%a0),%d0
	moveq #15,%d5
	cmp.l %d0,%d5
	jcs .L125
	mvz.b (%a0),%d1
	cmp.l %d3,%d1
	jne .L125
	mvz.b 2(%a0),%d1
	moveq #10,%d6
	moveq #9,%d7
	move.l %d2,%d4
	move.l %d0,%d5
	muls.l %d0,%d6
	lsl.l %d1,%d4
	addq.l #8,%d5
	cmp.l %d1,%d7
	jcs .L125
	lea (%a3,%d6.l),%a2
	move.l 44(%sp),%d6
	btst %d0,%d6
	jeq .L125
	move.w (%a3,%d5.l*2),%d6
	move.l %d2,%d7
	lsl.l %d0,%d7
	or.l %d6,%d4
	move.w %d4,(%a3,%d5.l*2)
	moveq #127,%d4
	mov3q.l #7,%d5
	move.b 3(%a0),%d0
	and.l %d4,%d0
	move.b %d0,48(%a2,%d1.l)
	cmp.l %d1,%d5
	jcc .L125
	move.l %a4,%d6
	or.l %d6,%d7
	move.l %d7,%a4
.L125:
	addq.l #4,%a0
	cmp.l %a1,%a0
	jne .L127
	move.w md_run+1556,%d1
	move.w %a5,%d7
	move.w md_run+1566,%d0
	or.l %d7,%d1
	move.l %a4,%d7
	or.l %d7,%d0
	move.w %d1,md_run+1556
	move.w %d0,md_run+1566
	addq.l #1,12(%a3)
.L120:
	move.l 92(%sp),%d0
	subq.l #1,64(%sp)
	add.l %d0,60(%sp)
	tst.l 64(%sp)
	jne .L128
.L106:
	movem.l (%sp),#31996
	lea (104,%sp),%sp
	rts
.L116:
	move.l %d3,%d1
	add.l #-32,%d1
	move.l 96(%sp),%d0
	lsr.l %d1,%d0
	mov3q.l #1,%d7
	and.l %d7,%d0
	jra .L117
.L130:
	move.l 64(%a2),%d6
	moveq #30,%d3
	move.l 68(%a2),%d7
	move.l 12(%a1),%a0
	move.l %d6,96(%sp)
	move.l %d7,100(%sp)
	move.b -2147457603,%d0
	move.b -2147457602,%d4
	cmp.l (%a3),%a0
	jne .L155
.L112:
	move.l 52(%sp),%d6
	cmp.l 8(%a3),%d6
	jeq .L113
	move.l 4(%a1),%d5
	move.l %d6,%d7
	move.l %d7,8(%a3)
	divu.l %d7,%d5
	addq.l #1,%d5
	muls.l %d5,%d7
	move.l %d7,4(%a3)
	jra .L113
.L129:
	moveq #12,%d0
	mov3q.l #6,%d2
	move.l %d0,52(%sp)
	jra .L109
.L107:
	mvz.w #36436,%d0
	mvz.w #36435,%d2
	move.b (%a0,%d0.l),%d0
	move.b (%a0,%d2.l),%d2
	jra .L108
	.size	md_seq_frame, .-md_seq_frame
	.align	2
	.globl	md_ctl_chunk
	.type	md_ctl_chunk, @function
md_ctl_chunk:
	link.w %fp,#-72
	move.l md_run+1536,%d0
	addq.l #1,%d0
	movem.l #15612,(%sp)
	move.l %d0,md_run+1536
	moveq #15,%d1
	cmp.l %d0,%d1
	jcc .L157
	move.l #-2147477476,%a0
	move.l (%a0),md_handler_sram_word
	jsr md_ui_frame
	clr.l md_parent_track
	tst.l %d0
	jeq .L158
	subq.l #1,%d0
	move.b %d0,md_lanes+208
	moveq #1,%d0
	move.b %d0,md_run+1564
	tst.b md_run+1565.l
	jeq .L250
.L163:
	move.l md_kit_active,%d0
.L161:
	move.l 1175473392,-(%sp)
	pea md_clock
	jsr md_clock_update
	mov3q.l #1,%d6
	clr.l %d3
	lea md_run,%a5
	cmp.l -2147457608.l,%d6
	seq %d0
	lea md_run+1344,%a4
	lea md_run+1348,%a2
	mvs.b %d0,%d0
	neg.l %d0
	move.l %d0,-(%sp)
	pea md_clock
	pea md_lanes
	jsr md_seq_frame
	lea (20,%sp),%sp
	move.w md_run+1560,%d0
	move.b md_run+1563,%d7
	lea md_kit+12,%a0
	lea md_kit,%a1
	move.l %a0,-24(%fp)
	move.w %d0,-26(%fp)
	move.l #md_run+84,%d0
.L180:
	tst.b %d7
	jeq .L208
	move.l %a1,%a0
	move.l %a1,%d4
	move.l %a4,%a1
.L167:
	mvz.b (%a0),%d2
	mvz.b (%a1),%d1
	addq.l #1,%a0
	addq.l #1,%a1
	cmp.l %d2,%d1
	jne .L166
	cmp.l -24(%fp),%a0
	jne .L167
	move.l %d4,%a1
	moveq #12,%d1
	addq.l #1,%d3
	lea (12,%a1),%a1
	add.l #84,%d0
	lea (12,%a4),%a4
	moveq #16,%d2
	lea (12,%a2),%a2
	lea (84,%a5),%a5
	add.l %d1,-24(%fp)
	cmp.l %d3,%d2
	jne .L180
.L253:
	moveq #1,%d3
	move.b %d3,md_run+1563
#APP
| 210 "modules/machinedrum/md_ctl.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l md_trig_request,%d1
	clr.l md_trig_request
#APP
| 213 "modules/machinedrum/md_ctl.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	move.w md_run+1556,%d2
	move.w md_run+1566,%d0
	move.l #md_run+1574,%d6
	move.w -26(%fp),%d5
	clr.w %d4
	move.l %d6,-12(%fp)
	mov3q.l #1,-24(%fp)
	clr.l %d6
	clr.l -8(%fp)
	clr.l -4(%fp)
	lea md_gain_values,%a2
	or.l %d2,%d1
	clr.l %d2
	lea (-16,%fp),%a5
	or.l %d5,%d0
	move.w %d4,md_run+1566
	lea (part_gains.constprop.0),%a3
	move.w %d1,md_run+1556
	move.w %d0,%a4
	move.w %d0,md_run+1560
.L187:
	mvz.w %a4,%d0
	mov3q.l #1,%d4
	lsl.l %d2,%d4
	move.l %d6,%d7
	addq.l #2,%d7
	or.l md_gain_dirty,%d0
	move.l %d4,%d1
	not.l %d1
	and.l %d4,%d0
	tst.l %d0
	jeq .L181
	move.l -8(%fp),%d3
	move.l %d3,%a0
	addq.l #8,%a0
	move.l %a0,-28(%fp)
	cmp.l #445,%a0
	jhi .L182
	moveq #64,%d0
	cmp.l %d7,%d0
	jcs .L182
	move.l md_gain_dirty,%d0
	and.l %d4,%d0
	tst.l %d0
	jeq .L185
	and.l %d1,md_gain_dirty
	move.l (%a2),%d1
	move.l %d2,%a0
	move.l 4(%a2),%d0
	move.l %d7,%d6
	add.l %d3,%d3
	and.l #16777215,%d1
	and.l #16777215,%d0
	lea (3072,%a0),%a0
	move.l %d3,%a1
	add.l #md_run+1574,%a1
	move.l %d1,%d4
	clr.w %d4
	swap %d4
	move.w %a0,(%a1)
	move.w %d1,6(%a1)
	move.l %d3,%a0
	move.l %d2,%d1
	add.l #md_run+1582,%a0
	add.l #3088,%d1
	move.l %d4,%a4
	move.l %d0,%d4
	clr.w %d4
	swap %d4
	move.w %a4,4(%a1)
	move.l %d4,-32(%fp)
	moveq #1,%d4
	move.w %d4,2(%a1)
	move.w %d1,(%a0)
	move.w %d4,2(%a0)
	move.w -30(%fp),4(%a0)
	move.w %d0,6(%a0)
	move.l -28(%fp),-8(%fp)
	move.l %d7,-4(%fp)
.L181:
	addq.l #1,%d2
	moveq #16,%d0
	cmp.l %d2,%d0
	jeq .L184
	move.w md_run+1560,%a4
	addq.l #8,%a2
	jra .L187
.L158:
	move.b md_run+1564,%d1
	move.l %d1,%d0
	subq.l #1,%d0
	mvz.b %d0,%d0
	cmp.l #253,%d0
	jls .L251
.L160:
	move.l md_kit_active,%d2
	move.l %d2,-24(%fp)
	tst.l %d2
	jne .L161
	clr.w %d4
	clr.b %d5
	move.l #md_run+1574,%d6
	clr.l %d2
	move.l %d6,-12(%fp)
	sub.l %a4,%a4
	clr.l md_run+1556
	clr.l %d6
	clr.l -8(%fp)
	clr.l -4(%fp)
	lea md_gain_values,%a2
	move.w %d4,md_run+1560
	lea (-16,%fp),%a5
	lea (part_gains.constprop.0),%a3
	move.b %d5,md_run+1563
	jra .L187
.L208:
	move.l %a5,%a0
.L170:
	clr.l (%a0)+
	cmp.l %d0,%a0
	jne .L170
	mov3q.l #1,%d2
	move.w md_run+1558,%d1
	lsl.l %d3,%d2
	clr.b %d6
	sub.l %a0,%a0
	or.l %d1,%d2
	move.w %d2,%d1
	move.w %d2,md_run+1558
	mov3q.l #1,%d2
	lsl.l %d3,%d2
	tst.b %d7
	jne .L172
.L171:
	or.l %d2,%d1
	addq.l #1,%a0
	moveq #8,%d6
	cmp.l %a0,%d6
	jne .L171
.L242:
	move.w %d1,md_run+1558
.L177:
	tst.b %d7
	jeq .L178
	mvz.b 1(%a1),%d2
	mvz.b 1(%a4),%d1
	cmp.l %d2,%d1
	jeq .L252
.L178:
	mov3q.l #1,%d1
	move.w -26(%fp),%d2
	lsl.l %d3,%d1
	or.l %d2,%d1
	move.w %d1,-26(%fp)
	move.w %d1,md_run+1560
.L179:
	move.l %a4,%a0
	move.l %a1,%a3
	move.l (%a3)+,(%a0)+
	move.l (%a3)+,(%a0)+
	moveq #12,%d1
	addq.l #1,%d3
	move.l (%a3),(%a0)
	lea (12,%a1),%a1
	add.l #84,%d0
	lea (12,%a4),%a4
	moveq #16,%d2
	lea (12,%a2),%a2
	lea (84,%a5),%a5
	add.l %d1,-24(%fp)
	cmp.l %d3,%d2
	jne .L180
	jra .L253
.L255:
	addq.l #1,%a0
	moveq #8,%d4
	cmp.l %a0,%d4
	jeq .L254
.L172:
	mvz.b 4(%a1,%a0.l),%d5
	mvz.b (%a2,%a0.l),%d4
	cmp.l %d5,%d4
	jeq .L255
	or.l %d2,%d1
	addq.l #1,%a0
	moveq #8,%d5
	cmp.l %a0,%d5
	jeq .L242
	moveq #1,%d6
	jra .L172
.L252:
	mvz.b 2(%a1),%d2
	mvz.b 2(%a4),%d1
	cmp.l %d2,%d1
	jne .L178
	move.b 3(%a1),%d1
	move.b 3(%a4),%d2
	eor.l %d2,%d1
	btst #0,%d1
	jeq .L179
	mov3q.l #1,%d1
	move.w -26(%fp),%d2
	lsl.l %d3,%d1
	or.l %d2,%d1
	move.w %d1,-26(%fp)
	move.w %d1,md_run+1560
	jra .L179
.L254:
	tst.b %d6
	jeq .L177
	move.w %d1,md_run+1558
	jra .L177
.L166:
	move.l %d4,%a1
	mvz.b (%a1),%d2
	mvz.b (%a4),%d1
	cmp.l %d2,%d1
	jne .L208
	mov3q.l #1,%d2
	move.w md_run+1558,%d1
	clr.b %d6
	lsl.l %d3,%d2
	sub.l %a0,%a0
	tst.b %d7
	jeq .L171
	jra .L172
.L185:
	move.l %a5,-(%sp)
	pea -20(%fp)
	move.l %d2,-(%sp)
	jsr (%a3)
	not.l %d4
	lea (12,%sp),%sp
	move.l %d7,%d6
	move.l %a4,%d1
	move.l %d2,%a0
	and.l %d1,%d4
	move.l -20(%fp),%d1
	move.l -16(%fp),%d0
	add.l %d3,%d3
	and.l #16777215,%d1
	and.l #16777215,%d0
	lea (3072,%a0),%a0
	move.w %d4,md_run+1560
	move.l %d3,%a1
	add.l #md_run+1574,%a1
	move.l %d1,%d4
	clr.w %d4
	swap %d4
	move.w %a0,(%a1)
	move.w %d1,6(%a1)
	move.l %d3,%a0
	move.l %d2,%d1
	add.l #md_run+1582,%a0
	add.l #3088,%d1
	move.l %d4,%a4
	move.l %d0,%d4
	clr.w %d4
	swap %d4
	move.w %a4,4(%a1)
	move.l %d4,-32(%fp)
	moveq #1,%d4
	move.w %d4,2(%a1)
	move.w %d1,(%a0)
	move.w %d4,2(%a0)
	move.w -30(%fp),4(%a0)
	move.w %d0,6(%a0)
	move.l -28(%fp),-8(%fp)
	move.l %d7,-4(%fp)
	jra .L181
.L182:
	addq.l #1,md_run+1548
.L184:
	clr.l %d4
	lea md_run+1556,%a2
	clr.l %d2
	lea md_run,%a3
	lea md_run+1344,%a4
.L188:
	move.w (%a2),%d0
	jeq .L198
	mov3q.l #1,%d3
	lsl.l %d2,%d3
	and.l %d3,%d0
	tst.w %d0
	jeq .L189
	move.l -8(%fp),%d0
	add.l #44,%d0
	cmp.l #445,%d0
	jhi .L190
	moveq #63,%d1
	cmp.l %d6,%d1
	jcs .L190
	mov3q.l #1,%d6
	eor.l %d4,%d6
	move.l %d6,-(%sp)
	moveq #72,%d6
	move.l %d2,-(%sp)
	jsr (build_record.constprop.0)
	mvz.b (%a4),%d1
	addq.l #8,%sp
	cmp.l %d1,%d6
	jcs .L246
	moveq #52,%d6
	muls.l %d1,%d6
	lea md_engines,%a0
	tst.l (%a0,%d6.l)
	jeq .L246
	move.b 44(%a0,%d6.l),%d6
	btst #0,%d6
	jeq .L246
	tst.l %d4
	jeq .L256
.L196:
	mvz.w %d2,%d1
	clr.l -(%sp)
	move.l %d0,-(%sp)
	move.l %a3,-(%sp)
	lsl.l #6,%d1
	not.l %d3
	move.l %d1,%a0
	pea 2048(%a0)
	pea -12(%fp)
	jsr put
	move.w (%a2),%d0
	clr.l (%a3)
	lea (20,%sp),%sp
	move.l -4(%fp),%d6
	and.l %d3,%d0
	move.w %d0,(%a2)
	move.w md_run+1558,%d0
	and.l %d0,%d3
	move.w %d3,md_run+1558
.L189:
	addq.l #1,%d2
	lea (84,%a3),%a3
	moveq #16,%d0
	lea (12,%a4),%a4
	cmp.l %d2,%d0
	jne .L188
.L198:
	lea md_run+1558,%a2
	subq.l #1,%d4
	tst.l %d4
	jne .L207
.L258:
	tst.l -24(%fp)
	jeq .L201
	tst.l %d6
	jeq .L257
.L202:
	clr.w %d1
	move.l -12(%fp),%a0
	move.l -8(%fp),%d0
	clr.w %d2
	move.w %d6,md_run+1570
	move.w %d0,md_run+1572
	add.l %d6,md_run+1540
	move.w %d1,md_run+1568
	move.l %d0,%d1
	move.l #md_run+1568,%d0
	lea (%a0,%d1.l*2),%a0
	move.w %d2,4(%a0)
	movem.l -72(%fp),#15612
	move.l #65535,(%a0)
	unlk %fp
	rts
.L246:
	clr.l %d1
	tst.l %d4
	jne .L196
.L256:
	move.l (%a3),%a0
	tst.l %a0
	jeq .L197
	move.l %d1,%a0
	addq.l #1,%a0
.L197:
	mvz.w %d2,%d1
	move.l %a0,-(%sp)
	move.l %d0,-(%sp)
	move.l %a3,-(%sp)
	lsl.l #6,%d1
	not.l %d3
	addq.l #1,%d2
	lea (84,%a3),%a3
	lea (12,%a4),%a4
	move.l %d1,%a0
	pea 2048(%a0)
	pea -12(%fp)
	jsr put
	move.w (%a2),%d0
	clr.l -84(%a3)
	lea (20,%sp),%sp
	move.l -4(%fp),%d6
	and.l %d3,%d0
	move.w %d0,(%a2)
	addq.l #1,md_run+1544
	move.w md_run+1558,%d0
	and.l %d0,%d3
	moveq #16,%d0
	move.w %d3,md_run+1558
	cmp.l %d2,%d0
	jne .L188
	jra .L198
.L190:
	addq.l #1,md_run+1548
	lea md_run+1558,%a2
	subq.l #1,%d4
	tst.l %d4
	jeq .L258
.L207:
	mov3q.l #1,%d4
	lea md_run,%a3
	clr.l %d2
	lea md_run+1344,%a4
	jra .L188
.L257:
	move.b md_run+1562,%d3
	moveq #15,%d2
	pea -16(%fp)
	pea -20(%fp)
	move.l -8(%fp),%d4
	move.l %d4,%d5
	move.l -12(%fp),%a3
	addq.l #8,%d4
	add.l %d5,%d5
	and.l %d3,%d2
	move.l %d3,%d1
	addq.l #1,%d1
	move.b %d1,md_run+1562
	lea (%a3,%d5.l),%a2
	move.l %d2,-(%sp)
	jsr (part_gains.constprop.0)
	lea 8(%a3,%d5.l),%a0
	move.l -20(%fp),%d1
	move.l %d2,%d3
	move.l -16(%fp),%d0
	move.l %d2,%a1
	and.l #16777215,%d1
	moveq #1,%d5
	and.l #16777215,%d0
	lea (3072,%a1),%a1
	move.w %a1,(%a2)
	lea (16,%a1),%a1
	move.l %d1,%d6
	clr.w %d6
	swap %d6
	move.w %d5,2(%a2)
	move.l %d0,%d5
	clr.w %d5
	swap %d5
	move.w %d1,6(%a2)
	move.w %d6,4(%a2)
	moveq #1,%d6
	move.w %a1,(%a0)
	move.w %d5,4(%a0)
	move.w %d0,6(%a0)
	move.w %d6,2(%a0)
	clr.l -(%sp)
	move.l %d2,-(%sp)
	move.l %d4,-8(%fp)
	mov3q.l #2,-4(%fp)
	jsr (build_record.constprop.0)
	clr.l -(%sp)
	lsl.l #6,%d2
	moveq #84,%d1
	muls.l %d1,%d3
	move.l %d0,-(%sp)
	add.l #md_run,%d3
	move.l %d3,-(%sp)
	move.l %d2,%a0
	pea 2048(%a0)
	pea -12(%fp)
	jsr put
	move.l -4(%fp),%d6
	lea (40,%sp),%sp
.L201:
	tst.l %d6
	jne .L202
.L157:
	movem.l -72(%fp),#15612
	clr.l %d0
	unlk %fp
	rts
.L251:
	mvz.b %d1,%d0
	addq.l #1,%d1
	move.b %d1,md_run+1564
	mov3q.l #7,%d1
	cmp.l %d0,%d1
	jcs .L160
	tst.b md_run+1565.l
	jne .L163
.L250:
	moveq #1,%d3
	pea md_kit
	jsr md_default_kit
	addq.l #4,%sp
	move.l md_kit_active,%d0
	mov3q.l #1,%d6
	lea md_run,%a5
	move.l 1175473392,-(%sp)
	pea md_clock
	lea md_run+1344,%a4
	lea md_run+1348,%a2
	move.b %d3,md_run+1565
	jsr md_clock_update
	cmp.l -2147457608.l,%d6
	seq %d0
	clr.l %d3
	mvs.b %d0,%d0
	neg.l %d0
	move.l %d0,-(%sp)
	pea md_clock
	pea md_lanes
	jsr md_seq_frame
	lea (20,%sp),%sp
	move.w md_run+1560,%d0
	lea md_kit+12,%a0
	move.b md_run+1563,%d7
	lea md_kit,%a1
	move.l %a0,-24(%fp)
	move.w %d0,-26(%fp)
	move.l #md_run+84,%d0
	jra .L180
	.size	md_ctl_chunk, .-md_ctl_chunk
	.section	.rodata
	.type	scales.0, @object
	.size	scales.0, 7
scales.0:
	.base64	"AwQGCAwYMA=="
	.type	md_default_engines, @object
	.size	md_default_engines, 16
md_default_engines:
	.base64	"EBEWFxMUFRgA"
	.zero	7
	.align	2
	.type	md_pan_q15, @object
	.size	md_pan_q15, 256
md_pan_q15:
	.word	-19195
	.word	-19199
	.word	-19209
	.word	-19227
	.word	-19252
	.word	-19284
	.word	-19323
	.word	-19369
	.word	-19422
	.word	-19482
	.word	-19549
	.word	-19623
	.word	-19705
	.word	-19793
	.word	-19888
	.word	-19990
	.word	-20100
	.word	-20216
	.word	-20339
	.word	-20469
	.word	-20606
	.word	-20749
	.word	-20900
	.word	-21058
	.word	-21222
	.word	-21393
	.word	-21571
	.word	-21755
	.word	-21946
	.word	-22144
	.word	-22349
	.word	-22560
	.word	-22778
	.word	-23002
	.word	-23233
	.word	-23470
	.word	-23713
	.word	-23964
	.word	-24220
	.word	-24483
	.word	-24752
	.word	-25027
	.word	-25308
	.word	-25596
	.word	-25890
	.word	-26189
	.word	-26495
	.word	-26807
	.word	-27125
	.word	-27448
	.word	-27778
	.word	-28113
	.word	-28454
	.word	-28800
	.word	-29153
	.word	-29510
	.word	-29874
	.word	-30242
	.word	-30616
	.word	-30996
	.word	-31381
	.word	-31771
	.word	-32166
	.word	-32566
	.word	32565
	.word	32154
	.word	31739
	.word	31319
	.word	30894
	.word	30465
	.word	30031
	.word	29592
	.word	29148
	.word	28701
	.word	28248
	.word	27792
	.word	27331
	.word	26866
	.word	26397
	.word	25924
	.word	25447
	.word	24966
	.word	24481
	.word	23993
	.word	23501
	.word	23005
	.word	22506
	.word	22003
	.word	21497
	.word	20987
	.word	20475
	.word	19959
	.word	19440
	.word	18918
	.word	18394
	.word	17866
	.word	17336
	.word	16803
	.word	16268
	.word	15730
	.word	15189
	.word	14647
	.word	14102
	.word	13555
	.word	13006
	.word	12455
	.word	11902
	.word	11347
	.word	10790
	.word	10232
	.word	9672
	.word	9111
	.word	8548
	.word	7984
	.word	7419
	.word	6853
	.word	6285
	.word	5717
	.word	5148
	.word	4578
	.word	4007
	.word	3436
	.word	2864
	.word	2292
	.word	1719
	.word	1146
	.word	573
	.word	0

| Appended to the generated md_ctl.s (generate_ctl.py).
|
| The PLAY hooks. Both stock PLAY paths store PLAYING (0x800065b8) and then
| anchor the sequencer's step clock (0x4610757c); the lanes restart there,
| on the same anchor as the OT tracks. Euclid (modules/euclid/hooks.s) takes
| the same two sites for its own clock, so the two modules do not share a
| remix. The displaced store sets the condition codes the stock code after
| it tests: keep them across the call.
        .text
        .balign 4
        .global md_start_hook, md_resume_hook
md_start_hook:
        move.l  %d0,0x800065b8     | displaced: PLAYING
        bsr.s   md_reset_clock
        jmp     0x4009c3da

md_resume_hook:
        move.l  %d0,0x800065b8
        bsr.s   md_reset_clock
        jmp     0x4009c4da

md_reset_clock:
        lea     -28(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@(12)
        move.w  %ccr,%d1
        move.w  %d1,%sp@(8)
        move.l  #md_clock,(%sp)
        move.l  0x4610757c,%d0
        move.l  %d0,4(%sp)
        jsr     md_clock_start
        move.w  %sp@(8),%d1
        move.w  %d1,%ccr
        movem.l %sp@(12),%d0-%d1/%a0-%a1
        lea     28(%sp),%sp
        rts

| The platform runtime is an objcopy'd image with no .bss, so the control
| engine's mutable state is explicit zeroed storage here. md_ctl.c's static
| assertions pin the sizes against md_ctl.h.
        .data
        .balign 4
        .global md_kit, md_run, md_trig_request, md_kit_active
        .global md_clock, md_lanes, md_patterns, md_parent_track
md_kit:
        .zero   192
md_run:
        .zero   2476
md_clock:
        .zero   20
md_lanes:
        .zero   212
md_trig_request:
        .long   0
md_kit_active:
        .long   0
md_parent_track:
        .long   0
md_patterns:                       | 256 x 384: one MD pattern per OT pattern
        .zero   98304
        .text
