| Generated by modules/machinedrum/generate_ctl.py; edit md_persist.c / md_persist_tail.s.
#NO_APP
	.file	"md_persist.c"
	.text
	.align	2
	.type	project_hash, @function
project_hash:
	move.l %d2,-(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	jsr 1073893936
	addq.l #8,%sp
	tst.l %d0
	jeq .L4
	move.l %d0,%a0
	move.b (%a0),%d1
	jeq .L4
	move.l %d0,%a1
	addq.l #1,%a0
	lea (273,%a1),%a1
	move.l #-2128831035,%d0
.L6:
	mvz.b %d1,%d2
	move.b (%a0),%d1
	addq.l #1,%a0
	eor.l %d2,%d0
	move.l #16777619,%d2
	muls.l %d2,%d0
	tst.b %d1
	jeq .L1
	cmp.l %a1,%a0
	jne .L6
.L1:
	move.l (%sp)+,%d2
	rts
.L4:
	move.l (%sp)+,%d2
	move.l #-2128831035,%d0
	rts
	.size	project_hash, .-project_hash
	.align	2
	.type	sanitize_bank, @function
sanitize_bank:
	lea (-24,%sp),%sp
	movem.l #252,(%sp)
	move.w 30(%sp),%d5
	mulu.w #768,%d5
	move.l %d5,%d4
	move.l %d5,%d6
	add.l #md_kits+204,%d4
	add.l #768,%d6
.L20:
	move.l %d4,%a1
	move.l %d4,%d1
	lea (-204,%a1),%a1
	add.l #-192,%d1
.L19:
	mvz.b (%a1),%d0
	moveq #72,%d2
	cmp.l %d0,%d2
	jcc .L17
	clr.b (%a1)
.L17:
	move.b 1(%a1),%d3
	move.b 2(%a1),%d2
	move.b 3(%a1),%d0
	moveq #127,%d7
	move.l %d1,%a0
	subq.l #8,%a0
	and.l %d7,%d3
	and.l %d7,%d2
	mov3q.l #1,%d7
	and.l %d7,%d0
	move.b %d3,1(%a1)
	move.b %d2,2(%a1)
	move.b %d0,3(%a1)
.L18:
	move.b (%a0),%d0
	moveq #127,%d2
	and.l %d2,%d0
	move.b %d0,(%a0)+
	cmp.l %a0,%d1
	jne .L18
	move.l %a0,%d1
	add.l #12,%d1
	lea (12,%a1),%a1
	cmp.l %d1,%d4
	jne .L19
	move.l %a0,%d4
	add.l #192,%d5
	add.l #204,%d4
	cmp.l %d5,%d6
	jne .L20
	move.w 30(%sp),%d0
	mulu.w #6144,%d0
	move.l %d0,%d1
	move.l %d0,%a1
	add.l #md_patterns+384,%d1
	add.l #md_patterns+6528,%a1
.L25:
	move.l %d1,%a0
	lea (-256,%a0),%a0
.L24:
	mvz.b 1(%a0),%d0
	moveq #15,%d7
	cmp.l %d0,%d7
	jcs .L21
	mvz.b (%a0),%d0
	moveq #63,%d2
	cmp.l %d0,%d2
	jcs .L21
	mvz.b 2(%a0),%d0
	moveq #9,%d7
	cmp.l %d0,%d7
	jcs .L21
	move.b 3(%a0),%d0
	moveq #127,%d2
	addq.l #4,%a0
	and.l %d2,%d0
	move.b %d0,-1(%a0)
	cmp.l %a0,%d1
	jne .L24
.L33:
	move.l %a0,%d1
	add.l #384,%d1
	cmp.l %d1,%a1
	jne .L25
	movem.l (%sp),#252
	lea (24,%sp),%sp
	rts
.L21:
	st %d0
	addq.l #4,%a0
	move.b %d0,-3(%a0)
	cmp.l %a0,%d1
	jne .L24
	jra .L33
	.size	sanitize_bank, .-sanitize_bank
	.align	2
	.type	slice_to_sram, @function
slice_to_sram:
	move.l %d2,-(%sp)
	moveq #15,%d2
	and.l 8(%sp),%d2
	move.l #269459472,%d0
	clr.l 269459456
	move.w %d2,%d1
	mulu.w #768,%d1
	add.l #md_kits-269459472,%d1
.L35:
	move.l %d0,%a1
	addq.l #1,%d0
	move.b (%a1,%d1.l),(%a1)
	cmp.l #269460240,%d0
	jne .L35
	move.w %d2,%d1
	mulu.w #6144,%d1
	add.l #md_patterns-269460240,%d1
.L36:
	move.l %d0,%a1
	addq.l #1,%d0
	move.b (%a1,%d1.l),(%a1)
	cmp.l #269466384,%d0
	jne .L36
	move.l %d2,269459460
	move.l #1296323377,%d0
	lea (12,%sp),%a0
	move.l %d2,md_persist+4
	move.l (%sp)+,%d2
	clr.l md_persist+8
	move.l (%a0),269459464
	move.l %d0,269459456
	rts
	.size	slice_to_sram, .-slice_to_sram
	.align	2
	.type	take.constprop.0, @function
take.constprop.0:
	lea (-24,%sp),%sp
	movem.l #1148,(%sp)
	move.l 28(%sp),%d3
	move.l 32(%sp),%d4
	move.l 36(%sp),%d5
	move.l 40(%sp),%a2
.L47:
	move.l %d4,%d6
	cmp.l #512,%d4
	jls .L42
	mvz.w #512,%d6
.L42:
	move.l %d6,-(%sp)
	pea md_persist+608
	pea md_persist+32
	jsr 1073833316
	lea (12,%sp),%sp
	tst.l %d0
	jle .L48
	move.l (%a2),%d0
	move.l %d6,%a1
	move.l #md_persist+608,%d1
	add.l #md_persist+608,%a1
.L44:
	move.l %d1,%a0
	addq.l #1,%d1
	mvz.b (%a0),%d2
	eor.l %d2,%d0
	move.l #16777619,%d2
	muls.l %d2,%d0
	cmp.l %d1,%a1
	jne .L44
	move.l %d0,(%a2)
	tst.l %d5
	jne .L58
.L45:
	sub.l %d6,%d4
	jne .L47
	movem.l (%sp),#1148
	mov3q.l #1,%d0
	lea (24,%sp),%sp
	rts
.L58:
	move.l %d3,%d1
	move.l #md_persist+608,%d0
	add.l %d6,%d1
.L46:
	move.l %d0,%a1
	move.l %d3,%a0
	move.b (%a1),(%a0)
	addq.l #1,%d0
	addq.l #1,%d3
	cmp.l %d3,%d1
	jeq .L45
	move.l %d0,%a1
	move.l %d3,%a0
	move.b (%a1),(%a0)
	addq.l #1,%d0
	addq.l #1,%d3
	cmp.l %d3,%d1
	jne .L46
	jra .L45
.L48:
	movem.l (%sp),#1148
	clr.l %d0
	lea (24,%sp),%sp
	rts
	.size	take.constprop.0, .-take.constprop.0
	.align	2
	.type	put.constprop.0, @function
put.constprop.0:
	lea (-16,%sp),%sp
	movem.l #1052,(%sp)
	move.l 28(%sp),%a2
	move.l 24(%sp),%d4
	move.l 20(%sp),%d3
	add.l %d4,%d3
.L60:
	move.l %d3,%d1
	move.l #md_persist+608,%d0
	sub.l %d4,%d1
.L61:
	move.l %d1,%a1
	move.l %d0,%a0
	move.b (%a1),(%a0)
	addq.l #1,%d1
	addq.l #1,%d0
	cmp.l #md_persist+1120,%d0
	jne .L61
	move.l (%a2),%d0
	move.l #md_persist+608,%d1
.L62:
	move.l %d1,%a0
	addq.l #1,%d1
	mvz.b (%a0),%d2
	eor.l %d2,%d0
	move.l #16777619,%d2
	muls.l %d2,%d0
	cmp.l #md_persist+1120,%d1
	jne .L62
	pea 512.w
	pea md_persist+608
	move.l %d0,(%a2)
	pea md_persist+32
	jsr 1073833656
	lea (12,%sp),%sp
	tst.l %d0
	jlt .L64
	add.l #-512,%d4
	tst.l %d4
	jne .L60
	movem.l (%sp),#1052
	mov3q.l #1,%d0
	lea (16,%sp),%sp
	rts
.L64:
	movem.l (%sp),#1052
	clr.l %d0
	lea (16,%sp),%sp
	rts
	.size	put.constprop.0, .-put.constprop.0
	.align	2
	.type	path_in.isra.0, @function
path_in.isra.0:
	move.l %a3,-(%sp)
	move.l %a2,-(%sp)
	move.l 20(%sp),%a1
	clr.l %d0
	move.l 12(%sp),%a2
	move.l 16(%sp),%a3
	move.l 24(%sp),%a0
	tst.l %a1
	jeq .L92
.L71:
	move.b (%a3,%d0.l),%d1
	jeq .L74
	cmp.l #240,%d0
	jeq .L76
	move.b %d1,(%a2,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%a1
	jne .L71
	mvs.b -1(%a2,%a1.l),%d0
	lea (%a2,%a1.l),%a3
	moveq #47,%d1
	cmp.l %d0,%d1
	jeq .L84
.L93:
	move.b #47,(%a3)
	move.l %a1,%d0
	addq.l #1,%d0
	lea (%a2,%d0.l),%a3
.L72:
	move.b (%a0),%d1
	lea (%a2,%d0.l),%a1
	tst.b %d1
	jeq .L80
.L81:
	move.b %d1,(%a1)
	addq.l #1,%a0
	addq.l #1,%d0
	addq.l #1,%a1
	move.b (%a0),%d1
	jeq .L89
	cmp.l #271,%d0
	jne .L81
.L89:
	lea (%a2,%d0.l),%a3
.L80:
	clr.b (%a3)
	move.l (%sp)+,%a2
	move.l (%sp)+,%a3
	rts
.L74:
	move.l %a2,%a3
	tst.l %d0
	jeq .L72
.L76:
	move.l %d0,%a1
	moveq #47,%d1
	lea (%a2,%a1.l),%a3
	mvs.b -1(%a2,%a1.l),%d0
	cmp.l %d0,%d1
	jne .L93
.L84:
	move.b (%a0),%d1
	move.l %a1,%d0
	lea (%a2,%d0.l),%a1
	tst.b %d1
	jne .L81
	jra .L80
.L92:
	move.b (%a0),%d1
	move.l %a2,%a3
	lea (%a2,%d0.l),%a1
	tst.b %d1
	jne .L81
	jra .L80
	.size	path_in.isra.0, .-path_in.isra.0
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	""
	.text
	.align	2
	.type	project_path.isra.0, @function
project_path.isra.0:
	clr.l -(%sp)
	clr.l -(%sp)
	jsr 1073893936
	addq.l #8,%sp
	move.l %d0,%a1
	tst.l %d0
	jne .L102
	move.l 8(%sp),-(%sp)
	move.l %a1,-(%sp)
	move.l #.LC0,%d0
	move.l %d0,-(%sp)
	move.l 16(%sp),-(%sp)
	jsr (path_in.isra.0)
	lea (16,%sp),%sp
	rts
.L102:
	tst.b (%a1)
	jeq .L98
	sub.l %a0,%a0
.L96:
	addq.l #1,%a0
	tst.b (%a1,%a0.l)
	jne .L96
	move.l 8(%sp),-(%sp)
	move.l %a0,%a1
	move.l %a1,-(%sp)
	move.l %d0,-(%sp)
	move.l 16(%sp),-(%sp)
	jsr (path_in.isra.0)
	lea (16,%sp),%sp
	rts
.L98:
	move.l 8(%sp),-(%sp)
	sub.l %a1,%a1
	move.l %a1,-(%sp)
	move.l %d0,-(%sp)
	move.l 16(%sp),-(%sp)
	jsr (path_in.isra.0)
	lea (16,%sp),%sp
	rts
	.size	project_path.isra.0, .-project_path.isra.0
	.align	2
	.globl	md_persist_frame
	.type	md_persist_frame, @function
md_persist_frame:
	move.l %d2,-(%sp)
	tst.l md_persist
	jeq .L103
	move.l #1296323377,%d0
	cmp.l 269459456.l,%d0
	jeq .L113
.L103:
	move.l (%sp)+,%d2
	rts
.L113:
	move.l 269459460,%d0
	cmp.l md_persist+4.l,%d0
	jne .L103
	move.l md_persist+8,%d1
	moveq #15,%d2
	and.l %d2,%d0
	cmp.l #767,%d1
	jhi .L105
	mulu.w #768,%d0
	move.l %d1,%a1
	add.l #269459472,%a1
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #md_kits,%a0
	move.l %a0,%d0
	add.l #128,%d0
.L107:
	move.l (%a0)+,(%a1)+
	cmp.l %a0,%d0
	jne .L107
	add.l #128,%d1
	cmp.l #6911,%d1
	jls .L108
	clr.l %d1
.L108:
	move.l (%sp)+,%d2
	move.l %d1,md_persist+8
	rts
.L105:
	mulu.w #6144,%d0
	move.l %d1,%a0
	move.l %d1,%a1
	add.l #269459472,%a1
	add.l %d0,%a0
	add.l #md_patterns-768,%a0
	move.l %a0,%d0
	add.l #128,%d0
	jra .L107
	.size	md_persist_frame, .-md_persist_frame
	.section	.rodata.str1.1
.LC1:
	.string	"machinedrum.work"
.LC2:
	.string	"r"
.LC3:
	.string	"machinedrum.bad"
	.text
	.align	2
	.globl	md_persist_loaded
	.type	md_persist_loaded, @function
md_persist_loaded:
	lea (-88,%sp),%sp
	movem.l #31996,(%sp)
	moveq #15,%d4
	move.b -2147483646,%d3
	jsr project_hash
	move.l 92(%sp),%d2
	mvz.w %d2,%d2
	move.l %d0,%d5
	and.l %d3,%d4
	move.l %d4,%d3
	btst %d4,%d2
	jne .L115
	move.l #1296323377,%d1
	cmp.l 269459456.l,%d1
	jeq .L172
.L115:
	mov3q.l #1,%d0
	lsl.l %d3,%d0
	clr.l 44(%sp)
	pea .LC1
	pea md_persist+64
	lea (project_path.isra.0),%a3
	or.l %d0,%d2
	jsr (%a3)
	addq.l #8,%sp
	sub.l %a6,%a6
	lea (56,%sp),%a4
.L125:
	pea 4096.w
	pea md_persist+1120
	pea .LC2
	pea md_persist+64
	pea md_persist+32
	jsr 1073834084
	lea (20,%sp),%sp
	tst.l %d0
	jlt .L117
	pea 32.w
	move.l #-2128831035,%d6
	move.l %a4,-(%sp)
	move.l %d6,56(%sp)
	pea md_persist+32
	jsr 1073833316
	lea (12,%sp),%sp
	tst.l %d0
	jle .L118
	move.l #1296323149,%d0
	cmp.l 56(%sp),%d0
	jeq .L173
.L118:
	pea md_persist+32
	jsr 1073833852
	addq.l #1,md_persist+28
	addq.l #4,%sp
	tst.l %a6
	jeq .L174
.L117:
	move.l #md_patterns,%d1
	clr.l %d7
	lea md_kits,%a1
	lea md_kits+768,%a2
.L128:
	btst %d7,%d2
	jne .L168
	move.l %d1,%a3
	lea (6144,%a3),%a3
.L131:
	addq.l #1,%d7
	move.l %a3,%d1
	moveq #16,%d0
	lea (768,%a1),%a1
	cmp.l %d7,%d0
	jne .L128
.L130:
	tst.l 44(%sp)
	jne .L175
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	jsr slice_to_sram
	move.l %d5,md_persist+12
	mov3q.l #1,md_persist
	movem.l 8(%sp),#31996
	lea (96,%sp),%sp
	rts
.L175:
	ext.w %d4
	move.l #269459472,%d0
	move.w %d4,%d1
	mulu.w #768,%d1
	add.l #md_kits-269459472,%d1
.L137:
	move.l %d0,%a0
	addq.l #1,%d0
	move.b (%a0),(%a0,%d1.l)
	cmp.l #269460240,%d0
	jne .L137
	mulu.w #6144,%d4
	move.l %d4,%d1
	add.l #md_patterns-269460240,%d1
.L138:
	move.l %d0,%a0
	addq.l #1,%d0
	move.b (%a0),(%a0,%d1.l)
	cmp.l #269466384,%d0
	jne .L138
	move.l %d3,-(%sp)
	jsr sanitize_bank
	addq.l #4,%sp
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	jsr slice_to_sram
	move.l %d5,md_persist+12
	mov3q.l #1,md_persist
	movem.l 8(%sp),#31996
	lea (96,%sp),%sp
	rts
.L173:
	mov3q.l #1,%d1
	cmp.l 60(%sp),%d1
	jne .L118
	mvz.w #192,%d6
	cmp.l 64(%sp),%d6
	jne .L118
	moveq #64,%d0
	cmp.l 68(%sp),%d0
	jne .L118
	mvz.w #384,%d1
	cmp.l 72(%sp),%d1
	jne .L118
	mvz.w #256,%d6
	cmp.l 76(%sp),%d6
	jne .L118
	move.l #md_kits,%d7
	clr.l %d6
	lea (take.constprop.0),%a2
.L120:
	tst.l %a6
	jeq .L140
	move.l %d6,%d1
	lsr.l #2,%d1
	move.l %d2,%d0
	lsr.l %d1,%d0
	mov3q.l #1,%d1
	and.l %d1,%d0
.L119:
	pea 48(%sp)
	move.l %d0,-(%sp)
	pea 192.w
	move.l %d7,-(%sp)
	jsr (%a2)
	lea (16,%sp),%sp
	tst.l %d0
	jeq .L118
	addq.l #1,%d6
	add.l #192,%d7
	moveq #64,%d0
	cmp.l %d6,%d0
	jne .L120
	lea md_patterns,%a5
	clr.l %d6
.L122:
	tst.l %a6
	jeq .L141
	move.l %d6,%d1
	lsr.l #4,%d1
	move.l %d2,%d0
	lsr.l %d1,%d0
	mov3q.l #1,%d1
	and.l %d1,%d0
.L121:
	pea 48(%sp)
	move.l %d0,-(%sp)
	pea 384.w
	move.l %a5,-(%sp)
	jsr (%a2)
	lea (16,%sp),%sp
	move.l %d0,%d7
	tst.l %d0
	jeq .L118
	addq.l #1,%d6
	lea (384,%a5),%a5
	cmp.l #256,%d6
	jne .L122
	mov3q.l #4,-(%sp)
	pea 56(%sp)
	pea md_persist+32
	jsr 1073833316
	lea (12,%sp),%sp
	tst.l %d0
	jle .L118
	move.l 48(%sp),%d6
	cmp.l 52(%sp),%d6
	jne .L118
	pea md_persist+32
	jsr 1073833852
	addq.l #4,%sp
	mov3q.l #1,%d0
	cmp.l %a6,%d0
	jne .L176
	addq.l #1,md_persist+20
	clr.l %d7
	lea sanitize_bank,%a2
	btst %d7,%d2
	jne .L177
.L129:
	addq.l #1,%d7
	moveq #16,%d1
	cmp.l %d7,%d1
	jeq .L130
.L171:
	btst %d7,%d2
	jeq .L129
	jra .L177
.L168:
	move.w %d7,%d6
	move.l %a1,%d0
	mulu.w #768,%d6
	lea (%a2,%d6.l),%a3
.L132:
	move.l %d0,%a0
	addq.l #1,%d0
	clr.b (%a0)
	cmp.l %d0,%a3
	jne .L132
	move.l %d1,%a3
	move.l %d1,%d0
	lea (6144,%a3),%a3
.L133:
	move.l %d0,%a0
	addq.l #1,%d0
	clr.b (%a0)
	cmp.l %d0,%a3
	jne .L133
	move.l %d1,%d0
	add.l #385,%d0
	move.l %d0,%a0
	add.l #6529,%d1
	lea (-256,%a0),%a0
.L135:
	move.b #-1,(%a0)
	addq.l #4,%a0
	cmp.l %d0,%a0
	jne .L135
	add.l #384,%d0
	cmp.l %d0,%d1
	jeq .L131
	move.l %d0,%a0
	lea (-256,%a0),%a0
	jra .L135
.L172:
	cmp.l 269459460.l,%d4
	jne .L115
	cmp.l 269459464.l,%d0
	jne .L115
	mov3q.l #1,44(%sp)
	pea .LC1
	pea md_persist+64
	lea (project_path.isra.0),%a3
	jsr (%a3)
	addq.l #8,%sp
	sub.l %a6,%a6
	lea (56,%sp),%a4
	jra .L125
.L174:
	pea .LC3
	pea md_persist+336
	jsr (%a3)
	clr.l -(%sp)
	pea md_persist+64
	pea md_persist+336
	jsr md_copy_stock
	lea (20,%sp),%sp
	clr.l %d7
	lea md_kits+768,%a2
	move.l #md_patterns,%d1
	lea md_kits,%a1
	jra .L128
.L177:
	move.l %d7,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	addq.l #1,%d7
	moveq #16,%d1
	cmp.l %d7,%d1
	jne .L171
	jra .L130
.L141:
	clr.l %d0
	jra .L121
.L140:
	clr.l %d0
	jra .L119
.L176:
	move.l %d7,%a6
	jra .L125
	.size	md_persist_loaded, .-md_persist_loaded
	.align	2
	.globl	md_persist_sram_saved
	.type	md_persist_sram_saved, @function
md_persist_sram_saved:
	tst.l md_persist
	jne .L182
	rts
.L182:
	jsr project_hash
	move.l %d0,-(%sp)
	move.l 8(%sp),-(%sp)
	jsr slice_to_sram
	addq.l #8,%sp
	rts
	.size	md_persist_sram_saved, .-md_persist_sram_saved
	.section	.rodata.str1.1
.LC4:
	.string	"w"
	.text
	.align	2
	.globl	md_persist_bank_saved
	.type	md_persist_bank_saved, @function
md_persist_bank_saved:
	link.w %fp,#-40
	tst.l md_persist
	jeq .L183
	tst.l 8(%fp)
	jlt .L183
	pea .LC1
	move.l #1296323149,%d0
	pea md_persist+64
	move.l %d0,-32(%fp)
	mvz.w #192,%d0
	mov3q.l #1,-28(%fp)
	clr.l -8(%fp)
	clr.l -4(%fp)
	move.l %d0,-24(%fp)
	moveq #64,%d0
	move.l %d0,-20(%fp)
	mvz.w #384,%d0
	move.l %d0,-16(%fp)
	mvz.w #256,%d0
	move.l %d0,-12(%fp)
	move.l #-2128831035,%d0
	move.l %d0,-36(%fp)
	jsr (project_path.isra.0)
	pea 4096.w
	pea md_persist+1120
	pea .LC4
	pea md_persist+64
	pea md_persist+32
	jsr 1073834084
	lea (28,%sp),%sp
	tst.l %d0
	jlt .L188
	pea 32.w
	pea -32(%fp)
	pea md_persist+32
	jsr 1073833656
	lea (12,%sp),%sp
	tst.l %d0
	jge .L195
.L186:
	pea md_persist+32
	jsr 1073833852
	addq.l #4,%sp
.L188:
	addq.l #1,md_persist+24
.L183:
	unlk %fp
	rts
.L195:
	pea -36(%fp)
	pea 12288.w
	pea md_kits
	lea (put.constprop.0),%a0
	move.l %a0,-40(%fp)
	jsr (%a0)
	lea (12,%sp),%sp
	move.l -40(%fp),%a0
	tst.l %d0
	jeq .L186
	pea -36(%fp)
	move.l #98304,-(%sp)
	pea md_patterns
	jsr (%a0)
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L186
	mov3q.l #4,-(%sp)
	pea -36(%fp)
	pea md_persist+32
	jsr 1073833656
	lea (12,%sp),%sp
	tst.l %d0
	jlt .L186
	pea md_persist+32
	jsr 1073833852
	addq.l #4,%sp
	tst.l %d0
	jlt .L188
	addq.l #1,md_persist+16
	unlk %fp
	rts
	.size	md_persist_bank_saved, .-md_persist_bank_saved
	.align	2
	.globl	md_persist_copied
	.type	md_persist_copied, @function
md_persist_copied:
	lea (-52,%sp),%sp
	movem.l #31748,(%sp)
	move.l 56(%sp),%a2
	move.l 60(%sp),%a3
	tst.l 64(%sp)
	jlt .L196
	tst.l %a2
	jeq .L196
	tst.l %a3
	jeq .L196
	move.b (%a3),%d0
	move.l %a3,%a4
	tst.b %d0
	jeq .L198
	move.l %a3,%a0
.L200:
	mvs.b %d0,%d0
	addq.l #1,%a0
	moveq #47,%d1
	cmp.l %d0,%d1
	jeq .L242
	move.b (%a0),%d0
	jne .L200
.L198:
	move.b (%a2),%d0
	move.l %a2,%a5
	tst.b %d0
	jeq .L201
	move.l %a2,%a0
.L203:
	mvs.b %d0,%d0
	addq.l #1,%a0
	moveq #47,%d2
	cmp.l %d0,%d2
	jeq .L243
	move.b (%a0),%d0
	jne .L203
.L201:
	lea (m.0),%a6
	move.l %a4,%d2
	move.l %a4,%a0
	move.l %a6,%a1
	addq.l #8,%d2
.L204:
	mvs.b (%a1),%d1
	mvs.b (%a0),%d0
	addq.l #1,%a0
	addq.l #1,%a1
	cmp.l %d1,%d0
	jne .L196
	cmp.l %d2,%a0
	jne .L204
	lea (8,%a5),%a1
	move.l %a5,%a0
	move.l %a1,24(%sp)
.L206:
	mvs.b (%a0),%d1
	mvs.b (%a6),%d0
	addq.l #1,%a0
	addq.l #1,%a6
	cmp.l %d1,%d0
	jne .L196
	cmp.l 24(%sp),%a0
	jne .L206
	moveq #109,%d1
	clr.l %d0
	lea (28,%sp),%a0
	lea (md.1),%a1
.L208:
	move.b %d1,(%a0)+
	addq.l #1,%d0
	move.b (%a1,%d0.l),%d1
	jne .L208
	move.b 8(%a4),%d1
	jeq .L209
	lea 28(%sp,%d0.l),%a0
	move.l %d2,%a1
.L211:
	move.b %d1,(%a0)
	move.b 1(%a1),%d1
	addq.l #1,%d0
	addq.l #1,%a1
	addq.l #1,%a0
	tst.b %d1
	jeq .L209
	moveq #23,%d2
	cmp.l %d0,%d2
	jne .L211
.L209:
	clr.b %d1
	sub.l %a3,%a4
	lea (path_in.isra.0),%a6
	move.b %d1,28(%sp,%d0.l)
	pea 28(%sp)
	move.l %a4,-(%sp)
	move.l %a3,-(%sp)
	pea md_persist+64
	jsr (%a6)
	lea (16,%sp),%sp
	move.b 8(%a5),%d0
	jeq .L221
	move.l 24(%sp),%a1
	moveq #12,%d1
	lea (40,%sp),%a0
.L215:
	move.b %d0,(%a0)
	move.b 1(%a1),%d0
	addq.l #1,%d1
	addq.l #1,%a1
	addq.l #1,%a0
	tst.b %d0
	jeq .L213
	moveq #23,%d2
	cmp.l %d1,%d2
	jne .L215
.L213:
	clr.b %d0
	sub.l %a2,%a5
	move.l #md_persist+336,%d2
	move.b %d0,28(%sp,%d1.l)
	pea 28(%sp)
	move.l %a5,-(%sp)
	move.l %a2,-(%sp)
	pea md_persist+336
	jsr (%a6)
	move.l %d2,72(%sp)
	clr.l 80(%sp)
	movem.l 16(%sp),#31748
	move.l #md_persist+64,%d1
	move.l %d1,76(%sp)
	lea (68,%sp),%sp
	jra md_copy_stock
.L196:
	movem.l (%sp),#31748
	lea (52,%sp),%sp
	rts
.L242:
	move.b (%a0),%d0
	move.l %a0,%a4
	tst.b %d0
	jne .L200
	jra .L198
.L243:
	move.b (%a0),%d0
	move.l %a0,%a5
	tst.b %d0
	jne .L203
	jra .L201
.L221:
	clr.b %d0
	moveq #12,%d1
	sub.l %a2,%a5
	move.l #md_persist+336,%d2
	move.b %d0,28(%sp,%d1.l)
	pea 28(%sp)
	move.l %a5,-(%sp)
	move.l %a2,-(%sp)
	pea md_persist+336
	jsr (%a6)
	move.l %d2,72(%sp)
	clr.l 80(%sp)
	movem.l 16(%sp),#31748
	move.l #md_persist+64,%d1
	move.l %d1,76(%sp)
	lea (68,%sp),%sp
	jra md_copy_stock
	.size	md_persist_copied, .-md_persist_copied
	.section	.rodata
	.type	m.0, @object
	.size	m.0, 9
m.0:
	.string	"markers."
	.type	md.1, @object
	.size	md.1, 13
md.1:
	.string	"machinedrum."

| Appended to the generated md_persist.s (generate_ctl.py): the four stock
| detours WP-E1 needs and the unit's storage.
|
| Each wrapper runs the stock routine on the caller's own stack: it keeps
| the caller's return address, puts its own continuation in that slot, and
| runs the displaced first instructions and the rest of stock. Stock sees
| exactly the frame its caller built, whatever the number of arguments
| (the project load takes four and reads the fourth at sp@(344); a first
| draft that called it on three copied arguments stalled every load, found
| under octemu 25 Sep 2026). When stock returns to the continuation, the
| caller's arguments are at 0(sp): md_persist.c runs, stock's d0 is kept
| and the continuation returns to the caller. None of these routines is
| entered again before it returns (the copy of machinedrum.* uses
| md_copy_stock, which bypasses the detour).
        .text
        .balign 2
        .global md_hook_sram_save, md_hook_bank_save, md_hook_proj_load
        .global md_hook_copy, md_copy_stock

| 0x4000faf0(bank): stock copies a bank into SRAM; it is resident now.
| Displaced: move.l a2,-(sp) / move.l d2,-(sp) / move.l #0x8ed80,-(sp).
md_hook_sram_save:
        move.l  (%sp),md_ret_sram_save
        move.l  #.ss_after,(%sp)
        move.l  %a2,-(%sp)
        move.l  %d2,-(%sp)
        move.l  #0x8ed80,-(%sp)
        jmp     (0x4000fafa).l
.ss_after:                               | [bank]
        move.l  %d0,-(%sp)
        move.l  4(%sp),-(%sp)
        jsr     md_persist_sram_saved
        addq.l  #4,%sp
        move.l  (%sp)+,%d0
        move.l  md_ret_sram_save,-(%sp)
        rts

| 0x400917c8(ctx, bank mask): stock saves banks to the card.
| Displaced: link fp,#-324 / movem.l d2-d7/a2-a5,(sp).
md_hook_bank_save:
        move.l  (%sp),md_ret_bank_save
        move.l  #.bs_after,(%sp)
        link    %fp,#-324
        movem.l %d2-%d7/%a2-%a5,(%sp)
        jmp     (0x400917d0).l
.bs_after:                               | [ctx][mask]
        move.l  %d0,-(%sp)
        move.l  %d0,-(%sp)
        jsr     md_persist_bank_saved
        addq.l  #4,%sp
        move.l  (%sp)+,%d0
        move.l  md_ret_bank_save,-(%sp)
        rts

| 0x400905d4(ctx, bank mask, ., .): stock loads banks from the card.
| Displaced: lea -328(sp),sp / movem.l d2-d7/a2-fp,(sp).
md_hook_proj_load:
        move.l  (%sp),md_ret_proj_load
        move.l  #.pl_after,(%sp)
        lea     -328(%sp),%sp
        movem.l %d2-%d7/%a2-%fp,(%sp)
        jmp     (0x400905dc).l
.pl_after:                               | [ctx][mask]...
        move.l  %d0,-(%sp)
        move.l  8(%sp),-(%sp)            | the mask
        jsr     md_persist_loaded
        addq.l  #4,%sp
        move.l  (%sp)+,%d0
        move.l  md_ret_proj_load,-(%sp)
        rts

| 0x40016388(dst, src, flag): stock copies a file.
| Displaced: link fp,#-72 / movem.l d2-d6,(sp).
md_hook_copy:
        move.l  (%sp),md_ret_copy
        move.l  #.cp_after,(%sp)
        link    %fp,#-72
        movem.l %d2-%d6,(%sp)
        jmp     (0x40016390).l
.cp_after:                               | [dst][src][flag]
        move.l  %d0,-(%sp)               | [d0][dst][src]
        move.l  %d0,-(%sp)               | the result: [res][d0][dst][src]
        move.l  12(%sp),-(%sp)           | src
        move.l  12(%sp),-(%sp)           | dst
        jsr     md_persist_copied
        lea     12(%sp),%sp
        move.l  (%sp)+,%d0
        move.l  md_ret_copy,-(%sp)
        rts
| Stock's copy as a plain call (md_persist.c copies machinedrum.* with it).
md_copy_stock:
        link    %fp,#-72
        movem.l %d2-%d6,(%sp)
        jmp     (0x40016390).l

| No .bss in the runtime image: md_persist.c's state (MdPersist) and the
| wrappers' return addresses.
        .data
        .balign 4
        .global md_persist
md_persist:
        .zero   5216
md_ret_sram_save:
        .long   0
md_ret_bank_save:
        .long   0
md_ret_proj_load:
        .long   0
md_ret_copy:
        .long   0
        .text
