| Generated by modules/machinedrum/generate_ctl.py; edit md_ui.c / md_ui_tail.s.
#NO_APP
	.file	"md_ui.c"
	.text
	.align	2
	.type	choice_of, @function
choice_of:
	clr.b %d0
	lea (-92,%sp),%sp
	movem.l #17420,(%sp)
	move.l 96(%sp),%d3
	mov3q.l #1,%a6
	mov3q.l #1,%d2
	lea md_engine_ok,%a2
	move.b %d0,19(%sp)
.L2:
	move.l %d2,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L3
	move.b %d2,19(%sp,%a6.l)
	addq.l #1,%a6
.L3:
	addq.l #1,%d2
	moveq #73,%d0
	cmp.l %d2,%d0
	jne .L2
	tst.l %a6
	jeq .L7
	lea (19,%sp),%a0
	clr.l %d0
.L6:
	mvz.b (%a0),%d1
	addq.l #1,%a0
	cmp.l %d1,%d3
	jeq .L1
	addq.l #1,%d0
	cmp.l %d0,%a6
	jne .L6
.L7:
	clr.l %d0
.L1:
	movem.l (%sp),#17420
	lea (92,%sp),%sp
	rts
	.size	choice_of, .-choice_of
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	""
.LC1:
	.string	"Percussion"
.LC2:
	.string	"FUNC+YES:PLAY"
	.text
	.align	2
	.type	eng_draw, @function
eng_draw:
	lea (-64,%sp),%sp
	movem.l #19708,(%sp)
	move.l md_focus+208,%a6
	move.l #md_focus,%d4
	tst.l %a6
	jeq .L12
	move.l 40(%a6),%a2
	move.l %a2,%d5
	lea (36,%a6),%a6
	add.l #-9,%d5
	move.l %a6,-(%sp)
	jsr 1073960484
	move.b md_ui,%d0
	mvz.b md_focus+217,%d1
	addq.l #4,%sp
	move.l %d4,%a0
	clr.b %d6
	add.l %d1,%a0
	moveq #15,%d1
	moveq #80,%d2
	move.b 220(%a0),%d3
	and.l %d1,%d0
	move.b %d6,51(%sp)
	moveq #10,%d6
	move.b %d2,48(%sp)
	move.l %sp,%d2
	add.l #48,%d2
	move.l %d2,-(%sp)
	addq.l #1,%d0
	remu.l %d6,%d1:%d0
	divu.l %d6,%d0
	mov3q.l #-1,-(%sp)
	move.l %d5,-(%sp)
	mov3q.l #3,-(%sp)
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	add.l #48,%d0
	add.l #48,%d1
	mvz.b %d3,%d3
	move.b %d0,73(%sp)
	move.b %d1,74(%sp)
	jsr 1073818584
	lea (24,%sp),%sp
	move.l %d3,%d0
	moveq #79,%d1
	lsr.l #4,%d0
	cmp.l %d3,%d1
	jcc .L65
	move.l #.LC0,%d0
	move.l %d0,-(%sp)
	mov3q.l #-1,-(%sp)
	move.l %d5,-(%sp)
	pea 24.w
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	jsr 1073818584
	mov3q.l #1,-(%sp)
	pea 115.w
	pea -12(%a2)
	mov3q.l #2,-(%sp)
	move.l %a6,-(%sp)
	jsr 1073813776
	lea md_focus+217,%a0
	move.b (%a0),83(%sp)
	lea md_focus+220,%a1
	lea (44,%sp),%sp
	move.l %a1,%d5
	mvz.b 39(%sp),%d6
	add.l %d6,%d5
	move.l %d6,%a0
.L16:
	move.l %d5,%a3
	subq.l #1,%d5
	tst.l %a0
	jeq .L15
.L67:
	mvz.b -1(%a3),%d1
	mvz.b (%a3),%d0
	lsr.l #4,%d1
	lsr.l #4,%d0
	cmp.l %d1,%d0
	jne .L66
	move.l %d5,%a3
	subq.l #1,%a0
	subq.l #1,%d5
	tst.l %a0
	jne .L67
.L15:
	mvz.b md_focus+218,%d7
	cmp.l %d6,%d7
	jls .L68
.L18:
	move.l %d4,%a3
	add.l %d6,%a3
	mvz.b 220(%a3),%d1
	move.l %d6,%d5
	lsr.l #4,%d1
.L23:
	mvz.b (%a1,%d5.l),%d0
	lsr.l #4,%d0
	cmp.l %d1,%d0
	jne .L22
	addq.l #1,%d5
	cmp.l %d7,%d5
	jcs .L23
.L22:
	mvz.b md_focus+219,%d0
	cmp.l %d0,%a0
	jhi .L25
	cmp.l %d6,%d0
	jls .L19
.L25:
	move.l %a0,%d0
	addq.l #6,%d0
	cmp.l %d6,%d0
	jls .L48
	move.w %a0,%d0
	move.b %d0,md_focus+219
	mvz.b %d0,%d0
.L19:
	move.l %d0,%d1
	addq.l #5,%d1
	cmp.l %d1,%d6
	jle .L21
	move.b 39(%sp),%d0
	subq.l #5,%d0
	move.b %d0,md_focus+219
	mvz.b %d0,%d0
.L21:
	lea (-20,%a2),%a0
	clr.l %d7
	move.l %a0,36(%sp)
	move.l %a0,%d6
.L26:
	move.l %d0,%a3
	add.l %d7,%a3
	cmp.l %a3,%d5
	jls .L30
.L31:
	lea (%a3,%d4.l),%a0
	mvz.b 220(%a0),%d0
	lea (40,%sp),%a1
	mulu.w #52,%d0
	move.l %d0,%a0
	add.l #md_engines+46,%a0
	move.l %a0,%d1
	addq.l #6,%d1
.L28:
	move.b (%a0)+,%d0
	jne .L27
	moveq #32,%d0
.L27:
	move.b %d0,(%a1)+
	cmp.l %a0,%d1
	jne .L28
	clr.b %d0
	move.b %d0,46(%sp)
	pea 40(%sp)
	mov3q.l #-1,-(%sp)
	move.l %d6,-(%sp)
	mov3q.l #4,-(%sp)
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	jsr 1073818584
	mvz.b md_focus+217,%d0
	lea (24,%sp),%sp
	cmp.l %d0,%a3
	jeq .L69
.L29:
	addq.l #1,%d7
	mov3q.l #6,%d0
	cmp.l %d7,%d0
	jeq .L30
	mvz.b md_focus+219,%d0
	subq.l #7,%d6
	move.l %d0,%a3
	add.l %d7,%a3
	cmp.l %a3,%d5
	jhi .L31
.L30:
	mulu.w #52,%d3
	lea (keys.3),%a0
	clr.l %d0
	move.l %d3,%a1
	add.l #md_engines+46,%a1
	mvs.b 4(%a1),%d4
.L34:
	mvs.b (%a0),%d1
	cmp.l %d1,%d4
	jeq .L70
.L32:
	addq.l #1,%d0
	addq.l #2,%a0
	moveq #20,%d1
	cmp.l %d0,%d1
	jne .L34
	move.l #.LC1,%d0
	clr.l %d6
	move.l %d0,-(%sp)
	mov3q.l #-1,-(%sp)
	move.l 44(%sp),-(%sp)
	pea 48.w
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	jsr 1073818584
	move.l %a2,%d5
	add.l #md_engines+12,%d3
	add.l #-29,%d5
	lea (24,%sp),%sp
.L35:
	move.l %d3,%a2
	moveq #48,%d4
	move.l %d2,%a1
	sub.l %a0,%a0
.L36:
	move.b (%a2,%a0.l),%d0
	jeq .L71
	move.b %d0,(%a1)+
	addq.l #1,%a0
	mov3q.l #4,%d0
	cmp.l %a0,%d0
	jne .L36
	clr.b %d0
	move.b %d0,52(%sp)
.L42:
	move.l %d2,-(%sp)
	mov3q.l #-1,-(%sp)
	move.l %d5,-(%sp)
	move.l %d4,-(%sp)
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	jsr 1073818584
	lea (24,%sp),%sp
	addq.l #4,%a2
	moveq #74,%d0
	cmp.l %d4,%d0
	jne .L49
.L72:
	subq.l #7,%d5
	addq.l #8,%d3
	addq.l #2,%d6
	moveq #8,%d1
	cmp.l %d6,%d1
	jne .L35
	pea .LC2
	mov3q.l #-1,-(%sp)
	mov3q.l #2,-(%sp)
	pea 48.w
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	jsr 1073818584
	mov3q.l #1,1187497772
	lea (24,%sp),%sp
.L12:
	movem.l (%sp),#19708
	lea (64,%sp),%sp
	rts
.L65:
	lea CSWTCH.55,%a0
	move.l (%a0,%d0.l*4),%d0
	move.l %d0,-(%sp)
	mov3q.l #-1,-(%sp)
	move.l %d5,-(%sp)
	pea 24.w
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	jsr 1073818584
	mov3q.l #1,-(%sp)
	pea 115.w
	pea -12(%a2)
	mov3q.l #2,-(%sp)
	move.l %a6,-(%sp)
	jsr 1073813776
	lea md_focus+217,%a0
	move.b (%a0),83(%sp)
	lea md_focus+220,%a1
	lea (44,%sp),%sp
	move.l %a1,%d5
	mvz.b 39(%sp),%d6
	add.l %d6,%d5
	move.l %d6,%a0
	jra .L16
.L69:
	mov3q.l #-1,-(%sp)
	move.l %d6,%a0
	pea -1(%a0)
	pea 42.w
	pea 5(%a0)
	mov3q.l #2,-(%sp)
	move.l %a6,-(%sp)
	jsr 1073816148
	lea (24,%sp),%sp
	jra .L29
.L70:
	mvs.b 1(%a0),%d5
	mvs.b 5(%a1),%d1
	cmp.l %d5,%d1
	jne .L32
	lea (say.2),%a0
	clr.l %d6
	move.l (%a0,%d0.l*4),%d0
	move.l %a2,%d5
	add.l #md_engines+12,%d3
	add.l #-29,%d5
	move.l %d0,-(%sp)
	mov3q.l #-1,-(%sp)
	move.l 44(%sp),-(%sp)
	pea 48.w
	move.l %a6,-(%sp)
	move.l #1074505846,-(%sp)
	jsr 1073818584
	lea (24,%sp),%sp
	jra .L35
.L71:
	clr.b %d1
	move.b %d1,48(%sp,%a0.l)
	tst.l %a0
	jne .L42
	addq.l #4,%a2
	moveq #74,%d0
	cmp.l %d4,%d0
	jeq .L72
.L49:
	moveq #74,%d4
	sub.l %a0,%a0
	move.l %d2,%a1
	jra .L36
.L66:
	mvz.b md_focus+218,%d7
	cmp.l %d6,%d7
	jhi .L18
	move.l %d6,%d5
	jra .L22
.L48:
	move.b 39(%sp),%d0
	move.b %d0,md_focus+219
	mvz.b %d0,%d0
	jra .L19
.L68:
	mvz.b md_focus+219,%d0
	cmp.l %d6,%d0
	jls .L45
	mov3q.l #5,%d0
	cmp.l %d6,%d0
	jcs .L46
	clr.b %d1
	lea (-20,%a2),%a0
	clr.l %d0
	move.l %d6,%d5
	clr.l %d7
	move.l %a0,36(%sp)
	move.l %a0,%d6
	move.b %d1,md_focus+219
	jra .L26
.L45:
	move.l %d6,%d5
	jra .L19
.L46:
	move.b 39(%sp),%d0
	move.l %d6,%d5
	move.b %d0,md_focus+219
	mvz.b %d0,%d0
	jra .L19
	.size	eng_draw, .-eng_draw
	.align	2
	.globl	md_eng_close
	.type	md_eng_close, @function
md_eng_close:
	tst.l md_focus+208
	jeq .L73
	pea md_focus+208
	jsr 1074093492
	pea md_eng_layer
	jsr 1073943660
	clr.l md_preview
	moveq #1,%d0
	mov3q.l #1,1187497772
	addq.l #8,%sp
	move.b %d0,md_ui+32
.L73:
	rts
	.size	md_eng_close, .-md_eng_close
	.align	2
	.globl	md_ui_select
	.type	md_ui_select, @function
md_ui_select:
	moveq #15,%d1
	mov3q.l #1,%d0
	and.l 4(%sp),%d1
	lsl.l %d1,%d0
	move.b %d1,md_ui
	or.l %d0,md_trig_request
	rts
	.size	md_ui_select, .-md_ui_select
	.align	2
	.globl	md_eng_key
	.type	md_eng_key, @function
md_eng_key:
	lea (-44,%sp),%sp
	move.l 48(%sp),%d0
	movem.l #1036,(%sp)
	move.l 52(%sp),%d1
	moveq #15,%d2
	mov3q.l #1,%d3
	cmp.l %d0,%d2
	jcc .L139
	cmp.l %d1,%d3
	jeq .L85
	subq.l #2,%d1
	tst.l %d1
	jne .L79
	moveq #51,%d3
	cmp.l %d0,%d3
	jeq .L86
	moveq #32,%d1
	cmp.l %d0,%d1
	jeq .L87
.L79:
	movem.l (%sp),#1036
	lea (44,%sp),%sp
	rts
.L85:
	moveq #50,%d2
	cmp.l %d0,%d2
	jeq .L88
	jcs .L89
	moveq #33,%d3
	cmp.l %d0,%d3
	jeq .L90
	moveq #49,%d2
	cmp.l %d0,%d2
	jne .L140
	move.b 1175456541,%d2
	move.b md_ui,%d0
	mvz.b md_focus+217,%d3
	move.l %d3,%a0
	moveq #15,%d3
	add.l #md_focus,%a0
	move.w %d2,%a1
	and.l %d0,%d3
	move.b 220(%a0),%d2
	move.l %d3,26(%sp)
	move.b %d2,43(%sp)
	move.l %d3,%d0
	moveq #32,%d2
	move.l %a1,%d3
	and.l %d2,%d3
	move.b %d3,37(%sp)
	move.l %a1,%d3
	btst #5,%d3
	jne .L141
	moveq #63,%d1
	moveq #12,%d2
	and.l md_kit_index,%d1
	mvz.w #192,%d3
	muls.l %d0,%d2
	lea md_kits,%a1
	mvz.b 43(%sp),%d0
	move.l %d2,%a0
	muls.l %d1,%d3
	move.l %d3,38(%sp)
	add.l %d2,%d3
	mvz.b (%a1,%d3.l),%d2
	cmp.l %d2,%d0
	jeq .L104
	move.l %d0,30(%sp)
	tst.l %d0
	jne .L142
	move.l 26(%sp),%d2
	moveq #12,%d3
	move.w %d1,%d0
	muls.l %d3,%d2
	move.w 32(%sp),%d1
	add.l 38(%sp),%a0
	move.l %d2,26(%sp)
	move.b 37(%sp),%d2
	mulu.w #192,%d0
	mulu.w #52,%d1
	move.b %d2,(%a1,%a0.l)
	move.l %d0,%a0
	add.l #md_kits+4,%a0
	move.l %d1,%a1
	add.l #md_engines+8,%d1
	add.l 26(%sp),%a0
	add.l #md_engines,%a1
	tst.l 30(%sp)
	jne .L107
.L106:
	clr.b (%a0)+
	addq.l #1,%a1
	cmp.l %d1,%a1
	jne .L106
.L104:
	tst.l md_focus+208
	jeq .L79
	moveq #1,%d3
	pea md_focus+208
	jsr 1074093492
	pea md_eng_layer
	jsr 1073943660
	addq.l #8,%sp
	clr.l md_preview
	mov3q.l #1,1187497772
	move.b %d3,md_ui+32
	movem.l (%sp),#1036
	lea (44,%sp),%sp
	rts
.L139:
	lsl.l %d0,%d3
	mov3q.l #1,%d2
	move.l %d3,%a0
	cmp.l %d1,%d2
	jeq .L143
	move.l md_focus+212,%d3
	move.l %a0,%d2
	and.l %d3,%d2
	move.l %d3,26(%sp)
	tst.l %d2
	jeq .L82
	tst.l %d1
	jne .L79
	move.l %a0,%d0
	not.l %d0
	and.l %d3,%d0
	movem.l (%sp),#1036
	move.l %d0,md_focus+212
	lea (44,%sp),%sp
	rts
.L143:
	tst.l 1175263030
	jne .L82
	move.b 1175456541,%d3
	move.w %d3,%a1
	move.l %a1,%d2
	btst #5,%d2
	jeq .L144
.L82:
	movem.l (%sp),#1036
	move.l %d1,52(%sp)
	move.l %d0,48(%sp)
	lea (44,%sp),%sp
	jmp 1074138336
.L86:
	mvz.b md_focus+217,%d0
	subq.l #1,%d0
	tst.l %d0
	jlt .L145
	mvz.b md_focus+218,%d1
	cmp.l %d0,%d1
	jgt .L99
.L134:
	move.l %d1,%d0
	subq.l #1,%d0
.L99:
	move.b %d0,md_focus+217
.L133:
	movem.l (%sp),#1036
	lea (44,%sp),%sp
	jra eng_draw
.L140:
	moveq #32,%d3
	cmp.l %d0,%d3
	jne .L79
.L87:
	mvz.b md_focus+217,%d0
	mvz.b md_focus+218,%d1
	addq.l #1,%d0
	cmp.l %d0,%d1
	jgt .L99
	move.l %d1,%d0
	subq.l #1,%d0
	jra .L99
.L88:
	tst.l md_focus+208
	jeq .L79
	pea md_focus+208
	jsr 1074093492
	pea md_eng_layer
	jsr 1073943660
	addq.l #8,%sp
	moveq #1,%d0
	clr.l md_preview
	movem.l (%sp),#1036
	mov3q.l #1,1187497772
	move.b %d0,md_ui+32
	lea (44,%sp),%sp
	rts
.L89:
	moveq #51,%d1
	cmp.l %d0,%d1
	jeq .L86
	moveq #52,%d2
	cmp.l %d0,%d2
	jne .L79
	mvz.b md_focus+217,%d0
	move.l %d0,%a1
	add.l #md_focus+220,%a1
.L97:
	move.l %a1,%d1
	subq.l #1,%a1
	tst.l %d0
	jeq .L96
	move.l %d1,%a2
	mvz.b -1(%a2),%d3
	mvz.b (%a2),%d1
	lsr.l #4,%d3
	lsr.l #4,%d1
	cmp.l %d3,%d1
	jne .L146
	subq.l #1,%d0
	jra .L97
.L90:
	mvz.b md_focus+218,%d1
	mvz.b md_focus+217,%d0
	move.l %d1,%a1
	cmp.l %d0,%d1
	jls .L133
	move.l %d0,%a0
	add.l #md_focus,%a0
	mvz.b 220(%a0),%d1
	lea md_focus+220,%a0
	lsr.l #4,%d1
	move.l %d1,26(%sp)
.L101:
	mvz.b (%a0,%d0.l),%d1
	lsr.l #4,%d1
	cmp.l 26(%sp),%d1
	jne .L147
	addq.l #1,%d0
	cmp.l %a1,%d0
	jcs .L101
	movem.l (%sp),#1036
	lea (44,%sp),%sp
	jra eng_draw
.L144:
	tst.l 1175262960
	jne .L82
	move.l %a0,%d3
	moveq #12,%d1
	or.l %d3,md_trig_request
	muls.l %d0,%d1
	move.b %d0,md_ui
	moveq #63,%d0
	mvz.w #192,%d2
	lea md_kits,%a0
	or.l %d3,md_focus+212
	and.l md_kit_index,%d0
	muls.l %d2,%d0
	add.l %d1,%d0
	mvz.b (%a0,%d0.l),%d0
	move.l %d0,-(%sp)
	jsr choice_of
	addq.l #4,%sp
	move.b %d0,md_focus+217
	tst.l md_preview
	jge .L133
	movem.l (%sp),#1036
	clr.l md_preview
	lea (44,%sp),%sp
	jra eng_draw
.L141:
	move.l %d0,%d2
	lsl.l #8,%d2
	mvz.b 43(%sp),%d3
	lsl.l %d0,%d1
	move.l %d2,%d0
	or.l %d3,%d0
	movem.l (%sp),#1036
	bset #31,%d0
	move.l %d0,md_preview
	or.l %d1,md_trig_request
	lea (44,%sp),%sp
	rts
.L145:
	mvz.b md_focus+218,%d1
	clr.l %d0
	cmp.l %d0,%d1
	jgt .L99
	jra .L134
.L107:
	move.b 4(%a1),(%a0)+
	addq.l #1,%a1
	cmp.l %d1,%a1
	jeq .L104
	move.b 4(%a1),(%a0)+
	addq.l #1,%a1
	cmp.l %d1,%a1
	jne .L107
	jra .L104
.L142:
	move.l %d0,-(%sp)
	move.l %d1,26(%sp)
	move.l %a0,22(%sp)
	move.l %a1,18(%sp)
	jsr md_engine_ok
	addq.l #4,%sp
	move.l 22(%sp),%d1
	move.l 18(%sp),%a0
	move.l 14(%sp),%a1
	tst.l %d0
	jeq .L112
	move.l 26(%sp),%d2
	moveq #12,%d3
	move.b 43(%sp),37(%sp)
	move.w %d1,%d0
	muls.l %d3,%d2
	move.w 32(%sp),%d1
	add.l 38(%sp),%a0
	move.l %d2,26(%sp)
	move.b 37(%sp),%d2
	mulu.w #192,%d0
	mulu.w #52,%d1
	move.b %d2,(%a1,%a0.l)
	move.l %d0,%a0
	add.l #md_kits+4,%a0
	move.l %d1,%a1
	add.l #md_engines+8,%d1
	add.l 26(%sp),%a0
	add.l #md_engines,%a1
	tst.l 30(%sp)
	jeq .L106
	jra .L107
.L96:
	clr.b %d0
	move.b %d0,md_focus+217
	jra .L133
.L147:
	cmp.l %a1,%d0
	jcc .L133
	move.b %d0,md_focus+217
	jra .L133
.L146:
	move.l %d0,%a1
	add.l #md_focus+219,%d0
	subq.l #1,%a1
.L100:
	move.l %d0,%d1
	subq.l #1,%d0
	tst.l %a1
	jeq .L96
	move.l %d1,%a2
	mvz.b -1(%a2),%d2
	mvz.b (%a2),%d1
	lsr.l #4,%d2
	lsr.l #4,%d1
	cmp.l %d2,%d1
	jne .L148
	subq.l #1,%a1
	jra .L100
.L148:
	move.w %a1,%d0
	move.b %d0,md_focus+217
	jra .L133
.L112:
	move.l 26(%sp),%d2
	moveq #12,%d3
	move.w %d1,%d0
	clr.l 30(%sp)
	muls.l %d3,%d2
	move.w 32(%sp),%d1
	add.l 38(%sp),%a0
	move.l %d2,26(%sp)
	move.b 37(%sp),%d2
	mulu.w #192,%d0
	mulu.w #52,%d1
	move.b %d2,(%a1,%a0.l)
	move.l %d0,%a0
	add.l #md_kits+4,%a0
	move.l %d1,%a1
	add.l #md_engines+8,%d1
	add.l 26(%sp),%a0
	add.l #md_engines,%a1
	tst.l 30(%sp)
	jeq .L106
	jra .L107
	.size	md_eng_key, .-md_eng_key
	.align	2
	.globl	md_eng_level
	.type	md_eng_level, @function
md_eng_level:
	move.l 8(%sp),%d0
	tst.l %d0
	jeq .L149
	jle .L154
	mvz.b md_focus+217,%d1
	mov3q.l #1,%d0
	add.l %d1,%d0
	tst.l %d0
	jlt .L157
.L152:
	mvz.b md_focus+218,%d1
	cmp.l %d0,%d1
	jgt .L153
	move.l %d1,%d0
	subq.l #1,%d0
.L153:
	move.b %d0,md_focus+217
	jra eng_draw
.L149:
	rts
.L154:
	mvz.b md_focus+217,%d1
	mov3q.l #-1,%d0
	add.l %d1,%d0
	tst.l %d0
	jge .L152
.L157:
	clr.l %d0
	jra .L152
	.size	md_eng_level, .-md_eng_level
	.align	2
	.globl	md_layer_key
	.type	md_layer_key, @function
md_layer_key:
	lea (-16,%sp),%sp
	moveq #16,%d1
	move.l %a2,-(%sp)
	move.l %d2,-(%sp)
	move.l 28(%sp),%a0
	move.l %a0,%d0
	move.l 32(%sp),%a1
	cmp.l %a0,%d1
	jcc .L159
	moveq #16,%d0
.L159:
	mov3q.l #1,%d1
	lsl.l %d0,%d1
	mov3q.l #1,%d2
	cmp.l %a1,%d2
	jeq .L180
	move.l md_focus+204,%d2
	move.l %d2,16(%sp)
	and.l %d1,%d2
	tst.l %d2
	jne .L181
	tst.l %a1
	jne .L172
	lea md_focus,%a2
	mov3q.l #1,%d1
	move.l %a2,16(%sp)
.L163:
	move.l %d0,%a2
	mov3q.l #1,%d2
	lea (%a2,%d0.l*2),%a2
	add.l %a2,%d1
	move.l 16(%sp),%a2
	move.l (%a2,%d1.l*4),%d0
	move.l %d0,%d1
	addq.l #1,%d1
	cmp.l %d1,%d2
	jcc .L158
.L182:
	move.l %a1,32(%sp)
	move.l %a0,28(%sp)
	move.l (%sp)+,%d2
	move.l %d0,%a1
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	jmp (%a1)
.L172:
	lea md_focus,%a2
	mov3q.l #2,%d1
	move.l %a2,16(%sp)
	move.l %d0,%a2
	mov3q.l #1,%d2
	lea (%a2,%d0.l*2),%a2
	add.l %a2,%d1
	move.l 16(%sp),%a2
	move.l (%a2,%d1.l*4),%d0
	move.l %d0,%d1
	addq.l #1,%d1
	cmp.l %d1,%d2
	jcs .L182
.L158:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	rts
.L181:
	tst.l %a1
	jne .L158
	not.l %d1
	and.l 16(%sp),%d1
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	move.l %d1,md_focus+204
	lea (16,%sp),%sp
	rts
.L180:
	lea md_focus,%a2
	move.l %a2,16(%sp)
	tst.b md_focus+216.l
	jeq .L161
	tst.l md_layer
	jne .L161
	tst.l 1175263030
	jne .L161
	move.b 1175456541,%d2
	btst #5,%d2
	jne .L161
	moveq #15,%d2
	cmp.l %a0,%d2
	jcs .L183
	tst.l 1175262960
	jne .L161
	move.l %a0,%d2
	move.l %a1,%d0
	lsl.l %d2,%d0
	move.b %d2,md_ui
	move.l (%sp)+,%d2
	or.l %d1,md_focus+204
	move.l (%sp)+,%a2
	or.l %d0,md_trig_request
	lea (16,%sp),%sp
	rts
.L161:
	clr.l %d1
	jra .L163
.L183:
	moveq #1,%d0
	swap %d0
	or.l %d0,md_focus+204
	tst.l md_focus+208
	jne .L158
	tst.b md_focus+218.l
	jeq .L184
.L167:
	move.b md_ui,%d0
	moveq #63,%d1
	moveq #15,%d2
	and.l md_kit_index,%d1
	lea md_kits,%a0
	and.l %d2,%d0
	mvz.w #192,%d2
	muls.l %d2,%d1
	moveq #12,%d2
	muls.l %d2,%d0
	add.l %d1,%d0
	mvz.b (%a0,%d0.l),%d0
	move.l %d0,-(%sp)
	jsr choice_of
	pea md_eng_close
	mov3q.l #3,-(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	pea 64.w
	pea 118.w
	clr.l md_focus+212
	move.b %d0,md_focus+217
	st %d0
	move.b %d0,md_focus+219
	jsr 1074102940
	lea (28,%sp),%sp
	move.l %d0,md_focus+208
	tst.l %d0
	jeq .L158
	move.l %d0,-(%sp)
	jsr 1074097996
	pea md_eng_layer
	clr.l md_eng_layer
	jsr 1073943700
	addq.l #8,%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	jra eng_draw
.L184:
	clr.b %d0
	mov3q.l #1,%d1
	move.b %d0,md_focus+220
.L168:
	move.l %d1,-(%sp)
	move.l %d1,16(%sp)
	move.l %a1,12(%sp)
	jsr md_engine_ok
	addq.l #4,%sp
	move.l 12(%sp),%d1
	move.l 8(%sp),%a1
	tst.l %d0
	jeq .L169
	lea md_focus+220,%a0
	move.b %d1,(%a0,%a1.l)
	addq.l #1,%a1
.L169:
	addq.l #1,%d1
	moveq #73,%d0
	cmp.l %d1,%d0
	jne .L168
	move.w %a1,%d1
	move.b %d1,md_focus+218
	jra .L167
	.size	md_layer_key, .-md_layer_key
	.align	2
	.globl	md_ui_tick
	.type	md_ui_tick, @function
md_ui_tick:
	lea (-12,%sp),%sp
	move.l md_ui_md_track,%d0
	movem.l #1036,(%sp)
	move.b md_focus+216,%d1
	mov3q.l #3,%d2
	cmp.l %d0,%d2
	jcs .L186
	mvz.b 269161676,%d2
	cmp.l %d2,%d0
	jeq .L203
.L186:
	tst.b %d1
	jeq .L204
.L189:
	tst.l md_focus+204
	jne .L205
	clr.b %d3
	pea md_layer
	jsr 1073943660
	addq.l #4,%sp
	move.b %d3,md_focus+216
.L185:
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
.L204:
	movem.l (%sp),#1036
	move.l 1175262812,%d0
	lea (12,%sp),%sp
	rts
.L203:
	tst.b 1187502296.l
	jne .L186
	tst.b %d1
	jne .L187
	move.l 1175262812,%a0
	tst.l %a0
	jeq .L185
	move.l (%a0),%d1
	tst.l %d1
	jne .L185
	lea md_focus,%a0
	move.l #1187502302,%d2
.L194:
	moveq #16,%d3
	cmp.l %d1,%d3
	sne %d0
	move.l %d2,%a2
	neg.l %d0
	tst.b %d0
	jne .L193
	move.l #1187503478,%a2
.L193:
	move.l %a2,%a1
	addq.l #1,%d1
	move.l (%a1)+,(%a0)
	move.l (%a1),4(%a0)
	move.l 8(%a2),8(%a0)
	add.l #24,%d2
	lea (12,%a0),%a0
	moveq #17,%d0
	cmp.l %d1,%d0
	jne .L194
	moveq #1,%d2
	lea md_layer,%a2
	move.l %a2,-(%sp)
	clr.l md_layer
	jsr 1073943700
	addq.l #4,%sp
	move.b %d2,md_focus+216
.L191:
	tst.l (%a2)
	jne .L185
	tst.b md_ui+32.l
	jeq .L185
	clr.b %d3
	move.b %d3,md_ui+32
	jsr 1074059136
	mov3q.l #-1,-(%sp)
	jsr 1074059592
	addq.l #4,%sp
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
.L187:
	lea md_layer,%a2
	tst.l (%a2)
	jne .L189
	jra .L191
.L205:
	lea md_layer,%a2
	jra .L191
	.size	md_ui_tick, .-md_ui_tick
	.section	.rodata.str1.1
.LC3:
	.string	"---"
.LC4:
	.string	"SYN"
.LC5:
	.string	"SYNTH"
.LC6:
	.string	"VOL"
.LC7:
	.string	"PAN"
	.text
	.align	2
	.globl	md_ui_frame
	.type	md_ui_frame, @function
md_ui_frame:
	lea (-92,%sp),%sp
	movem.l #31996,(%sp)
	mov3q.l #3,%d2
	mvz.w #6322,%d4
	sub.l %a3,%a3
	clr.l %d3
	move.b 269161679,%d0
	move.l 1187521622,%d1
	add.l #585088,%d1
	move.l %d1,%a0
	and.l %d2,%d0
	muls.l %d0,%d4
	add.l %d4,%a0
	move.l %a0,%d1
	move.l %a0,%d2
	move.l %d4,58(%sp)
	move.l %a0,54(%sp)
	add.l #34,%d1
	add.l #60,%d2
.L209:
	move.l %d1,%a0
	add.l %d3,%a0
	mvz.b (%a0),%d0
	subq.l #1,%d0
	tst.l %d0
	jeq .L315
.L207:
	addq.l #1,%d3
	lea (30,%a3),%a3
	mov3q.l #4,%d0
	cmp.l %d3,%d0
	jne .L209
	st %d2
	mov3q.l #-1,md_ui_md_track
	move.l #1074607314,%d1
	clr.l md_ui_md_type
	move.l %d1,1074618188
	clr.l %d0
	move.b %d2,md_ui+33
	move.b %d2,md_ui+6
	move.b %d2,md_ui+1
	movem.l (%sp),#31996
	lea (92,%sp),%sp
	rts
.L315:
	lea (%a3,%d2.l),%a1
	moveq #77,%d5
	mvz.b (%a1),%d0
	cmp.l %d0,%d5
	jne .L207
	mvz.b 1(%a1),%d0
	moveq #68,%d4
	cmp.l %d0,%d4
	jne .L207
	mvz.b 2(%a1),%d0
	subq.l #1,%d0
	tst.l %d0
	jne .L207
	move.b md_ui,%d0
	moveq #80,%d1
	move.l %d3,md_ui_md_track
	moveq #63,%d4
	move.l %a0,md_ui_md_type
	moveq #15,%d5
	and.l md_kit_index,%d4
	moveq #32,%d2
	lea md_kits,%a0
	lea md_ui_name+4,%a1
	move.l 58(%sp),%a5
	add.l #269110990,%a5
	move.l %a5,80(%sp)
	and.l %d5,%d0
	move.b %d1,md_ui_name
	mvz.w #192,%d1
	moveq #10,%d5
	move.b %d2,md_ui_name+3
	muls.l %d1,%d4
	move.l %d0,%d1
	addq.l #1,%d1
	remu.l %d5,%d2:%d1
	divu.l %d5,%d1
	moveq #12,%d5
	muls.l %d5,%d0
	add.l #48,%d2
	move.b %d2,md_ui_name+2
	add.l #48,%d1
	add.l %d4,%d0
	move.b %d1,md_ui_name+1
	mvz.b (%a0,%d0.l),%d0
	mulu.w #52,%d0
	move.l %d0,%a0
	add.l #md_engines+46,%a0
	move.l %a0,%d1
	addq.l #6,%d1
.L208:
	move.b (%a0)+,%d0
	jne .L211
	moveq #32,%d0
.L211:
	move.b %d0,(%a1)+
	cmp.l %a0,%d1
	jne .L208
	move.b md_ui,%d4
	move.l md_kit_index,%d0
	moveq #63,%d1
	clr.b %d5
	and.l md_kit_index,%d1
	move.l %d0,76(%sp)
	moveq #15,%d0
	lea md_kits,%a1
	mvz.b md_ui+1,%d2
	and.l %d4,%d0
	mvz.w #192,%d4
	move.b %d5,md_ui_name+10
	moveq #12,%d5
	muls.l %d1,%d4
	muls.l %d0,%d5
	move.l %d0,62(%sp)
	move.l %d4,70(%sp)
	move.l %d5,%a0
	add.l %d4,%a0
	move.b (%a1,%a0.l),%d4
	move.l %d5,66(%sp)
	move.b %d4,75(%sp)
	cmp.l %d0,%d2
	jne .L316
	mvz.b md_ui+2,%d0
	cmp.l %d0,%d3
	jne .L311
	mvz.b md_ui+3,%d0
	cmp.l 76(%sp),%d0
	jne .L311
	mvz.b md_ui+4,%d2
	mvz.b 75(%sp),%d0
	cmp.l %d2,%d0
	jne .L212
	mvz.b md_ui+5,%d4
	cmp.l %d4,%d2
	jeq .L213
.L212:
	move.l #1074606414,%a1
	sub.l #md_ui,%a1
	lea md_ui+40,%a0
.L214:
	move.b (%a1,%a0.l),%d1
	move.b %d1,(%a0)+
	cmp.l #md_ui+498,%a0
	jne .L214
	lea .LC4,%a0
	lea md_ui+100,%a1
.L215:
	move.b (%a0)+,(%a1)+
	cmp.l #.LC4+5,%a0
	jne .L215
	clr.b %d1
	lea .LC5,%a0
	lea md_ui+105,%a1
	move.b %d1,md_ui+105
.L216:
	move.b (%a0)+,(%a1)+
	cmp.l #.LC5+6,%a0
	jne .L216
	mulu.w #52,%d0
	lea md_ui+202,%a0
	moveq #78,%d4
	moveq #-32,%d5
	clr.l %d6
	clr.l 50(%sp)
	clr.l %d1
	lea md_ui+190,%a4
	move.l %d0,%a2
	move.l %d0,%a5
	add.l #md_engines+12,%a2
	add.l #md_engines,%a5
.L229:
	mov3q.l #7,%d2
	cmp.l %d1,%d2
	jcs .L218
.L319:
	move.b 4(%a5,%d1.l),%d7
	move.l %a2,%a6
	tst.b (%a2)
	jeq .L280
	move.l %d4,%a1
	mov3q.l #1,%d2
	add.l #md_ui+40,%a1
	clr.l %d0
	move.l %d1,46(%sp)
.L225:
	mov3q.l #3,%d1
	cmp.l %d0,%d1
	jcs .L222
.L317:
	move.b (%a6,%d0.l),(%a1)+
	addq.l #1,%d0
	mov3q.l #3,%d1
	cmp.l %d0,%d1
	jcc .L317
.L222:
	clr.b (%a1)
	subq.l #5,%d0
	tst.l %d0
	jeq .L224
.L318:
	addq.l #1,%a1
	mov3q.l #5,%d0
	clr.b (%a1)
	subq.l #5,%d0
	tst.l %d0
	jne .L318
.L224:
	clr.b %d0
	move.l 46(%sp),%d1
	move.b %d7,(%a4,%d1.l)
	clr.b (%a0)
	move.b %d0,1(%a0)
	move.b %d0,2(%a0)
	move.b %d0,3(%a0)
	move.b %d0,48(%a0)
	move.b %d0,49(%a0)
	move.b %d0,50(%a0)
	moveq #-128,%d0
	move.b %d0,51(%a0)
	clr.b %d0
	move.b %d0,96(%a0)
	move.b %d0,97(%a0)
	move.b %d0,98(%a0)
	move.b %d0,99(%a0)
	move.b %d0,144(%a0)
	move.b %d0,145(%a0)
	move.b %d0,146(%a0)
	move.b %d0,147(%a0)
	mov3q.l #7,%d0
	cmp.l %d1,%d0
	jcs .L226
	mvz.w %d1,%d0
	addq.l #4,%d5
	addq.l #4,%a0
	addq.l #1,%d1
	lsl.l #2,%d0
	addq.l #6,%d4
	addq.l #4,%a2
	lsl.l %d0,%d2
	or.l %d2,%d6
	mov3q.l #7,%d2
	cmp.l %d1,%d2
	jcc .L319
.L218:
	moveq #11,%d0
	cmp.l %d1,%d0
	jeq .L320
.L220:
	move.l %d4,%a1
	clr.l %d2
	clr.b %d7
	lea .LC3,%a6
	add.l #md_ui+40,%a1
	clr.l %d0
	move.l %d1,46(%sp)
	jra .L225
.L280:
	move.l %d4,%a1
	clr.l %d2
	lea .LC3,%a6
	add.l #md_ui+40,%a1
	clr.l %d0
	move.l %d1,46(%sp)
	jra .L225
.L320:
	move.l #md_burn_build,%d2
	tst.l %d2
	jeq .L220
	lea (page2.1),%a1
	mov3q.l #1,%d2
	move.l (%a1,%d5.l),%a6
	clr.b %d7
	move.l %d4,%a1
	clr.l %d0
	add.l #md_ui+40,%a1
	move.l %d1,46(%sp)
	jra .L225
.L226:
	lsl.l %d5,%d2
	addq.l #1,%d1
	or.l %d2,50(%sp)
	moveq #12,%d2
	cmp.l %d1,%d2
	jeq .L228
	addq.l #4,%d5
	addq.l #4,%a0
	addq.l #6,%d4
	addq.l #4,%a2
	jra .L229
.L228:
	moveq #24,%d5
	moveq #63,%d0
	move.l %d6,%d2
	lsr.l %d5,%d2
	move.l %d6,%d1
	move.l #md_ui+96,%d4
	clr.w %d1
	swap %d1
	move.l %d4,md_desc_p
	move.b %d2,md_ui+494
	clr.w %d4
	move.b 75(%sp),%d2
	lea (52,%sp),%a0
	and.l md_kit_index,%d0
	move.w %d6,md_ui+496
	move.w (%a0),md_ui+492
	lea md_ui+10,%a1
	move.b %d1,md_ui+495
	move.l 62(%sp),%d1
	move.l %a1,%a0
	move.w %d4,md_ui+490
	move.b %d2,md_ui+5
	moveq #12,%d4
	mulu.w #192,%d0
	muls.l %d4,%d1
	add.l #md_kits+4,%d0
	move.l %d0,%a2
	add.l %d1,%a2
.L230:
	move.b (%a2)+,(%a0)+
	cmp.l #md_ui+18,%a0
	jne .L230
	clr.b %d5
	clr.w %d0
	move.l #md_burn_build,%d1
	move.b %d5,md_ui+20
	move.w %d0,md_ui+18
	tst.l %d1
	jeq .L281
	moveq #127,%d1
	and.l md_burn,%d1
	move.w %d3,%d0
	move.l 54(%sp),%a0
	move.l 54(%sp),%a5
	move.l 58(%sp),%a2
	add.l #269111038,%a2
	lea 48(%a0,%a3.l),%a6
	lea (474,%a5),%a5
	sub.l %a0,%a0
	add.l %a3,%a5
	add.l %a3,%a2
	move.b %d1,md_ui+21
	mulu.w #72,%d0
	move.l %d0,%a4
	add.l #-2147481584,%a4
.L235:
	move.b (%a1)+,%d1
	mov3q.l #5,%d2
	cmp.l %a0,%d2
	jcs .L321
.L232:
	lea (-1,%a1),%a3
	mov3q.l #5,%d2
	move.b (%a3),(%a6,%a0.l)
	move.b -1(%a1),(%a2)+
	move.b (%a3),(%a4,%a0.l)
	addq.l #1,%a0
	move.b (%a1)+,%d1
	cmp.l %a0,%d2
	jcc .L232
.L321:
	move.b %d1,(%a5,%a0.l)
	lea (-1,%a1),%a3
	addq.l #1,%a2
	moveq #12,%d1
	move.b -1(%a1),425(%a2)
	move.b (%a3),26(%a4,%a0.l)
	addq.l #1,%a0
	cmp.l %a0,%d1
	jne .L235
	move.l 66(%sp),%d1
	lea md_kits,%a1
	lea (65,%sp),%a5
	add.l 70(%sp),%d1
	lea (79,%sp),%a0
	move.b (%a5),md_ui+1
	move.b %d3,md_ui+2
	lea (%a1,%d1.l),%a3
	moveq #1,%d1
	move.b (%a0),md_ui+3
	move.b (%a3),md_ui+4
	move.b %d1,md_ui+32
.L236:
	mvz.b 269161676,%d1
	cmp.l %d1,%d3
	jeq .L322
.L244:
	move.l #1074607314,%d1
	move.l %d1,1074618188
	tst.l md_amp_desc_p
	jeq .L323
.L247:
	move.b md_ui,%d2
	move.w %d3,%d1
	move.l %d0,%a2
	moveq #15,%d0
	moveq #63,%d6
	moveq #63,%d5
	and.l md_kit_index,%d6
	mvz.b md_ui+33,%d7
	move.l 54(%sp),%a3
	add.l #-2147481572,%a2
	move.l 80(%sp),%a0
	and.l md_kit_index,%d5
	and.l %d0,%d2
	move.l %d3,%d0
	lsl.l #6,%d0
	mulu.w #24,%d1
	add.l #288,%d1
	mvz.b %d2,%d4
	or.l %d6,%d0
	move.b %d2,%d6
	add.l %d1,%a3
	add.l %d1,%a0
	cmp.l %d2,%d7
	jne .L265
.L331:
	mvz.b md_ui+34,%d1
	cmp.l %d0,%d1
	jne .L265
	moveq #12,%d4
	mulu.w #192,%d5
	muls.l %d4,%d2
	lea (slot.0),%a1
	lea md_ui+35,%a4
	lea (84,%sp),%a6
	move.l #slot.0+2,%d4
	move.l %a0,%d6
	add.l %d5,%d2
	move.l %d2,%d5
	add.l #md_kits+2,%d2
	add.l #md_kits+1,%d5
	move.l %d5,84(%sp)
	move.l %d2,88(%sp)
.L270:
	mvz.b (%a1)+,%d0
	mvz.b (%a4)+,%d2
	lea (%a3,%d0.l),%a5
	mvz.b (%a5),%d1
	cmp.l %d1,%d2
	jeq .L268
	move.b (%a5),-1(%a4)
	moveq #127,%d1
	move.l (%a6),%a0
	move.b (%a5),%d0
	and.l %d1,%d0
	move.b %d0,(%a0)
.L269:
	addq.l #4,%a6
	cmp.l %d4,%a1
	jne .L270
	move.b md_ui,%d4
	moveq #15,%d0
	and.l %d0,%d4
	move.b %d4,%d6
	mvz.b %d4,%d4
.L267:
	move.b -2147483646,%d7
	move.b -2147483644,%d5
	moveq #15,%d0
	mvz.b %d6,%d2
	mvz.b md_ui+6,%d1
	move.l %d2,50(%sp)
	mvz.w #36568,%d2
	move.l %d1,%a2
	and.l %d0,%d7
	and.l %d0,%d5
	move.l %d7,%d0
	lsl.l #4,%d0
	muls.l %d5,%d2
	mvz.b %d5,%d1
	move.l %d1,%a3
	move.l %d2,%a1
	move.w %d3,%d2
	add.l 1187521622,%a1
	add.l %d5,%d0
	mulu.w #2330,%d2
	add.l %d2,%a1
	cmp.l 50(%sp),%a2
	jne .L271
	mvz.b md_ui+7,%d1
	cmp.l %d1,%d3
	jne .L271
	mvz.b md_ui+8,%d1
	cmp.l %d7,%d1
	jne .L271
	mvz.b md_ui+9,%d1
	cmp.l %a3,%d1
	jeq .L272
.L271:
	moveq #48,%d1
	muls.l %d0,%d1
	lea md_ui+22,%a0
	clr.l %d0
	lea md_patterns,%a2
	move.l %d3,%a4
	add.l %d1,%d4
	add.l %d4,%d4
.L273:
	move.l %d0,%d1
	mov3q.l #3,%d3
	not.l %d1
	cmp.l %d0,%d3
	scc %d2
	and.l %d3,%d1
	move.l %d4,%a3
	mvs.b %d2,%d2
	lsl.l #3,%d1
	sub.l %d2,%a3
	move.l (%a2,%a3.l*4),%d2
	lsr.l %d1,%d2
	moveq #8,%d1
	move.b %d2,(%a1,%d0.l)
	move.b %d2,(%a0)+
	addq.l #1,%d0
	cmp.l %d0,%d1
	jne .L273
	move.l %a4,%d3
	move.b %d6,md_ui+6
	move.b %d3,md_ui+7
	move.b %d7,md_ui+8
	move.b %d5,md_ui+9
.L274:
	move.l %d3,%d0
	addq.l #1,%d0
.L335:
	movem.l (%sp),#31996
	lea (92,%sp),%sp
	rts
.L322:
	tst.l md_desc_p
	jeq .L244
	move.l md_desc_p,%d1
	move.l %d1,1074618188
	tst.l md_amp_desc_p
	jne .L247
.L323:
	lea md_amp_desc,%a0
	move.l #1074608464,%a1
	move.l #md_amp_desc+458,%d2
	sub.l %a0,%a1
.L248:
	move.b (%a1,%a0.l),%d1
	move.b %d1,(%a0)+
	cmp.l %d2,%a0
	jne .L248
	move.l #md_amp_desc+78,%d2
	clr.l %d4
	sub.l %a1,%a1
	lea .LC3,%a2
	mov3q.l #3,%d1
	lea .LC7,%a3
	lea .LC6,%a4
	cmp.l %a1,%d1
	jeq .L324
.L249:
	mov3q.l #4,%d5
	cmp.l %a1,%d5
	jeq .L325
	move.l %d2,%a0
	clr.l %d1
	mov3q.l #3,%d5
	cmp.l %d1,%d5
	jcs .L260
.L326:
	move.b (%a2,%d1.l),(%a0)+
	addq.l #1,%d1
	mov3q.l #3,%d5
	cmp.l %d1,%d5
	jcc .L326
.L260:
	clr.b (%a0)
	subq.l #5,%d1
	tst.l %d1
	jeq .L262
.L327:
	addq.l #1,%a0
	mov3q.l #5,%d1
	clr.b (%a0)
	subq.l #5,%d1
	tst.l %d1
	jne .L327
.L262:
	addq.l #1,%a1
	moveq #12,%d1
	cmp.l %a1,%d1
	jeq .L263
	addq.l #6,%d2
.L330:
	mov3q.l #3,%d1
	cmp.l %a1,%d1
	jne .L249
.L324:
	lea md_amp_desc+96,%a0
	clr.l %d1
	mov3q.l #3,%d5
	cmp.l %d1,%d5
	jcs .L250
.L328:
	move.b (%a4,%d1.l),(%a0)+
	addq.l #1,%d1
	mov3q.l #3,%d5
	cmp.l %d1,%d5
	jcc .L328
.L250:
	clr.b (%a0)
	subq.l #5,%d1
	tst.l %d1
	jeq .L252
.L329:
	addq.l #1,%a0
	mov3q.l #5,%d1
	clr.b (%a0)
	subq.l #5,%d1
	tst.l %d1
	jne .L329
.L252:
	moveq #100,%d1
	bset #12,%d4
	clr.l md_amp_desc+270
	addq.l #1,%a1
	move.b %d1,md_amp_desc+153
.L334:
	addq.l #6,%d2
	jra .L330
.L263:
	clr.b %d2
	move.l %d4,%d1
	lsr.l #8,%d4
	clr.w %d1
	swap %d1
	move.l %d0,%a2
	moveq #15,%d0
	moveq #63,%d6
	moveq #63,%d5
	move.b %d4,md_amp_desc+456
	move.l #md_amp_desc+56,%d4
	add.l #-2147481572,%a2
	move.l %d4,md_amp_desc_p
	and.l md_kit_index,%d6
	mvz.b md_ui+33,%d7
	move.b %d2,md_amp_desc+457
	clr.l md_amp_desc+450
	move.b %d2,md_amp_desc+454
	move.b md_ui,%d2
	move.b %d1,md_amp_desc+455
	move.w %d3,%d1
	move.l 54(%sp),%a3
	move.l 80(%sp),%a0
	and.l md_kit_index,%d5
	and.l %d0,%d2
	move.l %d3,%d0
	lsl.l #6,%d0
	mulu.w #24,%d1
	add.l #288,%d1
	mvz.b %d2,%d4
	or.l %d6,%d0
	move.b %d2,%d6
	add.l %d1,%a3
	add.l %d1,%a0
	cmp.l %d2,%d7
	jeq .L331
.L265:
	mvz.w #192,%d1
	muls.l %d1,%d5
	moveq #12,%d1
	muls.l %d4,%d1
	move.l %d1,%a1
	add.l %d5,%a1
	add.l #md_kits,%a1
	move.b 1(%a1),%d1
	move.b %d1,md_ui+35
	move.b %d1,3(%a2)
	move.b %d1,3(%a0)
	move.b %d1,3(%a3)
	move.b 2(%a1),%d1
	move.b %d1,md_ui+36
	move.b %d1,4(%a2)
	move.b %d1,4(%a0)
	move.b %d1,4(%a3)
	move.b %d2,md_ui+33
	move.b %d0,md_ui+34
	jra .L267
.L325:
	lea md_amp_desc+102,%a0
	clr.l %d1
	mov3q.l #3,%d5
	cmp.l %d1,%d5
	jcs .L256
.L332:
	move.b (%a3,%d1.l),(%a0)+
	addq.l #1,%d1
	mov3q.l #3,%d5
	cmp.l %d1,%d5
	jcc .L332
.L256:
	clr.b (%a0)
	subq.l #5,%d1
	tst.l %d1
	jeq .L258
.L333:
	addq.l #1,%a0
	mov3q.l #5,%d1
	clr.b (%a0)
	subq.l #5,%d1
	tst.l %d1
	jne .L333
.L258:
	bset #16,%d4
	addq.l #1,%a1
	jra .L334
.L311:
	move.l #1074606414,%a1
	mvz.b 75(%sp),%d0
	sub.l #md_ui,%a1
	lea md_ui+40,%a0
	jra .L214
.L316:
	move.l #1074606414,%a1
	mvz.b %d4,%d0
	sub.l #md_ui,%a1
	lea md_ui+40,%a0
	jra .L214
.L281:
	move.w %d3,%d0
	clr.b %d1
	move.l 54(%sp),%a0
	move.l 54(%sp),%a5
	move.l 58(%sp),%a2
	add.l #269111038,%a2
	lea 48(%a0,%a3.l),%a6
	lea (474,%a5),%a5
	sub.l %a0,%a0
	add.l %a3,%a5
	add.l %a3,%a2
	mulu.w #72,%d0
	move.b %d1,md_ui+21
	move.l %d0,%a4
	add.l #-2147481584,%a4
	jra .L235
.L268:
	move.l (%a6),%a0
	move.b (%a0),%d2
	mvz.b %d2,%d5
	cmp.l %d1,%d5
	jeq .L269
	move.b %d2,-1(%a4)
	move.b %d2,(%a2,%d0.l)
	move.l %d6,%a0
	move.b %d2,(%a0,%d0.l)
	move.b %d2,(%a5)
	jra .L269
.L272:
	moveq #-22,%d5
	clr.l %d7
	lea md_ui+22,%a2
	sub.l #md_ui,%d5
	move.l #md_ui+30,%d6
	add.l %a1,%d5
	move.l %a2,%a0
.L276:
	lea (%a0,%d5.l),%a1
	mvz.b (%a1),%d2
	mvz.b (%a0)+,%d1
	cmp.l %d2,%d1
	jeq .L275
	move.b (%a1),-1(%a0)
	mov3q.l #1,%d7
.L275:
	cmp.l %d6,%a0
	jne .L276
	tst.l %d7
	jeq .L274
	lea md_ui+26,%a0
	clr.l %d2
	clr.l %d1
.L277:
	lsl.l #8,%d1
	lsl.l #8,%d2
	mvz.b (%a2)+,%d6
	mvz.b 3(%a2),%d5
	or.l %d6,%d1
	or.l %d5,%d2
	cmp.l %a0,%a2
	jne .L277
	moveq #48,%d5
	muls.l %d5,%d0
	lea md_patterns,%a0
	add.l %d4,%d0
	lsl.l #3,%d0
	move.l %d2,(%a0,%d0.l)
	move.l %d1,4(%a0,%d0.l)
	move.l %d3,%d0
	addq.l #1,%d0
	jra .L335
.L213:
	move.l 62(%sp),%d0
	moveq #12,%d2
	mulu.w #192,%d1
	move.l 54(%sp),%a2
	muls.l %d2,%d0
	clr.l %d2
	lea (474,%a2),%a2
	lea md_ui+10,%a1
	add.l %a3,%a2
	move.l %d1,%a0
	add.l #md_kits,%a0
	add.l %d0,%a0
	sub.l 54(%sp),%a0
	sub.l %a3,%a0
	lea (-470,%a0),%a0
.L243:
	move.l %a1,%a3
	mov3q.l #5,%d4
	addq.l #1,%a1
	cmp.l %d2,%d4
	jcc .L237
	move.b (%a2),%d1
	mvz.b (%a3),%d0
	mvz.b %d1,%d4
	cmp.l %d4,%d0
	jeq .L238
	move.b %d1,-1(%a1)
	mov3q.l #7,%d5
	cmp.l %d2,%d5
	jcc .L278
	moveq #11,%d4
	cmp.l %d2,%d4
	jeq .L336
.L238:
	addq.l #1,%d2
	addq.l #1,%a2
	cmp.l #md_ui+22,%a1
	jne .L243
	move.w %d3,%d0
	mvz.b 269161676,%d1
	mulu.w #72,%d0
	cmp.l %d1,%d3
	jne .L244
	jra .L322
.L336:
	move.w %d3,%d0
	lea md_burn_build,%a0
	mulu.w #72,%d0
	tst.l %a0
	jeq .L236
	moveq #127,%d5
	and.l %d1,%d5
	move.l %d5,md_burn
	mvz.b 269161676,%d1
	cmp.l %d1,%d3
	jne .L244
	jra .L322
.L237:
	move.b -426(%a2),%d1
	mvz.b -1(%a1),%d0
	mvz.b %d1,%d4
	cmp.l %d4,%d0
	jeq .L238
	move.b %d1,-1(%a1)
.L278:
	moveq #127,%d0
	and.l %d0,%d1
	move.b %d1,(%a0,%a2.l)
	jra .L238
	.size	md_ui_frame, .-md_ui_frame
	.section	.rodata.str1.1
.LC8:
	.string	"GND  basic tones"
.LC9:
	.string	"TRX  analog drums"
.LC10:
	.string	"EFM  FM drums"
.LC11:
	.string	"P-I  physical models"
	.section	.rodata
	.align	2
	.type	CSWTCH.55, @object
	.size	CSWTCH.55, 20
CSWTCH.55:
	.long	.LC8
	.long	.LC9
	.long	.LC10
	.long	.LC0
	.long	.LC11
	.type	slot.0, @object
	.size	slot.0, 2
slot.0:
	.ascii	"\003\004"
	.section	.rodata.str1.1
.LC12:
	.string	"BURN"
	.section	.rodata
	.align	2
	.type	page2.1, @object
	.size	page2.1, 16
page2.1:
	.long	.LC3
	.long	.LC3
	.long	.LC3
	.long	.LC12
	.section	.rodata.str1.1
.LC13:
	.string	"Bass drum"
.LC14:
	.string	"Bass drum 2"
.LC15:
	.string	"Snare drum"
.LC16:
	.string	"Snare drum 2"
.LC17:
	.string	"Tom"
.LC18:
	.string	"Hand clap"
.LC19:
	.string	"Rim shot"
.LC20:
	.string	"Cowbell"
.LC21:
	.string	"Closed hi-hat"
.LC22:
	.string	"Open hi-hat"
.LC23:
	.string	"Hi-hat"
.LC24:
	.string	"Cymbal"
.LC25:
	.string	"Maracas"
.LC26:
	.string	"Claves"
.LC27:
	.string	"Ride cymbal"
.LC28:
	.string	"Crash cymbal"
.LC29:
	.string	"Sine"
.LC30:
	.string	"Noise"
.LC31:
	.string	"Impulse"
.LC32:
	.string	"Silent"
	.section	.rodata
	.align	2
	.type	say.2, @object
	.size	say.2, 80
say.2:
	.long	.LC13
	.long	.LC14
	.long	.LC15
	.long	.LC16
	.long	.LC17
	.long	.LC18
	.long	.LC19
	.long	.LC20
	.long	.LC21
	.long	.LC22
	.long	.LC23
	.long	.LC24
	.long	.LC25
	.long	.LC26
	.long	.LC27
	.long	.LC28
	.long	.LC29
	.long	.LC30
	.long	.LC31
	.long	.LC32
	.type	keys.3, @object
	.size	keys.3, 41
keys.3:
	.string	"BDB2SDS2XTCPRSCBCHOHHHCYMACLRCCCSNNSIM--"
	.weak	md_burn_build

| WP-D7: the UI task's display loop runs the MD focus once a tick. The
| loop's first two calls (0x4005221e: a PC-relative and an absolute jsr)
| are displaced; md_ui_tick then pushes or pops the MD's input layer.
        .text
        .global md_tick_hook
md_tick_hook:
        jsr     0x4005213c
        jsr     0x4007e940
        jsr     md_ui_tick
        jmp     0x40052228

| Explicit editor storage: the runtime copies a linked image and has no .bss.
| MdUi's first 10 bytes are selection/cache state; 0xff means unseen.
        .data
        .balign 4
        .global md_ui
md_ui:
        .byte 0,255,255,255,255,255,255,255,255,255
        .zero 23
        .byte 255,255                   | amp_sel, amp_key: unseen
        .zero 5
        .zero 0x1cc

| WP-D9: the MD track's AMP page and its address (0 until built).
        .global md_amp_desc, md_amp_desc_p
md_amp_desc:
        .zero 0x1cc
md_amp_desc_p:
        .long 0

| WP-D7: md_focus (MdFocus, md_ctl.h) and the MD's input layer, as the
| stock ones: {next, keys, encoders, 0, 0, -1, -1}. Key records, 26 B:
| {code, 0, press, release, repeat, sub-map, 0, delay, rate}; the trigs
| keep stock's repeat delay (16). No encoder records: the knobs reach the
| page underneath.
        .balign 4
        .global md_focus, md_layer
md_focus:
        .zero 296
md_layer:
        .long   0, md_layer_keys, md_layer_encs, 0, 0, -1, -1
md_layer_keys:
        .irp    k, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
        .byte   \k, 0
        .long   md_layer_key, md_layer_key, md_layer_key, 0, 0
        .word   16, 0
        .endr
        .byte   0x31, 0
        .long   md_layer_key, md_layer_key, 0, 0, 0
        .word   0, 0
        .byte   0xff, 0
        .long   0, 0, 0, 0, 0
        .word   0, 0
md_layer_encs:
        .byte   0xff, 0
        .long   0, 0, 0, 0, 0

| WP-D8: the ENGINE window's layer. Its keys: the trigs (a part), UP/DOWN
| (repeating, as TEMPO's), LEFT/RIGHT, YES, NO, and the page and track keys
| held while it is open; FUNC as TEMPO's layer has it (0x400bb4ec: press
| taken, stock's release, a sub-layer for FUNC + key: FUNC+YES previews).
| Knobs A-F are held (a null handler swallows the turn), LEVEL scrolls.
        .balign 4
        .global md_eng_layer
md_eng_layer:
        .long   0, md_eng_keys, md_eng_encs, 0, 0, -1, -1
md_eng_func:
        .long   0, md_eng_fkeys, 0, 0, 0, -1, -1
md_eng_keys:
        .irp    k, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
        .byte   \k, 0
        .long   md_eng_key, md_eng_key, md_eng_key, 0, 0
        .word   16, 0
        .endr
        .irp    k, 0x33, 0x20
        .byte   \k, 0
        .long   md_eng_key, 0, md_eng_key, 0, 0
        .word   15, 5
        .endr
        .irp    k, 0x34, 0x21, 0x31, 0x32, 0x22, 0x23, 0x24, 0x25, 0x26, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17
        .byte   \k, 0
        .long   md_eng_key, 0, 0, 0, 0
        .word   0, 0
        .endr
        .byte   0x2d, 0
        .long   0, 0x400568e4, 0, md_eng_func, 0
        .word   0, 0
        .byte   0xff, 0
        .long   0, 0, 0, 0, 0
        .word   0, 0
md_eng_fkeys:
        .irp    k, 0x33, 0x20
        .byte   \k, 0
        .long   md_eng_key, 0, md_eng_key, 0, 0
        .word   15, 5
        .endr
        .irp    k, 0x31, 0x32
        .byte   \k, 0
        .long   md_eng_key, 0, 0, 0, 0
        .word   0, 0
        .endr
        .byte   0xff, 0
        .long   0, 0, 0, 0, 0
        .word   0, 0
md_eng_encs:
        .irp    k, 0, 1, 2, 3, 4, 5
        .byte   \k, 0
        .long   0, 0, 0, 0, 0
        .endr
        .byte   6, 0
        .long   md_eng_level, 0, 0, 0, 0
        .byte   0xff, 0
        .long   0, 0, 0, 0, 0
