| Generated by modules/euclid/generate_control.py; edit control.c / hooks.s.
#NO_APP
	.file	"control.c"
	.text
	.align	2
	.globl	eu_clock_start
	.type	eu_clock_start, @function
eu_clock_start:
	move.l 4(%sp),%a0
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
	.size	eu_clock_start, .-eu_clock_start
	.align	2
	.globl	eu_clock_update
	.type	eu_clock_update, @function
eu_clock_update:
	move.l 4(%sp),%a0
	tst.l 16(%a0)
	jeq .L15
	move.l 8(%sp),%d0
	sub.l (%a0),%d0
	move.l 8(%sp),(%a0)
	add.l 8(%a0),%d0
	tst.l %d0
	jge .L16
	move.l 4(%a0),%d1
	subq.l #1,%d1
.L9:
	move.l %d1,%a1
	add.l #1323000,%d0
	subq.l #1,%d1
	tst.l %d0
	jlt .L9
	move.l %a1,4(%a0)
.L8:
	move.l %d0,8(%a0)
.L3:
	rts
.L15:
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
.L16:
	cmp.l #1322999,%d0
	jle .L8
	move.l 4(%a0),%d1
.L10:
	addq.l #1,%d1
	add.l #-1323000,%d0
	cmp.l #1322999,%d0
	jhi .L10
	move.l %d1,4(%a0)
	move.l %d0,8(%a0)
	jra .L3
	.size	eu_clock_update, .-eu_clock_update
	.align	2
	.globl	eu_random
	.type	eu_random, @function
eu_random:
	move.l %d2,-(%sp)
	moveq #13,%d2
	move.l 8(%sp),%a0
	move.l (%a0),%d1
	move.l %d1,%d0
	lsl.l %d2,%d0
	moveq #17,%d2
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d0,%d1
	move.l %d1,%d0
	lsl.l #5,%d0
	eor.l %d1,%d0
	move.l %d0,(%a0)
	lsr.l %d2,%d0
	move.l (%sp)+,%d2
	rts
	.size	eu_random, .-eu_random
	.align	2
	.globl	eu_pulse
	.type	eu_pulse, @function
eu_pulse:
	lea (-12,%sp),%sp
	move.l 24(%sp),%d0
	movem.l #28,(%sp)
	tst.l %d0
	jeq .L20
	move.l 16(%sp),%d1
	move.l 20(%sp),%d3
	muls.l %d0,%d1
	move.l %d1,%d2
	remu.l %d3,%d4:%d2
	cmp.l %d4,%d0
	shi %d0
	mvs.b %d0,%d0
	neg.l %d0
.L20:
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
	.size	eu_pulse, .-eu_pulse
	.align	2
	.globl	eu_process
	.type	eu_process, @function
eu_process:
	lea (-80,%sp),%sp
	movem.l #31996,(%sp)
	move.l 92(%sp),%a1
	move.l 84(%sp),%a0
	move.l 88(%sp),%a4
	move.b 4(%a1),%d2
	jeq .L79
	mvz.b %d2,%d2
	moveq #64,%d0
	cmp.l %d2,%d0
	jcs .L100
.L27:
	move.b 10(%a1),%d1
	move.b 5(%a1),%d3
	mov3q.l #3,%d4
	mvz.b %d1,%d6
	move.b %d1,70(%sp)
	move.w %d3,%a3
	move.l %d6,%d1
	cmp.l %d6,%d4
	jcc .L29
	mov3q.l #3,%d1
.L29:
	mvz.b 7(%a1),%d0
	mvz.b 11(%a1),%d4
	mov3q.l #4,%d5
	cmp.l %d0,%d5
	jcc .L30
	mov3q.l #4,%d0
.L30:
	move.l %d4,%d3
	lsl.l %d0,%d3
	jeq .L80
	move.l #1323000,%d0
	muls.l %d3,%d0
	clr.w %d0
	swap %d0
	move.l %d0,62(%sp)
.L31:
	move.b 9(%a1),%d0
	move.b 8(%a1),%d5
	mvz.b %d0,%d7
	move.b %d5,71(%sp)
	moveq #63,%d5
	move.l %d7,%a6
	cmp.l %d7,%d5
	jcs .L32
	addq.l #1,%d0
	ext.w %d0
	moveq #12,%d7
	mulu.w %d0,%d0
	mulu.w 64(%sp),%d0
	lsr.l %d7,%d0
	move.l %d0,72(%sp)
.L33:
	tst.b 158(%a0)
	jne .L34
	move.l 104(%sp),%d0
	move.l #-1640531527,%d5
	addq.l #1,%d0
	muls.l %d5,%d0
	move.l %a0,%d7
	move.l %d1,%a5
	lea (24,%a0),%a2
	add.l #152,%d7
	eor.l #1831565813,%d0
.L35:
	move.l %d0,%d5
	moveq #13,%d1
	lsl.l %d1,%d5
	moveq #17,%d1
	eor.l %d5,%d0
	move.l %d0,%d5
	lsr.l %d1,%d5
	eor.l %d0,%d5
	move.l %d5,%d0
	lsl.l #5,%d0
	eor.l %d5,%d0
	move.l %d0,%d5
	lsr.l %d1,%d5
	move.w %d5,(%a2)+
	cmp.l %d7,%a2
	jne .L35
	moveq #1,%d5
	move.l %d0,16(%a0)
	move.l 12(%a4),%d0
	move.l %a5,%d1
	move.b %d5,158(%a0)
.L36:
	clr.w %d7
	move.l %d0,(%a0)
	clr.l 4(%a0)
	mov3q.l #-1,12(%a0)
	clr.l 152(%a0)
	move.l %d3,8(%a0)
	mov3q.l #3,%d0
	move.w %d7,156(%a0)
	move.b 70(%sp),%d7
	cmp.l %d6,%d0
	jcs .L101
	clr.b %d5
	move.b %d7,159(%a0)
	move.b %d5,161(%a0)
.L39:
	mvz.b %d7,%d7
	move.l 96(%sp),%d0
	lsr.l #2,%d0
	cmp.l %d7,%d1
	jeq .L41
	move.b 70(%sp),%d7
	mov3q.l #3,%d1
	cmp.l %d6,%d1
	jcs .L102
	move.w 152(%a0),%d1
	move.b %d7,159(%a0)
	moveq #1,%d7
	mov3q.l #1,%d5
	move.w %d1,156(%a0)
	move.w %d1,154(%a0)
	cmp.l %d6,%d5
	jcc .L103
.L43:
	move.b %d7,161(%a0)
.L44:
	move.l %d0,12(%a0)
	tst.l 100(%sp)
	jeq .L45
	move.w %a3,%d7
	mvz.b %d7,%d5
	cmp.l %d5,%d2
	jcs .L104
	mvz.w %d3,%d0
	move.l 4(%a4),%a3
	move.l %a3,%d7
	move.l 4(%a0),%d1
	sub.l %d1,%d7
	add.l %d0,%d0
	cmp.l %d7,%d0
	jge .L47
.L110:
	move.l %a3,%d0
	divu.l %d3,%d0
	move.l %d0,%d1
	addq.l #1,%d1
	muls.l %d3,%d1
	move.l %d1,4(%a0)
.L47:
	mvz.b 13(%a1),%d0
	move.l %d4,%d7
	mov3q.l #3,%a2
	add.l %d7,%d7
	move.l %a6,76(%sp)
	move.l %d0,%a5
	move.l %d6,%a6
	mvz.b 12(%a1),%d0
	move.l %d3,50(%sp)
	move.l %d0,58(%sp)
	move.w %a5,%d0
	move.l %d7,46(%sp)
	mulu.w %d4,%d0
	mulu.w #52920,%d0
	divu.l %d7,%d0
	move.l 46(%sp),%d7
	move.l %a3,%d4
	move.l %d1,%a3
	move.l %d0,66(%sp)
	move.l %d1,%d0
	sub.l %d4,%a3
	remu.l %d7,%d6:%d0
	divu.l %d7,%d0
	move.l 58(%sp),%d7
	move.l %a3,%d3
	move.l #1323000,%d4
	muls.l %d4,%d3
	remu.l %d7,%d4:%d0
	move.l %d3,%a3
	move.l %d4,%a5
	addq.l #1,%a5
	move.l %a5,%d0
	remu.l %d7,%d3:%d0
	moveq #31,%d7
	move.l %d3,%a5
	cmp.l %d4,%d7
	jcs .L48
.L106:
	move.l 16(%a1),%d0
	lsr.l %d4,%d0
	mov3q.l #1,%d3
	moveq #31,%d7
	and.l %d3,%d0
	cmp.l %a5,%d7
	jcs .L50
.L107:
	move.l 16(%a1),%d4
	move.l %a5,%d3
	lsr.l %d3,%d4
	mov3q.l #1,%d7
	and.l %d7,%d4
.L51:
	move.l 46(%sp),%a5
	sub.l %d6,%a5
	move.l %a5,%d3
	neg.l %d0
	and.l %d3,%d0
	mulu.w %d4,%d6
	move.l 66(%sp),%d4
	move.l 8(%a4),%a5
	add.l %d6,%d0
	muls.l %d4,%d0
	add.l %a3,%d0
	cmp.l %d0,%a5
	jlt .L52
	move.b 6(%a1),%d4
	move.l 50(%sp),%d6
	add.l %d1,%d6
	move.l %d6,4(%a0)
	tst.l %d5
	jeq .L53
	move.l 50(%sp),%d7
	mvz.b %d4,%d4
	divu.l %d7,%d1
	remu.l %d2,%d7:%d4
	remu.l %d2,%d4:%d1
	move.l %d2,%d1
	sub.l %d7,%d1
	add.l %d4,%d1
	remu.l %d2,%d4:%d1
	move.w %d4,%d1
	mulu.w %d5,%d1
	remu.l %d2,%d3:%d1
	cmp.l %d5,%d3
	jcs .L105
.L53:
	subq.l #1,%a2
	tst.l %a2
	jeq .L52
	move.l 46(%sp),%d7
	move.l %d6,%d1
	move.l %d1,%d0
	move.l %d1,%a3
	move.l 4(%a4),%d4
	sub.l %d4,%a3
	remu.l %d7,%d6:%d0
	divu.l %d7,%d0
	move.l 58(%sp),%d7
	move.l %a3,%d3
	move.l #1323000,%d4
	muls.l %d4,%d3
	remu.l %d7,%d4:%d0
	move.l %d3,%a3
	move.l %d4,%a5
	addq.l #1,%a5
	move.l %a5,%d0
	remu.l %d7,%d3:%d0
	moveq #31,%d7
	move.l %d3,%a5
	cmp.l %d4,%d7
	jcc .L106
.L48:
	add.l #-32,%d4
	move.l 20(%a1),%d0
	lsr.l %d4,%d0
	mov3q.l #1,%d4
	moveq #31,%d7
	and.l %d4,%d0
	cmp.l %a5,%d7
	jcc .L107
.L50:
	lea (-32,%a5),%a5
	mov3q.l #1,%d7
	move.l 20(%a1),%d4
	move.l %a5,%d3
	lsr.l %d3,%d4
	and.l %d7,%d4
	jra .L51
.L52:
	move.l %a6,%d6
	move.l 76(%sp),%a6
	tst.l %d5
	jne .L57
.L45:
	clr.b %d0
	clr.w %d1
	move.b %d0,161(%a0)
	move.w %d1,152(%a0)
	mvz.w (%a1),%d1
.L58:
	cmp.l #32512,%d1
	jgt .L85
.L120:
	move.w %d1,%d0
	movem.l (%sp),#31996
	lea (80,%sp),%sp
	rts
.L41:
	move.l 12(%a0),%d1
	move.l %d1,%d7
	not.l %d7
	cmp.l %d7,%d0
	jls .L108
	mov3q.l #-1,%d0
	jra .L44
.L34:
	move.l 12(%a4),%d0
	cmp.l (%a0),%d0
	jne .L36
	cmp.l 8(%a0),%d3
	jeq .L109
	move.l 4(%a4),%d0
	move.l %d3,8(%a0)
	divu.l %d3,%d0
	move.b 159(%a0),%d7
	addq.l #1,%d0
	muls.l %d3,%d0
	move.l %d0,4(%a0)
	jra .L39
.L32:
	move.l %d7,%d0
	add.l #-63,%d0
	mulu.w %d0,%d0
	mulu.w 64(%sp),%d0
	move.l %d0,%d7
	lsl.l #3,%d7
	sub.l %d0,%d7
	moveq #12,%d0
	lsr.l %d0,%d7
	add.l 62(%sp),%d7
	move.l %d7,72(%sp)
	jra .L33
.L80:
	moveq #121,%d7
	mov3q.l #6,%d3
	move.l %d7,62(%sp)
	jra .L31
.L79:
	mov3q.l #1,%d2
	jra .L27
.L103:
	clr.b %d7
	move.b %d7,161(%a0)
	jra .L44
.L102:
	moveq #3,%d7
	move.w 152(%a0),%d1
	mov3q.l #1,%d5
	move.b %d7,159(%a0)
	moveq #1,%d7
	move.w %d1,156(%a0)
	move.w %d1,154(%a0)
	cmp.l %d6,%d5
	jcs .L43
	jra .L103
.L101:
	moveq #3,%d7
	clr.b %d5
	move.b %d7,159(%a0)
	move.b %d5,161(%a0)
	jra .L39
.L105:
	move.w #257,%d7
	move.l %a5,%d1
	sub.l %d0,%d1
	lsr.l #2,%d1
	move.w 152(%a0),154(%a0)
	addq.l #1,20(%a0)
	mov3q.l #1,%d0
	move.l %d1,12(%a0)
	move.w %d7,160(%a0)
	cmp.l %a6,%d0
	jcc .L53
	mov3q.l #2,%d1
	cmp.l %a6,%d1
	jeq .L54
	move.w 24(%a0,%d4.l*2),%d0
	move.w %d0,156(%a0)
	jra .L53
.L104:
	mvz.w %d3,%d0
	move.l 4(%a4),%a3
	move.l %d2,%d5
	move.l 4(%a0),%d1
	move.l %a3,%d7
	sub.l %d1,%d7
	add.l %d0,%d0
	cmp.l %d7,%d0
	jge .L47
	jra .L110
.L100:
	moveq #64,%d2
	jra .L27
.L57:
	tst.b 161(%a0)
	jeq .L111
	mvz.b 71(%sp),%d3
	mvz.w #16129,%d5
	moveq #14,%d4
	move.l 12(%a0),%d2
	lsr.l %d4,%d2
	mulu.w %d3,%d3
	mulu.w 64(%sp),%d3
	move.l %d3,%d1
	divu.l %d5,%d1
	tst.b 70(%sp)
	jeq .L112
	subq.l #1,%d6
	tst.l %d6
	jeq .L113
	move.w 156(%a0),%d0
	cmp.l #16128,%d3
	jls .L74
	cmp.l %d1,%d2
	jcc .L74
	move.w 154(%a0),%d4
	mvz.w %d0,%d0
	mvz.w %d4,%d3
	cmp.l %d0,%d3
	jls .L114
	sub.l %d0,%d3
	move.l %d3,%d0
	muls.l %d2,%d0
	divu.l %d1,%d0
	sub.l %d0,%d4
	move.w %d4,%d0
.L74:
	move.w %d0,152(%a0)
	mvz.w %d0,%d0
.L60:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jlt .L115
.L77:
	moveq #14,%d7
	asr.l %d7,%d1
	mvz.w (%a1),%d2
	clr.w %d0
	add.l %d2,%d1
	tst.l %d1
	jge .L58
.L99:
	movem.l (%sp),#31996
	lea (80,%sp),%sp
	rts
.L85:
	move.w #32512,%d0
	movem.l (%sp),#31996
	lea (80,%sp),%sp
	rts
.L111:
	mvz.w 2(%a1),%d1
	mvz.w 152(%a0),%d0
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L77
.L115:
	add.l #16383,%d1
	moveq #14,%d7
	asr.l %d7,%d1
	mvz.w (%a1),%d2
	clr.w %d0
	add.l %d2,%d1
	tst.l %d1
	jlt .L99
	jra .L58
.L109:
	move.b 159(%a0),%d7
	jra .L39
.L54:
	move.l 16(%a0),%d0
	moveq #13,%d3
	move.l %d0,%d1
	moveq #17,%d7
	lsl.l %d3,%d1
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d7,%d1
	eor.l %d0,%d1
	move.l %d1,%d0
	lsl.l #5,%d0
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d7,%d1
	move.l %d0,16(%a0)
	move.w %d1,%d0
	move.w %d1,24(%a0,%d4.l*2)
	move.w %d0,156(%a0)
	jra .L53
.L112:
	cmp.l %d1,%d2
	jcc .L62
	cmp.l #16128,%d3
	jls .L82
	move.w 154(%a0),%d0
	mvz.w %d0,%d3
	tst.w %d0
	jge .L116
	add.l #-32767,%d3
	muls.l %d3,%d2
	divu.l %d1,%d2
	sub.l %d2,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
.L118:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L77
	jra .L115
.L62:
	move.l 72(%sp),%d0
	tst.l %d0
	jne .L65
	mov3q.l #1,%d0
.L65:
	sub.l %d1,%d2
	cmp.l %d2,%d0
	jls .L117
	move.l %d2,%d1
	moveq #15,%d3
	lsl.l %d3,%d1
	mvz.w #32767,%d5
	sub.l %d2,%d1
	move.l %d1,%d2
	divu.l %d0,%d2
	mvz.w #32767,%d1
	sub.l %d2,%d1
	mulu.w %d1,%d1
	divu.l %d5,%d1
	move.l %d1,%d0
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L118
.L113:
	move.l %a6,%d0
	addq.l #1,%d0
	mulu.w 64(%sp),%d0
	move.l %d0,%d3
	lsr.l #7,%d3
	jne .L68
	mov3q.l #1,%d3
	clr.l %d0
.L69:
	cmp.l %d2,%d3
	jls .L70
	cmp.l %d2,%d0
	jhi .L119
	mvz.w #32767,%d0
	move.w %d0,%d2
	move.w %d2,152(%a0)
.L121:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L77
	jra .L115
.L68:
	lsr.l #8,%d0
	cmp.l %d0,%d1
	jcc .L69
	move.l %d1,%d0
	jra .L69
.L70:
	sub.l %d3,%d2
	cmp.l %d2,%d0
	jhi .L72
	clr.w %d4
	mvz.w (%a1),%d1
	move.w %d4,152(%a0)
	cmp.l #32512,%d1
	jle .L120
	jra .L85
.L82:
	mvz.w #32767,%d0
	move.w %d0,%d1
	move.w %d1,152(%a0)
	jra .L118
.L117:
	clr.w %d7
	mvz.w (%a1),%d1
	move.w %d7,152(%a0)
	cmp.l #32512,%d1
	jle .L120
	jra .L85
.L114:
	sub.l %d3,%d0
	muls.l %d2,%d0
	divu.l %d1,%d0
	add.l %d4,%d0
	move.w %d0,152(%a0)
	mvz.w %d0,%d0
	jra .L60
.L119:
	move.l %d2,%d1
	moveq #15,%d3
	lsl.l %d3,%d1
	sub.l %d2,%d1
	divu.l %d0,%d1
	move.w %d1,%d2
	move.l %d1,%d0
	mvz.w %d0,%d0
	move.w %d2,152(%a0)
	jra .L121
.L72:
	move.l %d2,%d1
	moveq #15,%d5
	lsl.l %d5,%d1
	sub.l %d2,%d1
	divu.l %d0,%d1
	mvz.w #32767,%d0
	sub.l %d1,%d0
	move.w %d0,%d2
	mvz.w %d0,%d0
	move.w %d2,152(%a0)
	jra .L121
.L116:
	mvz.w #32767,%d4
	sub.l %d3,%d4
	muls.l %d4,%d2
	divu.l %d1,%d2
	add.l %d2,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L118
.L108:
	add.l %d1,%d0
	jra .L44
	.size	eu_process, .-eu_process
	.align	2
	.globl	eu_publish
	.type	eu_publish, @function
eu_publish:
	lea (-96,%sp),%sp
	mov3q.l #1,%d0
	movem.l #23804,(%sp)
	cmp.l -2147457608.l,%d0
	seq %d4
	move.l 1175473392,-(%sp)
	pea eu_clock
	move.l 108(%sp),%d3
	move.l %d3,%a4
	move.l 112(%sp),%d2
	move.l %d2,%d5
	mvz.w #36437,%d6
	lea (54,%a4),%a4
	add.l %d5,%d5
	mvs.b %d4,%d4
	neg.l %d4
	move.l %d4,48(%sp)
	jsr eu_clock_update
	mvz.w #328,%d0
	mvz.w #2330,%d1
	move.l %d3,%a6
	addq.l #8,%sp
	lea (12,%a6),%a6
	add.l #58,%d3
	muls.l %d2,%d0
	muls.l %d1,%d2
	move.l %d0,%a2
	add.l #eu_states,%a2
.L132:
	mvz.w (%a4)+,%d0
	moveq #29,%d4
	cmp.l %d0,%d4
	jeq .L123
	clr.b %d7
	move.b %d7,158(%a2)
.L124:
	lea (164,%a2),%a2
	addq.l #1,%d5
	lea (12,%a6),%a6
	cmp.l %a4,%d3
	jne .L132
	movem.l (%sp),#23804
	lea (96,%sp),%sp
	rts
.L123:
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	moveq #8,%d4
	moveq #12,%d7
	move.l %d4,80(%sp)
	moveq #24,%d4
	move.l %d4,88(%sp)
	move.l #635712,%d4
	mulu.w #36568,%d1
	move.l %d7,84(%sp)
	moveq #48,%d7
	mov3q.l #3,68(%sp)
	mov3q.l #4,72(%sp)
	mov3q.l #6,76(%sp)
	mvz.b %d0,%d0
	move.l %d7,92(%sp)
	muls.l %d4,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%d6.l)
	jeq .L125
	move.b 81(%a0,%d2.l),%d0
.L126:
	mvz.b %d0,%d0
	tst.b (%a0,%d6.l)
	jeq .L127
	move.b 80(%a0,%d2.l),%d7
.L128:
	mvz.b 8(%a6),%d1
	move.w (%a6),44(%sp)
	add.l %d2,%a0
	mov3q.l #6,%d4
	addq.l #1,%d1
	move.w 4(%a6),46(%sp)
	move.b 6(%a6),53(%sp)
	move.b %d1,48(%sp)
	mvz.b %d7,%d1
	move.b 10(%a6),49(%sp)
	move.b 24(%a6),50(%sp)
	move.b 25(%a6),51(%sp)
	move.b 27(%a6),52(%sp)
	move.b 28(%a6),54(%sp)
	cmp.l %d0,%d4
	jcs .L133
	move.b 71(%sp,%d0.l*4),%d0
.L129:
	move.b %d0,55(%sp)
	move.l %d1,%d0
	moveq #63,%d1
	subq.l #1,%d0
	cmp.l %d0,%d1
	jcc .L130
	moveq #16,%d7
.L130:
	move.b 82(%a0),%d0
	move.b %d7,56(%sp)
	moveq #30,%d4
	mvz.b %d0,%d1
	cmp.l %d1,%d4
	jcc .L131
	moveq #30,%d0
.L131:
	move.b %d0,57(%sp)
	move.l 64(%a0),64(%sp)
	move.l 68(%a0),60(%sp)
	move.l -2147477476,%d0
	move.l %d5,-(%sp)
	move.l 44(%sp),-(%sp)
	lsl.l #4,%d0
	move.l %d0,-(%sp)
	pea 56(%sp)
	pea eu_clock
	move.l %a2,-(%sp)
	jsr eu_process
	lea (24,%sp),%sp
	move.w %d0,(%a6)
	jra .L124
.L133:
	moveq #6,%d0
	jra .L129
.L127:
	mvz.w #36435,%d1
	move.b (%a0,%d1.l),%d7
	jra .L128
.L125:
	mvz.w #36436,%d0
	move.b (%a0,%d0.l),%d0
	jra .L126
	.size	eu_publish, .-eu_publish
	.align	2
	.globl	eu_publish_frame
	.type	eu_publish_frame, @function
eu_publish_frame:
	lea (-12,%sp),%sp
	moveq #9,%d0
	movem.l #1036,(%sp)
	mov3q.l #1,%d3
	and.l -2147483424,%d3
	clr.l %d2
	lea eu_publish,%a2
	lsl.l %d0,%d3
	add.l #-2147483376,%d3
.L138:
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	jsr (%a2)
	addq.l #1,%d2
	add.l #64,%d3
	addq.l #8,%sp
	moveq #8,%d0
	cmp.l %d2,%d0
	jne .L138
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
	.size	eu_publish_frame, .-eu_publish_frame

| Generated control.s appends this adapter to the freestanding C engine.
| All stock scene/LFO writes have finished; publish into the outgoing frame.
        .text
        .balign 4
        .global eu_frame_hook, eu_start_hook, eu_resume_hook, eu_dial_hook
eu_frame_hook:
        lea     -16(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,(%sp)
        jsr     eu_publish_frame
        movem.l (%sp),%d0-%d1/%a0-%a1
        lea     16(%sp),%sp
        lea     0x800000f0,%a1     | displaced, next MOVE sets the flags
        jmp     0x4000d568

| A fresh PLAY resets all instances together at the same anchor the stock
| transport sets for its first tick.
eu_start_hook:
        move.l  %d0,0x800065b8     | displaced: PLAYING
        lea     -24(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@(8)
        move.l  #eu_clock,(%sp)
        move.l  0x4610757c,%d0
        move.l  %d0,4(%sp)
        jsr     eu_clock_start
        movem.l %sp@(8),%d0-%d1/%a0-%a1
        lea     24(%sp),%sp
        jmp     0x4009c3da

| The second PLAY path (resume) uses the same reset policy for the effect.
eu_resume_hook:
        move.l  %d0,0x800065b8
        lea     -24(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@(8)
        move.l  #eu_clock,(%sp)
        move.l  0x4610757c,%d0
        move.l  %d0,4(%sp)
        jsr     eu_clock_start
        movem.l %sp@(8),%d0-%d1/%a0-%a1
        lea     24(%sp),%sp
        jmp     0x4009c4da

| The plain dial always indexes its 128-position arc with the raw value.
| At this point its numeric label has already been formatted. Match only
| Euclid's formatter pointers, then scale the DRAWING value, leaving all
| parameter storage, encoder increments and displayed numbers unchanged.
eu_dial_hook:
        lea     -16(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,(%sp)
        move.l  0x400d6050,%a0    | FX2 descriptor table[EU_ID]
        moveq   #63,%d1
        cmpa.l  0xda(%a0),%a2    | STEPS A formatter, slot 4
        beq.s   eu_arc_scale
        cmpa.l  0xe2(%a0),%a2    | ROT A formatter, slot 6
        beq.s   eu_arc_scale
        moveq   #64,%d1
        cmpa.l  0xde(%a0),%a2    | PULSE A formatter, slot 5
        bne.s   eu_arc_done
eu_arc_scale:
        move.l  %d2,%d0
        cmp.l   %d1,%d0
        bls.s   eu_arc_bound
        move.l  %d1,%d0
eu_arc_bound:
        move.l  %d1,%a1
        moveq   #127,%d1
        mulu.l  %d1,%d0
        move.l  %a1,%d1
        lsr.l   #1,%d1
        add.l   %d1,%d0
        move.l  %a1,%d1
        divu.l  %d1,%d0
        move.l  %d0,%d2
eu_arc_done:
        movem.l (%sp),%d0-%d1/%a0-%a1
        lea     16(%sp),%sp
        moveq   #2,%d6           | displaced widget-flags branch
        and.l   %d5,%d6
        beq.s   eu_arc_normal
        jmp     0x40047a42
eu_arc_normal:
        jmp     0x40047a8a

| Explicitly initialized, loader-owned DRAM, not uninitialized BSS. The
| C's static assertions check these sizes on both target and host compilers.
        .balign 4
        .global eu_clock, eu_states
eu_clock:
        .zero   20
eu_states:
        .zero   2624
