| Generated by modules/euclid/generate_control.py; edit control.c / hooks.s.
#NO_APP
	.file	"control.c"
	.text
	.align	2
	.globl	eu_clock_start
	.type	eu_clock_start, @function
eu_clock_start:
	move.l 4(%sp),%a0
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
	.size	eu_clock_start, .-eu_clock_start
	.align	2
	.globl	eu_clock_update
	.type	eu_clock_update, @function
eu_clock_update:
	move.l 4(%sp),%a0
	tst.l 16(%a0)
	jeq .L15
	move.l 8(%sp),%d0
	sub.l (%a0),%d0
	move.l 8(%sp),(%a0)
	add.l 8(%a0),%d0
	tst.l %d0
	jge .L16
	move.l 4(%a0),%d1
	subq.l #1,%d1
.L9:
	move.l %d1,%a1
	add.l #1323000,%d0
	subq.l #1,%d1
	tst.l %d0
	jlt .L9
	move.l %a1,4(%a0)
.L8:
	move.l %d0,8(%a0)
.L3:
	rts
.L15:
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
.L16:
	cmp.l #1322999,%d0
	jle .L8
	move.l 4(%a0),%d1
.L10:
	addq.l #1,%d1
	add.l #-1323000,%d0
	cmp.l #1322999,%d0
	jhi .L10
	move.l %d1,4(%a0)
	move.l %d0,8(%a0)
	jra .L3
	.size	eu_clock_update, .-eu_clock_update
	.align	2
	.globl	eu_random
	.type	eu_random, @function
eu_random:
	move.l %d2,-(%sp)
	moveq #13,%d2
	move.l 8(%sp),%a0
	move.l (%a0),%d1
	move.l %d1,%d0
	lsl.l %d2,%d0
	moveq #17,%d2
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d0,%d1
	move.l %d1,%d0
	lsl.l #5,%d0
	eor.l %d1,%d0
	move.l %d0,(%a0)
	lsr.l %d2,%d0
	move.l (%sp)+,%d2
	rts
	.size	eu_random, .-eu_random
	.align	2
	.globl	eu_pulse
	.type	eu_pulse, @function
eu_pulse:
	lea (-12,%sp),%sp
	move.l 24(%sp),%d0
	movem.l #28,(%sp)
	tst.l %d0
	jeq .L20
	move.l 16(%sp),%d1
	move.l 20(%sp),%d3
	muls.l %d0,%d1
	move.l %d1,%d2
	remu.l %d3,%d4:%d2
	cmp.l %d4,%d0
	shi %d0
	mvs.b %d0,%d0
	neg.l %d0
.L20:
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
	.size	eu_pulse, .-eu_pulse
	.align	2
	.globl	eu_process
	.type	eu_process, @function
eu_process:
	lea (-68,%sp),%sp
	movem.l #31996,(%sp)
	move.l 80(%sp),%a1
	move.l 72(%sp),%a0
	move.l 76(%sp),%a4
	move.b 4(%a1),%d2
	jeq .L79
	mvz.b %d2,%d2
	moveq #64,%d0
	cmp.l %d2,%d0
	jcs .L99
.L27:
	move.b 10(%a1),%d1
	move.b 5(%a1),%d3
	mov3q.l #3,%d4
	mvz.b %d1,%d6
	move.b %d1,63(%sp)
	move.w %d3,%a3
	move.l %d6,%d1
	cmp.l %d6,%d4
	jcc .L29
	mov3q.l #3,%d1
.L29:
	mvz.b 7(%a1),%d0
	mvz.b 11(%a1),%d4
	mov3q.l #4,%d5
	cmp.l %d0,%d5
	jcc .L30
	mov3q.l #4,%d0
.L30:
	move.l %d4,%d3
	lsl.l %d0,%d3
	jne .L31
	mov3q.l #6,%d3
.L31:
	tst.b 158(%a0)
	jne .L32
	move.l #-1640531527,%d7
	move.l 92(%sp),%d0
	addq.l #1,%d0
	muls.l %d7,%d0
	move.l %a0,%d7
	move.l %d1,%a5
	lea (24,%a0),%a2
	add.l #152,%d7
	eor.l #1831565813,%d0
.L33:
	move.l %d0,%d5
	moveq #13,%d1
	lsl.l %d1,%d5
	moveq #17,%d1
	eor.l %d5,%d0
	move.l %d0,%d5
	lsr.l %d1,%d5
	eor.l %d0,%d5
	move.l %d5,%d0
	lsl.l #5,%d0
	eor.l %d5,%d0
	move.l %d0,%d5
	lsr.l %d1,%d5
	move.w %d5,(%a2)+
	cmp.l %a2,%d7
	jne .L33
	moveq #1,%d5
	move.l %d0,16(%a0)
	move.l 12(%a4),%d7
	move.l %a5,%d1
	move.b %d5,158(%a0)
.L34:
	clr.w %d0
	move.l %d7,(%a0)
	clr.l 4(%a0)
	mov3q.l #-1,12(%a0)
	clr.l 152(%a0)
	move.l %d3,8(%a0)
	mov3q.l #3,%d5
	move.w %d0,156(%a0)
	move.b 63(%sp),%d0
	cmp.l %d6,%d5
	jcs .L100
	clr.b %d7
	move.b %d0,159(%a0)
	move.b %d7,160(%a0)
.L37:
	mvz.b %d0,%d7
	move.l 84(%sp),%d0
	lsr.l #2,%d0
	cmp.l %d7,%d1
	jeq .L39
	move.b 63(%sp),%d7
	mov3q.l #3,%d1
	cmp.l %d6,%d1
	jcs .L101
	move.w 152(%a0),%d1
	move.b %d7,159(%a0)
	moveq #1,%d7
	mov3q.l #1,%d5
	move.w %d1,156(%a0)
	move.w %d1,154(%a0)
	cmp.l %d6,%d5
	jcc .L102
.L41:
	move.b %d7,160(%a0)
.L42:
	move.l %d0,12(%a0)
	tst.l 88(%sp)
	jeq .L43
	move.w %a3,%d7
	mvz.b %d7,%d5
	cmp.l %d5,%d2
	jcs .L103
	mvz.w %d3,%d0
	move.l 4(%a4),%a3
	move.l %a3,%d7
	move.l 4(%a0),%d1
	sub.l %d1,%d7
	add.l %d0,%d0
	cmp.l %d7,%d0
	jge .L45
.L109:
	move.l %a3,%d1
	divu.l %d3,%d1
	addq.l #1,%d1
	muls.l %d3,%d1
	move.l %d1,4(%a0)
.L45:
	mvz.b 13(%a1),%d0
	move.l %d4,%d7
	move.l %d6,%a6
	add.l %d7,%d7
	move.l %d3,50(%sp)
	move.l %d0,%a5
	mov3q.l #3,%a2
	mvz.b 12(%a1),%d0
	move.l %d0,58(%sp)
	move.w %a5,%d0
	move.l %d7,46(%sp)
	mulu.w %d4,%d0
	mulu.w #52920,%d0
	divu.l %d7,%d0
	move.l 46(%sp),%d7
	move.l %a3,%d4
	move.l %d1,%a3
	move.l %d0,64(%sp)
	move.l %d1,%d0
	sub.l %d4,%a3
	remu.l %d7,%d6:%d0
	divu.l %d7,%d0
	move.l 58(%sp),%d7
	move.l %a3,%d3
	move.l #1323000,%d4
	muls.l %d4,%d3
	remu.l %d7,%d4:%d0
	move.l %d3,%a3
	move.l %d4,%a5
	addq.l #1,%a5
	move.l %a5,%d0
	remu.l %d7,%d3:%d0
	moveq #31,%d7
	move.l %d3,%a5
	cmp.l %d4,%d7
	jcs .L46
.L105:
	move.l 16(%a1),%d0
	lsr.l %d4,%d0
	mov3q.l #1,%d3
	moveq #31,%d7
	and.l %d3,%d0
	cmp.l %a5,%d7
	jcs .L48
.L106:
	move.l 16(%a1),%d4
	move.l %a5,%d3
	lsr.l %d3,%d4
	mov3q.l #1,%d7
	and.l %d7,%d4
.L49:
	move.l 46(%sp),%a5
	sub.l %d6,%a5
	move.l %a5,%d3
	neg.l %d0
	and.l %d3,%d0
	mulu.w %d4,%d6
	move.l 64(%sp),%d4
	move.l 8(%a4),%a5
	add.l %d6,%d0
	muls.l %d4,%d0
	add.l %a3,%d0
	cmp.l %d0,%a5
	jlt .L50
	move.b 6(%a1),%d4
	move.l 50(%sp),%d6
	add.l %d1,%d6
	move.l %d6,4(%a0)
	tst.l %d5
	jeq .L51
	move.l 50(%sp),%d7
	mvz.b %d4,%d4
	divu.l %d7,%d1
	remu.l %d2,%d7:%d4
	remu.l %d2,%d4:%d1
	move.l %d2,%d1
	sub.l %d7,%d1
	add.l %d4,%d1
	remu.l %d2,%d4:%d1
	move.w %d4,%d1
	mulu.w %d5,%d1
	remu.l %d2,%d3:%d1
	cmp.l %d5,%d3
	jcs .L104
.L51:
	subq.l #1,%a2
	tst.l %a2
	jeq .L50
	move.l 46(%sp),%d7
	move.l %d6,%d1
	move.l %d1,%d0
	move.l %d1,%a3
	move.l 4(%a4),%d4
	sub.l %d4,%a3
	remu.l %d7,%d6:%d0
	divu.l %d7,%d0
	move.l 58(%sp),%d7
	move.l %a3,%d3
	move.l #1323000,%d4
	muls.l %d4,%d3
	remu.l %d7,%d4:%d0
	move.l %d3,%a3
	move.l %d4,%a5
	addq.l #1,%a5
	move.l %a5,%d0
	remu.l %d7,%d3:%d0
	moveq #31,%d7
	move.l %d3,%a5
	cmp.l %d4,%d7
	jcc .L105
.L46:
	add.l #-32,%d4
	move.l 20(%a1),%d0
	lsr.l %d4,%d0
	mov3q.l #1,%d4
	moveq #31,%d7
	and.l %d4,%d0
	cmp.l %a5,%d7
	jcc .L106
.L48:
	lea (-32,%a5),%a5
	mov3q.l #1,%d7
	move.l 20(%a1),%d4
	move.l %a5,%d3
	lsr.l %d3,%d4
	and.l %d7,%d4
	jra .L49
.L50:
	move.l 50(%sp),%d3
	tst.l %d5
	jne .L55
.L43:
	clr.b %d0
	clr.w %d1
	move.b %d0,160(%a0)
	move.w %d1,152(%a0)
	mvz.w (%a1),%d1
.L56:
	cmp.l #32512,%d1
	jgt .L84
.L117:
	move.w %d1,%d0
	movem.l (%sp),#31996
	lea (68,%sp),%sp
	rts
.L39:
	move.l 12(%a0),%d1
	move.l %d1,%d7
	not.l %d7
	cmp.l %d7,%d0
	jls .L107
	mov3q.l #-1,%d0
	jra .L42
.L32:
	move.l 12(%a4),%d7
	cmp.l (%a0),%d7
	jne .L34
	cmp.l 8(%a0),%d3
	jeq .L108
	move.l 4(%a4),%d7
	move.l %d3,8(%a0)
	divu.l %d3,%d7
	move.b 159(%a0),%d0
	addq.l #1,%d7
	muls.l %d3,%d7
	move.l %d7,4(%a0)
	jra .L37
.L79:
	mov3q.l #1,%d2
	jra .L27
.L102:
	clr.b %d7
	move.b %d7,160(%a0)
	jra .L42
.L101:
	moveq #3,%d7
	move.w 152(%a0),%d1
	mov3q.l #1,%d5
	move.b %d7,159(%a0)
	moveq #1,%d7
	move.w %d1,156(%a0)
	move.w %d1,154(%a0)
	cmp.l %d6,%d5
	jcs .L41
	jra .L102
.L100:
	moveq #3,%d0
	clr.b %d7
	move.b %d0,159(%a0)
	move.b %d7,160(%a0)
	jra .L37
.L104:
	moveq #1,%d7
	move.l %a5,%d1
	sub.l %d0,%d1
	lsr.l #2,%d1
	move.w 152(%a0),154(%a0)
	addq.l #1,20(%a0)
	mov3q.l #1,%d0
	move.l %d1,12(%a0)
	move.b %d7,160(%a0)
	cmp.l %a6,%d0
	jcc .L51
	mov3q.l #2,%d1
	cmp.l %a6,%d1
	jeq .L52
	move.w 24(%a0,%d4.l*2),%d0
	move.w %d0,156(%a0)
	jra .L51
.L103:
	mvz.w %d3,%d0
	move.l 4(%a4),%a3
	move.l %d2,%d5
	move.l 4(%a0),%d1
	move.l %a3,%d7
	sub.l %d1,%d7
	add.l %d0,%d0
	cmp.l %d7,%d0
	jge .L45
	jra .L109
.L99:
	moveq #64,%d2
	jra .L27
.L55:
	tst.b 160(%a0)
	jeq .L110
	move.l #1323000,%d2
	moveq #14,%d5
	muls.l %d2,%d3
	mvz.b 8(%a1),%d4
	mvz.w #16129,%d7
	move.l 12(%a0),%d1
	lsr.l %d5,%d1
	mulu.w %d4,%d4
	clr.w %d3
	swap %d3
	mulu.w %d3,%d4
	move.l %d4,%d2
	divu.l %d7,%d2
	tst.b 63(%sp)
	jne .L59
	move.b 9(%a1),%d0
	moveq #63,%d6
	mvz.b %d0,%d5
	cmp.l %d5,%d6
	jcs .L60
	addq.l #1,%d0
	ext.w %d0
	moveq #12,%d7
	mulu.w %d0,%d0
	mulu.w %d3,%d0
	lsr.l %d7,%d0
.L61:
	cmp.l %d2,%d1
	jcc .L62
	cmp.l #16128,%d4
	jls .L82
	move.w 154(%a0),%d0
	mvz.w %d0,%d3
	tst.w %d0
	jge .L111
	add.l #-32767,%d3
	muls.l %d3,%d1
	divu.l %d2,%d1
	sub.l %d1,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
.L58:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jlt .L112
.L77:
	moveq #14,%d5
	asr.l %d5,%d1
	mvz.w (%a1),%d2
	clr.w %d0
	add.l %d2,%d1
	tst.l %d1
	jge .L56
.L98:
	movem.l (%sp),#31996
	lea (68,%sp),%sp
	rts
.L84:
	move.w #32512,%d0
	movem.l (%sp),#31996
	lea (68,%sp),%sp
	rts
.L110:
	mvz.w 2(%a1),%d1
	mvz.w 152(%a0),%d0
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L77
.L112:
	add.l #16383,%d1
	moveq #14,%d5
	asr.l %d5,%d1
	mvz.w (%a1),%d2
	clr.w %d0
	add.l %d2,%d1
	tst.l %d1
	jlt .L98
	jra .L56
.L108:
	move.b 159(%a0),%d0
	jra .L37
.L52:
	move.l 16(%a0),%d0
	moveq #13,%d3
	move.l %d0,%d1
	moveq #17,%d7
	lsl.l %d3,%d1
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d7,%d1
	eor.l %d1,%d0
	move.l %d0,%d1
	lsl.l #5,%d1
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d7,%d1
	move.l %d0,16(%a0)
	move.w %d1,%d0
	move.w %d1,24(%a0,%d4.l*2)
	move.w %d0,156(%a0)
	jra .L51
.L59:
	mov3q.l #1,%d5
	cmp.l %a6,%d5
	jeq .L113
	move.w 156(%a0),%d0
	cmp.l #16128,%d4
	jls .L74
	cmp.l %d2,%d1
	jcc .L74
	move.w 154(%a0),%d4
	mvz.w %d0,%d0
	mvz.w %d4,%d3
	cmp.l %d0,%d3
	jls .L114
	sub.l %d0,%d3
	move.l %d3,%d0
	muls.l %d1,%d0
	divu.l %d2,%d0
	sub.l %d0,%d4
	move.w %d4,%d0
.L74:
	move.w %d0,152(%a0)
	mvz.w %d0,%d0
.L118:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L77
	jra .L112
.L60:
	add.l #-63,%d5
	mulu.w %d5,%d5
	mulu.w %d3,%d5
	move.l %d5,%d0
	lsl.l #3,%d0
	sub.l %d5,%d0
	moveq #12,%d5
	lsr.l %d5,%d0
	add.l %d3,%d0
	jra .L61
.L113:
	mvz.b 9(%a1),%d0
	addq.l #1,%d0
	mulu.w %d0,%d3
	move.l %d3,%d0
	lsr.l #7,%d0
	jne .L68
	mov3q.l #1,%d0
	clr.l %d3
.L69:
	cmp.l %d1,%d0
	jls .L70
	cmp.l %d1,%d3
	jhi .L115
.L82:
	mvz.w #32767,%d0
	move.w %d0,%d1
	move.w %d1,152(%a0)
	jra .L58
.L115:
	move.l %d1,%d0
	moveq #15,%d6
	lsl.l %d6,%d0
	sub.l %d1,%d0
	divu.l %d3,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L58
.L62:
	tst.l %d0
	jne .L65
	mov3q.l #1,%d0
.L65:
	sub.l %d2,%d1
	cmp.l %d1,%d0
	jls .L116
	move.l %d1,%d2
	moveq #15,%d7
	lsl.l %d7,%d2
	sub.l %d1,%d2
	divu.l %d0,%d2
	mvz.w #32767,%d1
	sub.l %d2,%d1
	mulu.w %d1,%d1
	mvz.w #32767,%d2
	divu.l %d2,%d1
	move.l %d1,%d0
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L58
.L68:
	lsr.l #8,%d3
	cmp.l %d3,%d2
	jcc .L69
	move.l %d2,%d3
	jra .L69
.L70:
	sub.l %d0,%d1
	cmp.l %d1,%d3
	jhi .L72
	clr.w %d7
	mvz.w (%a1),%d1
	move.w %d7,152(%a0)
	cmp.l #32512,%d1
	jle .L117
	jra .L84
.L116:
	clr.w %d6
	mvz.w (%a1),%d1
	move.w %d6,152(%a0)
	cmp.l #32512,%d1
	jle .L117
	jra .L84
.L114:
	sub.l %d3,%d0
	muls.l %d1,%d0
	divu.l %d2,%d0
	add.l %d4,%d0
	move.w %d0,152(%a0)
	mvz.w %d0,%d0
	jra .L118
.L111:
	mvz.w #32767,%d4
	sub.l %d3,%d4
	muls.l %d4,%d1
	divu.l %d2,%d1
	add.l %d1,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L58
.L72:
	move.l %d1,%d0
	moveq #15,%d2
	lsl.l %d2,%d0
	sub.l %d1,%d0
	move.l %d0,%d1
	divu.l %d3,%d1
	mvz.w #32767,%d0
	sub.l %d1,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L58
.L107:
	add.l %d1,%d0
	jra .L42
	.size	eu_process, .-eu_process
	.align	2
	.globl	eu_publish
	.type	eu_publish, @function
eu_publish:
	link.w %fp,#-112
	movem.l #1052,(%sp)
	move.l -2147457608,%d2
	moveq #29,%d3
	move.l 1175473392,-(%sp)
	pea eu_clock
	jsr eu_clock_update
	addq.l #8,%sp
	move.l 8(%fp),%a0
	move.l 12(%fp),%d1
	mvz.w 54(%a0),%d0
	add.l %d1,%d1
	cmp.l %d0,%d3
	jeq .L120
	mvz.w 56(%a0),%d0
	cmp.l %d0,%d3
	jeq .L120
	mvz.w #164,%d0
	mvz.w #164,%d4
	muls.l %d1,%d0
	addq.l #1,%d1
	muls.l %d4,%d1
	move.l %d0,%a0
	add.l #eu_states+158,%a0
	clr.b (%a0)
	move.l %d1,%a0
	add.l #eu_states+158,%a0
	clr.b (%a0)
.L119:
	movem.l -112(%fp),#1052
	unlk %fp
	rts
.L120:
	move.b -2147457603,%d0
	mvz.b -2147457602,%d3
	mov3q.l #1,%d4
	cmp.l %d2,%d4
	seq %d2
	mvz.w #2330,%d4
	move.l %d3,%a0
	move.l 12(%fp),%d3
	mov3q.l #3,-28(%fp)
	mov3q.l #4,-24(%fp)
	muls.l %d4,%d3
	move.w %a0,%d4
	mvz.b %d0,%d0
	mov3q.l #6,-20(%fp)
	mvs.b %d2,%d2
	move.l %d3,%a1
	mvz.w #36437,%d3
	neg.l %d2
	move.l %d2,-72(%fp)
	mulu.w #36568,%d4
	move.l %d4,%a0
	moveq #8,%d4
	move.l %d4,-16(%fp)
	moveq #12,%d4
	move.l %d4,-12(%fp)
	moveq #24,%d4
	move.l %d4,-8(%fp)
	move.l #635712,%d4
	muls.l %d4,%d0
	moveq #48,%d4
	move.l %d4,-4(%fp)
	add.l %d0,%a0
	add.l #1074668000,%a0
	add.l %a0,%a1
	tst.b (%a0,%d3.l)
	jeq .L122
	move.b 81(%a1),%d0
	move.b 80(%a1),%d2
	mov3q.l #6,%d3
	mvz.b %d0,%d0
	mvz.b %d2,%d2
	cmp.l %d0,%d3
	jcs .L130
.L142:
	move.l -28(%fp,%d0.l*4),%d0
	move.l %d0,-56(%fp)
.L124:
	move.l %d2,%d0
	moveq #63,%d4
	subq.l #1,%d0
	cmp.l %d0,%d4
	jcc .L125
	moveq #16,%d2
.L125:
	move.b 82(%a1),%d3
	move.l 64(%a1),%d4
	move.l 68(%a1),%a1
	move.l 12(%fp),%d0
	move.l %d4,-68(%fp)
	mvz.w #328,%d4
	move.l 8(%fp),%a2
	move.l %a1,-64(%fp)
	muls.l %d4,%d0
	move.b %d3,-74(%fp)
	lea (58,%a2),%a2
	move.l -2147477476,%d3
	move.l 8(%fp),%a1
	move.l %a2,-78(%fp)
	lsl.l #4,%d3
	move.l %d0,%a2
	add.l #eu_states,%a2
	lea (54,%a1),%a1
	move.l %a2,-94(%fp)
	move.l 8(%fp),%a0
	mvz.w (%a1)+,%d0
	lea (12,%a0),%a0
	move.l %d3,-60(%fp)
	moveq #29,%d3
	cmp.l %d0,%d3
	jeq .L126
.L141:
	clr.b %d4
	mvz.w #164,%d0
	lea (12,%a0),%a0
	addq.l #1,%d1
	move.l -94(%fp),%a2
	add.l %d0,-94(%fp)
	move.b %d4,158(%a2)
	cmp.l -78(%fp),%a1
	jeq .L119
.L140:
	mvz.w (%a1)+,%d0
	moveq #29,%d3
	cmp.l %d0,%d3
	jne .L141
.L126:
	mvz.b 8(%a0),%d3
	move.w (%a0),-52(%fp)
	mvz.b -74(%fp),%d0
	move.b -74(%fp),-73(%fp)
	addq.l #1,%d3
	moveq #30,%d4
	move.w 4(%a0),-50(%fp)
	move.b 6(%a0),-43(%fp)
	move.b %d3,-48(%fp)
	move.l %d2,%d3
	lsl.l #8,%d3
	move.b 10(%a0),-47(%fp)
	move.b 24(%a0),-46(%fp)
	move.b 25(%a0),-45(%fp)
	move.b 27(%a0),-44(%fp)
	move.b 28(%a0),-42(%fp)
	move.b -53(%fp),-41(%fp)
	cmp.l %d0,%d4
	jcc .L128
	moveq #30,%d0
	move.b %d0,-73(%fp)
.L128:
	move.l %d1,-(%sp)
	move.l -72(%fp),-(%sp)
	move.l -60(%fp),-(%sp)
	move.b -73(%fp),%d3
	pea -52(%fp)
	pea eu_clock
	move.l -94(%fp),-(%sp)
	move.l %d1,-90(%fp)
	move.l %a0,-86(%fp)
	move.l %a1,-82(%fp)
	move.w %d3,-40(%fp)
	move.l -68(%fp),-32(%fp)
	move.l -64(%fp),-36(%fp)
	jsr eu_process
	lea (24,%sp),%sp
	move.l -86(%fp),%a0
	move.l -82(%fp),%a1
	move.l -90(%fp),%d1
	addq.l #1,%d1
	move.w %d0,(%a0)
	mvz.w #164,%d0
	lea (12,%a0),%a0
	add.l %d0,-94(%fp)
	cmp.l -78(%fp),%a1
	jne .L140
	jra .L119
.L122:
	mvz.w #36436,%d0
	mvz.w #36435,%d2
	mov3q.l #6,%d3
	move.b (%a0,%d0.l),%d0
	move.b (%a0,%d2.l),%d2
	mvz.b %d0,%d0
	mvz.b %d2,%d2
	cmp.l %d0,%d3
	jcc .L142
.L130:
	mov3q.l #6,-56(%fp)
	jra .L124
	.size	eu_publish, .-eu_publish
	.align	2
	.globl	eu_publish_frame
	.type	eu_publish_frame, @function
eu_publish_frame:
	lea (-12,%sp),%sp
	moveq #9,%d0
	movem.l #1036,(%sp)
	mov3q.l #1,%d3
	and.l -2147483424,%d3
	clr.l %d2
	lea eu_publish,%a2
	lsl.l %d0,%d3
	add.l #-2147483376,%d3
.L144:
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	jsr (%a2)
	addq.l #1,%d2
	add.l #64,%d3
	addq.l #8,%sp
	moveq #8,%d0
	cmp.l %d2,%d0
	jne .L144
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
	.size	eu_publish_frame, .-eu_publish_frame

| Generated control.s appends this adapter to the freestanding C engine.
| All stock scene/LFO writes have finished; publish into the outgoing frame.
        .text
        .balign 4
        .global eu_frame_hook, eu_start_hook, eu_resume_hook
eu_frame_hook:
        lea     -16(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,(%sp)
        jsr     eu_publish_frame
        movem.l (%sp),%d0-%d1/%a0-%a1
        lea     16(%sp),%sp
        lea     0x800000f0,%a1     | displaced, next MOVE sets the flags
        jmp     0x4000d568

| A fresh PLAY resets all instances together at the same anchor the stock
| transport sets for its first tick.
eu_start_hook:
        move.l  %d0,0x800065b8     | displaced: PLAYING
        bsr.s   eu_reset_clock
        jmp     0x4009c3da

| The second PLAY path (resume) uses the same reset policy for the effect.
eu_resume_hook:
        move.l  %d0,0x800065b8
        bsr.s   eu_reset_clock
        jmp     0x4009c4da

| Preserve the CCR produced by the displaced PLAYING store. BSR, LEA and
| MOVEM do not alter it, so save it only after the call has pushed its return
| address; restore it after every instruction that can change the flags.
eu_reset_clock:
        lea     -28(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@(12)
        move.w  %ccr,%d1
        move.w  %d1,%sp@(8)
        move.l  #eu_clock,(%sp)
        move.l  0x4610757c,%d0
        move.l  %d0,4(%sp)
        jsr     eu_clock_start
        move.w  %sp@(8),%d1
        move.w  %d1,%ccr
        movem.l %sp@(12),%d0-%d1/%a0-%a1
        lea     28(%sp),%sp
        rts

| Explicitly initialized, loader-owned DRAM, not uninitialized BSS. The
| C's static assertions check these sizes on both target and host compilers.
        .balign 4
        .global eu_clock, eu_states
eu_clock:
        .zero   20
eu_states:
        .zero   2624
