| Generated by modules/euclid/generate_control.py; edit control.c / hooks.s.
#NO_APP
	.file	"control.c"
	.text
	.align	2
	.globl	eu_clock_start
	.type	eu_clock_start, @function
eu_clock_start:
	move.l 4(%sp),%a0
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
	.size	eu_clock_start, .-eu_clock_start
	.align	2
	.globl	eu_clock_update
	.type	eu_clock_update, @function
eu_clock_update:
	move.l 4(%sp),%a0
	tst.l 16(%a0)
	jeq .L15
	move.l 8(%sp),%d0
	sub.l (%a0),%d0
	move.l 8(%sp),(%a0)
	add.l 8(%a0),%d0
	tst.l %d0
	jge .L16
	move.l 4(%a0),%d1
	subq.l #1,%d1
.L9:
	move.l %d1,%a1
	add.l #1323000,%d0
	subq.l #1,%d1
	tst.l %d0
	jlt .L9
	move.l %a1,4(%a0)
.L8:
	move.l %d0,8(%a0)
.L3:
	rts
.L15:
	move.l 8(%sp),(%a0)
	clr.l 8(%a0)
	clr.l 4(%a0)
	addq.l #1,12(%a0)
	mov3q.l #1,16(%a0)
	rts
.L16:
	cmp.l #1322999,%d0
	jle .L8
	move.l 4(%a0),%d1
.L10:
	addq.l #1,%d1
	add.l #-1323000,%d0
	cmp.l #1322999,%d0
	jhi .L10
	move.l %d1,4(%a0)
	move.l %d0,8(%a0)
	jra .L3
	.size	eu_clock_update, .-eu_clock_update
	.align	2
	.globl	eu_random
	.type	eu_random, @function
eu_random:
	move.l %d2,-(%sp)
	moveq #13,%d2
	move.l 8(%sp),%a0
	move.l (%a0),%d1
	move.l %d1,%d0
	lsl.l %d2,%d0
	moveq #17,%d2
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d0,%d1
	move.l %d1,%d0
	lsl.l #5,%d0
	eor.l %d1,%d0
	move.l %d0,(%a0)
	lsr.l %d2,%d0
	move.l (%sp)+,%d2
	rts
	.size	eu_random, .-eu_random
	.align	2
	.globl	eu_pulse
	.type	eu_pulse, @function
eu_pulse:
	lea (-12,%sp),%sp
	move.l 24(%sp),%d0
	movem.l #28,(%sp)
	tst.l %d0
	jeq .L20
	move.l 16(%sp),%d1
	move.l 20(%sp),%d3
	muls.l %d0,%d1
	move.l %d1,%d2
	remu.l %d3,%d4:%d2
	cmp.l %d4,%d0
	shi %d0
	mvs.b %d0,%d0
	neg.l %d0
.L20:
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
	.size	eu_pulse, .-eu_pulse
	.align	2
	.globl	eu_process
	.type	eu_process, @function
eu_process:
	lea (-80,%sp),%sp
	movem.l #31996,(%sp)
	move.l 92(%sp),%a1
	move.l 84(%sp),%a0
	move.l 88(%sp),%a4
	move.b 4(%a1),%d2
	jeq .L80
	mvz.b %d2,%d2
	moveq #64,%d0
	cmp.l %d2,%d0
	jcs .L98
.L27:
	move.b 10(%a1),%d1
	move.b 5(%a1),%d3
	mov3q.l #3,%d4
	mvz.b %d1,%d6
	move.b %d1,70(%sp)
	move.w %d3,%a3
	move.l %d6,%d1
	cmp.l %d6,%d4
	jcc .L29
	mov3q.l #3,%d1
.L29:
	mvz.b 7(%a1),%d0
	mvz.b 11(%a1),%d4
	mov3q.l #4,%d5
	cmp.l %d0,%d5
	jcc .L30
	mov3q.l #4,%d0
.L30:
	move.l %d4,%d3
	lsl.l %d0,%d3
	jeq .L81
	move.l #1323000,%d0
	muls.l %d3,%d0
	clr.w %d0
	swap %d0
	move.l %d0,62(%sp)
.L31:
	move.b 8(%a1),%d5
	mvz.b 9(%a1),%d0
	moveq #63,%d7
	move.l %d0,%a6
	move.b %d5,71(%sp)
	cmp.l %d0,%d7
	jcs .L32
	addq.l #1,%d0
	mulu.w %d0,%d0
	moveq #12,%d5
	mulu.w 64(%sp),%d0
	lsr.l %d5,%d0
	move.l %d0,72(%sp)
.L33:
	tst.b 158(%a0)
	jne .L34
	move.l 104(%sp),%d0
	move.l #-1640531527,%d5
	addq.l #1,%d0
	muls.l %d5,%d0
	move.l %a0,%d7
	move.l %d1,%a5
	lea (24,%a0),%a2
	add.l #152,%d7
	eor.l #1831565813,%d0
.L35:
	move.l %d0,%d5
	moveq #13,%d1
	lsl.l %d1,%d5
	moveq #17,%d1
	eor.l %d5,%d0
	move.l %d0,%d5
	lsr.l %d1,%d5
	eor.l %d0,%d5
	move.l %d5,%d0
	lsl.l #5,%d0
	eor.l %d5,%d0
	move.l %d0,%d5
	lsr.l %d1,%d5
	move.w %d5,(%a2)+
	cmp.l %d7,%a2
	jne .L35
	moveq #1,%d5
	move.l %d0,16(%a0)
	move.l 12(%a4),%d0
	move.l %a5,%d1
	move.b %d5,158(%a0)
.L36:
	clr.w %d7
	move.l %d0,(%a0)
	clr.l 4(%a0)
	mov3q.l #-1,12(%a0)
	clr.l 152(%a0)
	move.l %d3,8(%a0)
	mov3q.l #3,%d0
	move.w %d7,156(%a0)
	move.b 70(%sp),%d7
	cmp.l %d6,%d0
	jcs .L99
	clr.b %d5
	move.b %d7,159(%a0)
	move.b %d5,160(%a0)
.L39:
	mvz.b %d7,%d7
	move.l 96(%sp),%d0
	lsr.l #2,%d0
	cmp.l %d7,%d1
	jeq .L41
	move.b 70(%sp),%d7
	mov3q.l #3,%d1
	cmp.l %d6,%d1
	jcs .L100
	move.w 152(%a0),%d1
	move.b %d7,159(%a0)
	moveq #1,%d7
	mov3q.l #1,%d5
	move.w %d1,156(%a0)
	move.w %d1,154(%a0)
	cmp.l %d6,%d5
	jcc .L101
.L43:
	move.b %d7,160(%a0)
.L45:
	move.l %d0,12(%a0)
	tst.l 100(%sp)
	jeq .L61
	move.w %a3,%d1
	mvz.b %d1,%d5
	cmp.l %d5,%d2
	jcs .L102
	mvz.w %d3,%d0
	move.l 4(%a4),%a3
	move.l %a3,%d7
	move.l 4(%a0),%d1
	sub.l %d1,%d7
	add.l %d0,%d0
	cmp.l %d7,%d0
	jge .L49
.L109:
	move.l %a3,%d0
	divu.l %d3,%d0
	move.l %d0,%d1
	addq.l #1,%d1
	muls.l %d3,%d1
	move.l %d1,4(%a0)
.L49:
	mvz.b 13(%a1),%d7
	mvz.b 12(%a1),%d0
	move.l %a6,76(%sp)
	move.l %d6,%a6
	mov3q.l #3,%a2
	move.l %d7,%a5
	move.l %d4,%d7
	move.l %d0,58(%sp)
	move.l %d3,50(%sp)
	move.w %a5,%d0
	add.l %d7,%d7
	mulu.w %d4,%d0
	move.l %d7,46(%sp)
	mulu.w #52920,%d0
	divu.l %d7,%d0
	move.l 46(%sp),%d7
	move.l %a3,%d4
	move.l %d1,%a3
	move.l %d0,66(%sp)
	move.l %d1,%d0
	sub.l %d4,%a3
	remu.l %d7,%d6:%d0
	divu.l %d7,%d0
	move.l 58(%sp),%d7
	move.l %a3,%d3
	move.l #1323000,%d4
	muls.l %d4,%d3
	remu.l %d7,%d4:%d0
	move.l %d3,%a3
	move.l %d4,%a5
	addq.l #1,%a5
	move.l %a5,%d0
	remu.l %d7,%d3:%d0
	moveq #31,%d7
	move.l %d3,%a5
	cmp.l %d4,%d7
	jcs .L50
.L104:
	move.l 16(%a1),%d0
	lsr.l %d4,%d0
	mov3q.l #1,%d3
	moveq #31,%d7
	and.l %d3,%d0
	cmp.l %a5,%d7
	jcs .L52
.L105:
	move.l 16(%a1),%d4
	move.l %a5,%d3
	lsr.l %d3,%d4
	mov3q.l #1,%d7
	and.l %d7,%d4
.L53:
	move.l 46(%sp),%a5
	sub.l %d6,%a5
	move.l %a5,%d3
	neg.l %d0
	and.l %d3,%d0
	mulu.w %d4,%d6
	move.l 66(%sp),%d4
	move.l 8(%a4),%a5
	add.l %d6,%d0
	muls.l %d4,%d0
	add.l %a3,%d0
	cmp.l %d0,%a5
	jlt .L54
	move.b 6(%a1),%d4
	move.l 50(%sp),%d6
	add.l %d1,%d6
	move.l %d6,4(%a0)
	tst.l %d5
	jeq .L56
	move.l 50(%sp),%d7
	mvz.b %d4,%d4
	divu.l %d7,%d1
	remu.l %d2,%d7:%d4
	remu.l %d2,%d4:%d1
	move.l %d2,%d1
	sub.l %d7,%d1
	add.l %d4,%d1
	remu.l %d2,%d4:%d1
	move.w %d4,%d1
	mulu.w %d5,%d1
	remu.l %d2,%d3:%d1
	cmp.l %d5,%d3
	jcs .L103
.L56:
	subq.l #1,%a2
	tst.l %a2
	jeq .L54
	move.l 46(%sp),%d7
	move.l %d6,%d1
	move.l %d1,%d0
	move.l %d1,%a3
	move.l 4(%a4),%d4
	sub.l %d4,%a3
	remu.l %d7,%d6:%d0
	divu.l %d7,%d0
	move.l 58(%sp),%d7
	move.l %a3,%d3
	move.l #1323000,%d4
	muls.l %d4,%d3
	remu.l %d7,%d4:%d0
	move.l %d3,%a3
	move.l %d4,%a5
	addq.l #1,%a5
	move.l %a5,%d0
	remu.l %d7,%d3:%d0
	moveq #31,%d7
	move.l %d3,%a5
	cmp.l %d4,%d7
	jcc .L104
.L50:
	add.l #-32,%d4
	move.l 20(%a1),%d0
	lsr.l %d4,%d0
	mov3q.l #1,%d4
	moveq #31,%d7
	and.l %d4,%d0
	cmp.l %a5,%d7
	jcc .L105
.L52:
	lea (-32,%a5),%a5
	mov3q.l #1,%d7
	move.l 20(%a1),%d4
	move.l %a5,%d3
	lsr.l %d3,%d4
	and.l %d7,%d4
	jra .L53
.L54:
	move.l %a6,%d6
	move.l 76(%sp),%a6
	tst.l %d5
	jne .L106
.L61:
	clr.b %d7
	clr.w %d0
	move.b %d7,160(%a0)
	move.w %d0,152(%a0)
	mvz.w (%a1),%d1
.L47:
	cmp.l #32512,%d1
	jgt .L86
.L119:
	move.w %d1,%d0
	movem.l (%sp),#31996
	lea (80,%sp),%sp
	rts
.L41:
	move.l 12(%a0),%d1
	move.l %d1,%d7
	not.l %d7
	cmp.l %d7,%d0
	jls .L107
	mov3q.l #-1,%d0
	jra .L45
.L34:
	move.l 12(%a4),%d0
	cmp.l (%a0),%d0
	jne .L36
	cmp.l 8(%a0),%d3
	jeq .L108
	move.l 4(%a4),%d0
	move.l %d3,8(%a0)
	divu.l %d3,%d0
	move.b 159(%a0),%d7
	addq.l #1,%d0
	muls.l %d3,%d0
	move.l %d0,4(%a0)
	jra .L39
.L32:
	add.l #-63,%d0
	mulu.w %d0,%d0
	mulu.w 64(%sp),%d0
	move.l %d0,%d7
	lsl.l #3,%d7
	sub.l %d0,%d7
	moveq #12,%d0
	lsr.l %d0,%d7
	add.l 62(%sp),%d7
	move.l %d7,72(%sp)
	jra .L33
.L81:
	moveq #121,%d7
	mov3q.l #6,%d3
	move.l %d7,62(%sp)
	jra .L31
.L80:
	mov3q.l #1,%d2
	jra .L27
.L101:
	clr.b %d7
	move.b %d7,160(%a0)
	jra .L45
.L100:
	moveq #3,%d7
	move.w 152(%a0),%d1
	mov3q.l #1,%d5
	move.b %d7,159(%a0)
	moveq #1,%d7
	move.w %d1,156(%a0)
	move.w %d1,154(%a0)
	cmp.l %d6,%d5
	jcs .L43
	jra .L101
.L99:
	moveq #3,%d7
	clr.b %d5
	move.b %d7,159(%a0)
	move.b %d5,160(%a0)
	jra .L39
.L103:
	moveq #1,%d7
	move.l %a5,%d1
	sub.l %d0,%d1
	lsr.l #2,%d1
	move.w 152(%a0),154(%a0)
	addq.l #1,20(%a0)
	mov3q.l #1,%d0
	move.l %d1,12(%a0)
	move.b %d7,160(%a0)
	cmp.l %a6,%d0
	jcc .L56
	mov3q.l #2,%d1
	cmp.l %a6,%d1
	jeq .L58
	move.w 24(%a0,%d4.l*2),%d0
	move.w %d0,156(%a0)
	jra .L56
.L102:
	mvz.w %d3,%d0
	move.l 4(%a4),%a3
	move.l %d2,%d5
	move.l 4(%a0),%d1
	move.l %a3,%d7
	sub.l %d1,%d7
	add.l %d0,%d0
	cmp.l %d7,%d0
	jge .L49
	jra .L109
.L98:
	moveq #64,%d2
	jra .L27
.L106:
	tst.b 160(%a0)
	jeq .L110
	mvz.b 71(%sp),%d3
	mvz.w #16129,%d4
	moveq #14,%d0
	move.l 12(%a0),%d2
	lsr.l %d0,%d2
	mulu.w %d3,%d3
	mulu.w 64(%sp),%d3
	move.l %d3,%d1
	divu.l %d4,%d1
	tst.b 70(%sp)
	jeq .L111
	subq.l #1,%d6
	tst.l %d6
	jeq .L112
	move.w 156(%a0),%d0
	cmp.l #16128,%d3
	jls .L76
	cmp.l %d1,%d2
	jcc .L76
	move.w 154(%a0),%d4
	mvz.w %d0,%d0
	mvz.w %d4,%d3
	cmp.l %d0,%d3
	jls .L113
	sub.l %d0,%d3
	move.l %d3,%d0
	muls.l %d2,%d0
	divu.l %d1,%d0
	sub.l %d0,%d4
	move.w %d4,%d0
.L76:
	move.w %d0,152(%a0)
	mvz.w %d0,%d0
.L63:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jlt .L114
.L78:
	moveq #14,%d4
	asr.l %d4,%d1
	mvz.w (%a1),%d2
	clr.w %d0
	add.l %d2,%d1
	tst.l %d1
	jge .L47
.L97:
	movem.l (%sp),#31996
	lea (80,%sp),%sp
	rts
.L86:
	move.w #32512,%d0
	movem.l (%sp),#31996
	lea (80,%sp),%sp
	rts
.L110:
	mvz.w 2(%a1),%d1
	mvz.w 152(%a0),%d0
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L78
.L114:
	add.l #16383,%d1
	moveq #14,%d4
	asr.l %d4,%d1
	mvz.w (%a1),%d2
	clr.w %d0
	add.l %d2,%d1
	tst.l %d1
	jlt .L97
	jra .L47
.L108:
	move.b 159(%a0),%d7
	jra .L39
.L58:
	move.l 16(%a0),%d0
	moveq #13,%d3
	move.l %d0,%d1
	moveq #17,%d7
	lsl.l %d3,%d1
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d7,%d1
	eor.l %d0,%d1
	move.l %d1,%d0
	lsl.l #5,%d0
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d7,%d1
	move.l %d0,16(%a0)
	move.w %d1,%d0
	move.w %d1,24(%a0,%d4.l*2)
	move.w %d0,156(%a0)
	jra .L56
.L111:
	cmp.l %d1,%d2
	jcc .L65
	cmp.l #16128,%d3
	jls .L83
	move.w 154(%a0),%d0
	mvz.w %d0,%d3
	tst.w %d0
	jge .L115
	add.l #-32767,%d3
	muls.l %d3,%d2
	divu.l %d1,%d2
	sub.l %d2,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
.L117:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L78
	jra .L114
.L65:
	move.l 72(%sp),%d0
	tst.l %d0
	jne .L68
	mov3q.l #1,%d0
.L68:
	sub.l %d1,%d2
	cmp.l %d2,%d0
	jls .L116
	move.l %d2,%d1
	moveq #15,%d7
	lsl.l %d7,%d1
	mvz.w #32767,%d4
	sub.l %d2,%d1
	move.l %d1,%d2
	divu.l %d0,%d2
	mvz.w #32767,%d1
	sub.l %d2,%d1
	mulu.w %d1,%d1
	divu.l %d4,%d1
	move.l %d1,%d0
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L117
.L112:
	move.l %a6,%d0
	addq.l #1,%d0
	mulu.w 64(%sp),%d0
	move.l %d0,%d3
	lsr.l #7,%d3
	jne .L71
	mov3q.l #1,%d3
	clr.l %d0
.L72:
	cmp.l %d2,%d3
	jls .L73
	cmp.l %d2,%d0
	jhi .L118
	mvz.w #32767,%d0
	move.w %d0,%d2
	move.w %d2,152(%a0)
.L120:
	mvz.w 2(%a1),%d1
	add.l #-16384,%d1
	muls.l %d0,%d1
	tst.l %d1
	jge .L78
	jra .L114
.L71:
	lsr.l #8,%d0
	cmp.l %d0,%d1
	jcc .L72
	move.l %d1,%d0
	jra .L72
.L73:
	sub.l %d3,%d2
	cmp.l %d2,%d0
	jhi .L75
	clr.w %d0
	mvz.w (%a1),%d1
	move.w %d0,152(%a0)
	cmp.l #32512,%d1
	jle .L119
	jra .L86
.L116:
	clr.w %d5
	mvz.w (%a1),%d1
	move.w %d5,152(%a0)
	cmp.l #32512,%d1
	jle .L119
	jra .L86
.L83:
	mvz.w #32767,%d0
	move.w %d0,%d1
	move.w %d1,152(%a0)
	jra .L117
.L118:
	move.l %d2,%d1
	moveq #15,%d7
	lsl.l %d7,%d1
	sub.l %d2,%d1
	divu.l %d0,%d1
	move.w %d1,%d2
	move.l %d1,%d0
	mvz.w %d0,%d0
	move.w %d2,152(%a0)
	jra .L120
.L113:
	sub.l %d3,%d0
	muls.l %d2,%d0
	divu.l %d1,%d0
	add.l %d4,%d0
	move.w %d0,152(%a0)
	mvz.w %d0,%d0
	jra .L63
.L75:
	move.l %d2,%d1
	moveq #15,%d3
	lsl.l %d3,%d1
	sub.l %d2,%d1
	divu.l %d0,%d1
	mvz.w #32767,%d0
	sub.l %d1,%d0
	move.w %d0,%d2
	mvz.w %d0,%d0
	move.w %d2,152(%a0)
	jra .L120
.L115:
	mvz.w #32767,%d4
	sub.l %d3,%d4
	muls.l %d4,%d2
	divu.l %d1,%d2
	add.l %d2,%d0
	move.w %d0,%d1
	mvz.w %d0,%d0
	move.w %d1,152(%a0)
	jra .L117
.L107:
	add.l %d1,%d0
	jra .L45
	.size	eu_process, .-eu_process
	.align	2
	.globl	eu_publish
	.type	eu_publish, @function
eu_publish:
	link.w %fp,#-112
	movem.l #1052,(%sp)
	move.l -2147457608,%d3
	moveq #29,%d2
	move.l 1175473392,%d0
	move.l %d0,-(%sp)
	pea eu_clock
	jsr eu_clock_update
	addq.l #8,%sp
	move.l 8(%fp),%a0
	move.l 12(%fp),%d1
	mvz.w 54(%a0),%d0
	add.l %d1,%d1
	cmp.l %d0,%d2
	jeq .L122
	mvz.w 56(%a0),%d0
	cmp.l %d0,%d2
	jeq .L122
	mvz.w #164,%d0
	mvz.w #164,%d3
	muls.l %d1,%d0
	addq.l #1,%d1
	muls.l %d3,%d1
	move.l %d0,%a0
	add.l #eu_states+158,%a0
	clr.b (%a0)
	move.l %d1,%a0
	add.l #eu_states+158,%a0
	clr.b (%a0)
.L121:
	movem.l -112(%fp),#1052
	unlk %fp
	rts
.L122:
	move.b -2147457603,%d0
	move.b -2147457602,%d4
	mov3q.l #1,%d2
	cmp.l %d3,%d2
	seq %d3
	move.l 12(%fp),%d2
	mov3q.l #3,-28(%fp)
	mov3q.l #4,-24(%fp)
	mov3q.l #6,-20(%fp)
	mvz.b %d0,%d0
	move.w %d4,%a1
	mvz.w #2330,%d4
	mvs.b %d3,%d3
	muls.l %d4,%d2
	moveq #8,%d4
	neg.l %d3
	move.l %d4,-16(%fp)
	moveq #12,%d4
	move.l %d4,-12(%fp)
	move.l %d3,-72(%fp)
	moveq #48,%d3
	move.w %a1,%d4
	move.l %d3,-4(%fp)
	mvz.b %d4,%d4
	move.l %d4,%a1
	move.l #635712,%d4
	muls.l %d4,%d0
	moveq #24,%d4
	move.l %d4,-8(%fp)
	move.w %a1,%d4
	mulu.w #36568,%d4
	move.l %d4,%a1
	lea (%a1,%d0.l),%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	lea (%a0,%d2.l),%a1
	move.b (%a0,%d0.l),%d0
	jeq .L124
	move.b 81(%a1),%d0
	move.b 80(%a1),%d2
	mov3q.l #6,%d4
	mvz.b %d0,%d0
	mvz.b %d2,%d2
	cmp.l %d0,%d4
	jcs .L132
.L144:
	move.l -28(%fp,%d0.l*4),%d0
	move.l %d0,-56(%fp)
.L126:
	move.l %d2,%d0
	moveq #63,%d3
	subq.l #1,%d0
	cmp.l %d0,%d3
	jcc .L127
	moveq #16,%d2
.L127:
	move.b 82(%a1),%d4
	move.l 64(%a1),%a0
	move.l 68(%a1),%a1
	move.l 12(%fp),%d0
	move.l -2147477476,%d3
	move.l 8(%fp),%a2
	move.l %a1,-64(%fp)
	lsl.l #4,%d3
	move.l 8(%fp),%a1
	lea (58,%a2),%a2
	move.l %a2,-78(%fp)
	move.b %d4,-74(%fp)
	mvz.w #328,%d4
	move.l %a0,-68(%fp)
	lea (54,%a1),%a1
	move.l 8(%fp),%a0
	muls.l %d4,%d0
	move.l %d3,-60(%fp)
	moveq #29,%d3
	lea (12,%a0),%a0
	move.l %d0,%a2
	add.l #eu_states,%a2
	mvz.w (%a1)+,%d0
	move.l %a2,-94(%fp)
	cmp.l %d0,%d3
	jeq .L128
.L143:
	mvz.w #164,%d0
	clr.b %d4
	move.l -94(%fp),%a2
	addq.l #1,%d1
	lea (12,%a0),%a0
	add.l %d0,-94(%fp)
	move.b %d4,158(%a2)
	cmp.l -78(%fp),%a1
	jeq .L121
.L142:
	mvz.w (%a1)+,%d0
	moveq #29,%d3
	cmp.l %d0,%d3
	jne .L143
.L128:
	mvz.b 8(%a0),%d3
	move.w (%a0),-52(%fp)
	mvz.b -74(%fp),%d0
	move.b -74(%fp),-73(%fp)
	addq.l #1,%d3
	moveq #30,%d4
	move.w 4(%a0),-50(%fp)
	move.b 6(%a0),-43(%fp)
	move.b %d3,-48(%fp)
	move.l %d2,%d3
	lsl.l #8,%d3
	move.b 10(%a0),-47(%fp)
	move.b 24(%a0),-46(%fp)
	move.b 25(%a0),-45(%fp)
	move.b 27(%a0),-44(%fp)
	move.b 28(%a0),-42(%fp)
	move.b -53(%fp),-41(%fp)
	cmp.l %d0,%d4
	jcc .L130
	moveq #30,%d0
	move.b %d0,-73(%fp)
.L130:
	move.l %d1,-(%sp)
	move.l -72(%fp),-(%sp)
	move.l -60(%fp),-(%sp)
	move.b -73(%fp),%d3
	pea -52(%fp)
	pea eu_clock
	move.l -94(%fp),-(%sp)
	move.l %d1,-82(%fp)
	move.l %a0,-90(%fp)
	move.l %a1,-86(%fp)
	move.w %d3,-40(%fp)
	move.l -68(%fp),-32(%fp)
	move.l -64(%fp),-36(%fp)
	jsr eu_process
	lea (24,%sp),%sp
	move.l -90(%fp),%a0
	move.l -86(%fp),%a1
	move.l -82(%fp),%d1
	addq.l #1,%d1
	move.w %d0,(%a0)
	mvz.w #164,%d0
	lea (12,%a0),%a0
	add.l %d0,-94(%fp)
	cmp.l -78(%fp),%a1
	jne .L142
	jra .L121
.L124:
	mvz.w #36436,%d0
	mvz.w #36435,%d2
	mov3q.l #6,%d4
	move.b (%a0,%d0.l),%d0
	move.b (%a0,%d2.l),%d2
	mvz.b %d0,%d0
	mvz.b %d2,%d2
	cmp.l %d0,%d4
	jcc .L144
.L132:
	mov3q.l #6,-56(%fp)
	jra .L126
	.size	eu_publish, .-eu_publish
	.align	2
	.globl	eu_publish_frame
	.type	eu_publish_frame, @function
eu_publish_frame:
	lea (-12,%sp),%sp
	mov3q.l #1,%d0
	movem.l #1036,(%sp)
	move.l -2147483424,%d3
	clr.l %d2
	lea eu_publish,%a2
	and.l %d0,%d3
	moveq #9,%d0
	lsl.l %d0,%d3
	add.l #-2147483376,%d3
.L146:
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	jsr (%a2)
	addq.l #1,%d2
	add.l #64,%d3
	addq.l #8,%sp
	moveq #8,%d0
	cmp.l %d2,%d0
	jne .L146
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
	.size	eu_publish_frame, .-eu_publish_frame
	.section	.note.GNU-stack,"",@progbits

| Generated control.s appends this adapter to the freestanding C engine.
| All stock scene/LFO writes have finished; publish into the outgoing frame.
        .text
        .balign 4
        .global eu_frame_hook, eu_start_hook, eu_resume_hook
eu_frame_hook:
        lea     -16(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,(%sp)
        jsr     eu_publish_frame
        movem.l (%sp),%d0-%d1/%a0-%a1
        lea     16(%sp),%sp
        lea     0x800000f0,%a1     | displaced, next MOVE sets the flags
        jmp     0x4000d568

| A fresh PLAY resets all instances together at the same anchor the stock
| transport sets for its first tick.
eu_start_hook:
        move.l  %d0,0x800065b8     | displaced: PLAYING
        bsr.s   eu_reset_clock
        jmp     0x4009c3da

| The second PLAY path (resume) uses the same reset policy for the effect.
eu_resume_hook:
        move.l  %d0,0x800065b8
        bsr.s   eu_reset_clock
        jmp     0x4009c4da

| Preserve the CCR produced by the displaced PLAYING store. BSR, LEA and
| MOVEM do not alter it, so save it only after the call has pushed its return
| address; restore it after every instruction that can change the flags.
eu_reset_clock:
        lea     -28(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@(12)
        move.w  %ccr,%d1
        move.w  %d1,%sp@(8)
        move.l  #eu_clock,(%sp)
        move.l  0x4610757c,%d0
        move.l  %d0,4(%sp)
        jsr     eu_clock_start
        move.w  %sp@(8),%d1
        move.w  %d1,%ccr
        movem.l %sp@(12),%d0-%d1/%a0-%a1
        lea     28(%sp),%sp
        rts

| Explicitly initialized, loader-owned DRAM, not uninitialized BSS. The
| C's static assertions check these sizes on both target and host compilers.
        .balign 4
        .global eu_clock, eu_states
eu_clock:
        .zero   20
eu_states:
        .zero   2624
