| Generated by generate.py from allocator.c.
#NO_APP
	.file	"allocator.c"
	.text
	.align	2
	.type	place, @function
place:
	lea (-448,%sp),%sp
	move.w 458(%sp),%d0
	movem.l #31996,(%sp)
	move.l 452(%sp),%a5
	mulu.w #192,%d0
	move.l %d0,%a0
	lea (408,%a0),%a0
	move.l %d0,48(%sp)
	add.l %a5,%a0
	move.l %a0,%d0
	add.l #192,%d0
.L2:
	clr.b (%a0)+
	cmp.l %a0,%d0
	jne .L2
	tst.l 464(%sp)
	jeq .L19
	move.l 48(%sp),%d1
	clr.l %d2
	lea 24(%a5,%d1.l),%a2
	lea 30(%a5,%d1.l),%a3
	add.l #216,%d1
	add.l %a5,%d1
.L6:
	tst.b 4(%a2)
	jne .L39
.L4:
	addq.l #6,%a2
	addq.l #6,%a3
	cmp.l %a2,%d1
	jne .L6
	mvz.w #192,%d1
	move.l 456(%sp),%d0
	clr.l %d4
	move.l 456(%sp),%a4
	addq.l #2,%a4
	muls.l %d1,%d0
	move.l %d0,56(%sp)
.L18:
	move.l %d4,%d0
	lsr.l #2,%d0
	mov3q.l #1,%d1
	and.l %d1,%d0
	eor.l %d1,%d0
	cmp.l 456(%sp),%d0
	jne .L10
	move.l 460(%sp),%a0
	mvz.b (%a0,%d4.l),%d0
	cmp.l #255,%d0
	jeq .L10
	move.w %d0,%d1
	move.l (%a5),%a0
	mulu.w #12,%d1
	add.l %d1,%a0
	tst.b 9(%a0)
	jne .L10
	mov3q.l #6,%d1
	muls.l %d0,%d1
	move.l %d1,%a1
	add.l 56(%sp),%a1
	move.l %d1,52(%sp)
	add.l %a5,%a1
	tst.b 412(%a1)
	jne .L10
	mulu.w #6,%d0
	add.l 48(%sp),%d0
	move.l %d0,%d1
	add.l #408,%d1
	add.l %a5,%d1
	move.l %d1,60(%sp)
	tst.l 464(%sp)
	jeq .L8
	tst.b 28(%a1)
	jne .L40
.L8:
	move.w (%a0),%a3
	mvz.w (%a5,%a4.l*2),%d0
	move.l %d0,%a1
	mvz.w %a3,%d6
	cmp.l %d6,%d0
	jcs .L11
	tst.l %d2
	jeq .L20
	mvz.w 2(%a0),%d1
	move.l %d6,%d5
	clr.l %d3
	lea (64,%sp),%a6
	move.l %d1,%a2
	neg.l %d1
	move.l %d1,44(%sp)
.L14:
	lea (64,%sp),%a0
	clr.l %d1
.L16:
	mvz.w (%a0),%d7
	mvz.w 2(%a0),%d0
	addq.l #1,%d1
	addq.l #6,%a0
	add.l %d7,%d0
	cmp.l %d0,%d3
	jcc .L13
	cmp.l %d7,%d5
	jhi .L41
.L13:
	cmp.l %d1,%d2
	jne .L16
	moveq #1,%d0
	move.l 52(%sp),%a0
	move.l 60(%sp),%a1
	move.l %a1,%d1
	addq.l #6,%d1
	add.l 56(%sp),%a0
	add.l %a5,%a0
	move.w %d3,408(%a0)
	move.b %d0,412(%a0)
	mov3q.l #6,%d0
	muls.l %d2,%d0
	move.w %a3,410(%a0)
	addq.l #1,%d2
	lea (%a6,%d0.l),%a0
.L17:
	move.b (%a1)+,%d0
	move.b %d0,(%a0)+
	cmp.l %d1,%a1
	jne .L17
.L10:
	addq.l #1,%d4
	moveq #16,%d1
	cmp.l %d4,%d1
	jne .L18
	movem.l (%sp),#31996
	mov3q.l #1,%d0
	lea (448,%sp),%sp
	rts
.L39:
	mov3q.l #6,%d0
	muls.l %d2,%d0
	addq.l #1,%d2
	move.l %a2,%a0
	lea 64(%sp,%d0.l),%a1
.L5:
	move.b (%a0)+,%d0
	move.b %d0,(%a1)+
	cmp.l %a0,%a3
	jeq .L4
	move.b (%a0)+,%d0
	move.b %d0,(%a1)+
	cmp.l %a0,%a3
	jne .L5
	jra .L4
.L41:
	lea -1(%a2,%d0.l),%a0
	move.l 44(%sp),%d3
	move.l %d6,%d5
	move.l %a0,%d0
	and.l %d0,%d3
	add.l %d3,%d5
	cmp.l %a1,%d5
	jls .L14
.L11:
	movem.l (%sp),#31996
	mov3q.l #-1,%d0
	lea (448,%sp),%sp
	rts
.L20:
	moveq #1,%d0
	move.l 52(%sp),%a0
	clr.l %d3
	lea (64,%sp),%a6
	move.l 60(%sp),%a1
	move.l %a1,%d1
	add.l 56(%sp),%a0
	addq.l #6,%d1
	add.l %a5,%a0
	move.w %d3,408(%a0)
	move.b %d0,412(%a0)
	mov3q.l #6,%d0
	muls.l %d2,%d0
	move.w %a3,410(%a0)
	addq.l #1,%d2
	lea (%a6,%d0.l),%a0
	jra .L17
.L19:
	mvz.w #192,%d1
	move.l 456(%sp),%d0
	clr.l %d2
	move.l 456(%sp),%a4
	clr.l %d4
	addq.l #2,%a4
	muls.l %d1,%d0
	move.l %d0,56(%sp)
	jra .L18
.L40:
	lea 24(%a5,%d0.l),%a0
	move.l %d1,%a1
	move.l %a0,%d1
	addq.l #6,%d1
.L9:
	move.b (%a0)+,%d0
	move.b %d0,(%a1)+
	cmp.l %d1,%a0
	jeq .L10
	move.b (%a0)+,%d0
	move.b %d0,(%a1)+
	cmp.l %d1,%a0
	jne .L9
	jra .L10
	.size	place, .-place
	.align	2
	.globl	dl_allocator_init
	.type	dl_allocator_init, @function
dl_allocator_init:
	move.l 4(%sp),%a1
	move.l %a1,%d0
	move.l %a1,%a0
	add.l #828,%d0
.L43:
	clr.b (%a0)+
	cmp.l %a0,%d0
	jne .L43
	move.l 12(%sp),%d0
	move.l 8(%sp),(%a1)
	or.l 16(%sp),%d0
	cmp.l #65535,%d0
	jhi .L44
	move.w 14(%sp),4(%a1)
	move.w 18(%sp),6(%a1)
.L44:
	move.l %a1,%d0
	add.l #808,%d0
	move.l 20(%sp),8(%a1)
	move.l 24(%sp),12(%a1)
	lea (792,%a1),%a0
.L45:
	move.b #-1,(%a0)+
	cmp.l %a0,%d0
	jne .L45
	rts
	.size	dl_allocator_init, .-dl_allocator_init
	.align	2
	.globl	dl_allocator_prepare
	.type	dl_allocator_prepare, @function
dl_allocator_prepare:
	lea (-44,%sp),%sp
	movem.l #23580,(%sp)
	move.l 48(%sp),%a2
	move.l 52(%sp),%a3
	move.l 56(%sp),%a6
	clr.l 28(%sp)
	clr.l 32(%sp)
	tst.b 824(%a2)
	jne .L70
	tst.l %a6
	jeq .L53
	cmp.l 20(%a2),%a6
	jeq .L53
	clr.l %d1
.L61:
	move.b (%a3,%d1.l),%d0
	mvz.b %d0,%d2
	cmp.l #255,%d2
	jeq .L54
	moveq #31,%d3
	cmp.l %d2,%d3
	jcs .L56
	ext.w %d0
	move.l (%a2),%a0
	mulu.w #12,%d0
	add.l %d0,%a0
	tst.b 10(%a0)
	jeq .L56
	mvz.b 8(%a0),%d0
	mov3q.l #7,%d4
	cmp.l %d1,%d4
	jcs .L71
	mov3q.l #1,%d2
	and.l %d2,%d0
	tst.l %d0
	jeq .L56
.L96:
	tst.b 9(%a0)
	jne .L60
	tst.w (%a0)
	jeq .L56
	move.w 2(%a0),%d0
	jeq .L56
	mvz.w %d0,%d0
	move.l %d0,%d2
	subq.l #1,%d2
	and.l %d2,%d0
	tst.l %d0
	jne .L56
.L60:
	move.l %d1,%d0
	lsr.l #2,%d0
	mov3q.l #1,%d2
	move.l 4(%a0),%a1
	and.l %d2,%d0
	eor.l %d2,%d0
	move.l 28(%sp,%d0.l*4),%a0
	move.l 8(%a2,%d0.l*4),%d2
	sub.l %a0,%d2
	cmp.l %a1,%d2
	jcs .L63
	add.l %a0,%a1
	move.l %a1,28(%sp,%d0.l*4)
.L54:
	addq.l #1,%d1
	moveq #16,%d3
	cmp.l %d1,%d3
	jne .L61
	move.l 28(%sp),36(%sp)
	move.l 32(%sp),40(%sp)
	clr.l %d1
	lea (792,%a2),%a4
.L64:
	move.l %d1,%d0
	lsr.l #2,%d0
	mvz.b (%a4,%d1.l),%d2
	mov3q.l #1,%d4
	and.l %d4,%d0
	move.w %d2,%d3
	mulu.w #12,%d3
	cmp.l #255,%d2
	jeq .L62
	mvz.b (%a3,%d1.l),%d4
	cmp.l %d2,%d4
	jeq .L62
	mov3q.l #1,%d2
	eor.l %d2,%d0
	move.l (%a2),%a0
	move.l 4(%a0,%d3.l),%a0
	move.l 36(%sp,%d0.l*4),%a1
	move.l 8(%a2,%d0.l*4),%d2
	sub.l %a1,%d2
	cmp.l %d2,%a0
	jhi .L63
	add.l %a0,%a1
	move.l %a1,36(%sp,%d0.l*4)
.L62:
	addq.l #1,%d1
	moveq #16,%d3
	cmp.l %d1,%d3
	jne .L64
	clr.l %d2
	move.l #place,%d3
.L65:
	clr.l -(%sp)
	move.l %a3,-(%sp)
	move.l %d2,-(%sp)
	move.l %a2,-(%sp)
	move.l %d3,%a0
	jsr (%a0)
	lea (16,%sp),%sp
	mov3q.l #-1,%d1
	cmp.l %d0,%d1
	jeq .L50
	subq.l #1,%d2
	tst.l %d2
	jne .L72
	clr.l %d2
.L66:
	mov3q.l #1,-(%sp)
	move.l %a3,-(%sp)
	move.l %d2,-(%sp)
	move.l %a2,-(%sp)
	move.l %d3,%a0
	jsr (%a0)
	lea (16,%sp),%sp
	addq.l #1,%d0
	tst.l %d0
	jeq .L73
	subq.l #1,%d2
	tst.l %d2
	jne .L74
	move.l %a3,%d1
	move.l %a3,%a0
	lea (808,%a2),%a1
	add.l #16,%d1
.L67:
	move.b (%a0)+,%d0
	move.b %d0,(%a1)+
	cmp.l %a0,%d1
	jne .L67
	clr.w %d0
	move.l %a6,20(%a2)
	move.w %d0,825(%a2)
	clr.l %d0
.L69:
	move.l %d0,%d1
	lsr.l #2,%d1
	mvz.b (%a3,%d0.l),%d3
	mvz.b (%a4,%d0.l),%d2
	mov3q.l #1,%d4
	and.l %d4,%d1
	addq.l #1,%d0
	cmp.l %d3,%d2
	jeq .L68
	eor.l %d4,%d1
	mov3q.l #1,%d2
	move.b 825(%a2),%d3
	lsl.l %d1,%d2
	or.l %d3,%d2
	move.b %d2,825(%a2)
.L68:
	moveq #16,%d1
	cmp.l %d0,%d1
	jne .L69
	moveq #1,%d2
	mov3q.l #1,%d0
	move.b %d2,824(%a2)
.L50:
	movem.l (%sp),#23580
	lea (44,%sp),%sp
	rts
.L71:
	mov3q.l #2,%d2
	and.l %d2,%d0
	tst.l %d0
	jne .L96
.L56:
	movem.l (%sp),#23580
	moveq #-3,%d0
	lea (44,%sp),%sp
	rts
.L63:
	movem.l (%sp),#23580
	moveq #-2,%d0
	lea (44,%sp),%sp
	rts
.L72:
	mov3q.l #1,%d2
	jra .L65
.L74:
	mov3q.l #1,%d2
	jra .L66
.L73:
	movem.l (%sp),#23580
	moveq #-5,%d0
	lea (44,%sp),%sp
	rts
.L53:
	movem.l (%sp),#23580
	moveq #-6,%d0
	lea (44,%sp),%sp
	rts
.L70:
	movem.l (%sp),#23580
	moveq #-4,%d0
	lea (44,%sp),%sp
	rts
	.size	dl_allocator_prepare, .-dl_allocator_prepare
	.align	2
	.globl	dl_allocator_ack
	.type	dl_allocator_ack, @function
dl_allocator_ack:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	move.l 12(%sp),%a0
	mov3q.l #1,%d1
	move.l 20(%sp),%a1
	mvz.b 824(%a0),%d0
	cmp.l %d0,%d1
	jne .L100
	move.l 16(%sp),%d2
	cmp.l 20(%a0),%d2
	jne .L100
	mov3q.l #1,%d1
	cmp.l %a1,%d1
	jcs .L102
	mvz.b 825(%a0),%d1
	move.l %a1,%d2
	btst %d2,%d1
	jeq .L102
	move.b 826(%a0),%d1
	move.b %d1,7(%sp)
	move.l %d0,%d1
	mov3q.l #1,%d0
	lsl.l %d2,%d1
	move.b 7(%sp),%d2
	or.l %d2,%d1
	move.b %d1,826(%a0)
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L100:
	move.l (%sp)+,%d2
	moveq #-6,%d0
	addq.l #4,%sp
	rts
.L102:
	move.l (%sp)+,%d2
	moveq #-3,%d0
	addq.l #4,%sp
	rts
	.size	dl_allocator_ack, .-dl_allocator_ack
	.align	2
	.globl	dl_allocator_commit
	.type	dl_allocator_commit, @function
dl_allocator_commit:
	lea (-16,%sp),%sp
	movem.l #3076,(%sp)
	move.l 20(%sp),%a3
	mvz.b 824(%a3),%d0
	subq.l #1,%d0
	tst.l %d0
	jne .L109
	move.l 24(%sp),%d0
	cmp.l 20(%a3),%d0
	jne .L109
	mvz.b 826(%a3),%d1
	mvz.b 825(%a3),%d0
	cmp.l %d1,%d0
	jeq .L125
	movem.l (%sp),#3076
	clr.l %d0
	lea (16,%sp),%sp
	rts
.L125:
	move.l %a3,%d2
	add.l #600,%d2
	move.l %d2,%a2
	move.l %d2,%d1
	clr.l 12(%sp)
	lea (-192,%a2),%a2
	add.l #-186,%d1
.L115:
	tst.b 4(%a2)
	jne .L126
.L113:
	addq.l #6,%a2
	addq.l #6,%d1
	cmp.l %a2,%d2
	jne .L115
	move.l 12(%sp),%d1
	add.l #192,%d2
	cmp.l #192,%d1
	jeq .L116
	mvz.w #192,%d0
	move.l %d2,%a2
	move.l %d2,%d1
	lea (-192,%a2),%a2
	add.l #-186,%d1
	move.l %d0,12(%sp)
	jra .L115
.L126:
	lea (-384,%a2),%a1
	move.l %a2,%a0
.L114:
	move.b (%a0)+,%d0
	move.b %d0,(%a1)+
	cmp.l %a0,%d1
	jeq .L113
	move.b (%a0)+,%d0
	move.b %d0,(%a1)+
	cmp.l %a0,%d1
	jne .L114
	jra .L113
.L116:
	move.l %a3,%d1
	add.l #824,%d1
	lea (808,%a3),%a0
.L117:
	move.b (%a0),%d0
	move.l %a0,%a1
	addq.l #1,%a0
	move.b %d0,-16(%a1)
	cmp.l %a0,%d1
	jne .L117
	moveq #2,%d1
	addq.l #1,16(%a3)
	mov3q.l #1,%d0
	move.b %d1,824(%a3)
	movem.l (%sp),#3076
	lea (16,%sp),%sp
	rts
.L109:
	movem.l (%sp),#3076
	moveq #-6,%d0
	lea (16,%sp),%sp
	rts
	.size	dl_allocator_commit, .-dl_allocator_commit
	.align	2
	.globl	dl_allocator_retire
	.type	dl_allocator_retire, @function
dl_allocator_retire:
	move.l %a2,-(%sp)
	move.l 8(%sp),%a2
	mvz.b 824(%a2),%d0
	subq.l #2,%d0
	tst.l %d0
	jne .L130
	move.l 12(%sp),%d0
	cmp.l 20(%a2),%d0
	jne .L130
	move.l %a2,%d1
	add.l #792,%d1
	lea (408,%a2),%a0
.L131:
	move.b (%a0),%d0
	move.l %a0,%a1
	addq.l #1,%a0
	move.b %d0,-384(%a1)
	cmp.l %a0,%d1
	jne .L131
	clr.b %d1
	mov3q.l #1,%d0
	move.b %d1,824(%a2)
	move.l (%sp)+,%a2
	rts
.L130:
	move.l (%sp)+,%a2
	moveq #-6,%d0
	rts
	.size	dl_allocator_retire, .-dl_allocator_retire
	.align	2
	.globl	dl_allocator_cancel
	.type	dl_allocator_cancel, @function
dl_allocator_cancel:
	move.l 4(%sp),%a1
	mvz.b 824(%a1),%d0
	subq.l #1,%d0
	tst.l %d0
	jne .L138
	move.l 8(%sp),%d0
	cmp.l 20(%a1),%d0
	jne .L138
	move.l %a1,%d0
	add.l #792,%d0
	lea (408,%a1),%a0
.L139:
	clr.b (%a0)+
	cmp.l %a0,%d0
	jne .L139
	clr.b %d1
	mov3q.l #1,%d0
	move.b %d1,824(%a1)
	move.b %d1,826(%a1)
	rts
.L138:
	moveq #-6,%d0
	rts
	.size	dl_allocator_cancel, .-dl_allocator_cancel
