#!/usr/bin/env python3
"""Generate checked-in freestanding ColdFire assembly, no stock bytes."""
from pathlib import Path
import subprocess
import sys
import tempfile
HERE=Path(__file__).resolve().parent
FLAGS=['-mcpu=5407','-msoft-float','-O2','-ffreestanding','-fno-builtin','-fno-common',
       '-fno-jump-tables','-fno-asynchronous-unwind-tables','-fno-ident',
       '-fomit-frame-pointer','-fno-zero-initialized-in-bss','-Wall','-Wextra','-Werror']
with tempfile.TemporaryDirectory() as tmp:
    dest=Path(tmp)/'transfer.s'
    subprocess.run(['m68k-elf-gcc',*FLAGS,'-S',str(HERE/'transfer.c'),'-o',str(dest)],check=True)
    content='| Generated by generate.py from transfer.c.\n'+dest.read_text()
    path=HERE/'transfer.s'
    if '--check' in sys.argv:
        if path.read_text()!=content: raise SystemExit('stale transfer.s')
    else: path.write_text(content)
