#!/usr/bin/env python3
"""Generate checked-in freestanding ColdFire assembly, no stock bytes."""
from pathlib import Path
import subprocess
import sys
import tempfile
HERE=Path(__file__).resolve().parent
FLAGS=['-mcpu=5407','-msoft-float','-O2','-ffreestanding','-fno-builtin','-fno-common',
       '-fno-jump-tables','-fno-asynchronous-unwind-tables','-fno-ident',
       '-fomit-frame-pointer','-fno-zero-initialized-in-bss','-Wall','-Wextra','-Werror']
for name in ('transfer','selection','selection_probe','allocator','manager','preflight','publication'):
    with tempfile.TemporaryDirectory() as tmp:
        dest=Path(tmp)/(name+'.s')
        subprocess.run(['m68k-elf-gcc',*FLAGS,'-S',str(HERE/(name+'.c')),'-o',str(dest)],check=True)
        content=f'| Generated by generate.py from {name}.c.\n'+dest.read_text()
        if '.comm' in content or '.bss' in content:
            raise SystemExit(name+': loader carries initialized bytes only; explicitly initialize every static/global')
        path=HERE/(name+'.s')
        if '--check' in sys.argv:
            if path.read_text()!=content: raise SystemExit('stale '+name+'.s')
        else: path.write_text(content)
