| Generated by generate.py from transfer.c.
#NO_APP
	.file	"transfer.c"
	.text
	.align	2
	.type	packet, @function
packet:
	lea (-28,%sp),%sp
	movem.l #1276,(%sp)
	move.l 32(%sp),%d4
	mvz.w %d4,%d1
	lsl.l #7,%d1
	move.l %d1,%a0
	add.l #dl_tx+134217728,%a0
	move.l %d1,%d2
	move.l %a0,%a2
	add.l #dl_tx+134217856,%d2
	move.l %a0,%a1
.L2:
	clr.w (%a1)+
	cmp.l %a1,%d2
	jne .L2
	lea sequence,%a1
	move.w (%a1,%d4.l*2),%d0
	addq.l #1,%d0
	move.w %d0,%d5
	jeq .L6
	move.w %d0,%d6
	move.w #19524,(%a0)
	move.w %d5,2(%a0)
	move.w 38(%sp),4(%a0)
	move.w %d4,6(%a0)
	mvz.w %d0,%d3
	move.l %d4,%d0
	add.l #1193046,%d0
	add.l #dl_tx+134217744,%d1
	add.l %d3,%d0
	move.w %d6,(%a1,%d4.l*2)
	moveq #24,%d6
	move.l %d0,%d7
	add.l #127730520,%d7
	move.w %d6,8(%a0)
.L4:
	move.l %d0,%d6
	lsr.l #8,%d6
	move.l %d1,%a1
	move.l %d0,%d3
	mvz.b %d3,%d3
	addq.l #4,%d1
	move.w %d6,(%a1)+
	add.l #5322105,%d0
	move.w %d3,(%a1)
	cmp.l %d0,%d7
	jne .L4
	clr.w %d1
.L5:
	move.w (%a0)+,%d0
	add.l %d1,%d0
	move.w %d0,%d1
	cmp.l %a0,%d2
	jne .L5
	neg.l %d0
	move.w %d0,12(%a2)
	clr.w %d0
	lea pending,%a0
	move.w %d5,(%a0,%d4.l*2)
	lea age,%a0
	move.w %d0,(%a0,%d4.l*2)
	movem.l (%sp),#1276
	lea (28,%sp),%sp
	rts
.L6:
	moveq #1,%d6
	moveq #1,%d5
	move.w #19524,(%a0)
	mov3q.l #1,%d3
	move.l %d4,%d0
	add.l #1193046,%d0
	add.l %d3,%d0
	move.l %d0,%d7
	add.l #dl_tx+134217744,%d1
	add.l #127730520,%d7
	move.w %d6,(%a1,%d4.l*2)
	moveq #24,%d6
	move.w %d5,2(%a0)
	move.w 38(%sp),4(%a0)
	move.w %d4,6(%a0)
	move.w %d6,8(%a0)
	jra .L4
	.size	packet, .-packet
	.align	2
	.globl	dl_frame
	.type	dl_frame, @function
dl_frame:
	lea (-20,%sp),%sp
	clr.l %d0
	movem.l #3084,(%sp)
	addq.l #1,dl_frames
	lea dl_tx+134217728,%a1
	clr.l %d1
	lea dl_rx+134217728,%a0
	lea pending,%a2
.L17:
	move.w (%a2,%d0.l),%d2
	jeq .L13
	mvz.w (%a0),%d3
	cmp.l #16715,%d3
	jeq .L30
.L14:
	lea age,%a3
	move.w (%a3,%d0.l),%d2
	addq.l #1,%d2
	mvz.w %d2,%d3
	move.w %d2,(%a3,%d0.l)
	moveq #63,%d2
	cmp.l %d3,%d2
	jcs .L31
.L13:
	addq.l #1,%d1
	lea (128,%a1),%a1
	subq.l #2,%d0
	lea (64,%a0),%a0
	tst.l %d0
	jne .L23
	move.l requests,%d3
	move.l stages,%d2
	cmp.l dl_request_probe.l,%d3
	jeq .L18
	move.l pending,%d0
	tst.l %d0
	jeq .L32
	move.l dl_request_stage,%d1
.L21:
	tst.l %d0
	sne %d0
	movem.l (%sp),#3084
	mvs.b %d0,%d0
	neg.l %d0
	lea (20,%sp),%sp
	rts
.L23:
	mov3q.l #2,%d0
	jra .L17
.L31:
	addq.l #1,dl_errors
	clr.w %d3
	clr.w (%a1)
	move.w %d3,(%a2,%d0.l)
	mov3q.l #1,dl_modal_pending
	jra .L13
.L30:
	mvz.w %d2,%d2
	mvz.w 2(%a0),%d3
	cmp.l %d2,%d3
	jne .L14
	tst.w 4(%a0)
	jne .L15
	mvz.w 6(%a0),%d2
	cmp.l %d2,%d1
	jeq .L33
.L15:
	clr.w %d2
	lea dl_rejected,%a3
	addq.l #1,(%a3,%d1.l*4)
	addq.l #1,dl_errors
	mov3q.l #1,dl_modal_pending
	clr.w (%a1)
	move.w %d2,(%a2,%d0.l)
	jra .L13
.L32:
	mov3q.l #1,-(%sp)
	clr.l -(%sp)
	lea dl_request_probe,%a0
	move.l (%a0),requests
	lea packet,%a2
	jsr (%a2)
	mov3q.l #1,-(%sp)
	mov3q.l #1,-(%sp)
	jsr (%a2)
	lea (16,%sp),%sp
.L18:
	move.l pending,%d0
	cmp.l dl_request_stage.l,%d2
	jeq .L21
	tst.l %d0
	jne .L21
	mov3q.l #2,-(%sp)
	clr.l -(%sp)
	lea dl_request_stage,%a0
	move.l (%a0),stages
	lea packet,%a2
	jsr (%a2)
	mov3q.l #2,-(%sp)
	mov3q.l #1,-(%sp)
	jsr (%a2)
	lea (16,%sp),%sp
	move.l pending,%d0
	movem.l (%sp),#3084
	tst.l %d0
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	lea (20,%sp),%sp
	rts
.L33:
	clr.w %d2
	lea dl_accepted,%a3
	addq.l #1,(%a3,%d1.l*4)
	clr.w (%a1)
	move.w %d2,(%a2,%d0.l)
	jra .L13
	.size	dl_frame, .-dl_frame
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"DSP LOAD FAILED"
.LC1:
	.string	"DSP MEMORY FULL"
.LC2:
	.string	"DSP OVERLOAD"
	.text
	.align	2
	.globl	dl_ui
	.type	dl_ui, @function
dl_ui:
	jsr dl_selection_tick
	tst.l dl_modal_pending
	jeq .L34
	move.l dl_modal_pending,%d0
	mov3q.l #2,%d1
	clr.l dl_modal_pending
	addq.l #1,dl_modal_shown
	cmp.l %d0,%d1
	jeq .L37
	subq.l #3,%d0
	tst.l %d0
	jeq .L44
	pea 48.w
	move.l #.LC0,%d0
	move.l %d0,-(%sp)
	jsr 1074111160
	addq.l #8,%sp
.L34:
	rts
.L37:
	pea 48.w
	move.l #.LC1,%d0
	move.l %d0,-(%sp)
	jsr 1074111160
	addq.l #8,%sp
	jra .L34
.L44:
	pea 48.w
	move.l #.LC2,%d0
	move.l %d0,-(%sp)
	jsr 1074111160
	addq.l #8,%sp
	jra .L34
	.size	dl_ui, .-dl_ui
	.data
	.align	2
	.type	stages, @object
	.size	stages, 4
stages:
	.zero	4
	.align	2
	.type	requests, @object
	.size	requests, 4
requests:
	.zero	4
	.align	2
	.type	age, @object
	.size	age, 4
age:
	.zero	4
	.align	2
	.type	pending, @object
	.size	pending, 4
pending:
	.zero	4
	.align	2
	.type	sequence, @object
	.size	sequence, 4
sequence:
	.zero	4
	.globl	dl_modal_shown
	.align	2
	.type	dl_modal_shown, @object
	.size	dl_modal_shown, 4
dl_modal_shown:
	.zero	4
	.globl	dl_modal_pending
	.align	2
	.type	dl_modal_pending, @object
	.size	dl_modal_pending, 4
dl_modal_pending:
	.zero	4
	.globl	dl_request_stage
	.align	2
	.type	dl_request_stage, @object
	.size	dl_request_stage, 4
dl_request_stage:
	.zero	4
	.globl	dl_request_probe
	.align	2
	.type	dl_request_probe, @object
	.size	dl_request_probe, 4
dl_request_probe:
	.zero	4
	.globl	dl_errors
	.align	2
	.type	dl_errors, @object
	.size	dl_errors, 4
dl_errors:
	.zero	4
	.globl	dl_rejected
	.align	2
	.type	dl_rejected, @object
	.size	dl_rejected, 8
dl_rejected:
	.zero	8
	.globl	dl_accepted
	.align	2
	.type	dl_accepted, @object
	.size	dl_accepted, 8
dl_accepted:
	.zero	8
	.globl	dl_frames
	.align	2
	.type	dl_frames, @object
	.size	dl_frames, 4
dl_frames:
	.zero	4
	.globl	dl_rx
	.align	2
	.type	dl_rx, @object
	.size	dl_rx, 128
dl_rx:
	.zero	128
	.globl	dl_tx
	.align	2
	.type	dl_tx, @object
	.size	dl_tx, 256
dl_tx:
	.zero	256
